eclipse-edc/Connector

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/EdcHttpClientImpl.java, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/EdcHttpClientImplTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/EdcHttpClient.java
Make `DspHttpRemoteMessageDispatcherImpl` fails if response status is not 200.
dsp
Closes #2987
=> fix: make DSP dispatcher fails if response code is not 200

core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationControllerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractAgreementMessageHttpDelegateTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractRequestMessageHttpDelegateTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractAgreementMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractAgreementVerificationMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractNegotiationEventMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractNegotiationTerminationMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractRequestMessageTransformer.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferCompletionMessageTransformer.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferRequestMessageTransformer.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferStartMessageTransformer.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferTerminationMessageTransformer.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/message/ProcessRemoteMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementVerificationMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractNegotiationEventMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiationTerminationMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/protocol/ContractRemoteMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferCompletionMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRemoteMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRequestMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferStartMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java
The PR moves out id creation from the DSP transformers by introducing the `ProcessRemoteMessage` type. This is the first step for introducing end-to-end idempotency and reliability in M10.
Closes #2908
=> feat: introduce `ProcessRemoteMessage` and pull up id creation

extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/JsonObjectToCallbackAddressDtoTransformer.java, extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectToCallbackAddressDtoTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/ContractOfferDescription.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractOfferDescriptionTransformer.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToNegotiationInitiateRequestDtoTransformer.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractOfferDescriptionTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToNegotiationInitiateRequestDtoTransformerTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java
Fix `JsonObjectToNegotiationInitiateRequestDto` when json-ld is expanded
Also fixed in this PR `JsonObjectToCallbackAddressDtoTransformer` when deserializing `events` field and added json-ld expasion on `ContractNegotiationNewApiController#initiateContractNegotiation`
Closes #2994
=> fix(JsonObjectToNegotiationInitiateRequestDto): fix with expanded json-ld

extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/model/TransferProcessDocumentSerializationTest.java, extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/resources/raw_json.json, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/CoreConstants.java, spi/common/core-spi/src/test/resources/serialized_asset.json, system-tests/management-api/management-api-test-runner/src/test/resources/policy-definition.json
Creates a (ficticious) W3ID namespace for EDC.
I based the namespace on [this](https://w3id.org/) recommendation, but did not create a pull request there. As far as I understood this is only necessary if permanent redirection is required.
We must have a unique and immutable namespace
=> chore: add W3ID compliant identifier

data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/DspCatalogTransformExtension.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogRequestMessageTransformer.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/to/JsonObjectToCatalogRequestMessageTransformer.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogRequestMessageTransformerTest.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/to/JsonObjectToCatalogRequestMessageTransformerTest.java, data-protocols/dsp/dsp-transform/src/main/java/org/eclipse/edc/protocol/dsp/transform/DspTransformExtension.java, extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/query/QuerySpecDto.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToCriterionTransformer.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToQuerySpecTransformer.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformerTest.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformerTest.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToCriterionTransformerTest.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToQuerySpecTransformerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/Criterion.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QuerySpec.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
Add `QuerySpec` as JSON-LD object in `CatalogRequestMessage`
fix issue on catalog query
I've created transformers directly for `QuerySpec` and `Criterion` which are used in `CatalogRequestMessage` and also the new controllers  `ContractNegotiationNewApiController` and `TransferProcessNewApiController`.  
I didn't change `CatalogNewApiController` since it share `CatalogRequestDto` with the old controller.
Once we remove the old controller we can use the `QuerySpec` directly in the `CatalogRequestDto`.
To make it compatible with this future refactor  the `CriterionDto.CRITERION_TYPE` has been renamed: ~~CriterionDto~~ Criterion
Closes #3015
=> fix(CatalogRequestMessage): `QuerySpec` as JSON-LD

.github/PULL_REQUEST_TEMPLATE.md
Removes the checkboxes from the PR template.
they became obsolete
=> chore: remove checkboxes from PR template

data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiController.java, spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceFailure.java, spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
Refactors the `handleMessage` method of two controllers (`DspNegotiation...` and `DspTransferProcess...`) such that errors are conveyed using instances of `Result` rather than exceptions.
Make code cleaner and more efficient.
Closes #3026
=> refactor(dsp): make handleResult return a Result

docs/developer/decision-records/2023-05-23-java-17-baseline/README.md, docs/developer/decision-records/README.md
Add DR to migrate the Java baseline version to 17
_Please be sure to take a look at
the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request)
and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)_
=> docs: java 17 baseline decision record

docs/developer/decision-records/2023-03-27_private_properties/README.md
This PR adds the decision record concerning private properties in assets.
Enriching an `Asset` with information not relevant for
external consumers/providers is currently not possible.
To achieve this, it has to be done through an external storage.
A prominent use-case for `privateProperties` would be internal tags, that help with filtering `Assets` when it comes
to selecting a policy.
=> docs(Asset): Private properties asset decision record

.github/actions/setup-build/action.yml, build.gradle.kts, core/common/util/src/test/java/org/eclipse/edc/util/configuration/ConfigurationFunctionsTest.java, gradle.properties
Switch to Java 17 by removing custom project version and letting the version being set by the `edc-build` plugin
- cleanup build file a little
- had to change `ConfigurationFunctionsTest` because of https://junit-pioneer.org/docs/environment-variables/#warnings-for-reflective-access
Closes #3069 
=> build: switch to java 17

spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java, spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/DataAddressTest.java
Align behavior of `getProperty` and `hasProperty` methods in `DataAddress` (handling of the `EDC_NAMESPACE` prefix).
`hasProperty` is not checking if property existing with the `EDC_NAMESPACE` prefix while `getProperty` does. This leads to inconsistent behaviors, for example in `Oauth2HttpRequestParamsDecorator`.
=> fix: Align behavior of getProperty and hasProperty in DataAddress

extensions/common/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/edc/iam/did/service/DecentralizedIdentityService.java, extensions/common/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/edc/iam/did/service/DecentralizedIdentityServiceTest.java
Set missing `client_id` in `DecentralizedIdentityService`.
`client_id` is request by `ContractValidationServiceImpl`.
=> fix: Set missing `client_id` in `DecentralizedIdentityService`

.github/actions/bump-version/action.yml, .github/workflows/bump-version.yaml, .github/workflows/release-edc.yml
Creates a workflow, that  bumps the (patch) version found in gradle.properties and commits it back into git.
Preliminary work needed for #3084
The commit is made "as" the `eclipse-edc-bot` to avoid potential ECA check failures
Contributes #3084
=> build: add workflow to bump the snapshot version

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImplTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEndpointDataReferenceServiceImpl.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyTransformer.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferEndpointDataReferenceServiceImplTest.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullTransferProxyTransformerTest.java, spi/control-plane/transfer-data-plane-spi/src/main/java/org/eclipse/edc/connector/transfer/dataplane/spi/TransferDataPlaneConstants.java
Adds `EndpointDataReferenceTransformerRegistry#transform` call upon receiving the `TransferProcessStarted` 
backward compatibility
Closes #3079
=> fix(EndpointDataReferenceTransformerRegistry): adds transform call 

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/model/TransferRequestDto.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestDtoTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferProcessToTransferProcessDtoTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestDtoTransformerTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformerTest.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/TestFunctions.java, resources/openapi/yaml/management-api/transfer-process-api.yaml, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferRequest.java, spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcessTest.java, spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java, system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/edc/test/e2e/ConsumerBackendServiceController.java, system-tests/e2e-transfer-test/control-plane/build.gradle.kts, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
Adds a new field `TransferProcessRequestDto#privateProperties` that will be stored in the `TransferProcess#properties` field
Consistency
Also in this PR the `HttpDynamicEndpointDataReferenceReceiver` has been fixed
To make the change more consistent `TransferProcess#properties` has been renamed to `TransferProcess#privateProperties`
Closes #3063 
=> fix: feed `TransferProcess#properties` from the new field 

.github/actions/bump-version/action.yml, .github/workflows/release-edc.yml, docs/developer/releases.md
This PR improves the version-bump action slightly, in that it recursively greps for the OLDVERSION in all files, and replaces it with the NEWVERSION using sed.
more consistent version
I adapted the `releases.md` document so that it doesn't get picked up by that job 
=> chore: improve version bump job

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogServiceImplTest.java, core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java, core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/TestFunctions.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/ContractNegotiationDto.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/NegotiationInitiateRequestDto.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/NegotiationInitiateRequestDtoValidationTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/model/TransferRequestDto.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/model/TransferRequestDtoValidationTest.java, extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreIntegrationTest.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/docs/schema.sql, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtension.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/ServiceExtensionContext.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/TestFunctions.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/catalog/CatalogService.java, spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TestFunctions.java
Remove all the "ids-multipart" occurrences and related code
cleanup
- removed some `@Deprecated` methods in the `ServiceExtensionContext`
Closes #2442
=> refactor: purge ids-multipart occurrences

extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerTest.java
fix NPE when calling `POST|/transferprocesses/request` with without body
Fix the InternalServerError returned
Closes #3102
=> fix(TransferProcessController): fix NPE on empty request

extensions/README.md
https://github.com/eclipse-edc/Connector/issues/3085
The documentation was missing the Google Cloud Storage extension in the data pane section. This PR adds the missing extension.
NA
NA
https://github.com/eclipse-edc/Connector/issues/3085
Closes 1
=> docs: Added missing Google Cloud Storage extension in extensions/README.md #3085

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/InMemoryStatefulEntityStore.java, core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStore.java, core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStoreTest.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java, extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java, extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStoreIntegrationTest.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/store/TransferProcessStore.java, spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java
Add  `findForCorrelationId` method on `TransferProcessStore` to align with `ContractNegotiationStore`
refactor
- removed the now unused `processIdForDataRequestId`
- cleaned up store tests a bit
Closes #3062 
=> refactor: add `findForCorrelationId` method on `TransferProcessStore`

docs/developer/decision-records/2023-06-02-separating_plugins_and_metamodel/README.md, docs/developer/decision-records/README.md
Adds a decision-record about splitting the GradlePlugins repo and moving out the `runtime-metamodel`
transparency of decisions
- I put the D-R here because the org-repo (`.github`) still seems to be empty. 
=> docs: add decision record about splitting the GradlePlugins repo

core/common/policy-evaluator/src/main/java/org/eclipse/edc/policy/evaluator/PolicyEvaluator.java, core/common/policy-evaluator/src/test/java/org/eclipse/edc/policy/evaluator/PolicyEvaluatorTest.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToConstraintTransformer.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToAtomicConstraintComplexTypeTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java
Adds support for processing complex types (in addition to scalars) for right policy operands. Also performs some minor code cleanup in related classes.
The `PolicyEvaluator` remains type system agnostic (e.g., it does not have knowledge about Json-Ld or other type systems). `JsonObjectToConstraintTransformer` is enhanced to handle extraction of scalars and Json-Ld types according to the following rules:
- Json-Ld expanded scalar types are extracted from their enclosing array and passed directly to the constraint evaluator.
- Json-Ld arrays that contain a single element (Json-Ld scalar or complex type) will return the extracted element. 
- Json-Ld arrays that contain multiple elements will be returned as-is.
- Json-Ld objects that contain an `@value` property will have that property …
=> feat(policy): Support complex literal operand types

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, data-protocols/dsp/dsp-http-core/build.gradle.kts, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/dispatcher/DspHttpRemoteMessageDispatcher.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/TokenParameters.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementVerificationMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractNegotiationEventMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiationTerminationMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/protocol/ContractRemoteMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferCompletionMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRemoteMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRequestMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferStartMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java
evaluate policy on specific registered `RemoteMessage`
- removed some deprecated fields from the messages
=> feat: evaluate policy on message dispatch for CN and TP

data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java
Minor cleanup, makes scopes constants and adds the `PolicyScope` annotation.
=> chore: Make scopes constant and add annotation

data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/TokenParameters.java
Adds an additional map field in `TokenParameters`
Be able to provide additional information when evaluating a policy in the dispatcher
Closes #3168
=> feat(TokenParameters): add field for additional information

spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/TokenParameters.java
Make `TokenParameters.Builder#additional` additive
When working with multiple policy functions that deals with `TokenParamenter.Builder` it's better to have an additive version of `additional` method in the builder.
=> chore(TokenParameters): make additional additive

data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java, spi/common/catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/CatalogRequestMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/offer/ContractDefinitionResolver.java
This PR adds a policy scope `"contract.cataloging.request"`, so that we can invoke policy evaluation functions on outgoing catalog requests.
For now, the corresponding policy is an empty stub, because we don't (yet) have a way to supply one, but that may change in the future, e.g. by another extension.
We need a way to invoke policy functions on all outgoing requests to attach credentials to the request. At this time, this is a requirement from Catena-X, but it is not limited to it.
- at this time, the type of credential that gets attached is determined by the function, but in future iterations we could have a policy (or policies) that determine(s), which credentials need to be attached for which request.
_Please be sure to take a look at …
=> feat: add a policy scope for outgoing Catalog requests

extensions/common/api/api-observability/build.gradle.kts, extensions/common/api/api-observability/src/main/java/org/eclipse/edc/api/observability/ObservabilityApiController.java, extensions/common/api/api-observability/src/main/java/org/eclipse/edc/api/observability/ObservabilityApiExtension.java, extensions/common/api/api-observability/src/test/java/org/eclipse/edc/api/observability/ObservabilityApiControllerTest.java, extensions/common/api/api-observability/src/test/java/org/eclipse/edc/api/observability/ObservabilityApiExtensionTest.java
Remove observability controller from management api and put on the default context as it was before the api context refactoring
Untangling dependencies between an hi-level api as observability and the management api
-
Closes #3165 
=> feat: move observability api from `management` to `default` 

core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java
This PR implements pre- and post- policy validator filtering (which was never done). 
Also, this PR renames the following recently added scopes:
`contract.negotiation.request` --> `request.contract.negotiation`
`transfer.process.request` --> `request.transfer.process`
This renaming is necessary due to the hierarchical behavior of policy scope filtering. Under the previous naming scheme, any function and rule registered to the `contract.negotiation` and `transfer.process` scopes would be engaged when their `.request` analogs are in scope. Prefixing instead of post-fixing `request.` solves this problem and also avoids breaking changes if we were to introduce a post-fix such as `.receive` to the existing scope names (since in that case existing end-user functions would be egaged when either …
=> feat(policy): Implement validator filtering including changing request scope names 

extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java, extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiExtension.java, extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiControllerTest.java
In fact this only adds the validation for the `QuerySpecDto` object, as `ContractAgreement` doesn't have any input dto to be validated
validation
Part of #3011
=> feat: validate contract agreement controller

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiExtension.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/validation/AssetEntryDtoValidator.java, extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiExtensionTest.java, extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/validation/AssetEntryDtoValidatorTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractDefinitionApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Make `TitaniumJsonLd` expansion fails if the result is empty (that usually happens when there are no expanded properties, e.g. when there are no namespaced properties withouth the `@context` property set).
It also fix a nit that avoided the validator to work correctly on the `update` method
improve error messages
-
Closes #3172 
=> feat: make json-ld expansion fails if titanium returns empty result

docs/developer/decision-records/2023-06-19-new-issue-triage-process/README.md, docs/developer/decision-records/README.md
Adds a D-R about the auto-application of new labels, and our new triage process. 
make the decision transparent.
=> docs: add decision record about automatically labelling new issues

docs/developer/decision-records/2023-06-19-onboarding-contributors/README.md, docs/developer/decision-records/README.md
Adds a decision record about the requirements to become a contributor.
persist the decision from June 16 2023
=> docs: decision record about contributor onboarding process

core/common/policy-engine/build.gradle.kts, core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplScenariosTest.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractDefinitionResolverImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractExpiryCheckFunction.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractDefinitionResolverImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractExpiryCheckFunctionEvaluationTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImplTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyContext.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyContextImpl.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java
Add a new method that accepts a `PolicyContext` object, deprecating the others 
improve interface
- went using `PolicyContext` also if in the issue I stated that it should not be done, has been shown to be the best approach
Closes #3162 
=> refactor: improve `PolicyEngine` interface

.github/actions/bump-version/action.yml, .github/workflows/release-edc.yml
This PR modifies the `bump-version` action and takes the release version (base version) from an action input and only falls back to the `gradle.properties` if that input was `null`.
when releasing e.g. `0.2.0`, the next snapshot is supposed to be `0.2.1-SNAPSHOT`.
- I also improved the snapshot patch version increment, so that when releasing versions with metadata, e.g. `0.3.6-rc2`, the next snapshot version will still be `0.3.6-SNAPSHOT`.
- once this PR is approved, i'll do the same thing in all other repos as well.
Closes #3198 
=> feat(build): use release version in bump-job

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/close-inactive-issues.yml
- auto assigns labels `triage` and `bug_report`/`feature_request` respectively
- automatically sets `triage` issues to `stale` after 28 days, and closes them after another 14 days.
decision record
- once this gets approved, I'll do the same thing in all other repos as well.
Closes #3199 
=> chore: adapt issue labels and auto-stale

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, data-protocols/dsp/dsp-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/api/configuration/error/DspErrorResponse.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractnegotiation/ContractNegotiationProtocolService.java
Adds a method `findById` to the `ContractNegotiationProtocolService`, that takes a `ClaimToken` as parameter and returns a negotiation only if the requesting party is authorized. Using this method, implements the `GET /id` endpoint in the `DspNegotiationApiController`.
To support the protocol specification
Closes #2795
=> feat(dsp): implement GET /id negotiation endpoint

extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/JsonObjectToCriterionDtoTransformer.java, extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectToCriterionDtoTransformerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/Criterion.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java
Make `JsonObjectToCriterionDtoTransformer` handle `in` operator correctly
support "in" operator
- cleaned up some unused methods
Fix #3216
=> fix: handle iterable Criterion operandRight

.github/workflows/close-inactive-issues.yml
Change `only-labels` according to [the GH action's guide](https://github.com/actions/stale#list-of-input-options).
A typo currently leads to issues being marked as `stale` although they are assigned to milestones.
=> fix(workflow): correct `only-labels` in stale bot

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiController.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiControllerTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessProtocolService.java
Adds a method `findById` to the `TransferProcessProtocolService`, that takes a ClaimToken as parameter and returns a transfer process only if the requesting party is authorized. Using this method, implements the `GET /id` endpoint in the `DspTransferProcessApiController`.
To support the protocol specification
Adds a second `validateRequest()` method to the `ContractValidationService`, that checks whether a requesting participant is authorized for a contract agreement, but does not perform policy evaluation.
Closes #2761
=> feat(dsp): implement GET /id transfer process endpoint

.github/ISSUE_TEMPLATE/config.yml
removes the option to submit a blank issue.
all issues should either be feature requests or bug reports. or they should really be a discussion.
=> chore: remove blank-issue option

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java, spi/control-plane/contract-spi/build.gradle.kts, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/ContractId.java, spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/ContractIdTest.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/TestFunctions.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/KafkaTransferTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java, system-tests/tests/src/testFixtures/java/org/eclipse/edc/test/system/utils/TransferTestClient.java
Encodes the three parts of a `ContractId` with base64
avoid issues with id containing `:`.
- ~~this is a BREAKING CHANGE, so already stored ongoing contracts could stop working~~ it will work also with not encoded old ids
- refactored the `ContractId` class to adhere our convention, adding the `parseId` method returning a `Result<ContractId>` and adding a `create` that returns a `ContractId`
- deprecating old methods to avoid compilation errors in downstream projects. 
Closes #3211 
=> feat: encode `ContractId` parts

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplPerformanceTest.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImplTest.java, data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/CatalogApiPaths.java, data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/DspCatalogApiController.java, data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/DspCatalogApiControllerTest.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToDatasetTransformer.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToDatasetTransformerTest.java, spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java, spi/common/catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/Dataset.java, spi/common/catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/DatasetResolver.java, spi/common/catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/Distribution.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/catalog/CatalogProtocolService.java
Implement DSP `/catalog/datasets/{id}` endpoint
dsp compliance
- now the Dataset id is the same as the Asset id.
Closes #3220 
Closes #3231 
=> feat: implement get dataset dsp endpoint

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
Remove contract id validation on `ContractAgreementMessage` received on consumer side
To permit the connector to interact with a non-EDC counter-party connector
Closes #3240 
=> fix: avoid contract id validation on consumer side

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/DispatchFailure.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
Avoid sending `TranferRequestMessage`s on failing `CONSUMER` `TransferProcess`es that have not been notified to the `PROVIDER` yet.
bugfix
- moved the test classes from `package org.eclipse.edc.connector.transfer.transfer;` to `package org.eclipse.edc.connector.transfer.process;`
Closes #3247 
=> fix: avoid sending messages on failing not-yet-requested consumer transfers

docs/developer/decision-records/2023-06-30-allow-use-of-testcontainers/README.md, docs/developer/decision-records/README.md, docs/developer/testing.md
Adds a D-R about the use of Testcontainers
documentation, decision tracing
Closes #3254 
=> docs: add decision record about using Testcontainers

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/DspNegotiationHttpDispatcherExtension.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractOfferMessageHttpDelegate.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractOfferMessageHttpDelegateTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/DspNegotiationTransformExtension.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractOfferMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractOfferMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractOfferMessageTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractOfferMessageTransformerTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractOfferMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractnegotiation/ContractNegotiationProtocolService.java
Adds the type `ContractOfferMessage` including transformers and a dispatcher. Using this message, implements the `notifyOffered` method in `ContractNegotiationProtocolService` as well as the `providerOffer` method in `DspNegotiationApiController`.
To support the protocol specification
Closes #2750
=> feat(protocol): add ContractOfferMessage

extensions/common/api/api-core/build.gradle.kts, extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/ApiCoreExtension.java, extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java, extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/JsonObjectToQuerySpecDtoTransformer.java, extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/model/ApiCoreSchemaTest.java, extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectToQuerySpecDtoTransformerTest.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiExtension.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java, extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiTest.java, gradle/libs.versions.toml, resources/openapi/openapi.yaml, resources/openapi/yaml/management-api/contract-definition-api.yaml
Adds example to openapi specs for `ContractDefinition` api endpoints
documentations
- introduced schema records that are used to create the specs
- doing this the `Dto` objects will become obsolete (and the related transformers too)
- the example json strings are tested doing deserialization / expansion / validation and transformation.
Part of #3146
=> docs: add example to contract definition management api

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/OkHttpClientFactory.java, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/OkHttpClientFactoryTest.java
Make connect and read timeout configurable
Configurability
- added the `client` part in the setting path to make it more self-descripting, deprecated the old "https enforcement" config value and add a new one replacing it 
Closes #3273 
=> feat: make http client timeouts configurable

core/common/junit/build.gradle.kts, core/common/junit/src/main/java/org/eclipse/edc/junit/annotations/PostgresqlDbIntegrationTest.java, extensions/common/sql/sql-core/build.gradle.kts, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/SqlQueryExecutorIntegrationTest.java, extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlLocalInstance.java, extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlStoreSetupExtension.java, extensions/common/sql/sql-lease/src/test/java/org/eclipse/edc/sql/lease/PostgresLeaseContextTest.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultIntegrationTest.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultTest.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/PathUtilTest.java, extensions/control-plane/store/sql/asset-index-sql/build.gradle.kts, extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java, extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractdefinition/PostgresContractDefinitionStoreTest.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java, extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/policydefinition/PostgresPolicyDefinitionStoreTest.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java, extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java, extensions/data-plane/store/sql/data-plane-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/store/sql/PostgresDataPlaneStoreTest.java, gradle/libs.versions.toml, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/PostgresConstants.java
This PR converts all `@PostgresqlDbIntegrationTest` instances to `@ComponentTests` using Testcontainers. All tests - **except E2e**, that is. 
Converting the E2E tests over seemed to be quite a large undertaking, given how we are using test extensions and all the static initialization stuff etc. If needed, we can do it in a subsequent PR. 
Consequently, the `@PostgresqlDbIntegrationTest` annotation is only used for E2E tests anymore.
Decision to use test containers.
- .
=> feat(test): convert all postgres tests to use testcontainers

.github/workflows/dependency-review.yml, DEPENDENCIES, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImplTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/model/TransferRequestDto.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestDtoTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/JsonObjectToTransferRequestDtoTransformerTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferRequestDtoToTransferRequestTransformerTest.java, extensions/control-plane/store/sql/transfer-process-store-sql/docs/schema.sql, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/BaseSqlDialectStatements.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/DataRequestMapping.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md, resources/openapi/openapi.yaml, resources/openapi/yaml/management-api/transfer-process-api.yaml, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/DataRequest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/ProvisionedResource.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/ProvisionedResourceSet.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java, spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TestFunctions.java
removed the `managedResource` field on `DataRequest` and all the accessors because it had no more meaning in the current situation
refactoring
Closes #3292 
=> refactor: get rid of `managedResource`

.github/workflows/dependency-review.yml
If the `DEPENDENCIES` file is outdated or differs from the generated one in any way, an error is issued and the job fails.
Also, in that case, the contents of the regenerated file are echoed.
improved convenience function
- after this is merged, we should move the `dependency-review.yaml` job up into the `.github` repository.
=> feat(ci): improve outputting dependencies if they are different

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/TransferProcessManager.java
removes a method from the `TransferProcessManager` that was only used in tests.
trimming the fat -> remove dead code
=> chore: remove unneeded method

.github/workflows/apidoc.yaml, .github/workflows/release-edc.yml
This PR lets the `release-edc` workflow call the `apidoc` workflow, which publishes the OpenAPI specs to Swaggerhub.
If the `apidoc` workflow is invoked passing in a non-snapshot version, the API is set to `"published"` on SwaggerHub, which means it cannot be altered afterwards.
We should publish immutable OpenAPI documents of our release versions.
Closes #2834 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull …
=> feat(ci): publish OpenAPI specs on releases

core/common/util/src/main/java/org/eclipse/edc/util/configuration/ConfigurationFunctions.java, core/common/util/src/test/java/org/eclipse/edc/util/configuration/ConfigurationFunctionsTest.java, extensions/common/vault/vault-filesystem/src/main/java/org/eclipse/edc/vault/filesystem/FsVaultExtension.java
Uses `getSetting` where possible instead of `propOrEnv`
permit vault to be configured via configuration (!)
Closes #1106
=> feat: permit to configure fs vault with configuration file

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
Adds a null check on the data destination to `TransferProcessProtocolServiceImpl::notifyRequested` before validating the destination. In `requestedAction` creates a destination `DataAddress` of type `HTTP_PROXY` (= pull) for the `DataRequest`, if no destination was specified.
The destination is optional according to the protocol spec, as it is only required for push transfers.
Closes #2728
=> chore: handle missing destination in transfer protocol service

DEPENDENCIES, docs/developer/decision-records/2023-07-20-state-machine-guards/README.md, docs/developer/decision-records/2023-07-20-state-machine-manual-interactions/README.md, docs/developer/decision-records/README.md
Adds a decision record about state machine manual interactions
Part of #3308 
=> docs: add decision record about state machine manual interactions

.github/workflows/apidoc.yaml
Only publishes OpenAPI specs when pushing to `main`
no reason to create openapi publications on feature branches, e.g. dependabot branches
=> fix: create openapi only on pushes to main

extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java, extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/JerseyRestServiceTest.java
Bind controllers only on the specific context
bugfix
Closes #3312
=> fix(jersey): bind controllers to the correct context

docs/developer/contract-duration/contract-validity-check.md, docs/developer/contract-duration/policy.inforce.duration.json, docs/developer/contract-duration/policy.inforce.fixed.json
Adds documentation about the `inForce` policy used to limit the contract validity.
documentation
=> docs: add documentation about the in-force policy

DEPENDENCIES, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
Breaks the lease for `STARTED` transfer processes on the provider side.
Avoids zombie leases that never get broken.
Closes #3335
=> fix: break lease for STARTED processes

DEPENDENCIES, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
Adds a unit test to #3336 
was forgotten previously
Closes #3335 
=> test: adds unit test for the break-lease-on-started issue

docs/developer/contract-duration/contract-validity-check.md
Just a typo
Typos are the evil
=> docs: Fix typo in Contract In Force Policy documentation

docs/developer/decision-records/2023-08-01-default-datasource/README.md, docs/developer/decision-records/README.md
Adds decision about default datasource
Ref #3337
=> docs: adds decision record about default datasource

DEPENDENCIES, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToCatalogTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformerTest.java, data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspNegotiationPropertyAndTypeNames.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java, spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessageTest.java
Change `dataSet` to `dataset` in `ContractRequestMessage`
compliancy
- I made the deserialization transformer work also with the old value, this to avoid breaking changes in wire communication between older versions and newer ones.
Closes #3237 
=> feat: fix dataset case according to DSP specs

spi/common/core-spi/src/main/java/org/eclipse/edc/spi/command/CommandResult.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/response/StatusResult.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/health/HealthCheckResult.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/StreamResult.java
Makes the `AbstractREsult#newInstance` method abstract
avoids `UnsupportedOperationException`s when calling e.g. the `map()` operator
.
Closes #3353 
=> feat: implement newInstance everywhere

docs/developer/decision-records/2023-08-07-generic-properties/README.md, docs/developer/decision-records/README.md
Adds DR for generic properties
Part of #3357 
=> docs: generic properties DR

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractagreement/ContractAgreementServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractagreement/ContractAgreementServiceImplTest.java, extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchema.java, extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchemaTest.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java, extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApiTest.java, extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java, extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java, extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiControllerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractagreement/ContractAgreementService.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractAgreementApiEndToEndTest.java
Adds an additional endpoint `GET /v2/contractagreements/{id}/negotiation` to obtain a negotiation given a contract agreement id
Seems to be a pretty needed functionality
- improved some api documentation
Closes #2316
=> feat: add get negotiation by agreement id endpoint

DEPENDENCIES, data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/DspCatalogApiController.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/build.gradle.kts, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/DspNegotiationApiExtension.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractAgreementMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractAgreementVerificationMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractNegotiationEventMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractNegotiationTerminationMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractOfferMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractRequestMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/DspNegotiationApiExtensionTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractAgreementMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractAgreementVerificationMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractNegotiationEventMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractNegotiationTerminationMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractOfferMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractRequestMessageValidatorTest.java
Add `JsonObjectValidator` to negotiation DSP controller
consistency
Part of #2936 
=> feat: implement validation on negotiation DSP endpoints

DEPENDENCIES, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java
Handle `Accepted` message
dsp completion
- refactored the service protocol tests
- removed some debug logs as they are duplicated (on every update there's a debug log printed already)
Closes #3374 
=> feat: handle ContractNegotiationEventMessage.ACCEPTED message

.github/release.yaml
Updates release.yml file to add a `dependencies` category.
Also moved the `*` to the end, because it was avoiding the `documentation` group to be shown.
Removed the `dependabot` exclusion, firstly because it was not working (as dependabot PR are actually shown in the release notes), ans secondly because it's good to show them as dependency updates are important changes.
- if this file works out for everybody, I will spread it to all the other repos.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing …
=> build: update release.yml file

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java, system-tests/e2e-transfer-test/control-plane/build.gradle.kts, system-tests/e2e-transfer-test/data-plane/build.gradle.kts, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
Send correlationId and not transfer process id in the protocol messages
fix bug
- I enhanced the e2e transfer tests by making the TP going to COMPLETED, this was done adding the `control-plane-api` and `control-plane-api-client` to the runtimes
- **question 1**: given that we have this control-plane to data-plane communication I wonder if we need the `statusChecker` at all. From an hi level perspective it is correct that the data plane has the knowledge about the transfer completion, this will download some responsibilities from the control-plane
- **question 2** Currently as specified in #3334 not everyone is aware that there's this communication layer between CP and DP so I was wondering if it would be better to get rid of the `NoopTransferProcessClient` to clearly state that a DP needs …
=> fix: send correlation id as process id in the transfer messages

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java, spi/common/core-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java
Handles the `ContractRequestMessage` on an already existing negotiation.
dsp completion
- added a `recover` method on `AbstractResult` that will execute the mapping function when the result is failed, otherwise will do nothing. [Inspired by vertx Future.recover function](https://vertx.io/docs/apidocs/io/vertx/core/Future.html#recover-java.util.function.Function-)
Closes #3380 
=> feat: handle ContractRequestMessage on an already existing negotiation

core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/ProcessorImpl.java, core/common/state-machine/src/test/java/org/eclipse/edc/statemachine/ProcessorImplTest.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
Add a `onNotProcessed` listener on `Processor`, this will permit to define a unique post not-processed entity behavior, that is always a break lease, because there shouldn't be any leased entity after a state machine iteration.
This refactor will permit to centralize this behavior in a single place instead of having it spread over multiple methods/classes.
refactoring
Pre-refactoring for issue #3401  …
=> refactor: add onNotProcessed handler on Processor

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
Add counter party validation on all DSP messages
consistency
Shouldn't we also break lease in case of conflict or other error case? e.g.
https://github.com/eclipse-edc/Connector/blob/73d53586a6bb82e083de3dbd6b469e006111b39a/core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java#L172-L184
Closes #3397 
=> feat: adds counter party validation on all DSP messages

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java, spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/PolicyRegistrationTypes.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/ContractOfferId.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreement.java, spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/ContractOfferIdTest.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/TestFunctions.java, system-tests/e2e-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
Renamed `ContractId` to `ContractOfferId` and used it only for building/parsing contract offer ids, avoiding the use on `ContractAgreement`
Interoperability, furthermore contract agreement id does not need to contain information about the contract definition and asset id (the agreement itself already contains asset id and the whole policy)
- deprecated the old one
Closes #3403 
=> fix: specialize `ContractId` only for offers, not agreements

DEPENDENCIES, extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java, extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/model/ApiCoreSchemaTest.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java, extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApi.java
Adds example on `ApiErrorDetail` on api specs 
documentation
Closes #3393 
=> docs: add example for failing responses on api specs

core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/MandatoryArray.java, core/common/validator-core/src/test/java/org/eclipse/edc/validator/jsonobject/JsonObjectValidatorTest.java, extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/DataPlaneInstanceSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/SelectionRequestSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/TestFunctions.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneApiSelectorTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneSelectorApiControllerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidatorTest.java, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/client/RemoteDataPlaneSelectorClientTest.java
Adds the `@context` in the `addEntry` API example 
docs
- Added tests + validation on `addEntry` API
Closes #3421
=> docs: dataplanes api docs fix 

DEPENDENCIES, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImpl.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImplTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowControllerTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowController.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowManager.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
Add priority on `DataFlowController` registration
to permit having multiple `DataFlowController`s that could be chosen for a particular transfer, and having other used as fallback.
This is useful when there's, for example, the `ProviderPushDataFlowController` that pretty much can transfer anything but there's a specific `DataFlowController` for a particular `source`-to`destination` transfer that will be chosen first if the priority set is bigger. 
- simplified the interface methods on `DataFlowManager` and `DataFlowController`, now they accept the whole `TransferProcess` object.
Closes #3414 …
=> feat: add priority on `DataFlowController` registration

.github/workflows/apidoc.yaml
Call the `setdefault` cli command to set the default spi version after release
Closes #3435
=> build: set default version after api spec publish

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
Avoid illegal status on `TransferProcess` state machine by filtering by type on state machine processes.
Avoid wasting state machine cycles.
- use `correlationId` instead of `id` on `ConsumerContractNegotiationManagerImpl`, practically it's the same thing, but it's conceptually more correct.
Closes #3404
=> refactor: avoid illegal status in state machines

extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApi.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneSelectorApiControllerTest.java, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/client/RemoteDataPlaneSelectorClientTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
Returns `IdResponse` in the  `POST /v2/dataplanes`  API.
consistency
Closes #3352 
=> feat: add IdResponse on addEntry API

.github/workflows/trigger_snapshot.yml
Publishes snapshot artefacts directly from GHA using the reusable workflow from the `.github` repo.
reusability, better integration with GHA
Closes https://github.com/eclipse-edc/.github/issues/71
=> feat(build): publish directly from GHA using a reusable WF

extensions/common/api/api-observability/README.md
Removes the "recommended" docker base image from the docs.
the specific base image is not relevant here and should not be misconstrued as recommendation
Closes #3333
=> chore(docs): remove specific docker base image from readme

extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java, spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
Adds an update statement for the DataAddress to the `SqlAssetIndex` whenever the Asset is updated.
DataAddresses could only be updated through a separate method on the AssetIndex, which was never invoked through the v3 AssetApiController.
.
Closes #3469 
=> fix: update DataAddress in SqlAssetIndex

extensions/common/api/control-api-configuration/README.md, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/api/client/ControlPlaneApiClientExtension.java
Adds docs for `edc.control.endpoint` which is needed for notify the CP once the transfer has finished at the DP level.
documentation
Removes also `@Provides(TransferProcessApiClient.class)` not needed since there is a `Provider` annotation.
=> docs: add control api endpoint 

extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java
Adds `baseUrl` to the input/output examples for the creation of an asset in the v3 API.
Current example will be rejected with a `400 Bad Request`
Closes #3476
=> fix(api): add `baseUrl` to asset examples for v3 API

DEPENDENCIES, core/common/jersey-providers/src/main/java/org/eclipse/edc/web/jersey/jsonld/JerseyJsonLdInterceptor.java, core/common/jersey-providers/src/test/java/org/eclipse/edc/web/jersey/jsonld/JerseyJsonLdInterceptorTest.java, data-protocols/dsp/dsp-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/api/configuration/DspApiConfigurationExtension.java, data-protocols/dsp/dsp-http-core/build.gradle.kts, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/serialization/JsonLdRemoteMessageSerializerImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/serialization/JsonLdRemoteMessageSerializerImplTest.java, data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspConstants.java, extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java, extensions/common/json-ld/src/test/resources/schema-org-light.jsonld, extensions/common/json-ld/src/test/resources/test-org-light.jsonld, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/client/RemoteDataPlaneSelectorClientTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/JsonLd.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
Add configurable JSON-LD namespaces/prefix according to the DR #3509 
Flexibility and clean API
Still not sure about the management API scopes. For now only the base `edc` and the `odrl` are registered there,
bit the mgmt catalog API might speak also `dcat` and `dct`. As today we just forward the JSON-LD from the provider without touching it, so at code level it works and we might not care for now. 
Implements #3508
=> feat: add configurable JSON-LD namespaces/context for each scope

DEPENDENCIES, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/policy/ContractExpiryCheckFunction.java, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/policy/ContractExpiryCheckFunctionEvaluationTest.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java, core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/PolicyMonitorExtension.java, core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/manager/PolicyMonitorManagerImpl.java, core/policy-monitor/policy-monitor-core/src/test/java/org/eclipse/edc/connector/policy/monitor/PolicyMonitorExtensionTest.java, core/policy-monitor/policy-monitor-core/src/test/java/org/eclipse/edc/connector/policy/monitor/manager/PolicyMonitorManagerImplTest.java
Define a new `policy.monitor` scope that will be used by the policy monitor, on which the `ContractExpiryCheckFunction` is defined by default
policy monitor
Closes #3482 
=> feat: define `policy.monitor` policy scope

DEPENDENCIES, core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/manager/PolicyMonitorManagerImpl.java, core/policy-monitor/policy-monitor-core/src/test/java/org/eclipse/edc/connector/policy/monitor/manager/PolicyMonitorManagerImplTest.java
Check the `TransferProcess` state on every iteration, if it is completed/terminated/deprovisioned by other processes or user actions, move the `PolicyMonitorEntry` to `COMPLETED`
policy monitor
-
Closes #3506 
=> feat: stop policy monitor job when transfer is already completed/terminated

extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java, extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchema.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/JsonLdExtensionTest.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApi.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/DataPlaneInstanceSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/SelectionRequestSchema.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractAgreementApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractDefinitionApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Registers `@vocab` context definition (with the `https://w3id.org/edc/v0.0.1/ns/` value) at the global scope
To have consistent output jsonld responses
- this way, every json-ld produced by the edc won't have the "edc:" prefix in the edc namespaced properties
- as this could be considered as a breaking change (but technically it is not because the compacted json-ld responses will expand in the same way as the old ones) I added a `edc.jsonld.vocab.disable` that could be used to switch to the old behavior.
Closes #3525 
Closes #3522 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquet …
=> feat: register @vocab context definition

DEPENDENCIES, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/DataAddressToEndpointDataReferenceTransformer.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/DataAddressToEndpointDataReferenceTransformerTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImplTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullDataPlaneProxyResolver.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/proxy/ConsumerPullDataPlaneProxyResolverTest.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverTest.java, extensions/control-plane/transfer/transfer-pull-http-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/HttpEndpointDataReferenceReceiverTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java, spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReferenceTest.java
Duplicate the content of the `cid` claim in the access token generated for accessing the Data Plane into a dedicated field of `EndpointDataReference`.
Prevent collision in the access token if `cid` claim is already taken.
Closes #3477 
=> feat: add `contractId` to `EndpointDataReference`

DEPENDENCIES, extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVault.java
Add warning log to Hashicorp Vault `resolveSecret` function.
If the secret cannot be resolved, it is currently difficult to find out why. 
The log should help the developer to find the bug faster.
Closes #3462
=> feat: Add warning log to Hashicorp Vault resolveSecret function

extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java
In the `JettyService` class I have adjusted the `HttpConnectionFactory` and disabled the Jetty server version via the `HttpConfiguration`.
As mentioned in #3415, this issue can lead to a potential attacker finding a vulnerability in Jetty more quickly.
Closes #3415
=> fix: Disable jetty server version

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DefaultTrustedIssuerRegistry.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/DefaultTrustedIssuerRegistryTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/validation/rules/HasValidIssuer.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/validation/rules/HasValidIssuerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToIssuerTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/TestData.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToIssuerTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiablePresentationTransformerTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/TrustedIssuerRegistry.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/Issuer.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/VerifiableCredential.java, spi/common/identity-trust-spi/src/test/java/org/eclipse/edc/identitytrust/model/VerifiableCredentialTest.java, spi/common/identity-trust-spi/src/testFixtures/java/org/eclipse/edc/identitytrust/TestFunctions.java
This PR adds an extensible registry of trusted issuers plus a default in-mem implementation. In order to do that, the following additions/changes were necessary:
- introduce new `Issuer` class
- introduce a new `JsonObjectToIssuerTransformer`
- change `VerifiableCredential#issuer` from `Object` to `Issuer`
We need a possibility to contribute multiple trusted issuers in a dataspace, e.g. multiple govt. agencies and private companies.
- changed the wording from "allowed" to "trusted"
- other implementations could download that list of trusted issuers from some remote location
Closes #3531 …
=> feat: extensible trusted-issuer-registry

extensions/common/iam/identity-trust/identity-trust-sts-api/build.gradle.kts, extensions/common/iam/identity-trust/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/SecureTokenServiceApi.java, extensions/common/iam/identity-trust/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/controller/SecureTokenServiceApiController.java, extensions/common/iam/identity-trust/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/model/StsTokenErrorResponse.java, extensions/common/iam/identity-trust/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/model/StsTokenRequest.java, extensions/common/iam/identity-trust/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/model/StsTokenResponse.java, extensions/common/iam/identity-trust/identity-trust-sts-api/src/test/java/org/eclipse/edc/connector/api/sts/model/StsTokenErrorResponseTest.java, extensions/common/iam/identity-trust/identity-trust-sts-api/src/test/java/org/eclipse/edc/connector/api/sts/model/StsTokenResponseTest.java, settings.gradle.kts
Define the REST API for getting the Self-Issued ID token from the STS using OAuth2 client credentials flow
iatp adoption
Closes #3498 
=> feat: STS API spec

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/verification/JsonLdPresentationVerifier.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/verification/JwtPresentationVerifier.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/verification/MultiFormatPresentationVerifier.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/verification/SelfIssuedIdTokenVerifier.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/JwtCreationUtils.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/JwtPresentationVerifierTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/SelfIssuedIdTokenVerifierTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/TestData.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiablePresentationTransformer.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/verification/JwtVerifier.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/verification/PresentationVerifier.java, spi/common/identity-trust-spi/src/testFixtures/java/org/eclipse/edc/identitytrust/TestFunctions.java
This PR adds the cryptographic verification of VerifiablePresentations for the following formats:
- JSON-LD: verification is done based on LinkedDataProofs (**edit: will come in another PR**)
- JWT: verification is done based on JWS
Verifiers (e.g. a provider connector) must be able to ensure the cryptographic integrity of a presenter's VP
VPs must be homogenous, i.e. if a VP is presented as JWT, it may only contain VC's that are also encoded as JWT. 
**This is a restriction imposed by the [Verfiable Credentials Data Model v1.1](https://www.w3.org/TR/vc-data-model/#json-web-token-extensions).**
Closes #3533 …
=> feat: verification of (consumer) VP (VC-JWT)

extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSink.java, extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/DataSourceToDataSinkTests.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/pipeline/MultipleBinaryPartsDataSource.java
This PR introduces a test case to verify the loss of messages by HttpSink under various partitioning conditions.
This PR removes an early return statement in the partition transfer loop of HttpSink which leads to the loss of messages.
Currently, HttpSink looses messages even in completely deterministic settings. It may only be safely applied with partition.size=1
Closes #3417
=> fix: data-plane-http - HttpSink loosing messages #3417 

extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/ApiCoreSchema.java, extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultHealthCheck.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultHealthCheckTest.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApi.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/DataPlaneInstanceSchema.java
Add `required` attribute where needed on the input schema objects for management api
documentation
- 2 update methods were marked with a `200` status code but they are actually returning `204`
- added `@context` objects as well, marked as required.
- remove flooding debug log
Closes #3552
=> docs: add required field documentation on management api

extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiSchema.java, extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java
Adds the `FreeFormPropertiesSchema` type for openapi documentation
It will better describe the properties field, that are not strictly `string -> object`, but `string -> any` (in java there's no difference, but in the openapi domain there is)
Also part of #3552 
=> docs: add free form properties schema type

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlowStates.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
Adds a `TERMINATED` state on the `DataFlow`, to distinguish between a completed data flow (when the data plane completed it) and a terminated one (when the data flow gets stopped by an external actor, like the policy manager).
policy monitor
- this should fix the flaky end to end kafka that failed from time to time in the last weeks
PArt of #3422 
=> feat: improve DataFlow termination

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlowStates.java
Transition `DataFlow` to `STARTED` when the transfer gets started
Avoid multiple transfers start
Closes #3563 
=> fix: transition DataFlow to started when transfer starts

core/common/util/build.gradle.kts, core/common/util/src/main/java/org/eclipse/edc/util/reflection/ReflectionUtil.java, core/common/util/src/test/java/org/eclipse/edc/util/reflection/ReflectionUtilTest.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplIntegrationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java, core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/asset/CriterionToAssetPredicateConverterImpl.java, core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldMapping.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/TranslationMapping.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/SqlQueryStatementTest.java, extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlLocalInstance.java, extensions/control-plane/store/sql/asset-index-sql/README.md, extensions/control-plane/store/sql/asset-index-sql/docs/schema.sql, extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java, extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/AssetStatements.java, extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/BaseSqlDialectStatements.java, extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/postgres/AssetMapping.java, extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/PathItem.java, spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/PathItemTest.java, spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/asset/AssetService.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/PostgresUtil.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
Permits to query over nested properties in Asset.
To do that, the notation should be, e.g.:
```
{
"edc:operandLeft": "'https://w3id.org/edc/v0.0.1/ns/nested'.'https://w3id.org/edc/v0.0.1/ns/key'",
"edc:operator": "=",
"edc:operandRight": "value"
}
```
to navigate through the property tree, the wrapping `'` are needed to clearly separate path items (because keys could contain the `.`).
Current behavior without wrapping `'` for a not nested property is still valid.
fix bug
- refactored the asset related sql tables, now collapsed into a single table with JSON fields. **THIS IS A BREAKING CHANGE**. please refer to the `asset-index-sql` extension README to get migration instructions.
- removed the unused `updateDataAddress` method from `AssetService` 
Closes #3423 
_Please be sure to take a …
=> fix: permit query `Asset` json properties

extensions/common/iam/identity-trust/identity-trust-core/build.gradle.kts, spi/common/identity-trust-spi/build.gradle.kts, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/CredentialStatus.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/VerifiablePresentationContainer.java
Breaks coupling between `identity-trust-spi` and `json-ld-spi.`
Closes #3579
=> chore: Break coupling between `identity-trust-spi` and `json-ld-spi`

spi/common/oauth2-spi/build.gradle.kts, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressValidator.java, spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressValidatorTest.java
The `oauth2-spi` should not reference `data-address-http-data-spi` since the latter is an implementation detail of a data reference.
Closes #3583
=> chore: Decouple `oauth2-spi` from `data-address-http-data-spi`

core/control-plane/control-plane-aggregate-services/build.gradle.kts, spi/control-plane/control-plane-spi/build.gradle.kts
This PR removes the following unused dependencies from the `control-plane-spi` module:
- api(project(":spi:control-plane:transfer-data-plane-spi"))
- api(project(":spi:control-plane:policy-spi"))
- api(project(":spi:control-plane:asset-spi"))
Closes #3587
=> chore: Remove unused dependencies from `control-plane-spi`

DEPENDENCIES, docs/developer/decision-records/2023-11-09-api-versioning/README.md, docs/developer/decision-records/README.md
Adds a decision record about API versioning.
Transparent decision traces.
=> docs: decision record about API versioning

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IatpScopeExtractorExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultTrustedIssuerRegistry.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/InMemorySignatureSuiteRegistry.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorFunction.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorRegistry.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorVisitor.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IatpScopeExtractorExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultTrustedIssuerRegistryTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorFunctionTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorRegistryTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/scope/ScopeTestFunctions.java, spi/common/identity-trust-spi/build.gradle.kts, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/scope/ScopeExtractor.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/scope/ScopeExtractorRegistry.java
Add pluggable constraints to scope mapping:
-  Introduces `ScopeExtractorRegistry` for registering custom extractors.
- Implements `IatpScopeExtractorFunction` and register it as pre-validator in the policy engine for invoking estractors in the registry and map the result in the `scope`
`ScopeExtractor` for now are not tied to a specific `scope` or `rule`.
iatp adoption
Closes #3492 
=> feat(IATP): pluggable constraint to scope mapping

extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSource.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java
Set http sink partition size to 1 for the `EndToEndKafkaTransferTest`
Avoid test flakiness, the default partition size to 5 caused messages to be sent to the consumer slightly after termination, causing test failure.
- changed the implementation of the `next()` method in the `ConsumerRecordsIterator` because most of the time was doing duplicated pulls for a single `next()` call.
=> build: fix flaky test

extensions/common/iam/identity-trust/identity-trust-issuers-configuration/README.md, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/build.gradle.kts, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/main/java/org/eclipse/edc/identitytrust/issuer/configuration/TrustedIssuerConfigurationExtension.java, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/test/java/org/eclipse/edc/identitytrust/issuer/configuration/TrustedIssuerConfigurationExtensionTest.java, settings.gradle.kts
Adds an extension for configuring the list of trusted issuer in the `TrustedIssuerRegistry`
iatp adoption
Closes #3602
=> feat(IATP): configurable trusted issuers

extensions/common/auth/auth-tokenbased/src/main/java/org/eclipse/edc/api/auth/token/TokenBasedAuthenticationService.java, extensions/common/auth/auth-tokenbased/src/test/java/org/eclipse/edc/api/auth/token/TokenBasedAuthenticationServiceTest.java
This PR disallows the use of multiple `x-api-key` headers to avoid Header Duplication Exploitation.
I honestly don't know why issuing 100 billion requests is harder than 1 billion requests with 100 headers each, but a 
security report has been filed.
.
Closes https://github.com/eclipse-tractusx/tractusx-edc/security/advisories/GHSA-wqpq-r4w2-5q5x
=> fix: disallow multiple auth headers

README.md
Changes the release approach link to up-to-date one.
The current link points to nothing.
Closes #3598
=> fix(docs): adjust release approach link

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java
This PR fixes a bug, where the `PresentationVerifier` was `@Injected` in the same extension, where it id also `@Provider`-ed.
Previously, we had a default provider for the `PresentationVerifier`, which was a dummy. 
=> fix: create PresentationVerifier (no inject)

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-transform/build.gradle.kts, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/resources/presentation_ex.json, extensions/common/iam/identity-trust/identity-trust-transform/src/test/resources/presentation_query.json, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/VcConstants.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/credentialservice/InputDescriptorMapping.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/credentialservice/PresentationQuery.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/credentialservice/PresentationResponse.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/credentialservice/PresentationSubmission.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/presentationdefinition/Constraints.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/presentationdefinition/Field.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/presentationdefinition/FilterExpression.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/presentationdefinition/Format.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/presentationdefinition/InputDescriptor.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/presentationdefinition/PresentationDefinition.java, spi/common/identity-trust-spi/src/test/java/org/eclipse/edc/identitytrust/model/credentialservice/PresentationSubmissionSerDesTest.java
This PR moves most of the commonly used IATP model classes up into EDC from the IdentityHub. Most notably:
- model classes that are used to query the CredentialServce (=IdentityHub)
- Transformers for the model classes
- constants
The model classes will be shared by the connector and IdentityHub
- This PR does not introduce any functional changes, only moves classes from one repo to another
- once this PR is merged, the classes will be deleted from IdentityHub
=> chore: moved IATP model classes up from IdentityHub

extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApi.java
By removing unnecessary `@Path` annotation from the api interface
documentation
Closes #3613
=> docs: remove duplicated /select endpoint from api spec

DEPENDENCIES, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/JsonLdExtensionTest.java, extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java
This PR caches registered linked documents in memory for easy access.
speeding up the expansion process
Closes #3619
=> feat: cache registered LD documents in memory

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceIntegrationTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSink.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/TransferService.java
This PR brings back the overloaded method in the `DataPlaneManager` that takes a `DataSink` parameter.
If specified, the `DataPlaneManager`(`Impl`) will immediately delegate to the `PipelineService`.
This effectively restores the behaviour before #3486
For streaming, e.g. HTTP, we need to be able to supply just any random data sink …
=> feat: bring back the custom DataSink overload

core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformer.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractOfferTransformer.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractRequestTransformer.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidator.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractOfferTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractRequestTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidatorTest.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java, extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/README.md, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java, system-tests/telemetry/telemetry-test-runner/src/test/java/org/eclipse/edc/test/e2e/tracing/TracingEndToEndTest.java
Map the new `policy` field to `ContractOffer`
avoid null pointer exceptions, because `ContractOffer` cannot be missing in a `ContractRequest` object.
- make all the test use the new fields defined (`policy`, `counterPartyAddress`) instead of the deprecated ones
- policy transformer now sets the `target` as an `@id`, as requested by the [ODRL information model](https://www.w3.org/TR/odrl-model/#policy-has)
Closes #3624 
=> fix: transform policy to contract offer

DEPENDENCIES, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/DidCredentialServiceUrlResolver.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/DidCredentialServiceUrlResolverTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/CredentialServiceUrlResolver.java
This PR adds a pluggable `CredentialServiceUrlResolver`, whos job it is to take an issuer, and resolve its CredentialService URL.
The default implementation in IATP for this will be a `DidCredentialServiceUrlResolver`, that interprets the issuer as DID and
resolves the DID, which is expected to contain a `CredentialService` endpoint entry.
The relying party (RP) needs to be able to resolve the counter-party's CredentialService to obtain VCs.
Closes #3647
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.m …
=> feat: create pluggable CredentialService url resolver

system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java
This PR should fix the test `EndToEndKafkaTransferTest#kafkaToHttpTransfer` which currently fails sometime.
I've tracked down the reason and it seems due the fact that even though at consumer side the transfer is terminated
and on the provider side the data source is closed, there could be some stream records still waiting to be pushed via HTTP.
The fix is in the assert lambda clear the expectations on the `destinationServer` if the verify fails.
fix flaky test
=> chore: fix Kafka flaky test

extensions/common/crypto/crypto-core/src/main/java/org/eclipse/edc/verification/jwt/SelfIssuedIdTokenVerifier.java, extensions/common/crypto/crypto-core/src/test/java/org/eclipse/edc/verification/jwt/SelfIssuedIdTokenVerifierTest.java, extensions/common/crypto/jwt-verifiable-credentials/build.gradle.kts, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifierTest.java, extensions/common/crypto/jwt-verifiable-credentials/src/testFixtures/java/org/eclipse/edc/verifiablecredentials/TestFunctions.java, extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImpl.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImplTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/MultiFormatPresentationVerifierTest.java, spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/resolution/DidPublicKeyResolver.java
This PR changes the public key resolution, in that the `kid` is only required, if the DID contains multiple verification methods.
Taking the _first_ verification method if no `kid` is given is dangerous and wrong.
- In addition, the `JwtPresentationVerifier` now uses the `DidPublicKeyResolver` instead of the `DidResolverRegistry`, which is better, because it limits the API surface
Closes #3649
=> fix: require key-id when resolving key material

DEPENDENCIES, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityTrustTransformExtension.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/IdentityTrustTransformExtensionTest.java
Adds missing type transformer registrations
Well... they were missing.
Closes #3648
=> fix: add missing type transformer registrations

extensions/common/crypto/crypto-core/src/test/java/org/eclipse/edc/verification/jwt/SelfIssuedIdTokenVerifierTest.java, extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/JwkMethod.java, extensions/common/crypto/jws2020/src/main/java/org/eclipse/edc/security/signature/jws2020/Jws2020SignatureProvider.java, extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/DidMethodResolver.java, extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidResolverRegistryImpl.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImplTest.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidResolverRegistryImplTest.java, extensions/common/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/edc/iam/did/service/BaseDecentralizedIdentityServiceTest.java, extensions/common/iam/decentralized-identity/identity-did-web/src/main/java/org/eclipse/edc/iam/did/web/resolution/WebDidResolver.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/document/VerificationMethod.java, spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/resolution/DidResolverRegistry.java
This PR adds the `DidMethodResolver`, that implements the `MethodResolver` interface, so that it can be used in the `LdpVerifier`.
The `DidMethodResolver` delegates DID resolution to the `DidResolverRegistry`.
Avoid code duplication: previously the `LdpVerifier` used a class from the Titanium library, which in addition to duplicating code, was hard coded, and not pluggable.\
- The `VerificationMethod` received a new method `serializePublicKEy`, and the ability to contain Multibase public keys.
- The `DidResolverRegistry` received a new method `isSupported`
- the `JwkMethod` class has been adapted to use the same serialization method (JSON)
Closes #3646
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-p …
=> feat: create DidMethodResolver for use in the LdpVerifier

extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/LdpVerifier.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/validation/SelfIssuedIdTokenValidator.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/validation/SelfIssuedIdTokenValidatorTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/core/defaults/service/StsClientTokenGeneratorServiceImpl.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/core/defaults/StsClientTokenIssuanceIntegrationTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/main/java/org/eclipse/edc/iam/identitytrust/sts/embedded/EmbeddedSecureTokenService.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/test/java/org/eclipse/edc/iam/identitytrust/sts/embedded/EmbeddedSecureTokenServiceIntegrationTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenService.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenServiceTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/SelfIssuedTokenConstants.java, spi/common/identity-trust-spi/src/testFixtures/java/org/eclipse/edc/identitytrust/TestFunctions.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/RemoteStsEndToEndTest.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsApiEndToEndTest.java
This PR extends the `IdentityAndTrustService` and generates another SI token on the relying-party side 
which is then used to execute the VP query against the counter-party's CredentialService (= presentation endpoint).
Complete the circle of the presentation flow
- **Be aware that currently we need to parse the `access_token` to get the `scope` string. This is a workaround, until we can extract the scope from the verification context. This behaviour will change in subsequent developments and is only there for the immediate future. The related code has been marked accordingly.**
- the `access_token` constant was renamed to `PRESENTATION_ACCESS_TOKEN_CLAIM` and is now used everywhere
- this PR also adds the temporary `AudienceResolver` object, which maps a DSP url to an audience, which can …
=> feat: relying-party creates SI token for VP query

DEPENDENCIES, docs/developer/decision-records/2023-11-27-refactor-protocol-services/README.md, docs/developer/decision-records/README.md
Adds a Decision Record about moving the security checks (`IdentityService#verifyJwtToken`) from the DSP layer
to the protocol service layer.
This refactor will allow us to attach contextual information of the current DSP request that can be used in `IdentityService` implementations.
Relates #3662 
=> docs: decision record about Protocol Services refactor

DEPENDENCIES, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/store/ReflectionBasedQueryResolver.java, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/store/ReflectionBasedQueryResolverTest.java, core/common/util/src/main/java/org/eclipse/edc/util/uri/UriUtils.java, core/common/util/src/test/java/org/eclipse/edc/util/uri/UriUtilsTest.java, extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/DidMethodResolver.java, extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/LdpVerifier.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiablePresentationTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryTransformerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/TokenParameters.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QueryResolver.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/credentialservice/PresentationQuery.java
This PR adds several minor features and fixes for IATP:
- extracts a `ClaimToken` from a VC
- performs URI comparison without fragment when comparing Issuer and VerificationMethod
- fixes a wrong extracton of DID#VerificationMethod.controller and DID#VerificationMethod.type
- adds a customizable accumulator operation to the predicate-based query resolver
Closes #3650 …
=> feat: various minor improvements / patches for IATP

data-protocols/dsp/dsp-api-configuration/build.gradle.kts, data-protocols/dsp/dsp-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/api/configuration/DspApiConfigurationExtension.java, data-protocols/dsp/dsp-api-configuration/src/test/java/org/eclipse/edc/protocol/dsp/api/configuration/DspApiConfigurationExtensionTest.java, data-protocols/dsp/dsp-http-core/build.gradle.kts, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/message/DspRequestHandlerImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtensionTest.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/message/DspRequestHandlerImplTest.java, data-protocols/dsp/dsp-http-spi/build.gradle.kts, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/error/DspErrorResponse.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiController.java
- move `DspRequestHandlerImpl`  into `dsp-http-core` module.
- move `DspErrorResponse` into `dsp-http-spi` module.
preparatory refactor for #3662 
=> chore: refactor move DspRequestHandlerImpl 

core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/protocol/BaseProtocolService.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractdefinition/ContractDefinitionEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/DspHttpCoreExtension.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/message/DspRequestHandlerImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/message/DspRequestHandlerImplTest.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/message/DspRequest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java, extensions/common/iam/iam-mock/src/main/java/org/eclipse/edc/iam/mock/MockIdentityService.java, extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/catalog/CatalogProtocolService.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractnegotiation/ContractNegotiationProtocolService.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessProtocolService.java
Implements the refactor outlined in DR #3665 
Decoupling the net protocol from the security checksm which are now delegated to the protocol service layer.
This also will allow use to attach contextual information to the verification process.
In this PR since we are pushing here the invocation of the `IdentityService` we don't know the audience here/ The audience removal will be tackle in subsequent PRs. 
`IdentityService` that relies on this parameter would not work for the time being.
Closes #3667 
=> refactor: moved security checks in protocol service layer

extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/JsonLdExtensionTest.java
Fixes issue JSON-LD Unit tests fail on Windows #3408 
The URI is asserted against the value: "file:/tmp/foo/doc.json" but on Windows the value will include the drive name such as: "file:/C:/tmp/foo/doc.json".
Implemented suggested fix  to replace:
`assertThat(cache).containsEntry("http://foo.org/doc.json", new URI("file:/tmp/foo/doc.json"));`
With:
`assertThat(cache).containsEntry("http://foo.org/doc.json", new File("/tmp/foo/doc.json").toURI());`
If not fixed the bug prevents building connector with extensions on Windows systems. 
Closes #3408
=> fix(test): JSON-LD Unit tests fail on Windows

core/control-plane/catalog-core/build.gradle.kts, core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/CatalogDefaultServicesExtension.java, core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java, core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DefaultDistributionResolver.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java, core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DefaultDistributionResolverTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImplTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowControllerTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowController.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowManager.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/FlowType.java
Makes `Catalog`'s `Distribution` list being built by the knowledge of the `DataFlowManager`, because that's where the supported transfer types knowledge is stored.
This is the `DataFlowController` details:
- the `ProviderPush` will get the distributions out of the `DataPlaneInstance`s registered on the connector and associate them with the `PUSH` flow type
- the `ConsumerPull` for the moment will only return a single `Http-PULL` type, in the future it will be able to provide other pull mechanism as well (ref. #3637)
interoperability
-
Closes #3631
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contrib …
=> refactor: create distributions from `DataFlowManager` transfer types

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImplTest.java
Add missing transaction block on `CatalogService`
To ensure that all the database calls are finalized correctly
- to better handling `Stream` over cursor all the service will always return only collected iterables and not streams, and the operations will be wrapped by transaction blocks, that will take care of finalizing the connections. 
Closes #3640 
=> fix: add missing transaction block on `CatalogService`

extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/ConnectionFactory.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/DriverManagerConnectionFactory.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/SqlCoreExtension.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/SqlQueryExecutor.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/datasource/ConnectionFactoryDataSource.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/SqlQueryExecutorIntegrationTest.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/datasource/ConnectionFactoryDataSourceTest.java, extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlLocalInstance.java, extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlStoreSetupExtension.java, extensions/common/sql/sql-lease/src/test/java/org/eclipse/edc/sql/lease/PostgresLeaseContextTest.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPool.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/DriverManagerConnectionFactoryTest.java, extensions/common/transaction/transaction-local/build.gradle.kts, extensions/control-plane/store/sql/control-plane-sql/build.gradle.kts, spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/PostgresUtil.java
Postgres tests are using mocks and not real connections/connections factory. This makes certain issues harder to discover.
This PR removes mocks from `PostgresqlStoreSetupExtension`
test scope
Work done in the process of debugging #3640 
=> refactor: make postgresql integration tests use real components

.github/workflows/apidoc.yaml
- create & publish new `public-api` swagger hub page
- APIs which are publicly exposed (example: `DataPlanePublicApi)` should not be grouped under `control-api` or `management-api`. Therefore a new API group is necessary
Closes #3373
=> feat: add public api swagger hub page

spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/document/DidDocument.java
Moves adding the default JSON-LD context for DID documents to the builder method
Doing this hard-coded in the field initializer can cause problems when deserializing, for example 
when restoring a `DidDocument` from persistence.
=> chore: move adding the default DID context to builder

DEPENDENCIES, extensions/common/auth/auth-tokenbased/src/test/java/org/eclipse/edc/api/auth/token/TokenBasedAuthenticationExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtensionTest.java, extensions/control-plane/callback/callback-static-endpoint/src/test/java/org/eclipse/edc/connector/callback/staticendpoint/CallbackStaticEndpointExtensionTest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpWebhookExtensionTest.java, extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndexServiceExtensionTest.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtensionTest.java, extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtensionTest.java, spi/common/policy-model/build.gradle.kts
Fix compilation errors caused by https://github.com/eclipse-edc/GradlePlugins/pull/200 
=> fix: compilation

spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/CredentialSubject.java, spi/common/identity-trust-spi/src/test/java/org/eclipse/edc/identitytrust/model/CredentialSubjectTest.java
This PR changes the serialization/deserialization of a `CredentialSubject` in that it avoids 
serializing claims to a JSON `claims` object.
It is an implementation detail that the structure of the `CredentialSubject` is kept in a `claims` map. Java simply 
does not handle dynamic types, and in it is not relevant for the serialized form. …
=> chore: map claims of CredentialSubject during SerDes

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/store/CriterionToPredicateConverterImpl.java, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/store/ReflectionBasedQueryResolver.java, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/store/CriterionToPredicateConverterImplTest.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SqlConditionExpression.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SqlQueryStatement.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/SqlQueryStatementTest.java
This PR adds an overloaded constructor for the `SqlQueryStatement` class that allows 
to disable the operator checking. 
That means, that the `SqlQueryStatement` won't throw an `IllegalArgumentException` anymore when it encounters
a supposedly illegal operator.
Postgres has some very specific operators, such as the `?`, which can be used for JSONB (not JSON!) types. The `?` can be used to comfortably check if a value occurs in a JSON array:
```sql
SELECT *
FROM sometable
WHERE (someJsonColumn -> 'stringarray_prop')::jsonb ? 'someval_that_occurs_in_the_array';
```
Check out [this stackoverflow article](https://stackoverflow.com/a/27144175/7079724) for another example.
Now, since we do strict checks on `=`, `in`, `like`, constructing such a query would not be possible. 
- It would have been …
=> feat: allow unchecked SQL operators

DEPENDENCIES, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/EdcHttpClientImplTest.java, spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/FallbackFactories.java
Removes request logging on `FallbackFactories`
Closes #3709 
=> fix: remove request logging in FallbackFactories

DEPENDENCIES, docs/developer/decision-records/2023-11-20-transfer-type/README.md, docs/developer/decision-records/README.md
Adds a decision record about introduction of `Transfer Type` concept
Extensibility of the `DataFlowManager` and `DataFlowController`, in preparation for #3705 
Closes #3615 
=> docs: decision record about Transfer type

core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/PolicyMonitorDefaultServicesExtension.java
provide InMemoryPolicyMonitorStore as default
permits other implementations to be used
Closes #3722 
=> fix: provide InMemoryPolicyMonitorStore as default

docs/developer/data-plane-signaling/data-plane-signaling.md, docs/developer/decision-records/2023-12-12-dataplane-signaling/README.md, docs/developer/decision-records/README.md
Adds architecture documentation and a decision record covering Data Plane Signaling.
Closes #3704
=> docs: Add data plane signaling documents

DEPENDENCIES, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceConfiguration.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/rule/Oauth2ExpirationIssuedAtValidationRule.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/rule/Oauth2ValidationRulesRegistryImpl.java, extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtensionTest.java, extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/rule/Oauth2ExpirationIssuedAtValidationRuleTest.java
As discussed [here](https://github.com/eclipse-edc/Connector/issues/3692#issuecomment-1846767475), added a configurable leeway to the validation of the `issuedAt` claim in `oauth2-core`.
The validation was added due to the sensitivity to clock skew of the aforementioned `issuedAt` claim.
See the https://github.com/eclipse-edc/Connector/issues/3692 for more detail.
- Added no validation for the `expiresAt` claim as it is less sensitive to clock skew.
Closes https://github.com/eclipse-edc/Connector/issues/3692
=> fix: issuedAt now validated with leeway in Oauth2ExpirationIssuedAtValidationRule

extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
Adds configurable timeout and protocol in `Participant`
Extensibility/reusability
This PR also adds additional methods that can be useful when doing E2E tests:
- `getCatalogDatasets` with a query
- `initContractNegotiation` with asset id or a policy (just starts the contract negotiation)
- `getTransferProcesses` get transfer process with an optional query
- `getContractNegotiationState` get the state of a contract negotiaion
Since those method matching management APIs could grow. In subsequent PRs I'd suggest to start splitting those method in contexts.
For example  something like this:
`Participant#transferProcesses` all methods related to transfer processes
`Participant#negotiations` all methods related to contract negotiation
`Participant#catalog` all methods related to catalog
...etc …
=> feat: timeout and protocol configurable in Participant

DEPENDENCIES, gradle/wrapper/gradle-wrapper.properties
Looks to be necessary because there's some issue goin' on with jackson-2.16.1
dependency updates
=> build(deps): bump gradle-wrapper to 8.5

core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/RuleBindingRegistryImpl.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplScenariosTest.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/RuleBindingRegistryImplTest.java, core/common/policy-evaluator/src/main/java/org/eclipse/edc/policy/evaluator/PolicyEvaluator.java, core/common/policy-evaluator/src/test/java/org/eclipse/edc/policy/evaluator/PolicyEvaluatorTest.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/DynamicAtomicConstraintFunction.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/RuleBindingRegistry.java, spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/DynamicAtomicConstraintFunction.java
Implements [DR](https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2024-01-12-dynamic-constraint-functions) about dynamic constraint functions.
policy engine flexibility/extensibility 
Closes #3775
=> feat: dynamic constraint functions

extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/CriterionToWhereClauseConverterImpl.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/FieldTranslator.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldTranslator.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslator.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SortFieldConverter.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SortFieldConverterImpl.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/SqlQueryStatement.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/TranslationMapping.java, extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/StatefulEntityMapping.java, extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/postgres/AssetMapping.java, extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractdefinition/schema/postgres/ContractDefinitionMapping.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/postgres/ContractAgreementMapping.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/schema/postgres/ContractNegotiationMapping.java, extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/schema/postgres/PolicyDefinitionMapping.java, extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/schema/postgres/PolicyMapping.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/DataRequestMapping.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/ProvisionedResourceSetMapping.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/ResourceManifestMapping.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/postgres/TransferProcessMapping.java
second refactoring toward the solution of #3736 
in this PR the "translation" logic that was implemented in the `TranslationMapping` hierarchy has been extracted to a new interface `FieldTranslator` and its hierarchy, while `TranslationMapping` remains a simple tree data structure that can provide the `FieldTranslator` to the caller (we could find a better name for it, suggestions welcome)
now that we have the `FieldTranslator` we can add a method there that can return a `WhereClause` directly, giving the possibility to translate the whole criteria following the specific SQL implementation
Part of #3736  …
=> refactor: extract the translation logic from the TranslationMapping class

docs/developer/ids-dataspace-protocol/ids-endpoints-services-architecture.md, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApi.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/Namespaces.java
Fix the DCAT namespace IRI according to the documentation (https://www.w3.org/TR/vocab-dcat-3/#normative-namespaces)
dcat compliance
- this is a breaking change because the Catalog will be expanded in a different way than before. No issue on persistance because we don't store anything related to DCAT.
Closes #3458
=> fix: align DCAT namespace IRI to the correct one

extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
Fixes the `HttpDynamicEndpointDataReferenceReceiver` for receiving the EDR
bugfix
Closes #3788
=> fix: edr dynamic http receiver

extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImpl.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImplTest.java
Supports verification method id to be both full URL (didUrl + keyId) and relative URL (keyId)
Closes #3794
=> feat: supports verification method id as URL

DEPENDENCIES, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseSourceHttpParamsDecorator.java, extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSourceTest.java
The `method` property was mandatory when the `proxyMethod` was true, but, in fact, also if a source `DataAddress` defines that property, it could be that the same asset is used in a `PUSH` type transfer, this fix permits to do that by adding an additional check.
fix bug
- in the future (see dataplane signaling DR) this information will be taken out from the `transferType` field that will be mandatory, while the `dataDestination` won't be supplied for `pull` transfers.
Closes #3768 
=> fix: stop `method` property from being mandatory for push http transfers

extensions/common/crypto/crypto-common/src/main/java/org/eclipse/edc/security/token/jwt/CryptoConverter.java, extensions/common/crypto/crypto-common/src/test/java/org/eclipse/edc/security/token/jwt/CryptoConverterTest.java
Adds the `BouncyCastleProvider` to the JCA context when creating JWS signers and JWS verifiers.
Some curves (e.g. `secp256k1`) are not supported natively in the JDK, check https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-es256k-signature
=> chore: add BouncyCastle provider to JWSSigner and JWSVerifier

core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java
Fixes `TransferProcessEventDispatchTest#shouldDispatchEventOnTransferProcessTerminated` test which sometimes depending on the state machine failed.
flaky test
=> chore: fix TransferProcessEventDispatchTest flaky test

extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/LdpVerifier.java, extensions/common/crypto/ldp-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/linkeddata/LdpVerifierTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/InMemorySignatureSuiteRegistry.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/MultiFormatPresentationVerifierTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/main/java/org/eclipse/edc/iam/identitytrust/sts/embedded/SelfIssuedTokenDecorator.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/from/JsonObjectFromPresentationResponseMessageTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/from/JsonObjectFromPresentationResponseMessageTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/serde/PresentationResponseMessageSerdeTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/credentialservice/PresentationQueryMessage.java
minor IATP fixes for E2E tests specifically:
- `LdpVerifier` removed `SignatureSuiteProvider` and used directly `SignatureSuiteRegistry` for fetching the `SignatureSuite`
- Fix on `DefaultCredentialServiceClient`  after iatp context refactoring in #3805
- Changed the `JsonObjectFromPresentationResponseMessageTransformer` transformer for emitting correct embedded `@json` for verifiable presentation
=> chore: minor IATP fixes for E2E tests

core/common/token-core/src/main/java/org/eclipse/edc/token/JwtGenerationService.java, core/common/token-core/src/test/java/org/eclipse/edc/token/JwtGenerationServiceTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneConfig.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtension.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtensionTest.java
Add settings check to `TransferDataPlaneCoreExtension`, if the ones related to the private/public keys are missing, then the "consumer-pull" transfer won't be enabled.
avoid weird exceptions when settings are missing
- added a check also in the `JwtGenerationService` to avoid null pointer exceptions there in the case the key is not available.
Closes #3810
=> feat: disable consumer pull transfers if key settings are missing

core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/protocol/BaseProtocolService.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorFunction.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/scope/IatpScopeExtractorFunctionTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/RequestScope.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/VerificationContext.java
Introduces the policy scopes extractor in transfer process messages at protocol layers:
- Injected in all `*ProtocolService` the `policy` engine for scope extraction
- When evaluating the `policy` for the request scope the in context object has been changed from `TokenParameters.Builder`  to `RequestScope.Builder` for ingress/egress symmetry
- Now we need to fetch some additional data before verifying the actual token. To prevent possible leakage of resource presence to unauthenticated calls, all the transfer process apis returns `404` not found, in case of resource (transferprocess/contract negotiation) not present in the database and in the case token verification failure as outlined in the [spec](https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/transfer-pr …
=> feat: policy scope extractors for transfer process ingress calls

extensions/common/crypto/crypto-common/src/main/java/org/eclipse/edc/security/token/jwt/CryptoConverter.java, extensions/common/crypto/crypto-common/src/test/java/org/eclipse/edc/security/token/jwt/CryptoConverterTest.java
This PR an overload taking a `keyId` parameter to the `CryptoConverter#createJwk()` method
Usually, the resulting JWK should have a `kid` property, to make it identifiable, e.g. in DID documents.
- I also reordered some methods in `CryptoConverter` to have publics first, and privates further down in the file.
- 
=> fix: add 'keyId' param to methods of the CryptoConverter

DEPENDENCIES, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestFactory.java, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSink.java, extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestFactoryTest.java, extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpIntegrationTests.java, spi/data-plane/data-plane-http-spi/src/test/java/org/eclipse/edc/connector/dataplane/http/spi/HttpRequestParamsTest.java
Forward `Content-Type` to `HttpSink` for Provider-push transfers
fix
Closes #3798 
=> fix: forward content-type to http sink

DEPENDENCIES, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractNegotiationDefaultServicesExtension.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ConsumerOfferResolverImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ConsumerOfferResolverImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/offer/ConsumerOfferResolver.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ValidatableConsumerOffer.java
Introduces the policy scopes extractor in contract negotiation messages at protocol layers:
- in all contract negotiation messages, `ContractRequestMessage` excluded, we first load the contract negotiation in read mode based on the message, then we extract the policy and verify the token with the scope attached running the policy engine. Same as in #3822,  if the contract negotiation is not found or the token verification fails the returned error is `404`
- When dealing with `ContractRequestMessage` we changed a bit how the sequence of fetching stuff from the database for validation is done. We first fetch all the information what we need in order to validate the `ContractRequestMessage`  through the new core service `ConsumerOfferResolver`. Then we verify the token with the extracted …
=> feat: policy scope extractors for contract negotiation ingress calls

extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImpl.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImplTest.java
This PR fixes the Regex we use to parse DIDs. Previously, in a DID `"did:web:foobar#key-1"`the key-id would have been extracted as`""#key-1"`, where now it is `"key-1"` without the pound sign.
Would have caused a bug when matching verification methods
=> fix: use correct Regex when parsing DID

core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/protocol/ProtocolTokenValidatorImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImplTest.java, extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/DapsIntegrationTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/IdentityService.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/VerificationContext.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/protocol/ProtocolTokenValidator.java
- Extracts `BaseProtocolService` into `ProtocolTokenValidator`
- Removes the parsing of `access_token` for fetching the scopes
- Removes the deprecated `VerificationContext#audience` field
refactoring
Closes #3832
=> refactor: introduction of ProtocolTokenValidator

extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImpl.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImplTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtensionTest.java, spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/document/DidConstants.java
- improve error message when no Verification Method with supported type is found in DID document
- improve naming and documentation of STS setting for the public key: current documentation indicates this setting refers to public key alias in the Vault, while it actually corresponds to the public ID resolves by the counterparty.
Easier investigations …
=> refactor: minor improvements in Iatp and Did modules

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformerTest.java, data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspNegotiationPropertyAndTypeNames.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java, spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessageTest.java
The `offerId` property is not defined in the DSP spec, so let's get rid of it. 
dsp compliance
Closes #3846 
=> feat(dsp): remove `offerId` property

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IatpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/ClaimTokenCreatorFunction.java
This PR changes, what the `ClaimtToken` contains when the `IdentityAndTrustService` creates it.
Before, it only contained the `credentialSubject` of each VC, where now it contains the actual list of VCs.
This is also pluggable, with a default implementation.
More versatile ways to evaluate the `ClaimToken` in policy evaluation functions.
Closes #3855 …
=> feat: attach entire VC to claimtoken

.github/dependabot.yml
Because the version is automatically set by the release process.
Will supersede #3870 
=> build(deps): ignore runtime-metamodel version updates

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
Improves the failure message in `ContractValidationServiceImpl#validateInitialOffer` by including the failure details of the policy evaluation 
Closes #3864
=> feat: improves reported error in ContractValidationServiceImpl

extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiablePresentationTransformer.java
This PR adds some robustness when transforming JWT-VPs and JWT-VCs
...well... it wasn't robust enought :)
=> feat: make JWT-to-VP_VC-transformer more robust

core/common/token-core/src/main/java/org/eclipse/edc/token/TokenValidationRulesRegistryImpl.java, extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifier.java, extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/HasSubjectRule.java, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifierTest.java, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/rules/HasSubjectRuleTest.java, extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidPublicKeyResolverImpl.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/validation/rules/HasValidSubjectIds.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/verification/MultiFormatPresentationVerifier.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityTrustTransformExtension.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/AbstractJwtTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiablePresentationTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/AbstractJwtTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiablePresentationTransformerTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/VerifiableCredential.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/verification/VerifierContext.java, spi/common/identity-trust-spi/src/test/java/org/eclipse/edc/identitytrust/model/VerifiableCredentialTest.java
- Avoid `NullPointerException` in `TokenValidationRulesRegistryImpl` if there is no rules registered for a given context
- In `JwtPresentationVerifier`:
- do not validate VC `aud` claim, as they don't have one
- do not validate VP `sub` claim, as they don't have one
- **MAKE VERIFIER CONTEXT IMMUTABLE**: this was causing very dubious behavior as `JwtPresentationVerifier.verify` was modifying the `audience` in the `VerificationContext` in the 
recursive call but it was never restored to the initial and expected value for the subsequent presentation verifications! So basically, first presentation verification was fine, but all consecutives were failing because the context audience was changed at the end of the first execution!
- In `DidPublicKeyResolverImpl`: improve error logging when the …
=> fix: multiple fix in `Iatp` modules

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/protocol/ProtocolTokenValidatorImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/protocol/ProtocolTokenValidatorImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/DspNegotiationApiExtension.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/NegotiationApiPaths.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractOfferMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractRequestMessageValidator.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiControllerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractOfferMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/api/validation/ContractRequestMessageValidatorTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractOfferMessageTransformerTest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractOfferMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessage.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java, spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestMessageTest.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/protocol/ProtocolTokenValidator.java
Add the `negotiations/offer` endpoint, that can be used by a provider to start a negotiation.
dsp compliance
- to create a new negotiation from a `ContractOfferMessage` I had to move the extraction of the counter party id from the contract validator to the `ProtocolTokenValidator`, that returns a `ServiceResult<ParticipantAgent>` now. I left the old methods and I will align the missing services (transfer process and catalog) to the new behavior in a subsequent PR.
- moved the validation on the `ContractRequestMessage` for the `callbackAddress` property to the JsonLdValidator instance, because it didn't make much sense in the controller (and it wasn't properly tested too).
Closes #3840 
_Please be sure to take a look at the [contributing …
=> feat(dsp): add `negotiations/offer` endpoint

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/protocol/ProtocolTokenValidatorImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/CatalogProtocolServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/protocol/ProtocolTokenValidator.java
Remove some deprecated methods introduced in #3854
cleanup
Closes #3877
=> refactor: cleanup `ContractValidationService`

extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/AbstractJwtTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/AbstractJwtTransformerTest.java
Remove useless function `toInstant` in `JwtToVerifiableCredentialTransformer`.
Clean up.
=> chore: remove useless function in `JwtToVerifiableCredentialTransformer`

extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/validation/rules/HasValidSubjectIds.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiablePresentationTransformerTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/model/VerifiableCredential.java
Use class argument name and serialized name for the `type` and `credentialSubject` properties of the `VerifiableCredential` object.
This is required to have a consistent way to query for a VC independently on the type of VC store (in-mem store uses reflection while PostgreSQL store will work on the serialized json structure. …
=> fix: use `type` and `credentialSubject` properties in `VerifiableCredential`

core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/TypeIs.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidator.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidatorTest.java
add @type validation on policy definition api
preventing NPE when posting a policy definition without `@type`
Closes #3876 
=> feat: add @type validation on policy definition api

core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java
this PR fixes the scope, that dynamically bound eval functions are evaluated against. They should use the _delimited_ scope, not the raw one.
Dynamically bound functions did not get evaluated on any scope other than `".*"`
=> fix: use delimited scope

docs/developer/data-plane-signaling/data-plane-signaling-token-handling.md
Adds a technical specification for data plane token handling and extensibility
Required functionality
Closes #3890
=> feat: add token handling technical specification

core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorService.java, core/data-plane-selector/data-plane-selector-core/src/test/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorServiceTest.java, extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
Applies the transactional context in the getAll on the `SqlDataPlaneInstanceStore` and in the caller when consuming the streaming.
bug fix
Closes #3887
=> fix: applies transactional context in getAll

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultServicesExtension.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryAccessTokenDataStore.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryAccessTokenDataStoreTest.java, extensions/data-plane/store/sql/accesstokendata-store-sql/build.gradle.kts, extensions/data-plane/store/sql/accesstokendata-store-sql/docs/schema.sql, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlAccessTokenDataStore.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlAccessTokenDataStoreExtension.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/AccessTokenDataStatements.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlAccessTokenStatements.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/AccessTokenDataMapping.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/PostgresAccessTokenDataStatements.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/data-plane/store/sql/accesstokendata-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/store/sql/SqlAccessTokenDataStoreTest.java, settings.gradle.kts, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/AccessTokenData.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataStore.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataTestBase.java
This PR adds the `AccessTokenDataStore` with an in-mem implementation and a Postgres-based
implementation.
preparatory work for Dataplane Signaling
Closes #3893 
=> feat: implement AccessTokenStore

extensions/data-plane/data-plane-signaling-api/build.gradle.kts, extensions/data-plane/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApi.java, extensions/data-plane/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiController.java, extensions/data-plane/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/model/DataFlowState.java, settings.gradle.kts, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowRequest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowResponseMessage.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowSuspendMessage.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowTerminateMessage.java
Adds a new module `data-plane-signaling-api` containing the scaffold for a new controller and an OpenAPI spec for the signaling API. 
The new APIs will be JSON-LD aware, and some the JSON-LD constants are introduced of the `DataFlow`* classes 
The refactor of `DataFlowRequest` will be handled in subsequent PRs.
The reference of `DataAddress` in the docs still reference the EDC one and not the `dspace` one.  To be change once this lands #3841
dataplane signaling story
Closes #3897
=> feat: adds OpenApi spec for the new signaling APIs

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultServicesExtension.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessControlService.java
This PR adds the `DataPlaneAccessControlService` plus a default allow-all implementation.
data plane signaling.
Closes #3894
=> feat: implement DataPlaneAccessControlService

DEPENDENCIES, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferRequestMessageTransformer.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferRequestMessageTransformer.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromTransferRequestMessageTransformerTest.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferRequestMessageTransformerTest.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApi.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/Namespaces.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
Fix the `dct` namespace url.
**Breaking change**: clients will need to adapt and use the new url to process the catalog.
In the `TransferRequestMessage` the change has been handled, so older versions will be able to understand newer ones and vice-versa. …
=> fix: dct namespace

extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/DataPlaneKafkaExtension.java, extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSinkFactory.java, extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/dataplane/kafka/pipeline/KafkaDataSinkFactoryTest.java
Adds the possibility to configure the `partitionSize` of the `KafkaDataSink` via the `.properties` file.
Enhances the usability of the extension.
Closes #3849
=> feat(kafka_extension): make partitionSize configurable

docs/developer/data-plane-signaling/data-plane-signaling-mapping.md
This PR adds documentation about mapping the "transfer type" (=format) onto a `DataPlaneDescriptor`, which consists of
a `destinationType` and a `flowType`.
documentation
Pertains to #3892
=> docs: add documentation about mapping the format

extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowControllerTest.java
if the dataplane is embedded the instance will be null, hence we don't have a dataplaneId
fix NPE
=> chore: fix NPE when dataplane is embedded

core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/policy/ContractExpiryCheckFunctionEvaluationTest.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplScenariosTest.java, core/common/policy-engine/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java, core/common/policy-evaluator/src/test/java/org/eclipse/edc/policy/evaluator/PolicyEvaluatorTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformerTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToActionTransformerTest.java, core/control-plane/contract-core/build.gradle.kts, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/policy-monitor/policy-monitor-core/build.gradle.kts, core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/PolicyMonitorExtension.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementMessageTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractRequestMessageTransformerTest.java, docs/developer/policy-engine.md, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java, spi/common/policy-model/src/test/java/org/eclipse/edc/policy/model/DutyTest.java, spi/common/policy-model/src/test/java/org/eclipse/edc/policy/model/PermissionTest.java, spi/common/policy-model/src/test/java/org/eclipse/edc/policy/model/PolicyTest.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java, spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/TestFunctions.java, spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/edc/connector/policy/spi/testfixtures/store/PolicyDefinitionStoreTestBase.java
The correct case for such action is [`use`](http://www.w3.org/ns/odrl/2/use)
ODRL compliance
Closes #3925
=> refactor: switch ODRL action `USE` to `use`

core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformer.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToPolicyTransformer.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformerTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToPolicyTransformerTest.java, core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/policy/PolicyEquality.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/policy/PolicyEqualityTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/build.gradle.kts, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementMessageTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java, data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/type/DspNegotiationPropertyAndTypeNames.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidator.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidatorTest.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java, system-tests/telemetry/telemetry-test-runner/src/test/java/org/eclipse/edc/test/e2e/tracing/TracingEndToEndTest.java
Map `assigner` and `assignee` fields in the `Policy` object in the transformers.
Ensures that every `Offer` has the `assigner` property set.
DSP compliance
- in the model objects like `ContractAgreement` I kept the current nomenclature (`consumerId` and `providerId`), to avoid disruptive changes
Closes #3792
=> feat(dsp): replace consumerId and providerId with odrl assignee and assigner

data-protocols/dsp/dsp-catalog/dsp-catalog-api/build.gradle.kts, data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/build.gradle.kts, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/build.gradle.kts, data-protocols/dsp/dsp-version/dsp-version-api/build.gradle.kts
Generate Swagger documentation for DSP APIs.
Documentation.
=> docs: generate Swagger API documentation for DSP APIs

core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromDataFlowSuspendMessageTransformer.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromDataFlowTerminateMessageTransformer.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToDataFlowSuspendMessageTransformer.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToDataFlowTerminateMessageTransformer.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromDataFlowSuspendMessageTransformerTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromDataFlowTerminateMessageTransformerTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToDataFlowSuspendMessageTransformerTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToDataFlowTerminateMessageTransformerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowSuspendMessage.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowTerminateMessage.java
add trasformers from/to for DataFlowTerminateMessage and DataFlowSuspendMessage
dataplane signaling
Part of #3934
=> feat: DataFlowTerminateMessage and DataFlowSuspendMessage transformers

core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformer.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformerTest.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidator.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidatorTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
Adds validation for `PolicyDefinition`
Currently, there is no validation for `Policies` according to [ODRL](https://www.w3.org/TR/odrl-model/), which led to issues with missing mandatory values.
Currently missing validation for logical constraints
Currently missing validation for different action value types and refinements
Makes action to json transformation null safe to avoid crashes for already saved policies
Organises constants in `PropertyAndTypeNames.java` by namespace
Closes #3661
=> feat(api): adds validation for `PolicyDefinition`

extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/build.gradle.kts, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/SignalingApiTransformerRegistry.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/SignalingApiTransformerRegistryImpl.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowSuspendMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowTerminateMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowSuspendMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowTerminateMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/SignalingApiTransformerRegistryImplTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/TestFunctions.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowSuspendMessageTransformerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowTerminateMessageTransformerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowSuspendMessageTransformerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowTerminateMessageTransformerTest.java, settings.gradle.kts
This PR introduces the `data-plane-signaling-transform` module, which contains JSON-LD transformers specific to the DP-Signaling API as well as
an explicitly typed `SignalingApiTransformerRegistry`.
The Signaling API will employ different serialization formats than e.g. the DSP APIs or the management API. Thus, we need to contain
the transformers to that particular HTTP context.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) …
=> feat: introduce DPS-API JSON-LD transformer registry

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessage.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/FlowType.java, spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessageTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneEndToEndTest.java
- Adds trasformers from/to for DataFlowStartMessage
- Replaces `transferType` with `flowType` as described https://github.com/eclipse-edc/Connector/pull/3924 
- Moves `FlowType`  into `core-spi`
data plane signaling
Part of #3934
=> feat: add trasformers from/to for DataFlowStartMessage

.github/workflows/publish-openapi-ui.yml
On every push on main branch will trigger the `.github` workflow to publish the static ui
=> build: add openapi ui publish workflow

extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowResponseMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowResponseMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowResponseMessageTransformerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowResponseMessageTransformerTest.java
adds trasformers from/to for DataFlowResponseMessage
data plane signaling protocol
Part of #3934
=> feat: add trasformers from/to for DataFlowResponseMessage

DEPENDENCIES, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/build.gradle.kts, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtensionTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtensionTest.java, settings.gradle.kts
Introduces a new module `data-plane-signaling-client` that implements a `DataPlaneClient` for the data plane signaling protocol.
data plane signaling adoption
Closes #3900
=> feat: data plane client for signaling protocol

DEPENDENCIES, core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorService.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/model/SelectionRequest.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/DataPlaneInstanceSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/schemas/SelectionRequestSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectFromDataPlaneInstanceTransformer.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToDataPlaneInstanceTransformer.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToSelectionRequestTransformer.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneApiSelectorTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectFromDataPlaneInstanceTransformerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToDataPlaneInstanceTransformerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToSelectionRequestTransformerTest.java, extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorService.java, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java, spi/data-plane-selector/data-plane-selector-spi/src/test/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstanceTest.java, spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/TestFunctions.java, spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
Introduces `allowedTransferTypes` in DataPlaneInstance.
A new `select` method has been added to `DataPlaneSelectorService` to support selection based also on the `transferType`. If it's  not present the behaviour will be as today only inspecting source/destination.
The current `DataFlowController`s don't use the `transferType` for selection. For the data plane signaling a new `DataFlowController` will be introduced #3901 that will take into account the `transferType` for dispatching the request to the right data plane.  
enabling data plane signaling protocol for selecting the correct data plane instance
Closes #3943
=> feat: introduce allowedTransferTypes in DataPlaneInstance

DEPENDENCIES, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseSourceHttpParamsDecorator.java, extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/params/HttpRequestParamsProviderImplSourceTest.java, extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpIntegrationTests.java, extensions/data-plane/data-plane-public-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/DataFlowRequestSupplier.java
Fix "proxyMethod" and cover it with a test.
fix bug
Closes #3954
=> fix: proxy method on Http Pull calls

DEPENDENCIES, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/agent/NoOpParticipantIdMapper.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/OdrlTransformersFactory.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformer.java, core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToPolicyTransformer.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/from/JsonObjectFromPolicyTransformerTest.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/to/JsonObjectToPolicyTransformerTest.java, data-protocols/dsp/dsp-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/api/configuration/DspApiConfigurationExtension.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/DspCatalogTransformExtension.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformer.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/agent/ParticipantIdMapper.java
Permits to map the participantId in the DSP messages to/from IRI.
By default this service returns what gets in input, but it could be extended accordingly (e.g. to provide/parse a specific `urn`)
dsp compliance
Closes #3930 
=> feat(dsp): map participant ids to/from IRI

.github/workflows/apidoc.yaml, extensions/common/api/api-observability/build.gradle.kts
Moves move observability api docs to default api documentations.
Currently the observability endpoints are listed under the [management-api swaggerhub documentation](https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.5.1#/Application%20Observability/checkHealth), but in fact they are exposed in the default api context.
Closes #3759
=> chore: move observability api docs to default api docs

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessTokenService.java
This PR adds a feature that reads all of the `DataFlowStartMessage#properties` and stores them in the `AccessTokenData#additionalProperties` field.
When generating access tokens, we may need to store additional information, such as participant aliases etc. that should _not_ end up in the token itself. …
=> feat: store additional properties with the AccessTokenData

DEPENDENCIES, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java, core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImpl.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplIntegrationTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java, core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImplTest.java, extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/impl/HttpProviderResourceDefinitionGenerator.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProviderResourceDefinitionGeneratorTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/provision/ConsumerResourceDefinitionGenerator.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/provision/ProviderResourceDefinitionGenerator.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/provision/ResourceManifestGenerator.java
First refactoring step to inline `DataRequest`, make `ResourceManifestGenerator` and relative consumer/provider interfaces to accept `TransferProcess` instead of `DataRequest`
** Breaking change ** for those who implemented a custom `ConsumerResourceDefinitionGenerator` or a `ProviderResourceDefinitionGenerator`, pretty straightforward to adapt
refactoring
Part of #3732  …
=> refactor: make resource manifest generator handle TransferProcess

extensions/control-plane/transfer/transfer-data-plane-signaling/build.gradle.kts, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneSignalingExtension.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowController.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneSignalingExtensionTest.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java, extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiController.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiControllerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTransformExtension.java, settings.gradle.kts, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java, system-tests/e2e-transfer-test/control-plane/build.gradle.kts, system-tests/e2e-transfer-test/data-plane/build.gradle.kts, system-tests/e2e-transfer-test/runner/build.gradle.kts, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndKafkaTransferTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/AbstractSignalingTransfer.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingTransferInMemoryTest.java
Introduces a new module `transfer-data-plane-signaling` that contains a new `DataFlowController`
compliant with the data plane signaling spec.
This is additive and does not impact the current `DataFlowController`s.
A first E2E test with PUSH scenario was also implemented using the data plane signaling protocol.
For making the test work the transformer for the `DataAddress` for the client -> api communicantion
where reverted to EDC one.
data plane signaling
For having a E2E test with PULL scenario we have to tackle the following topics
- DataAddress format dspace vs edc #dataaddress in the signaling protocol (relates to #3841)
- transferType/format -> dataaddress type in case of destination missing
- EDR generator for http pull scenario destination type
- DataPlaneManagerImpl refactor …
=> feat: implements Signaling Data Flow Controller

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryAccessTokenDataStore.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlAccessTokenDataStore.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/AccessTokenDataStatements.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlAccessTokenStatements.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataStore.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataTestBase.java
This PR adds an `update()` method to the `AccessTokenDataStore`.
In certain scenarios it is necessary to be able to update an `AccessTokenData` entry, e.g. when implementing a token-refresh mechanism
=> feat: add update method to AccessTokenDataStore

core/common/edr-store-core/build.gradle.kts, core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreDefaultServicesExtension.java, core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreExtension.java, core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/defaults/InMemoryEndpointDataReferenceEntryIndex.java, core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/defaults/VaultEndpointDataReferenceCache.java, core/common/edr-store-core/src/main/java/org/eclipse/edc/core/edr/store/EndpointDataReferenceStoreImpl.java, core/common/edr-store-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreDefaultServicesExtensionTest.java, core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/EndpointDataReferenceStoreExtensionTest.java, core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/defaults/InMemoryEndpointDataReferenceEntryStoreTest.java, core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/defaults/VaultEndpointDataReferenceCacheTest.java, core/common/edr-store-core/src/test/java/org/eclipse/edc/core/edr/store/EndpointDataReferenceStoreImplTest.java, settings.gradle.kts, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreFailure.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java, spi/common/edr-store-spi/build.gradle.kts, spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceCache.java, spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceEntryIndex.java, spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceStore.java, spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/types/EndpointDataReferenceEntry.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/TestFunctions.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceCacheTestBase.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceEntryIndexTestBase.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceStoreTestBase.java
Introduces an EDR (dataaddress) cache and associated metadata storage:
- introduced `edr-store-spi` module
- introduced `edr-store-core` module with default implementations
In the `spi` three extensible interface are introduced:
- `EndpointDataReferenceStore`: the main entry point for storing and retrieving EDR and metadata associated
- `EndpointDataReferenceCache` subcomponent for caching EDR (DataAddress) in a secured environment
- `EndpointDataReferenceEntryIndex` subcomponent for storing EDR metadata (assetId, agreementId, ..etc)
The default implementation of `EndpointDataReferenceStore` uses the two subcomponents for dealing with EDR and metadata. 
A default implementation of `EndpointDataReferenceCache` backed by the `Vault` is provider as well as an in memory one for the metadata …
=> feat: EDR (data address) and metadata storage/cache

extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiExtension.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java
This PR adds an optional config property `edc.dataplane.api.public.baseurl` that configures the base URL (including host, port) of the `DataPlanePublicApiController`.
If that config value is not provided, a fallback `http://<HOST>:<PORT>/<PATH>` is constructed dynamically, and is determined by the following config properties:
- `HOST`: determined by the injected `Hostname`, defaulting to `localhost`
- `PORT`: determined by `web.http.public.port` , defaulting to `8185`
- `PATH`: determined by `web.http.public.path`, defaulting to `/api/v1/public`
Every dataplane should be able to represent itself as `Endpoint`
signature changes, package declarations, bugs that were …
=> feat: register default PublicEndpointGenerator fct

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultIamServicesExtension.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImplTest.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java, extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiV2Extension.java, extensions/data-plane/data-plane-public-api-v2/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiController.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiControllerTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java, system-tests/e2e-transfer-test/data-plane/build.gradle.kts, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferInMemoryTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferPostgresqlTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/AbstractSignalingTransfer.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingTransferInMemoryTest.java
enable HTTP pull scenario E2E test with DPS
data plane signaling
In `DataPlaneSignalingApiController` the validation for now it's skipped for PULL scenario (otherwise will fail)
and thus the  test `start_whenInvalidMessage` has been disabled, waiting for  #3990
Closes #3989
=> feat: enable HTTP pull scenario E2E test with DPS

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneDefaultIamServicesExtension.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessControlService.java
some additional claims, that were previously stored as claims on the EDR's `access_token` were moved to the `additionalProperties` map on the `AccessTokenData`.
Specifically: `participantId, processId, assetId, agreementId, transferType`
Having those on the access token is not necessary. The access token should be as slim as possible. …
=> feat: store claims on additionalProperties

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java, extensions/data-plane/data-plane-client-embedded/build.gradle.kts, extensions/data-plane/data-plane-client-embedded/src/main/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClient.java, extensions/data-plane/data-plane-client-embedded/src/test/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClientTest.java, extensions/data-plane/data-plane-client/build.gradle.kts, extensions/data-plane/data-plane-control-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlaneControlApiController.java, extensions/data-plane/data-plane-control-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlaneControlApiControllerTest.java, extensions/data-plane/data-plane-http/src/testFixtures/java/org/eclipse/edc/connector/dataplane/http/testfixtures/TestFunctions.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneSignalingApiExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiController.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiControllerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtensionTest.java, extensions/data-plane/store/sql/data-plane-store-sql/docs/schema.sql, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStore.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataPlaneStatements.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/DataPlaneStatements.java, settings.gradle.kts, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessage.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/participant/EndToEndTransferParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/EmbeddedSignalingTransferInMemoryTest.java
In this PR:
- `DataPlaneManager#initiate` renamed to `start` and now it returns directly the `DataFlowResponseMessage`.
-  moved `EmbeddedDataPlaneClient` into `data-plane-client-embedded` module and adapted to the `DataPlaneManager` refactor.
-  The `DataPlaneAuthorizationService` usage has been moved from the controller to the `DataPlaneManagerImpl` for reaching the same functionality when running the dataplane in embedded and remote deployment.
- When a `PULL` request hits the dataplane the generation of the EDR is called and if succeeded a DataFlow is created in the `STARTED` state (RECEIVED in case of PUSH scenario).
- The `DataFlow` now contains also the `flowType` which can be useful when terminating the transfer which differs PULL/PUSH.
- Introduced a new E2E test …
=> feat: data plane refactor for DPS

core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/JsonObjectValidator.java, core/common/validator-core/src/main/java/org/eclipse/edc/validator/jsonobject/validators/LogDeprecatedValue.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractRequestTransformer.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidator.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToContractRequestTransformerTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/validation/ContractRequestValidatorTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequest.java
Deprecated provider_id field in ContractRequest
Clean up.
Closes #3929
=> chore: deprecate provider_id field in ContractRequest

extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifier.java, extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/TokenNotNullRule.java, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifierTest.java, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/rules/TokenNotNullRuleTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/verification/MultiFormatPresentationVerifierTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/controller/SecureTokenServiceApiController.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/src/main/java/org/eclipse/edc/connector/api/sts/model/StsTokenRequest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/core/defaults/service/StsClientTokenGeneratorServiceImpl.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/core/defaults/StsClientTokenIssuanceIntegrationTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/main/java/org/eclipse/edc/iam/identitytrust/sts/embedded/EmbeddedSecureTokenService.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded/src/test/java/org/eclipse/edc/iam/identitytrust/sts/embedded/EmbeddedSecureTokenServiceIntegrationTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenService.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenServiceTest.java, launchers/sts-server/README.md, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/SecureTokenService.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/identitytrust/SelfIssuedTokenConstants.java, spi/common/identity-trust-spi/src/testFixtures/java/org/eclipse/edc/identitytrust/TestFunctions.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/RemoteStsEndToEndTest.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsApiEndToEndTest.java
Fixes after IATP changes about renaming `access_token` to `token`.
Also in this PR:
- Fixes some case of  Verifiable Presentation verification in JWT format
- Removed the `nbf` claim verification
- Changed the API path for the presentation query to `{base_path}/presentations/query`
=> chore: fix after IATP changes

DEPENDENCIES, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java
restored the `scope` property when doing the presentation query request. Removed by accident in #4012.
Added also a test to ensure it's presence
=> chore: restore scope field

DEPENDENCIES, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/OkHttpClientFactory.java, core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/OkHttpClientFactoryTest.java
Provide a way to eventually configure `Socket` send and receive `bufferSize` on the http client
permit certain particular cases like streaming over long running http connection to configure lower values.
Closes #4015
=> feat: make http client buffer sizes configurable

DEPENDENCIES, spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java
Adds the `UNAUTHORIZED` case label to the `ServiceResultHandler`, so exceptions can be properly mapped.
=> chore: add UNAUTHORIZED case label

core/common/transform-core/src/main/java/org/eclipse/edc/core/transform/transformer/edc/to/JsonObjectToAssetTransformer.java, core/common/transform-core/src/test/java/org/eclipse/edc/core/transform/transformer/edc/to/JsonObjectToAssetTransformerTest.java
Do not map root level properties as `Asset` properties (only the ones contained in the `properties` nested property will be taken into consideration
api consistency
Closes #3701
=> feat: do not map root level properties as asset properties

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/listener/TransferProcessEventListener.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/iam/DefaultDataPlaneAccessTokenServiceImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, extensions/control-plane/edr/edr-store-receiver/src/main/java/org/eclipse/edc/connector/edr/store/receiver/EndpointDataReferenceStoreReceiver.java, extensions/control-plane/edr/edr-store-receiver/src/test/java/org/eclipse/edc/connector/edr/store/receiver/EndpointDataReferenceStoreReceiverTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAccessTokenService.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAuthorizationService.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/store/AccessTokenDataTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingEndToEndTransferTest.java
implements revocation in DataPlaneAuthorizationService
Notify the `DataPlaneAuthorizationService` that the transfer has been terminated or suspended
Closes #3997
=> feat: implements revocation in DataPlaneAuthorizationService

extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndInstance.java, extensions/common/store/sql/edr-index-sql/build.gradle.kts, extensions/common/store/sql/edr-index-sql/docs/schema.sql, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndex.java, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndexExtension.java, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/BaseSqlDialectStatements.java, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/EndpointDataReferenceEntryStatements.java, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/postgres/EndpointDataReferenceEntryMapping.java, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/edr/schema/postgres/PostgresDialectStatements.java, extensions/common/store/sql/edr-index-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/common/store/sql/edr-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndexExtensionTest.java, extensions/common/store/sql/edr-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/edr/SqlEndpointDataReferenceEntryIndexTest.java, settings.gradle.kts, spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceEntryIndex.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/TestFunctions.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/store/EndpointDataReferenceEntryIndexTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/PostgresSignalingRuntimes.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/signaling/SignalingEndToEndTransferTest.java
SQL implementation of the EDR index store
Persistent Postgres/SQL variant of the EDR index store.
Closes #3972 
=> feat: SQL implementation of the EDR index store

extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
Changes Participant#self method to  protected for extensibility
extensibility
=> chore: Participant self method as protected 

core/common/util/src/test/java/org/eclipse/edc/util/reflection/PathItemTest.java, spi/common/core-spi/build.gradle.kts
Cleans up an unused dependency and test.
Related to #4028
=> feat: Remove Junit dependency and move test to proper module

extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java
fix NPE when dataplane is null on data plane signaling client.
Refactored also the `DataPlaneSignalingClientTest` with two additional `@Nested` for `Start` and `Terminate` tests
Closes #4033 
=> chore: fix NPE when dataplane is null on data plane signaling client

extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneSignalingExtension.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowController.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowPropertiesProvider.java
Allows adding additional/custom properties when sending the `DataFlowStartMessage` with the DPS protocol
A default provider is created, which returns an empty map
extensibility
Closes #4043
=> feat: introduces properties provider for DataFlowStartMessage

extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/JtiValidationRule.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
Log the warning of `JtiValidationRule` (that says it is not yet implemented) only at creation time.
Prevent flooding the console with the same warning.
=> refactor: log `JtiValidationRule` warning only once at creation time

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java, extensions/common/json-ld/src/main/resources/document/dspace.jsonld
Caches DSPACE jsonld context document in the JsonLd extension
To permit usage of that context file without having enable the http resolution
Closes #4047 
=> feat(dsp): cache dspace jsonld context document

DEPENDENCIES, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiController.java, extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java, extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiController.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApi.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiController.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/model/SelectionRequest.java
- Align management API operation names.
- add missing `@Consumes` annotation in some API controllers.
Harmonize the management APIs
=> fix: minor fixes in management API

core/common/lib/crypto-common-lib/src/main/java/org/eclipse/edc/security/token/jwt/CryptoConverter.java, core/common/lib/crypto-common-lib/src/test/java/org/eclipse/edc/security/token/jwt/CryptoConverterTest.java
This PR allows to convert a RSA key -> JWK if only the private portion of the key is specified by restoring the 
public key from the modulus and the exponent.
Using RSA keys in LDP-VPs is impossible otherwise
Closes #4054
=> fix: convert RSA private key to JWK

.github/workflows/publish-autodoc.yml, .github/workflows/publish-openapi-ui.yml, DEPENDENCIES
Add the possibility to trigger publish "autodoc" and "openapi ui" manually
looks like that didn't work during the release
=> build: add workflow_dispatch for publish autodoc and openapi ui

DEPENDENCIES, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/iam/DataPlaneAuthorizationServiceImpl.java
This PR reorders two method arguments that were in the wrong order
=> chore: reorder method arguments

DEPENDENCIES, core/common/boot/src/main/java/org/eclipse/edc/boot/system/ExtensionLoader.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EdcRuntimeExtension.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/monitor/ConsoleColor.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/monitor/ConsoleMonitor.java
This PR adds colored console output to the `ConsoleMonitor`. This is achieved by inserting special unicode characters before log lines to access ANSI coloring.
Note that the _actual_ color depends on the color configuration in your terminal.
This behaviour is on by default, and it can be deactivated by passing the `--no-color` command line argument. This might be useful in certain environments, for example running in clustered environments, where log tools like [stern](https://github.com/stern/stern) are used, that do coloring on their own.
Also, some docker base images may not print colored output correctly, depending on the shell they use. There are ways to mitigate it, e.g. using the `tty: true` property in docker-compose, or passing the `--it` parameter to `docker run`.
Better …
=> feat: console colors

DEPENDENCIES, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java
Only a `SEVERE` warning message is logged when no `edc.iam.issuer.id` is provided.
Sometimes it is necessary to have a booted runtime, even if it won't be fully operational.
=> chore: issue SEVERE message when no DID value provided

extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/transform/JsonObjectFromTransferProcessTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/transform/JsonObjectFromTransferProcessTransformerTest.java
Avoid NPEs when TP attributes are null.
The egress transformers should fail as less as possible.
Avoid NPE
Closes #4078 
=> fix: avoid NPE when attributes are null

DEPENDENCIES, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/ScopeFilter.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/ScopeFilterTest.java, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/from/JsonObjectFromPolicyTransformer.java, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToDutyTransformer.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/from/JsonObjectFromPolicyTransformerTest.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToDutyTransformerTest.java, spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/Duty.java, spi/control-plane/policy-spi/src/test/java/org/eclipse/edc/connector/controlplane/policy/spi/PolicyDefinitionSerializationTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
Permit to define multiple `consequence` in the ODRL duty object, as reported by the ODRL spec.
dsp completion
Closes #3960 
=> fix: handle multiple consequences in ODRL duty

DEPENDENCIES, extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2Controller.java, extensions/data-plane/data-plane-public-api-v2/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2ControllerTest.java
removes v2 from the new public endpoint
Having `/v2` in the  `@Path` means that we'd have to remove it when proxying the request. Since there is no way to make 
the old public api and the new one working in the same runtime, we decided to remove it from the `@Path` instead of
stripping it at runtime
Closes #4072 
=> fix: removes v2 from the new public endpoint

DEPENDENCIES, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromDistributionTransformer.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromDistributionTransformerTest.java, system-tests/management-api/management-api-test-runner/build.gradle.kts, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
Fix `accessService` serialization
it was serialized as a string, but it should follow a [specific representation.](https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_access_service)
Closes #3995
=> fix: accessService serialization

extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/main/java/org/eclipse/edc/iam/identitytrust/issuer/configuration/TrustedIssuerConfigurationExtension.java, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/test/java/org/eclipse/edc/iam/identitytrust/issuer/configuration/TrustedIssuerConfigurationExtensionTest.java
Removes the checks for empty trusted issuers in config and replace it with a warning
=> chore: remove the checks for empty trusted issuers in config

extensions/common/crypto/ldp-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/linkeddata/LdpVerifierTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/resources/statuslist2021.json, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/validation/rules/IsInValidityPeriod.java, extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationService.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationServiceTest.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/TestData.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/VcConstants.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/StatusList2021Credential.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/StatusListStatus.java, spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/StatusList2021CredentialTest.java, spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/StatusListStatusTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlanePublicApiEndToEndTest.java
This PR fixes some smaller issues with credential revocation, such as caching the StatusList context, using property prefixes, etc.
Needed to utilize the `StatusList2021` credential revocation list.
=> fix: several smaller fixes re Credential Revocation

extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationService.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationServiceTest.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/TestData.java
sometimes VCs are deserialized as plain JSON, e.g. when obtaining StatusList2021 credentials. The spec says that `credentialStatus` and `credentialSubject`
can be either an ARRAY or an OBJECT, so a custom deserialization feature is enabled to allow that.
The StatusList2021 specification (and the VC DataModel, for that matter) demand that. …
=> chore: allow OBJECT or ARRAY when deserializing VC

extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/DidCredentialServiceUrlResolver.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/CredentialServiceUrlResolver.java
moves the `CredentialServiceUrlResolver` to the SPI package, where it belongs.
=> chore: move interface to SPI

core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/ScopeFilter.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/ScopeFilterTest.java
#4056 added `remedy` to `Prohibition` but the `ScopeFilter` part was missing
policy evaluation
Part of #3959 
=> feat: filter remedies in prohibitions

extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationService.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationServiceTest.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/TestData.java, spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/result/Result.java, spi/common/boot-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialStatus.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialSubject.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/BitString.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/StatusList2021Credential.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/StatusListStatus.java, spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialSubjectTest.java, spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/BitStringTest.java
- Adds the API for fetching properties from CredentialSubject and CredentialStatus with the tuple (namespace, property)
- Removes the usage of Bitset and implemented custom Bitstring for parsing the bitstring encoded list and checking if an index is `1`
=> chore: add support for fetching properties w/wo namespace + bitstring

data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/build.gradle.kts, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/DspCatalogApiExtension.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiController.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiController20241.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/decorator/Base64continuationTokenSerDes.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/decorator/CatalogPaginationResponseDecorator.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/decorator/ContinuationTokenManagerImpl.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiControllerTest.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/decorator/Base64ContinuationTokenSerDesTest.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/decorator/CatalogPaginationResponseDecoratorTest.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/decorator/ContinuationTokenManagerImplTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/message/DspRequestHandlerImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/message/DspRequestHandlerImplTest.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/message/ContinuationTokenManager.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/message/ContinuationTokenSerDes.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/message/DspRequestHandler.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/message/ResponseDecorator.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QuerySpec.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/Catalog.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspCatalogApiEndToEndTest.java
Implement pagination as described by [DSP specification](https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/catalog/catalog.binding.https#id-3.1-pagination).
The continuationToken is the json representation of a `QuerySpec` object encoded in base64.
The core of the implementation is the `ContinuationTokenManager` component that provides two features:
- being able to eventually deserialize and apply to the requestBody the continuationToken
- set the `Link` header on the response through the `ResponseDecorator` 
dsp completion
Closes #3866
_Please be …
=> feat(dsp): catalog pagination through continuation token and Link header

core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/CriterionOperatorRegistryImpl.java, core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/IlikeOperatorPredicate.java, core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/IlikeOperatorPredicateTest.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslator.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslatorTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionOperatorRegistry.java, spi/control-plane/asset-spi/src/testFixtures/java/org/eclipse/edc/connector/controlplane/asset/spi/testfixtures/AssetIndexTestBase.java
Add `ilike` operator for `Criterion`
improve query system
Closes #4104
=> feat: add ilike operator for Criterion

core/common/lib/transform-lib/src/main/java/org/eclipse/edc/transform/TransformerContextImpl.java, core/common/lib/transform-lib/src/test/java/org/eclipse/edc/transform/TransformerContextImplTest.java, spi/common/transform-spi/src/main/java/org/eclipse/edc/transform/spi/TransformerContext.java
Add a data map on the `TransferContext`
Closes #4117 
=> feat: add data map on TransformContext

DEPENDENCIES, extensions/common/sql/sql-pool/sql-pool-apache-commons/build.gradle.kts, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtensionTest.java
Reads database URL, user and password from the vault first, and falls back to reading it from the config later.
security
- removed some deprecated config values 
Closes #4128
=> feat: read database config from vault

DEPENDENCIES, core/common/lib/http-lib/src/main/java/org/eclipse/edc/http/client/EdcHttpClientImpl.java
Removes the logging of the entire request object when catching the exception
=> chore: remove logging of entire request on exception

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImplTest.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/TransferProcessDefaultServicesExtension.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/flow/FlowTypeExtractorImpl.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/flow/FlowTypeExtractorImplTest.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/validation/ContractRequestValidator.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/TransferProcessApi.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/transform/JsonObjectToTransferRequestTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/validation/TransferRequestValidator.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/transform/JsonObjectToTransferRequestTransformerTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/validation/TransferRequestValidatorTest.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/TransferDataPlaneSignalingExtension.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowController.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/flow/FlowTypeExtractor.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferRequest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
in `TransferRequest`:
- `transferType` becomes mandatory
- `dataDestination` becomes optional (only validated if `FlowType` is PUSH
`transferType` needs to be used to discriminate which dataplane to choose
- added a `FlowTypeExtractor` service that takes care of extracting the `FlowType` from the `transferType`
- in the `Participant` test class, added a `RequestAsset` inner class that helps defining a request asset operation in a fluent way (instead of having multiple methods with different parameters)
- removed `properties` field in `TransferProcess` that was deprecated in 0.2.0
Part of #4031 …
=> feat: make TransferRequest transferType mandatory and dataDestination optional

DEPENDENCIES, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToPolicyTransformer.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToPolicyTransformerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractOfferMessageTransformer.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractOfferMessageTransformerTest.java
Set "Offer" as implicit policy type on `JsonObjectToContractOfferMessageTransformer`
because it's not mandatory in the `dspace:offer` type
Closes #4118
=> feat(dsp): support implicit Offer policy type

data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/DspCatalogApiExtension.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromDataServiceTransformer.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromDataServiceTransformerTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/DataService.java
replace `dct:endpointUrl` and `dct:forms` with `dcat:endpointUrl` and `dcat:endpointDescription`
stick to the specs
- the erratic attributes have been maintained to avoid breaking changes, they will be removed in the future
Closes #4145
=> fix: correct DataService json-ld attributes

extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/DataPlaneHttpOauth2Extension.java, extensions/data-plane/data-plane-http-oauth2-core/src/test/java/org/eclipse/edc/connector/dataplane/http/oauth2/DataPlaneHttpOauth2ExtensionTest.java
removes OAuth2 capabilities from the data sink
=> chore: removes OAuth2 capabilities from the data sink

core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/ScopeFilter.java, spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/Duty.java, spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/Permission.java
Remove unneeded `parentPermission` from `Duty` that caused `StackOverflowException` in json serialization.
cleanup
Closes #3830 
=> fix: remove unused parentPermission field that caused stack overflow exceptions

extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/TestData.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformerTest.java
In case a JWT's VC does not contain a claim `issuanceDate` the fallback is to take the date from the JWT itself. Currently the fallback picks the `exp` claim for this, which is applicable for expiration date but not for issuance date. Therefore the claim `iat`, the issued at time of the JWT, should be used instead.
Misleading issuanceDate would be used, by setting it to the JWT's expiration date.
This is only a minor issue as it is only the fallback value.
Minor cleanup in the TestData.
Closes #4113
=> fix: issuanceDate fallback in vc transformer

docs/developer/decision-records/2024-05-24-dataplane-selection-improvements/README.md, docs/developer/decision-records/README.md
Add DR for dataplane selection improvements.
documentation
Closes #4148
=> docs: add DR about dataplane selection improvements

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceIntegrationTest.java, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java, extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java, extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java, extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSinkFactory.java, extensions/data-plane/data-plane-kafka/src/main/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSourceFactory.java, extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSinkFactoryTest.java, extensions/data-plane/data-plane-kafka/src/test/java/org/eclipse/edc/connector/dataplane/kafka/pipeline/KafkaDataSourceFactoryTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSinkFactory.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSourceFactory.java
Add `supportedType` on `DataSourceFactory` and `DataSinkFactory`
permit the dataplane to tell which sources/sinks it can handle
- deprecated the now unused `canHandle`
Closes #4150
=> feat: add supportedType method on source and sink factories

core/common/boot/src/main/java/org/eclipse/edc/boot/BootServicesExtension.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContext.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContextTest.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java, extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionExtension.java, extensions/common/transaction/transaction-atomikos/src/test/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionExtensionTest.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/SqlContractNegotiationStoreExtension.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/transferprocess/SqlTransferProcessStoreExtension.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStoreExtension.java, extensions/policy-monitor/store/sql/policy-monitor-store-sql/src/main/java/org/eclipse/edc/connector/policy/monitor/store/sql/SqlPolicyMonitorStoreExtension.java, spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/system/ServiceExtensionContext.java
Add a new configuration setting called `edc.runtime.id`, that will replace `edc.connector.name`
`edc.connector.name` was not really used for its purpose, instead of being the name of the connector was used as `leaseHolder` for sql lease, so I generalized its concept calling it `edc.runtime.id` because its an Id that represent a specific runtime, that could be used in clustered environments to allow idempotence.
Specifically, it will be used by data-planes for self-registration. (see #4031)
- the way the configuration is loaded inside the `DefaultServiceContext` is not optimal, there could be a dedicated component that could do that (like the `ExtensionLoader`) so the context could be instantiated with a `Config` instance passed. This will untangle some knots and will improve testing …
=> feat: define runtime id as a configurable setting

DEPENDENCIES, core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/CriterionOperatorRegistryImpl.java, core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/EqualOperatorPredicate.java, core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/NotEqualOperatorPredicate.java, core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/EqualOperatorPredicateTest.java, core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/NotEqualOperatorPredicateTest.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslator.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslatorTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionOperatorRegistry.java
Adds the "not-equals" or "!=" operator to our default operator portfolio
General functional completeness, but there is one particular use case: when querying for VerifiableCredentials, we only want those where the status is not `"REVOKED"` and not `"EXPIRED"`.
If we wanted to "cross all t's and dot all i's" we'd also have to add a "not-in" operator, but this seems good enough for now and keeps the complexity down.
Closes #4163
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) …
=> feat: add not-equals (!=) operator

extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/StatefulEntityMapping.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
adds the `stateTimestamp` to the translation model for stateful entities (`StatefulEntityMapping`).
sorting stateful entities by `stateTimestamp` threw an IllegalArgumentException, because the translation model did not 
contain a corresponding mapping.
=> fix: add stateTimestamp to translation model

extensions/common/crypto/ldp-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/linkeddata/DataIntegrityKeyPair.java
Fixes the type hierarchy of the `DataIntegrityKeyPair`
- wrong type hierarchy leads to failing checks
- wrong constructor argument leads to NPE
Closes #4170
=> fix: constructor arg and type hierarchy

DEPENDENCIES, extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifier.java, extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/IssuerKeyIdValidationRule.java, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/JwtPresentationVerifierTest.java
This PR fixes a security issue, where an attacker would do the following:
- obtain a legit VC issued to Bob (i.e. Bob's DID is the `credentialSubject.id`)
- generate a VP using Bob's DID as `iss` claim and `holder` property
- sign this seemingly legit VP with the attacker's private key
- put the key-ID of the attacker's key as `kid` header in the VP-JWT token
This caused the public key resolver to take the (malicious) key-ID "at face value", and resolve the public key from it.
**This is a problem, because that would resolve the ATTACKER's public key, instead of the LEGIT HOLDER's public key!**
prevent impersonation attacks
signature changes, package declarations, bugs that …
=> fix: prevent JWT attacks by spoofed keyIDs

DEPENDENCIES, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/from/JsonObjectFromPolicyTransformer.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/from/JsonObjectFromPolicyTransformerTest.java
serialize the `leftOperand` of a constraint as an @id
The breaking change only affects management API, since at protocol level EDC in input can handle both `@value` and `@id` as expanded form
Closes #4179
=> fix: serialize the leftOperand as an @id

data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/build.gradle.kts, extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfiguration.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api-configuration/src/main/java/org/eclipse/edc/connector/api/signaling/configuration/SignalingApiConfigurationExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/build.gradle.kts, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneSignalingApiExtension.java, system-tests/e2e-dataplane-tests/runtimes/data-plane/build.gradle.kts, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
Merge the `signaling-api` context into the `control-api` context
we should keep the context number consistent to the ones described in this decision record:
https://github.com/eclipse-edc/Connector/blob/main/docs/developer/decision-records/2022-11-09-api-refactoring/renaming.md
Closes #4175 
=> refactor(api): merge signaling api context into control

core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/from/JsonObjectFromPolicyTransformer.java, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToActionTransformer.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/from/JsonObjectFromPolicyTransformerTest.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToActionTransformerTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
Fixes the serialization of an `Action`
Currently the output is when the action is not refined
```json
"odrl:action": {
"odrl:type": "http://www.w3.org/ns/odrl/2/use"
}
```
Now it changes to :
```json
"odrl:action": {
"@id": "odrl:use"
}
```
Since now the action is an `@id` in compaction phase:
`http://www.w3.org/ns/odrl/2/use` => `odrl:use`
bug fix
This is a breaking change for the MGMT API mostly since at protocol level older EDC should be able to deal wit the `@id` syntax.
The patch also support in input the old wrong `type` when deserializing the action from json.
Closes #4192
=> fix: action as @id if it's not refined

extensions/control-plane/api/management-api/secrets-api/src/main/java/org/eclipse/edc/connector/api/management/secret/SecretsApi.java
nothing fancy, just removing the overloaded `name` value, because as it was done it reported the full namespaced parameter name on the schema, but we usually report only the "compacted" version attribute name (in this case simply `value`).
documentation consistency
=> docs(api): fix secrets api doc

extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowController.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
Resolved a TODO on `DataPlaneSignalingFlowController`. The original idea (described in the issue #4203) was to move dp selection into the client factory, but in fact now that data-planes can register themselves, this simple fix solves also the "embedded" case: a data-plane always need to be registered with the correct supported types, the only difference will be that for an embedded data-plane the `EmbeddedDataPlaneClient` will be used instead of the `Remote` one
refactor
- `DataPlaneSelectorService` could offer a `findById` method, so the caller won't need to fetch all the dataplanes and apply the filter by itself. Issue will come.
Closes #4203 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-re …
=> refactor: cleanup DataPlaneSignalingFlowController

DEPENDENCIES, extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/model/SelectionRequest.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/schemas/DataPlaneInstanceSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/schemas/SelectionRequestSchema.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiV2.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataplaneSelectorApiV2Controller.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v3/DataplaneSelectorApiV3.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v3/DataplaneSelectorApiV3Controller.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/validation/DataPlaneInstanceValidator.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToSelectionRequestTransformer.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtensionTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataPlaneApiSelectorTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/v2/DataPlaneSelectorApiV2ControllerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/v3/DataPlaneSelectorApiV3ControllerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/transformer/JsonObjectToSelectionRequestTransformerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/validation/DataPlaneInstanceValidatorTest.java
Bumps the `DataPlaneSelectorApi` from `/v2 -> /v3`, deprecating `/v2`.
the V3 Controller does **not** contain deprecated methods of the V2 Controller!
- updates the `operationId` property of endpoints - **this is a breaking change**
Closes #4208
=> feat: bump the Dataplane Selector management API endpoints to `v3`

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
Replaces the `File.separator` with a hard-coded forward slash, to avoid path errors on Windows.
- no tests - Windows is not a supported platform.
Closes #4219
=> fix: replace File.separator with forward-slash

core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorService.java, core/data-plane-selector/data-plane-selector-core/src/test/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorServiceTest.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowController.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java, extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorService.java, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java, extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApi.java, extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiController.java, extensions/data-plane-selector/data-plane-selector-control-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiControllerTest.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java
Add `findById` method on `DataPlaneSelectorService`
Avoid unnecessary calls to `getAll`
Closes #4210 
=> feat: add `findById` method on `DataPlaneSelectorService`

core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java
This correctly sets the HealthCheckResult of the base runtime to `succeeeded`, where previously it was initially set to failure, but later
the builder method `success()` was called, which caused the resulting result to contain a failure and a `success=true` flag.
This in turn was interpreted as failure by the HealthCheckService.
Docker images never became healthy, causing our nightly builds to fail, specifically IdentityHub and FederatedCatalog.
_Please be sure to take a look at the [contributing …
=> fix: correctly reset HealthStatus of BaseRuntime

DEPENDENCIES, core/common/lib/json-ld-lib/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java, core/common/lib/json-ld-lib/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java
fixes document cache usage + test
Closes #4232 
=> fix: document cache usage + test

core/common/lib/json-ld-lib/build.gradle.kts, core/common/lib/json-ld-lib/src/main/java/org/eclipse/edc/jsonld/JsonLdConfiguration.java, core/common/lib/json-ld-lib/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java, core/common/lib/json-ld-lib/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java, core/common/lib/validator-lib/src/main/java/org/eclipse/edc/validator/jsonobject/JsonObjectValidator.java, core/common/lib/validator-lib/src/main/java/org/eclipse/edc/validator/jsonobject/validators/MissingPrefixes.java, core/common/lib/validator-lib/src/test/java/org/eclipse/edc/validator/jsonobject/MissingPrefixesTest.java, extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java, spi/common/validator-spi/src/main/java/org/eclipse/edc/validator/spi/ValidationResult.java
A new JSON-LD validator has been introduced in order to walk the input JsonObject after the expansion process
and check if some `property` name or `@id`/`@type` values still contains prefixed notation and checks those prefixes against the configured ones for the runtime. 
This can happen on custom properties (that we have in almost all entities) when the input JSON-LD object does not contains the prefix alias in the `@context`.
For example like in the #4160  issue if a user post a property `dct:type` without explicitly  mapping `dct` in the context :
```json
{
"@context": {
"dct": "http://purl.org/dc/terms/"
},
"dct:type": "mytype"
}
``` 
It will cause the property to be stored as `dct:type` instead of the expanded form. This is not always an issue but it can lead to JsonLD error  in …
=> fix: adds checks on prefixes post JSON-LD expansion process

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
adds documentation for edc.jsonld.document.* setting that will be rendered in autodoc
documentation
Closes #4246
=> feat: adds documentation for edc.jsonld.document.* setting

core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/manager/DataPlaneSelectorManagerImpl.java, core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorService.java, core/data-plane-selector/data-plane-selector-core/src/test/java/org/eclipse/edc/connector/dataplane/selector/service/EmbeddedDataPlaneSelectorServiceTest.java, extensions/common/http/jersey-core/src/testFixtures/java/org/eclipse/edc/web/jersey/testfixtures/RestControllerTestBase.java, extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorService.java, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java, extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApi.java, extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiController.java, extensions/data-plane-selector/data-plane-selector-control-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiControllerTest.java, extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java, extensions/data-plane/data-plane-self-registration/src/test/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtensionTest.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java
Make the data plane "unregister" itself instead of "delete".
Closes #4238 
=> feat: data-plane self unregistration

spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/types/EndpointDataReferenceEntry.java
This PR corrects the null check error message for the providerId within the EDREntry. 
Wrong validation message was given for the providerId field.
Closes #4250
=> chore: correct null check message to corresponding field

extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/StatusList2021RevocationServiceTest.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/TestData.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/VerifiableCredential.java
Adds a JSON alias `validFrom` for the issuance date of a `VerifiableCredential` to compensate a vagueness in the StatusList2021 spec:
- VC Datamodel 1.1 requires a `issuanceDate` field
- VC Datamodel 2.0 requires a `validFrom` field
- StatusList2021 explicitly mentions the VC Datamodel 1.1 as normative reference
- StatusList2021 requires a `validFrom` field, which would violate the previous spec
- StatusList2021 uses yet another option, an `issued` field in its examples
This is quite inconsistent, and so far EDC could accomodate `issuanceDate` and `issued`, but not `validFrom`. This PR changes that.
VCs are not always parsed using the Json-LD transformers: when we fetch a `StatusList2021Credential` it is parsed using standard Jackson features.
_List other areas of code that have changed …
=> feat: add alias for issuance date

DEPENDENCIES, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImplTest.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/validation/ContractValidationServiceImpl.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
This PR fixes two issues of the current implementation:
- in contract negotiation request, the asset id part of the offer id can be different from the asset id provided in the `target` field of the `Policy`.
- in transfer request, the asset id provided in the request can be different to the one referred by the contract id also provided in this same request. This leads to inconsistent `EndpointDataReferenceEntry` being generated.
Fix.
Closes #4239 
Closes #4240 
=> fix: enforce consistency of contract negotiation request and transfer request

data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/DspHttpCoreExtensionTest.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, extensions/common/iam/iam-mock/src/main/java/org/eclipse/edc/iam/mock/IamMockExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtensionTest.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceDefaultServicesExtension.java, extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/Oauth2DefaultServiceExtensionTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/AudienceResolver.java
refactor AudienceResolver with Result as return
Closes #4265 
=> chore: refactor AudienceResolver with Result as return

core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/RuntimeExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImplTest.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java, extensions/common/api/management-api-configuration/src/main/resources/version.json, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/TransferProcessApiExtension.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/transform/JsonObjectToTransferRequestTransformer.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/v3/TransferProcessApiV3.java, extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/validation/TransferRequestValidator.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/TransferProcessApiTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/transform/JsonObjectToTransferRequestTransformerTest.java, extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/validation/TransferRequestValidatorTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferRequest.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspCatalogApiEndToEndTest.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspNegotiationApiEndToEndTest.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspTransferApiEndToEndTest.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspVersionApiEndToEndTest.java
Deprecates `TransferRequest.assetId` attribute on management api.
Upgrades api version to 3.0.1.
Remove `assetId` from the `TransferRequest` value object and replace its usages with the policy target (that has the same value)
cleanup
- improve RuntimeExtension a little, to permit better usage of the `RuntimePerClassExtension` (as shown in the `TransferProcessEventDispatchTest`)
- replaced some `EdcRuntimeExtension` occurrencies
Closes #4267
=> refactor(api): deprecate TransferRequest assetId

DEPENDENCIES, core/common/lib/json-ld-lib/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java, extensions/common/api/management-api-json-ld-context/build.gradle.kts, extensions/common/api/management-api-json-ld-context/src/main/java/org/eclipse/edc/connector/api/management/jsonld/ManagementApiJsonLdContextExtension.java, extensions/common/api/management-api-json-ld-context/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/common/api/management-api-json-ld-context/src/main/resources/document/management-context-v1.jsonld, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/ManagementApiJsonLdContextExtensionTest.java, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/SerdeIntegrationTest.java, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/TestFunctions.java, settings.gradle.kts
- Draft a JSON-LD context for the management api
- Introduces an experimental extension that register the context in the management api scope
- E2E serialization/deserialization of management api entities using the context.
dev experience
Currently the context is cached and associated with the URL `https://w3id.org/edc/connector/management/v0.0.1` which is yet to be decided in the final form.
Since using the `odrl` context at root level could lead some issue when compacting on egress, it's automatically defined as local context when defining the `policy` term.
There is still an issue when compacting the `@type` of the `odrl` policy where currently the local context is not applied  there
For performance reason all `ser/de` tests are in a single class with a class level e2e runtime.
Closes …
=> feat: first JSON-LD context for management api

DEPENDENCIES, build.gradle.kts, core/common/lib/json-ld-lib/build.gradle.kts, core/common/lib/transform-lib/build.gradle.kts, core/common/lib/validator-lib/build.gradle.kts, core/control-plane/control-plane-transform/build.gradle.kts, data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/build.gradle.kts, data-protocols/dsp/dsp-http-spi/build.gradle.kts, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/build.gradle.kts, extensions/common/crypto/lib/jws2020-lib/build.gradle.kts, extensions/common/json-ld/build.gradle.kts, extensions/common/vault/vault-hashicorp/build.gradle.kts, gradle/libs.versions.toml, spi/common/json-ld-spi/build.gradle.kts, spi/common/validator-spi/build.gradle.kts, system-tests/e2e-dataplane-tests/tests/build.gradle.kts, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSelectorEndToEndTest.java, system-tests/e2e-transfer-test/runner/build.gradle.kts, system-tests/management-api/management-api-test-runner/build.gradle.kts, system-tests/sts-api/sts-api-test-runner/build.gradle.kts, system-tests/telemetry/telemetry-test-runner/build.gradle.kts, system-tests/version-api/version-api-test-runner/build.gradle.kts
Changes the group id fo the `jakarta.json` api library.
To do that I had to add a `parsson` implementation, because from version 2.1.0 api and implementation have been separated (ref. https://github.com/jakartaee/jsonp-api/releases/tag/2.1.0-RELEASE)
- took the opportunity to rename the reference in the version catalog to the standard notation
- speed up `DataPlaneSelectorEndToEndTest` and remove related deprecation usages
Closes #4271 
=> build(deps): switch to new namespace for jakarta.json-api library

docs/developer/management-domains/management-domains.md
- **chore: remove wrong deprecation warning on policy controller (#4273)**
- **docs: Add architecture document for Management Domains (#4263)**
- **docs: clarify Management Domains** …
=> docs: clarify mgmt domains

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java, core/common/lib/http-lib/build.gradle.kts, core/common/lib/http-lib/src/main/java/org/eclipse/edc/http/client/ControlApiHttpClientImpl.java, core/common/lib/http-lib/src/test/java/org/eclipse/edc/http/client/ControlApiHttpClientImplTest.java, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/ControlPlaneApiClientExtension.java, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClient.java, extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClientTest.java, extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorClientExtension.java, extensions/data-plane-selector/data-plane-selector-client/src/main/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorService.java, extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java, extensions/data-plane/data-plane-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneClientExtension.java, extensions/data-plane/data-plane-client/src/main/java/org/eclipse/edc/connector/dataplane/client/RemoteDataPlaneClient.java, extensions/data-plane/data-plane-client/src/test/java/org/eclipse/edc/connector/dataplane/client/RemoteDataPlaneClientTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java, spi/common/http-spi/src/main/java/org/eclipse/edc/http/spi/ControlApiHttpClient.java, spi/common/http-spi/src/main/java/org/eclipse/edc/http/spi/EdcHttpClientException.java, spi/common/http-spi/src/main/java/org/eclipse/edc/http/spi/FallbackFactories.java
Extract an HTTP client that can be used to implement "remote" services in an easier way.
refactoring
Closes #4259 
=> refactor: extract control api client

.github/workflows/publish-context.yaml
publish  workflow for management JSON-LD context in github pages
public version of the JSON-LD context for the management api that will be used as repository
for w3id 
Closes #4278
=> feat: publish workflow for management JSON-LD context

resources/openapi/README.md, resources/openapi/control-api.version, resources/openapi/management-api.version, resources/openapi/observability-api.version, resources/openapi/sts-api.version, resources/openapi/version-api.version
Add `resources/openapi/*.version` files, that contain each the path to the `version.json` that will be used by the [publish-openapi-ui workflow](https://github.com/eclipse-edc/.github/blob/main/.github/workflows/publish-openapi-ui.yml) to set the correct version in the published specs.
api versioning
- an alternative would be to put all the `version.json` in the `resources/openapi` folder and have a build taks in the modules that require it as resource to take care of copying it in the `build` resource folder, but the current implementation was easier so for the moment it will be preferable
Part of #4182  …
=> build: openapi version link

extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/build.gradle.kts
Publish STS api group
needed to execute the version check correctly implemented by #4283 
Part of #4182 
=> docs(api): publish sts api group

DEPENDENCIES, extensions/common/api/version-api/build.gradle.kts
The version api docs was published into management-api, but it should go into version-api
docs
part of #4182
=> docs(api): publish version endpoint in the correct api group

DEPENDENCIES, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/validator/DataAddressValidatorRegistryImpl.java, extensions/common/json-ld/src/main/resources/document/dspace.jsonld
=> feat: update cached dspace jsonld document

extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiExtension.java, extensions/data-plane-selector/data-plane-selector-control-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiExtensionTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneSelectorControlApiEndToEndTest.java
Fixes a dataplane selector control API endpoint.
Add a missing transformer.
/
Closes #4245
=> fix(api): dataplane selector control API

core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/EqualOperatorPredicate.java, core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/EqualOperatorPredicateTest.java, core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/NotEqualOperatorPredicateTest.java, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/edc/from/JsonObjectFromAssetTransformer.java, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/edc/to/JsonObjectToAssetTransformer.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/edc/from/JsonObjectFromAssetTransformerTest.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/edc/to/JsonObjectToAssetTransformerTest.java, docs/developer/management-domains/management-domains.md, spi/control-plane/asset-spi/src/main/java/org/eclipse/edc/connector/controlplane/asset/spi/domain/Asset.java, spi/control-plane/asset-spi/src/test/java/org/eclipse/edc/connector/controlplane/asset/spi/domain/AssetTest.java, spi/control-plane/asset-spi/src/testFixtures/java/org/eclipse/edc/connector/controlplane/asset/spi/testfixtures/AssetIndexTestBase.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
- added a method `Asset#isCatalog()`
- Management API ingress: JSON-LD transformers parse the `@type` field and set the `Asset#properties['isCatalog']` flag
- Management API egress: JSON-LD transformers set the `@type` field on egress if `Asset#properties['isCatalog']` is `true`
- the information whether an Asset is a `CatalogAsset` is stored in `Asset#properties`
prepare for the next iteration, where `Dataset` extends `Catalog`
- I had originally planned to store the information in the `privateProperties`, but that would have made querying for `CatalogAssets` impossible, because we currently can't query by private properties. **If we don't care about querying, I'd suggest moving the flag back to the `privateProperties`**
- the `EqualOperatorPredicate` can now handle booleans
Closes #4295 …
=> feat: implement Asset specialization

docs/developer/decision-records/2024-06-24-api-authentication-configuration/README.md, docs/developer/decision-records/README.md
Adds a decision record on flexible authentication configuration
=> docs: decision record about authentication configuration

core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/ClasspathReader.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, extensions/control-plane/transfer/transfer-data-plane-signaling/build.gradle.kts, system-tests/e2e-transfer-test/control-plane/build.gradle.kts, system-tests/e2e-transfer-test/data-plane/build.gradle.kts, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Runtimes.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPushEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Export classpath loading from `EmbeddedRuntime`
Classpath loading is a time consuming operation (approx 14 seconds first time it runs, 4-5 seconds other times) as it needs to invoke gradle wrapper and the `printClasspath` task. By doing it just once for every runtime in the `e2e-transfer-test` makes tests run faster (approx 1 minute less than before) …
=> refactor(test): speed up e2e tests

core/control-plane/control-plane-catalog/build.gradle.kts, core/control-plane/control-plane-catalog/src/main/java/org/eclipse/edc/connector/controlplane/catalog/DatasetResolverImpl.java, core/control-plane/control-plane-catalog/src/main/java/org/eclipse/edc/connector/controlplane/catalog/DefaultDistributionResolver.java, core/control-plane/control-plane-catalog/src/test/java/org/eclipse/edc/connector/controlplane/catalog/DatasetResolverImplTest.java, core/control-plane/control-plane-catalog/src/test/java/org/eclipse/edc/connector/controlplane/catalog/DefaultDistributionResolverTest.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformer.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/Catalog.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/Dataset.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/Distribution.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
implements the second part of the preparatory work for Management Domains, specifically:
- makes `Catalog` extend `Dataset`
- improves the `DatasetResolver` and `DistributionResolver` so that they can handle `CatalogAsset`s
- updates the JSON-LD transformers, so they can handle `CatalogAsset`s
Management Domain feature, specifically handling distributed catalogs
Closes #4296 …
=> feat: implement Asset/Dataset specialization pt. 2

core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java, extensions/data-plane/data-plane-public-api-v2/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiV2ControllerTest.java, extensions/data-plane/data-plane-public-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlanePublicApiControllerTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/StreamFailure.java, spi/data-plane/data-plane-spi/src/test/java/org/eclipse/edc/connector/dataplane/spi/pipeline/StreamFailureTest.java
Appends the reason for the error to the message that will be sent to the user when the transfer fails
To improve the user experience by returning some feedback when the `StreamResult` has no message associated with it
Closes #4280
=> feat: Enhancing debug information for HttpDataSource transfers

extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryMessageTransformerTest.java
Adds two test cases to the `JsonObjectToPresentationQueryTransformer`, testing an empty array and a `null` array for the `scope` parameter
test coverage
Contributes https://github.com/eclipse-edc/Connector/issues/4322
=> chore: add test to presenationquery transformer

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java, core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/ParallelSink.java, core/data-plane/data-plane-util/src/test/java/org/eclipse/edc/connector/dataplane/util/sink/ParallelSinkTest.java
Wrap the `ParallelSink` logic into an async bloc.
avoid blocking behavior on long-running transfers
Closes #4330
=> fix: avoid thread blocking in ParallelSink

DEPENDENCIES, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/SqlCoreExtension.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/SqlCoreExtensionTest.java, system-tests/e2e-transfer-test/runner/build.gradle.kts, system-tests/management-api/management-api-test-runner/build.gradle.kts, system-tests/version-api/version-api-test-runner/build.gradle.kts
throws an error when the SQL modules, in particular `sql-core` is on the classpath, but no `TransactionContext` implementation (other than `NoopTransactionContext`) was provided.
avoid pitfalls, where downstream projects have to explicitly add the `transaction-local` module, but there is no warning if they don't do that.
In those cases, there could be sporadic exceptions thrown by the connection pool
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#subm …
=> feat: prevent using SQL modules with the NoopTransactionContext

DEPENDENCIES, docs/developer/decision-records/2024-07-03-additional-catalogrequest-param/README.md, docs/developer/decision-records/README.md
adds a decision record about adding a new, optional `parameters` field to the `CatalogRequest` body
documentation
Closes #4322
=> docs: add decision record about optional params in CatalogRequest

extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/edr/store/index/sql/schema/postgres/EndpointDataReferenceEntryMapping.java, spi/common/edr-store-spi/src/testFixtures/java/org/eclipse/edc/edr/spi/store/EndpointDataReferenceEntryIndexTestBase.java
Adds support for filtering by `createdAt` property when querying the EDRs 
Closes #4305 
=> feat: supports filtering by createdAt

DEPENDENCIES, core/common/lib/transform-lib/src/main/java/org/eclipse/edc/transform/transformer/edc/from/JsonObjectFromDataPlaneInstanceTransformer.java, core/common/lib/transform-lib/src/main/java/org/eclipse/edc/transform/transformer/edc/to/JsonObjectToDataPlaneInstanceTransformer.java, core/common/lib/transform-lib/src/test/java/org/eclipse/edc/transform/transformer/edc/from/JsonObjectFromDataPlaneInstanceTransformerTest.java, extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/schemas/DataPlaneInstanceSchema.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java, system-tests/version-api/version-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/versionapi/VersionApiEndToEndTest.java
add state field on `DataPlaneInstance` response
Closes #4335 
=> feat: add state field on DataPlaneInstance response

DEPENDENCIES, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/catalog/CatalogServiceImpl.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/catalog/BaseCatalogApiController.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/catalog/CatalogApiExtension.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/catalog/transform/JsonObjectToCatalogRequestTransformer.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/catalog/v31alpha/CatalogApiV31AlphaController.java, extensions/control-plane/api/management-api/catalog-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/catalog/v31alpha/CatalogApiV31alpha.java, extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/catalog/CatalogApiExtensionTest.java, extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/catalog/transform/JsonObjectToCatalogRequestTransformerTest.java, extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/catalog/v31alpha/CatalogApiV31AlphaControllerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/RequestScope.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/CatalogRequest.java, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/CatalogRequestMessage.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/services/spi/catalog/CatalogService.java
adds an optional list `additionalScopes` to the `CatalogRequest` (CatalogApi DTO) and the `CatalogRequestMessage` (DSP message).
These additional scopes can be used by certain implementations of the `IdentityService` to enrich the generated token.
For example, in DCP we can use this to attach additional scope strings to the `access_token`, effectively giving permissions to request more credentials from the CredentialService.
being able to request additional VerifiableCredentials from the wallet
- Since this is an alpha feature, it will be made available under the `/v3.1alpha` context url path
- the `instanceof` check in the `DspHttpRemoteMessageDispatcherImpl` might not be the most elegant solution, but it is the least impactful, and considering that we don't really foresee …
=> feat(api): add additional scopes to the CatalogRequest

extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json, extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/edr/v3/EdrCacheApiV3.java, system-tests/version-api/version-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/versionapi/VersionApiEndToEndTest.java
Remove deprecation attribute from a not-deprecated api
Closes #4358 
=> docs: remove deprecation typo

core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/LocalPublicKeyDefaultExtensionTest.java, core/common/lib/keys-lib/src/main/java/org/eclipse/edc/keys/KeyParserRegistryImpl.java, core/common/lib/keys-lib/src/main/java/org/eclipse/edc/keys/LocalPublicKeyServiceImpl.java, core/common/lib/keys-lib/src/main/java/org/eclipse/edc/keys/keyparsers/JwkParser.java, core/common/lib/keys-lib/src/main/java/org/eclipse/edc/keys/keyparsers/PemParser.java, core/common/lib/keys-lib/src/test/java/org/eclipse/edc/keys/LocalPublicKeyServiceImplTest.java, core/common/lib/keys-lib/src/test/java/org/eclipse/edc/keys/keyparsers/JwkParserTest.java, core/common/lib/keys-lib/src/test/java/org/eclipse/edc/keys/keyparsers/PemParserTest.java, spi/common/keys-spi/src/main/java/org/eclipse/edc/keys/spi/KeyParser.java, spi/common/keys-spi/src/main/java/org/eclipse/edc/keys/spi/KeyParserRegistry.java
Adds a `parsePublic` method to they keyparsers, that attempt to extract the public key from an encoded string, leaving behind any potential private key parts.
LocalPublicKeyServiceImpl should be able to extract a public key from any serialized format
=> feat(keys): add functionality to extract public key to KeyParsers

spi/control-plane/catalog-spi/build.gradle.kts, spi/control-plane/catalog-spi/src/main/java/org/eclipse/edc/connector/controlplane/catalog/spi/Dataset.java, spi/control-plane/catalog-spi/src/test/java/org/eclipse/edc/connector/controlplane/catalog/spi/CatalogSerializationTest.java
chore: fix catalog deserialization of `offers` field + test
bugfix
=> chore: fix catalog deserialization

core/common/lib/util-lib/src/main/java/org/eclipse/edc/util/io/Ports.java, core/common/lib/util-lib/src/test/java/org/eclipse/edc/util/io/PortsTest.java
Add an `ALREADY_RETURNED` `HashSet` to ensure that the port generated by `getFreePort` is not already returned.
Avoid possible collisions.
- changed the "incremental" port generation to the complete randomic. Looking at the tests they are always calling the `getFreePort` without arguments, that is generating a random number anyway, so the "efficiency" of using the next number instead is pretty negligible.
Closes #4365
=> test: avoid getFreePort collisions

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java
When sending the STARTED notification, the data plane ID should always be recorded.
consistency
=> fix: always record dataplane ID

docs/developer/README.md, docs/developer/sql-persistence.md, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/configuration/DataSourceName.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/test/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtensionTest.java, extensions/common/store/sql/edr-index-sql/src/main/java/org/eclipse/edc/edr/store/index/SqlEndpointDataReferenceEntryIndexExtension.java, extensions/common/store/sql/edr-index-sql/src/test/java/org/eclipse/edc/edr/store/index/sql/SqlEndpointDataReferenceEntryIndexExtensionTest.java, extensions/control-plane/store/sql/asset-index-sql/README.md, extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/assetindex/SqlAssetIndexServiceExtension.java, extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/controlplane/store/sql/assetindex/SqlAssetIndexServiceExtensionTest.java, extensions/control-plane/store/sql/contract-definition-store-sql/README.md, extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractdefinition/SqlContractDefinitionStoreExtension.java, extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/edc/connector/controlplane/store/sql/contractdefinition/SqlContractDefinitionStoreExtensionTest.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/SqlContractNegotiationStoreExtension.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/SqlContractNegotiationStoreExtensionTest.java, extensions/control-plane/store/sql/policy-definition-store-sql/README.md, extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/policydefinition/SqlPolicyStoreExtension.java, extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/edc/connector/controlplane/store/sql/policydefinition/SqlPolicyDefinitionStoreExtensionTest.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/transferprocess/SqlTransferProcessStoreExtension.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/controlplane/store/sql/transferprocess/SqlTransferProcessStoreExtensionTest.java, extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtension.java, extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtensionTest.java, extensions/data-plane/store/sql/accesstokendata-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlAccessTokenDataStoreExtension.java, extensions/data-plane/store/sql/data-plane-store-sql/README.md, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStoreExtension.java, extensions/policy-monitor/store/sql/policy-monitor-store-sql/src/main/java/org/eclipse/edc/connector/policy/monitor/store/sql/SqlPolicyMonitorStoreExtension.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/sql/configuration/DataSourceNameTest.java
Separate stores and datasources configurations, making configuration easier and clearer:
- `edc.datasource` represents the datasource configuration, that by default requires only one `default` datasource, but there's the possibility to define multiple of them
- `edc.sql.store.<name>.datasource` will associate the store to a datasource, that by default will be `default`
this will not break the existent configuration, but a `warning` log will be printed to spur adopters to migrate.
simplify configuration
- some deserved refactoring to `CommonsConnectionPoolServiceExtension`
- added some documentation explaining how the datasource configuration works
Closes #3811
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#su …
=> refactor: separate sql stores from datasources

docs/developer/decision-records/2024-08-05-custom-jwssigners/README.md, docs/developer/decision-records/README.md
Adds a decision-record about customizable `JWSSigners`, which can be used to delegate token signing out to a HSM.
outline technical impact
=> docs: add decision record about customizable JWSSigners

core/common/boot/src/main/java/org/eclipse/edc/boot/BootServicesExtension.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContext.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContextTest.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/SqlContractNegotiationStore.java, extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java, extensions/data-plane/data-plane-self-registration/src/test/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtensionTest.java, spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/system/ServiceExtensionContext.java
This PR adds the `edc.component.id` property with the following logic:
- if `edc.runtime.id` is configured, a warning is issued
- if `edc.component.id` is not configured, a warning is issued. 
- if `edc.runtime.id` is configured, its value is used for `edc.component.id`, and `edc.runtime.id` receives a random UUID
- if `edc.runtime.id` is not configured, a random UUID is used for `edc.component.id`
This way, backwards compatibility can be provided for deployments that previously had configured a static `edc.runtime.id`.
In addition, Dataplane Self Registration was modified to use the `edc.component.id` property.
component IDs are used for idempotent processes, such as data plane registration. runtime IDs are used for lease acquisition.
_List other areas of code that have changed but are …
=> feat: add component ID

core/common/lib/crypto-common-lib/build.gradle.kts, core/common/lib/crypto-common-lib/src/main/java/org/eclipse/edc/security/token/jwt/DefaultJwsSignerProvider.java, core/common/token-core/src/main/java/org/eclipse/edc/token/TokenServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsClientTokenIssuanceIntegrationTest.java
provide a dedicated class for the default JwsSignerProvider
avoid code duplication
=> chore: dedicated class for default JwsSignerProvider

extensions/control-plane/transfer/transfer-data-plane/README.md
Typo?
Should it not be consumer instead provider?
Found a mistake in the readme.
Just correct a typo 
No code changed
=> chore: update README.md

extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-sts/lib/identity-trust-sts-remote-lib/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenService.java, extensions/common/iam/identity-trust/identity-trust-sts/lib/identity-trust-sts-remote-lib/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/StsRemoteClientConfiguration.java, extensions/common/iam/identity-trust/identity-trust-sts/lib/identity-trust-sts-remote-lib/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenServiceTest.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/RemoteStsEndToEndTest.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsApiEndToEndTest.java, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsEndToEndTestBase.java
The `StsRemoteClientConfiguration` now holds the secret alias instead of the secret itself.
The `RemoteSecureTokenService` before sending the request fetches the secret from the vault with the configured secret alias.
Closes #4412
=> refactor(remote STS): lazy fetch the secret from the vault before request

extensions/control-plane/transfer/transfer-data-plane-signaling/src/main/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowController.java, extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java
Add null checks on the `dataPlaneId` in the `DataPlaneSignalingFlowController` 
Avoid exceptions: terminating a `DataFlow` that does not exist will return `success`, because it can implicitly be considered terminated
- added the check also on the `suspend` method, but it work differently, it will return failure if `dataPlaneId` is null, because a non existing data flow cannot be suspended and that needs to be notified.
Closes #4418
=> fix: consider terminated a non existing DataFlow

docs/developer/decision-records/2024-08-16-policy-validation/README.md, docs/developer/decision-records/README.md
decision record about policy validation and evaluation plan
=> docs: decision record about policy validation and evaluation plan

DEPENDENCIES, extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/revocation/RevocationServiceRegistryImpl.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/RevocationServiceRegistryImplTest.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/RevocationServiceRegistry.java
- **feat: support BitStringStatusList  (#4427)**
- **chore: add getRevocationStatus method**
Adds a method `getRevocationStatus` to the `RevocationServiceRegistry`
IdentityHub requires the status as string, not only whether it's valid or not. With BitStringStatusList, there could be custom status fields that are not null, but still indicate success. …
=> chore: add method to obtain revocation status as string(s)

DEPENDENCIES, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/RuleBindingRegistryImpl.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/validation/PolicyValidator.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/validation/RuleValidator.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplScenariosTest.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplValidationTest.java, core/control-plane/lib/control-plane-policies-lib/src/test/java/org/eclipse/edc/connector/controlplane/policy/contract/ContractExpiryCheckFunctionEvaluationTest.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/AtomicConstraintFunction.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/DynamicAtomicConstraintFunction.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/RuleBindingRegistry.java
adds policy validation in policy engine
Closes #4423 
=> feat: adds policy validation in policy engine

.github/workflows/discord-webhook.yml, DEPENDENCIES
updates the name of the Discord webhook secret
in an effort to harmonize all EDC repos, the discord webhook secret was stored under a new name
=> chore(ci): update Discord webhook secret name

extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldTranslator.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/JsonFieldTranslatorTest.java
Allow different types of numeric field with postgresql database.
AS done for other types (Boolean, Integer), add the same validation for other numeric types to avoid additional logging errors that should not be reflected with expected user behaviour.
UT's were added to reflect new scenarios.
Took the opportunity of extending with primitive java types to include more potential query usages.
Closes https://github.com/eclipse-edc/Connector/issues/3688
=> feat: Support filter expressions for additional numberic types

core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/plan/PolicyEvaluationPlanner.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/validation/RuleValidator.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplPlannerTest.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/PolicyEvaluationPlan.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/AndConstraintStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/AtomicConstraintStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/ConstraintStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/DutyStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/MultiplicityConstraintStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/OrConstraintStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/PermissionStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/ProhibitionStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/RuleFunctionStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/RuleStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/ValidatorStep.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/XoneConstraintStep.java
Introduces the policy evaluation plan and planner:
Given a `Policy`  and a scope, the `PolicyEvaluationPlanner` will recursively visit the input policy and it builds the `PolicyEvaluationPlan` based on the `PolicyEngine` configuration.  
The `PolicyEvaluationPlan` contains all the  steps that the impl of `PolicyEngine` will take when evaluating a `Policy` withing a scope. 
improve policies usage and debuggability 
Closes #4424 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) …
=> feat: policy evaluation plan

DEPENDENCIES, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/validation/PolicyValidator.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplValidationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImplTest.java, extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/BasePolicyDefinitionApiController.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/PolicyDefinitionApiExtension.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/model/PolicyValidationResult.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/transform/JsonObjectFromPolicyValidationResultTransformer.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/v31alpha/PolicyDefinitionApiV31Alpha.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/v31alpha/PolicyDefinitionApiV31AlphaController.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/PolicyDefinitionApiExtensionTest.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/PolicyDefinitionApiTest.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/v31alpha/PolicyDefinitionApiV31AlphaControllerTest.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/services/spi/policydefinition/PolicyDefinitionService.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
adds REST API for policy validation
improves policies usability and debuggability 
Closes #4425
=> feat: adds REST API for policy validation

core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcessTest.java
Make `StatusResultRetryProcess` to catch eventual exceptions and consider it as a failure instead of having the caller to do so.
Closes #4457 
=> fix: catch exceptions in the StatusResultRetryProcess

extensions/common/api/management-api-json-ld-context/src/main/resources/document/management-context-v1.jsonld, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/SerdeIntegrationTest.java, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/TestFunctions.java
adds new terms definition in context for policy validation and  evaluation plan
Closes #4456
=> feat: adds new terms definition in json-ld context 

extensions/common/api/management-api-json-ld-context/src/main/resources/document/management-context-v1.jsonld, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/SerdeIntegrationTest.java, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/TestFunctions.java
adds missing terms in context definition
=> chore: adds missing terms in context definition

extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClient.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/main/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientExtensionTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/DataPlaneSignalingClientTest.java
introduces `dspace` prefix in signaling client
we use `dspace:DataAddress` format 
Closes #4467 
=> feat: introduces dspace prefix in signaling client

core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java, core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/plan/PolicyEvaluationPlanner.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplPlannerTest.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplTest.java, extensions/common/api/management-api-json-ld-context/src/test/java/org/eclipse/edc/connector/api/management/jsonld/serde/TestFunctions.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/transform/JsonObjectFromPolicyEvaluationPlanTransformerTest.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyValidatorFunction.java, spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/plan/step/ValidatorStep.java
Introduces PolicyEngineValidator for pre- or post-validators
Closes #4446
=> feat: introduces PolicyEngineValidator for pre- or post-validators

DEPENDENCIES, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/src/test/java/org/eclipse/edc/api/iam/identitytrust/sts/controller/SecureServiceTokenApiControllerTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-client-configuration/src/test/java/org/eclipse/edc/iam/identitytrust/sts/client/configuration/StsClientConfigurationExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/build.gradle.kts, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsDefaultStoresExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/defaults/store/InMemoryStsClientStore.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsClientTokenIssuanceIntegrationTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/store/InMemoryStsClientStoreTest.java, extensions/common/store/sql/sts-client-store-sql/build.gradle.kts, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/SqlStsClientStore.java, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/SqlStsClientStoreExtension.java, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/schema/BaseSqlDialectStatements.java, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/schema/StsClientStatements.java, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/schema/postgres/PostgresDialectStatements.java, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/schema/postgres/StsClientMapping.java, extensions/common/store/sql/sts-client-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/common/store/sql/sts-client-store-sql/src/main/resources/sts-client-schema.sql, extensions/common/store/sql/sts-client-store-sql/src/test/java/org/eclipse/edc/iam/identitytrust/sts/store/SqlStsClientStoreExtensionTest.java, extensions/common/store/sql/sts-client-store-sql/src/test/java/org/eclipse/edc/iam/identitytrust/sts/store/SqlStsClientStoreTest.java, settings.gradle.kts, spi/common/identity-trust-sts-spi/src/main/java/org/eclipse/edc/iam/identitytrust/sts/spi/model/StsClient.java, spi/common/identity-trust-sts-spi/src/main/java/org/eclipse/edc/iam/identitytrust/sts/spi/store/StsClientStore.java, spi/common/identity-trust-sts-spi/src/testFixtures/java/org/eclipse/edc/iam/identitytrust/sts/spi/store/fixtures/StsClientStoreTestBase.java, spi/common/identity-trust-sts-spi/src/testFixtures/java/org/eclipse/edc/iam/identitytrust/sts/spi/store/fixtures/TestFunctions.java, system-tests/sts-api/sts-api-test-runner/build.gradle.kts, system-tests/sts-api/sts-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/sts/api/StsApiEndToEndTest.java
STS client SQL store implementation
Closes #4473 
=> feat: STS client SQL store implementation

core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcessTest.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcessTest.java
Catches exceptions that could happen in the `CompletableFutureRetryProcess`
avoid state machine entry to stale
- I'm not considering this PR a bugfix because the bug-ish behavior is in the component that throws an unexpected exception (according to the issue it would be `AzureStorageDataSinkFactory`). having the overarching component to handle it safely it is a new feature to the state machine retry process component that will prevent such potential bugs downstream.
- improved behavior on `StatusResultRetryProcess`, that was treating the throwable as a "fatal error", but in fact it is better to consider it a generic failure because the exception could be temporary
Closes #4464 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/ …
=> fix: catch exceptions in CompletableFutureRetryProcess

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultTrustedIssuerRegistry.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultTrustedIssuerRegistryTest.java, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/main/java/org/eclipse/edc/iam/identitytrust/issuer/configuration/TrustedIssuerConfigurationExtension.java, extensions/common/iam/identity-trust/identity-trust-issuers-configuration/src/test/java/org/eclipse/edc/iam/identitytrust/issuer/configuration/TrustedIssuerConfigurationExtensionTest.java, extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImpl.java, extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/rules/HasValidIssuer.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImplTest.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/rules/HasValidIssuerTest.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/validation/TrustedIssuerRegistry.java
As of today the TrustedIssuerRegistry defines the list of trusted issuers ids. When validating the counter-party VCs, it is just checked that the issuer of each of these VC is contained in that list, which is quite limiting.
A typical use-case is that we want to be able to define the types of VCs that are supported for each trusted issuer.
VC validation module.
Closes #4453 
=> feat: enable defining supported VC types for trusted issuers

DEPENDENCIES, extensions/common/store/sql/sts-client-store-sql/src/main/java/org/eclipse/edc/iam/identitytrust/sts/store/SqlStsClientStore.java, spi/common/identity-trust-sts-spi/src/testFixtures/java/org/eclipse/edc/iam/identitytrust/sts/spi/store/fixtures/StsClientStoreTestBase.java
returns the `StsClient` from `StsClientStore#create()`
it was null before, allow for fluent statements
=> fix: return StsClient from create()

extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtension.java, extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/client/HashicorpVaultClient.java, extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/client/HashicorpVaultSettings.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/client/HashicorpVaultClientTest.java, extensions/common/vault/vault-hashicorp/src/test/java/org/eclipse/edc/vault/hashicorp/client/HashicorpVaultSettingsTest.java
Adds the possibility to configure a folder for the storage of secrets inside Hashicorp Vault.
Additional feature, as described in the discussion and issue.
Closes #4384 
=> feat(vault): implements custom secret folder config

extensions/common/json-ld/src/main/resources/document/management-context-v1.jsonld, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TestFunctions.java
Applies a [type-scoped-context](https://www.w3.org/TR/json-ld11/#dfn-type-scoped-context) for importing with `@import`
the ODRL context when needed. 
Fixes the `@type` of Policy which wasn't compacted correctly when scoping the context in the `property`
etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._
=> chore: management API JSON-LD context improvements

core/control-plane/control-plane-catalog/src/main/java/org/eclipse/edc/connector/controlplane/catalog/DatasetResolverImpl.java, core/control-plane/control-plane-catalog/src/test/java/org/eclipse/edc/connector/controlplane/catalog/DatasetResolverImplTest.java
Adds a check to the `DatasetResolverImpl` to only return a dataset if it has an offer attached.
To avoid exposing sensitive information (asset metadata) if the requesting participant is not authorized to see it.
Also adds a check for `query` and `getById` to immediately return if no valid contract definitions exist for the requesting participant, as then no offers would be returned anyway, so it doesn't make sense to query and evaluate the assets in that case.
=> fix: only return dataset with valid offers

DEPENDENCIES, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcessTest.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcessTest.java
Backport fixes brought by #4458 #4457 in 0.9.1 
=> fix: catch exceptions in `RetryProcess`

core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/LocalPublicKeyDefaultExtensionTest.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/ClasspathReader.java, core/common/lib/keys-lib/src/main/java/org/eclipse/edc/keys/VaultCertificateResolver.java, core/common/lib/keys-lib/src/test/java/org/eclipse/edc/keys/VaultCertificateResolverTest.java, extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/jwt/X509CertificateDecoratorTest.java
Change path handling to correctly handle Windows path names.
Change line ending handling from using `System.lineSeparator` to using the regex \R to treat all unicode line ending character sequences as the line endings.
Change unit tests that compared certificates read from file, to ignore the line ending characters, so differences in line ending did not break the test.
The code failed during the unit tests when build on Windows, this change corrects the issues and enables the code to build. Generally checking for specific line endings (ie. `System.lineSeperator`) could be avoided and instead using the `\R` to match all unicode line endings will make the code more robust towards being built on different systems.
Closes #4484
=> fix: build failing on Windows (#4484)

docs/developer/decision-records/2024-09-25-multiple-protocol-versions/README.md, docs/developer/decision-records/README.md
Decision record about multiple protocol versions
=> docs: decision record about multiple protocol versions

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/message/RemoteMessageDispatcherRegistryImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationEventDispatchTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessEventDispatchTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/DspHttpCoreExtension.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImplTest.java, extensions/control-plane/callback/callback-http-dispatcher/src/main/java/org/eclipse/edc/connector/controlplane/callback/dispatcher/http/CallbackEventDispatcherHttpExtension.java, extensions/control-plane/callback/callback-http-dispatcher/src/main/java/org/eclipse/edc/connector/controlplane/callback/dispatcher/http/GenericHttpRemoteDispatcherImpl.java, extensions/control-plane/callback/callback-http-dispatcher/src/test/java/org/eclipse/edc/connector/controlplane/callback/dispatcher/http/GenericHttpRemoteDispatcherWrapperExtensionTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/message/RemoteMessageDispatcher.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/message/RemoteMessageDispatcherRegistry.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/services/spi/callback/CallbackProtocolResolver.java, spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/controlplane/services/spi/callback/CallbackProtocolResolverRegistry.java
changes registration of dispatchers accordingly to the multiple versions [DR](https://github.com/eclipse-edc/Connector/issues/4495)
foundation for supporting multiple protocols
Closes #4506 
=> refactor: changes registration of dispatchers

DEPENDENCIES, extensions/common/json-ld/src/main/resources/document/management-context-v1.jsonld, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/SerdeEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TestFunctions.java
add missing ODRL mapping in ContractAgreement
missing ODRL mapping causing compaction issues on `ContractAgreement`
=> fix(jsonld): add missing ODRL mapping in ContractAgreement

data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromDataServiceTransformer.java, data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromDataServiceTransformerTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
adds `dcat:endpointURL` and deprecate `dcat:endpointUrl` in DataService transformer
Closes #4523
=> fix: typo dcat:endpointUrl 

DEPENDENCIES, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java
The incorrect process id is used. See #4527.
Closes #4527
=> fix: make consumer use the consumer process id to handle a provider offer

docs/developer/decision-records/2024-10-02-clustered-data-plane/README.md, docs/developer/decision-records/README.md
DR for implementing clustered data-plane.
Part of: #4439 #4440
=> docs: DR for clustered data-plane

DEPENDENCIES, spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/document/DidDocument.java
Changes the default json-ld context for `DidDocument`.
To follow the "Decentralized Identifiers (DIDs) v1.0 specification".
Closes #4501
=> fix: DidDocument default context

docs/developer/decision-records/2024-10-10-daps-deprecation/README.md, docs/developer/decision-records/README.md, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java, extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsExtension.java, extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsJwtDecorator.java, extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsTokenDecorator.java
Deprecate `oauth2-daps` module and releated classes.
cleanup
- given that the code effort was minimal, I included the DR in the same PR
Closes #4534 
=> docs: deprecate DAPS module

core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, core/control-plane/control-plane-transform/src/main/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToPolicyTransformer.java, core/control-plane/control-plane-transform/src/test/java/org/eclipse/edc/connector/controlplane/transform/odrl/to/JsonObjectToPolicyTransformerTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImpl.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/message/DspRequestHandlerImpl.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractNegotiationEventMessageTransformerTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/controlplane/contract/spi/types/negotiation/ContractNegotiation.java, spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/controlplane/contract/spi/types/negotiation/ContractNegotiationTest.java
Fixes for:
- `ConsumerContractNegotiationManagerImpl.processAccepting` did not pass the current `Policy` as part of the `RemoteMessage` when dispatching, causing an NPE during policy evaluation.
- `JsonObjectToPolicyTransformer` did not deserialize `assignee` and `assigner` if the policy type is an agreement, which is required by DSP
- `DspHttpRemoteMessageDispatcherImpl` did not report the HTTP error code
- `DspRequestHandlerImpl` reported the incorrect validation context
- `ContractNegotiation` did not allow for a valid state transition (OFFERED)
- `ContractNegotistion` should not allow transitions from FINALIZED to TERMINATED
Closes #4543
=> feat: fixes related to DSP conformance

.github/workflows/verify.yaml
deactivates the dataplane BOM smoke test for now until it has been replaced with a more robust test
it was flaky
=> fix(ci): deactivate dataplane BOM smoke test for now

extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/mapper/UnexpectedExceptionMapper.java, extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/UnexpectedExceptionMapperTest.java
Log only real unexpected exceptions
improve logging
Closes #4554 
=> refactor: avoid logging on WebApplicationException

data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiController.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiController20241.java, data-protocols/dsp/dsp-catalog/dsp-catalog-http-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiControllerTest.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/controller/DspNegotiationApiController.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/controller/DspNegotiationApiController20241.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-api/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/controller/DspNegotiationApiControllerTest.java, data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/type/DspConstants.java, data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/type/DspNamespace.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-api/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/controller/DspTransferProcessApiController.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-api/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/controller/DspTransferProcessApiController20241.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-api/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/controller/DspTransferProcessApiControllerTest.java
Adds support for multi-namespace in dsp controllers by passing the namespace in the controller constructor.
In order to type the available dsp namespaces a class `DspNamespace` has been introduced.
Closes #4510 
=> refactor: multi-namespace in dsp controllers

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/scope/DcpScopeExtractorRegistry.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/scope/DcpScopeExtractorVisitor.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/scope/DcpScopeExtractorRegistryTest.java, spi/common/identity-trust-spi/build.gradle.kts, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/scope/ScopeExtractor.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/scope/ScopeExtractorRegistry.java
Binds `ScopeExtractor` to `RequestPolicyContext` because it's the actual upper type that's passed to it. 
simplify implementation from adopters point of view
Closes #4569 
=> refactor(policy): narrow ScopeExtractor policy context type bounds

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/asset/AssetQueryValidator.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/contractagreement/ContractAgreementServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/contractdefinition/ContractDefinitionServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/query/QueryValidator.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/query/QueryValidators.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/asset/AssetQueryValidatorTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractagreement/ContractAgreementServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractdefinition/ContractDefinitionServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImplTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/query/QueryValidatorsTest.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImplTest.java
Improve `QueryValidator`s testing strategy, by moving the instantiations to a factory and testing them separately from the services in which they are used
Closes #3731
=> refactor(test): improve QueryValidator testing strategy

gradle/libs.versions.toml, spi/common/auth-spi/build.gradle.kts, spi/common/auth-spi/src/main/java/org/eclipse/edc/api/auth/spi/AuthenticationRequestFilter.java
This PR add the jarkarta @Priority annotation to the AuthenticationFilter.
Allow other extension to register filters in the correct order of precedence.
Closes #4580
=> fix: add missing @Priority to the AuthenticationRequestFilter

core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPointScanner.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ProviderMethodScanner.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ProviderMethodScannerTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/lifecycle/RegistrationPhaseTest.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/DependencyInjectionExtension.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/ReflectiveObjectFactory.java, core/common/junit/src/test/java/org/eclipse/edc/junit/extensions/ReflectiveObjectFactoryTest.java
Does some little tweaks to `DependencyGraph` to improve performance, both time and memory wise.
The code used to measure the improvements has been put on `ExtensionLoader` in the `loadServiceExtensions` method:
```java
Runtime runtime = Runtime.getRuntime();
var memoryUsed = runtime.totalMemory() - runtime.freeMemory();
System.out.println("USED MEMORY BEFORE: " + memoryUsed);
var l = System.currentTimeMillis();
System.out.println("CREATE DEPENDENCY GRAPH STARTED AT " + l);
var injectionContainers = new DependencyGraph(context).of(serviceExtensions);
System.out.println("DEPENDENCY GRAPH CREATED IN " + (System.currentTimeMillis() - l));
System.out.println("USED MEMORY BY DEP GRAPH: " + ((runtime.totalMemory() - runtime.freeMemory()) - memoryUsed));
```
With the changes put in place (details …
=> refactor: optimize dependency graph performances

README.md
Fixes the broken link to the sample runtime.
Changes the link from referring from the custom to the basic sample runtime example.
The current [link](https://github.com/eclipse-edc/Samples/blob/main/other/custom-runtime/src/main/java/org/eclipse/edc/sample/runtime/CustomRuntime.java) refers to a directory, which no longer exists.
The updated link refers to the basic instead of the custom sample runtime, as this provides an easier entrypoint into connector runtimes.
A link to the custom sample runtime is included in the README.md of the basic sample runtime.
-
-
=> docs: update broken sample runtime link

core/common/lib/transform-lib/src/main/java/org/eclipse/edc/transform/transformer/dspace/to/JsonObjectToDataAddressDspaceTransformer.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/flow/TransferTypeParserImpl.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/flow/TransferTypeParserImplTest.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/PublicEndpointGeneratorServiceImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/PublicEndpointGeneratorServiceImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, docs/developer/decision-records/2024-10-24-bidirectional-data-transfers/README.md, docs/developer/decision-records/README.md, extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DataPlaneAuthorizationServiceImpl.java, extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpIntegrationTests.java, extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiV2Extension.java, extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/main/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformer.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/from/JsonObjectFromDataFlowStartMessageTransformerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-transform/src/test/java/org/eclipse/edc/connector/api/signaling/transform/to/JsonObjectToDataFlowStartMessageTransformerTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessage.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/TransferType.java, spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/instance/DataPlaneInstance.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/PublicEndpointGeneratorService.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataPlaneSignalingApiEndToEndTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java
this PR introduces the capability on provider dataplanes to create "response channel EDRs": data planes that support this can expose a "response channel" through which consumers can tunnel back control information
=> feat: allow bi-directional data transfers

data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformer.java, data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java
backport  (#4602):   removes double forNamespace call
=> fix:  backport removal of double forNamespace call 

core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ProviderMethodScanner.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ProviderMethodScannerTest.java
Last PR of the "startup" optimization work (see also #4593 #4590 #4587)
This one ensures that the injection containers are instantiated in the first extensions loop so there's no need to create them in the additional loop that was executed right before method's return.
This saves some other millyseconds and memory, as the `serviceProviders` map is not necessary anymore.
startup optimization
- removed 2 unused methods in the `ProviderMethodScanner` component
=> refactor: save one iteration of the extension list in DependencyGraph

docs/developer/decision-records/2024-11-06-configuration-injection/README.md, docs/developer/decision-records/README.md
Adds a decision record that outlines the configuration injection feature
=> docs: decision record about configuration injection

data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformer.java, data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/v2024/from/JsonObjectFromCatalogV2024Transformer.java, data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogTransformerTest.java, data-protocols/dsp/dsp-catalog/lib/dsp-catalog-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/catalog/transform/v2024/from/JsonObjectFromCatalogV2024TransformerTest.java, spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/CatalogApiEndToEndTest.java
fixes  sub-catalogs serialization
Closes #4586 
=> fix: sub-catalogs serialization

core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionContainer.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPointScanner.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectorImpl.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ServiceInjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ValueInjectionPoint.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/ExtensionLoaderTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/InjectorImplTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/TestFunctions.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPointTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/InjectionPointDefaultServiceSupplierTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ServiceInjectionPointTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ValueInjectionPointTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ConfigurationObject.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ExtensionWithConfigObject.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ExtensionWithConfigValue.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/RequiredDependentExtension.java, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/test/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtensionTest.java
This PR implements the _configuration injection_ feature whereby configuration values can be injected in several ways.
To do that, some responsibility was moved from the `DependencyGraph` and the `InjectionPointScanner` into the concrete `InjectionPoint` implementations.
ease of use
- Adapting the EDC code base to this new feature will come in a subsequent PR, but just to show how the mechanism works, I used it in the `StsRemoteClientConfigurationExtension` and in the `CoreServicesExtension`.
- verified with MVD
- providing default values for `ValueInjectionPoints` and `ConfigurationInjectionPoints` isn't very elegant at the moment. The existing `defaultProvider` mechanism should be used, but that'll require some more refactoring. So I'll do this in a subsequent PR to keep this one …
=> feat: implement Configuration Injection

core/common/boot/src/main/java/org/eclipse/edc/boot/system/DependencyGraph.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionPointDefaultServiceSupplier.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ServiceInjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ValueInjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/lifecycle/ExtensionLifecycleManager.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/lifecycle/ServiceProvider.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPointTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/InjectionPointDefaultServiceSupplierTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ValueInjectionPointTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/lifecycle/ServiceProviderTest.java, core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/DependencyInjectionExtension.java, spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/system/ValueProvider.java
this PR improves the handling of default values for `ValueInjectionPoints`. 
Specifically, the `ValueInjectionPoint` now has a default `ValueProvider`, which reads the default value from the annotation attribute.
re-use existing infrastructure
the `ServiceProvider` class now implements the `ValueProvider` interface and is a specific variant for `ServiceInjectionPoints`
Contributes to #4610
=> feat: improve handling of default values for ValueInjectionPoints

core/common/lib/policy-engine-lib/src/main/java/org/eclipse/edc/policy/engine/validation/PolicyValidator.java, core/common/lib/policy-engine-lib/src/test/java/org/eclipse/edc/policy/engine/PolicyEngineImplValidationTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionServiceImplTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java
adds a configuration `edc.policy.validation.enabled` for enabling the call to `PolicyEngine#validate` while creating/updating the `PolicyDefinition` 
improves policy management
Renamed also the failure message from `left operand` to `leftOperand` for consistency 
Closes #4619
=> feat: adds flag to enable validation on create/update policy definitions

extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStore.java, extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStoreExtension.java, extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/schema/BaseSqlDialectStatements.java, extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/schema/JtiValidationStoreStatements.java, extensions/common/store/sql/jti-validation-store-sql/src/main/java/org/eclipse/edc/jtivalidation/store/sql/schema/postgres/PostgresDialectStatements.java, extensions/common/store/sql/jti-validation-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, extensions/common/store/sql/jti-validation-store-sql/src/test/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStoreExtensionTest.java, extensions/common/store/sql/jti-validation-store-sql/src/test/java/org/eclipse/edc/jtivalidation/store/sql/SqlJtiValidationStoreTest.java
This fixes the package declaration of the JTI validation store
it had a wrong package declaration, which causes confusion, and more importantly, causes runtime errors
specifically, the class
`org.eclipse.edc.edr.store.index.sql.schema.postgres.PostgresDialectStatements` existed twice on the classpath, but one was now updated to be `org.eclipse.edc.jtivalidation.store.index.sql.schema.postgres.PostgresDialectStatements`
=> fix: package declaration of JtiValidationStore

core/common/boot/src/main/java/org/eclipse/edc/boot/config/ConfigurationLoader.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/ExtensionLoader.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/lifecycle/ExtensionLifecycleManager.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/ExtensionLoaderTest.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java, extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java, extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java, extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/WebServiceConfigurerImpl.java, extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/health/HashicorpVaultHealthExtension.java, extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/controlplane/provision/http/HttpProvisionerExtension.java, extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java, extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DefaultDataPlaneAccessTokenServiceImpl.java, extensions/data-plane/data-plane-self-registration/src/main/java/org/eclipse/edc/connector/dataplane/registration/DataplaneSelfRegistrationExtension.java, spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/monitor/ConsoleMonitor.java
Sets `INFO` as default log level when the default `ConsoleMonitor` instance is created.
Switch some `INFO` logs to `DEBUG` (especially in the startup phase).
log cleanup
- refactored the way monitor extensions are loaded, before was through a static method that duplicated the logic already existing in `ServiceLocator`
Closes #4625 
=> refactor: set INFO as default log level, downgraded some log calls

extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java, extensions/data-plane/data-plane-http-oauth2-core/src/main/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactory.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecorator.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2DataAddressSchema.java, spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecoratorTest.java
As of today, Oauth2AssertionDecorator does not provide the capability to encode the optional kid header in the access token request to Oauth2 server.
We should be able to specify a kid: https://www.rfc-editor.org/rfc/rfc7515#page-11
Closes #4626 
=> fix: add  capability to encode `kid` header in request to Oauth2 server 

core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java, core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/CriterionOperatorRegistryImpl.java, core/common/lib/query-lib/src/main/java/org/eclipse/edc/query/LessThanOperatorPredicate.java, core/common/lib/query-lib/src/test/java/org/eclipse/edc/query/LessThanOperatorPredicateTest.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/AbstractStateEntityManager.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/StateMachineManager.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/StateMachineManagerTest.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtensionTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java, extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslator.java, extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/PostgresqlOperatorTranslatorTest.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataPlaneStatements.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/DataFlowMapping.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriterionOperatorRegistry.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/TransferService.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Restarts long running transfers after a data-plane restart
dataplane should be able to recover the transfers after a reboot
- this only provides the feature in a single data-plane instance environment, clustered environment will be supported in subsequent PRs
- added @Postgresql version of E2E tests for streaming. also because this scenario, that provides for the reboot is only testable with a persistent store and not in memory.
- added a `closeAll` method on `TransferService` that will shut down all the transfers during the shut down phase.
- implemented the `<` operator, I was actually surprised that it didn't already existed. this was necessary, I will provide an issue/PR to implement also the greater than.
the `restartFlows` method will in the future called in a different way as we're …
=> feat: restart interrupted data flows

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtensionTest.java
The following properties config in `DcpDefaultServicesExtension` are marked required:
- `edc.iam.sts.publickey.id`
- `edc.iam.sts.privatekey.alias`
They are only required when the embedded STS is used. 
It fixes the case where the `SecureTokenService` is not default (provided by another extension)
but the above properties are still required …
=> fix: not required properties in DcpDefaultServicesExtension

extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java, spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPushEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Adds a ```SUSPENDED``` state to the list of allowed states to be consumer started.
When provider resume the transfer it initiate transitionStarted for the consumer from ```SUSPENDED``` state, that is currently not allowed, as a result consumer return an error for the provider and transfer move to ```TERMINATED``` state. 
To make possible create e2e test by provider commands, method awaitTransferToBeInState from TransferEndToEndTestBase need to be unified.
Closes [#4591](https://github.com/eclipse-edc/Connector/issues/4591)
=> fix: Fatal error while resume PULL transfer from provider

data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/type/DspVersionPropertyAndTypeNames.java, data-protocols/dsp/dsp-version/dsp-version-http-api/src/main/java/org/eclipse/edc/protocol/dsp/version/http/api/DspVersionApiExtension.java, data-protocols/dsp/dsp-version/dsp-version-http-api/src/main/java/org/eclipse/edc/protocol/dsp/version/http/api/transformer/JsonObjectFromProtocolVersionsTransformer.java, data-protocols/dsp/dsp-version/dsp-version-http-api/src/main/java/org/eclipse/edc/protocol/dsp/version/http/api/transformer/JsonObjectFromVersionsError.java, data-protocols/dsp/dsp-version/dsp-version-http-api/src/test/java/org/eclipse/edc/protocol/dsp/version/http/api/transformer/JsonObjectFromProtocolVersionsTransformerTest.java, data-protocols/dsp/dsp-version/dsp-version-http-api/src/test/java/org/eclipse/edc/protocol/dsp/version/http/api/transformer/JsonObjectFromVersionsErrorTransformerTest.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspVersionApiEndToEndTest.java
removes JSON-LD requirements in dsp version endpoint as required by [this](https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/issues/37)
Closes #4654 
=> feat: removes JSON-LD requirements in dsp version endpoint

extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/controlplane/provision/http/impl/HttpProviderProvisioner.java, extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/controlplane/provision/http/impl/HttpProvisionerRequest.java, extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/controlplane/provision/http/impl/HttpProviderProvisionerTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
Fixes deprovisioning for `provision-http` module by: 
- changing the too strict `canDeprovision` implementation 
- fix the serialization of the `type` field in `HttpProvisionerRequest`
- fixing the id passed in the deprovisioned response
fix a broken feature
- the `provision-http` module is not tested in a comprehensive way, we should have some sort of "provision tests" that could be used by the modules that are providing a `Provisioner` implementation to being able to test a full `resource manifest -> provision -> deprovision` passing through the transfer process manager, because testing this thing in the e2e like we're doing looks not-optimal.
Closes #4630
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#subm …
=> fix: deprovision phase for provision-http

data-protocols/dsp/dsp-catalog/lib/dsp-catalog-http-api-lib/src/test/java/org/eclipse/edc/web/spi/configuration/WebServiceSettingsTest.java, data-protocols/dsp/dsp-http-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtension.java, extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtension.java, extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java, extensions/common/api/version-api/src/main/java/org/eclipse/edc/connector/api/management/version/VersionApiExtension.java, extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/WebServiceConfigurerImpl.java, extensions/common/http/jetty-core/src/test/java/org/eclipse/edc/web/jetty/WebServiceConfigurerImplTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-accounts-api/src/main/java/org/eclipse/edc/api/iam/identitytrust/sts/accounts/StsAccountsApiConfigurationExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-api/src/main/java/org/eclipse/edc/api/iam/identitytrust/sts/StsApiConfigurationExtension.java, extensions/data-plane/data-plane-public-api-v2/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlanePublicApiV2Extension.java, spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceSettings.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java
Remove the `useDefaultContext` attribute from `WebServiceSettings`, because it's use was not clear and it didn't permit runtimes to start with default configuration.
- removed also `name` because it was used only for logging, and for that `contextAlias` can be used as well
- uniformed the `defaultPath` value in the form of `/api/<context_alias>`
- the current design of the definition and use of these configurations is not really lean and it could deserve some more love
Closes #4669 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.m …
=> feat: permit default api context config to be used

extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json, extensions/control-plane/api/management-api/protocol-version-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/protocolversion/v4alpha/ProtocolVersionApiV4alpha.java
fix broken `ProtocolVersionApi` documentation that generates the swagger spec.
Api documentation is incorrect, causing an invalid swagger spec to be generated.
=> fix: fix broken protocol version api specification

core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java
Avoids unnecessary exception wrapping in the `EmbeddedRuntime` `boot` method
improve test failure message
- changed the way the properties are provided to the runtime, legacy way was to set them tosystem properties, I changed this behavior by registering a `ConfigurationExtension` that will load them into a `Config` object directly, more EDC-y :)
=> refactor(test): improving `EmbeddedRuntime` exception handling

extensions/common/crypto/ldp-verifiable-credentials/src/test/resources/jws2020/issuing/0001_vc.json, extensions/common/crypto/lib/jws2020-lib/src/test/java/org/eclipse/edc/security/signature/jws2020/IssuerTests.java, extensions/common/crypto/lib/jws2020-lib/src/test/java/org/eclipse/edc/security/signature/jws2020/VerifierTests.java, extensions/common/crypto/lib/jws2020-lib/src/test/resources/jws2020/issuing/0001_vc.json, extensions/common/crypto/lib/jws2020-lib/src/test/resources/jws2020/verifying/0001_vc.json, extensions/common/crypto/lib/jws2020-lib/src/test/resources/jws2020/verifying/0003_vc_embedded.json, extensions/common/crypto/lib/jws2020-lib/src/test/resources/jws2020/verifying/0004_vc_two_valid_proofs.json, extensions/common/crypto/lib/jws2020-lib/src/test/resources/jws2020/verifying/0007_vp_compacted.json
sets the expiration date of test VCs to 2099
fix tests
Closes #4699
=> fix: update expiration of test credentials

core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java, extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlStoreSetupExtension.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/LazySupplier.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/AbstractDataPlaneTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/ClusteredDataPlaneEndToEndTest.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/KafkaExtension.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Runtimes.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPushEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
Refactor EndToEnd tests to avoid flaky test executions when testcontainers is used.
Concepts:
- `EmbeddedRuntime` configurations are passed lazily through `configurationProvider`s
- The configuration values in `Participant` subclasses are generated lazily (using the provided `LazySupplier`) during the EDC runtime startup so they will take into account eventual testcontainers ports used 
avoid test flakyness by design
- there still are two potential pityfalls in `Participant`: `managementEndpoint` and `protocolEndpoint` that are currently instantiated statically while they should follow the same pattern. It will be fixed in a subsequent PR to avoid clogging this one
- I will also provide some guidance in the documentation that will be useful also for downstream projects
Part of #4710 …
=> ci: fix flaky testcontainers tests

.github/workflows/nightly-tests.yaml
added missing cron: prefix to nightly-tests.yaml configuration
In order to fix trigger mechanism of nightly tests, from being run every push to run scheduled at 00:00 AM
Documentation chapter:
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
Closes #4683
=> fix(configuration): nightly-tests

extensions/common/iam/oauth2/oauth2-core/README.md, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceConfiguration.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java, extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java, extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImplTest.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/client/Oauth2CredentialsRequest.java
This PR makes the OAuth2 implementation ask for a token with a resource from param to follow the RFC-8707. 
This allows an IDP to set the correct `aud` claim in the access token given to the connector.
Closes #4668
=> feat: Add resource parameter to the OAuth2 token request to follow RFC-8707

core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EmbeddedRuntime.java, core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/RuntimePerClassExtension.java, extensions/control-plane/api/management-api/management-api-test-fixtures/build.gradle.kts, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/participant/DataPlaneParticipant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
Completes the work done in #4712 by making `Participant` class lazy in creating port configurations.
avoid testcontainers flaky tests
- `Endpoint` class has been deprecated, as it was just an unnecessary wrapper around RestAssured's `RequestSpecification`. with the addition of a `enrichManagementRequest` adopters can eventually enrich the management request used by tests object (e.g. by adding authentication headers, as it [is currently done in the tractusx-edc tests](https://github.com/eclipse-tractusx/tractusx-edc/blob/86461ba9cc41c9c7f1cf71c9726615e36d7097af/edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java#L263)).
- no need to keep a request object for `protocol` endpoint, as it is not supposed to be called in E2E …
=> refactor(test): make `Participant` lazy

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
This PR adds logic to allow to filter a transfer process flow from a single id (TP ID) for dataplane by adding said id in the logs.
This will improve troubleshooting scenarios of a transfer process and improve overall traceability.
Logs updated are:
- Transfer from source to destination;
- Unknown data source type;
- Unknown data sink type.
This PR does not add any breaking changes and for better examples of expected logs, please check the issue related.
Closes #https://github.com/eclipse-edc/Connector/issues/4732
=> feat: improve dataplane transfer process logs

docs/developer/decision-records/2025-01-21-multipe-protocol-webhooks/README.md, docs/developer/decision-records/README.md
add DR about supporting multiple `ProtocolWebhook`
multi protocol support improvements
Relates #4722
=> docs: decision record about multiple protocol webhooks

docs/developer/decision-records/2025-01-17-key-management-improvement/README.md, docs/developer/decision-records/README.md
adds a decision record outlining planned changes in key management (remote signing, automatic key rotation)
improved security, centralized key management
=> docs: decision record about key management

extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtension.java, extensions/common/api/control-api-configuration/src/test/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtensionTest.java, extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java, extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtensionTest.java, extensions/common/auth/auth-configuration/src/main/java/org/eclipse/edc/api/auth/configuration/ApiAuthenticationConfigurationExtension.java, extensions/common/auth/auth-configuration/src/test/java/org/eclipse/edc/api/auth/configuration/ApiAuthenticationConfigurationExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-accounts-api/src/main/java/org/eclipse/edc/api/iam/identitytrust/sts/accounts/StsAccountsApiExtension.java, extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-accounts-api/src/test/java/org/eclipse/edc/api/iam/identitytrust/sts/accounts/StsAccountsApiExtensionTest.java
removes hardcoded `AuthenticationRequestFilter` in each web context.
cleanup after #4726 
Closes #4753 _
=> refactor: removes hardcoded AuthenticationRequestFilter

core/common/lib/util-lib/src/main/java/org/eclipse/edc/util/collection/TimestampedValue.java, extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/IdentityDidCoreExtension.java, extensions/common/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/edc/iam/did/resolution/DidResolverRegistryImpl.java, extensions/common/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/edc/iam/did/resolution/DidResolverRegistryImplTest.java
Cached DidDocuments in the `DidResolverRegistry` expire after a configurable amount of time and are re-resolved after expiry.
up until now, DidDocuemnts are cached forever, until the runtime restarts. this will prevent updated did documents (e.g. after a key rotation, updated service endpoints...) from being re-downloaded.
expiring the docs will cause them to eventually get updated.
I decided against using a reaper thread, and for evicting the entries lazily, because changes are expected to be few and far between, so a reaper would spin empty most of the time.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRI …
=> fix: expire cached DidDocuments

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityTrustTransformExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/resources/document/dcp.v1.0.jsonld, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/from/JsonObjectFromPresentationQueryTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/from/JsonObjectFromPresentationResponseMessageTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationResponseMessageTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/TestContextProvider.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/from/JsonObjectFromPresentationQueryTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/from/JsonObjectFromPresentationResponseMessageTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/serde/PresentationResponseMessageSerdeTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationQueryMessageTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToPresentationResponseMessageTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/resources/document/dcp.v1.0.jsonld, spi/common/identity-trust-spi/build.gradle.kts, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/DcpConstants.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/model/PresentationQueryMessage.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/model/PresentationResponseMessage.java
add initial support for DCP namespace v1.0:
- introduces `JsonLdNamespace` for dcp 0.8 and 1.0
- Transformers can be configured to used different namespace
- Introduced cached dcp 1.0 JSON-LD context
- Changed transformers tests to target both dcp namespace
dcp v1.0 adoption
Closes #4764  …
=> feat: add initial support for DCP namespace v1.0

extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToCredentialSchemaTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/TestData.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToCredentialSchemaTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JsonObjectToVerifiableCredentialTransformerTest.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformerTest.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialSchema.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/VerifiableCredential.java
adds the `credentialSchema` property to the VerifiableCredential class and updates JWT- and Json-Transformers
Closes #4771
=> feat: add `credentialSchema` object to VCs

extensions/common/iam/identity-trust/identity-trust-transform/src/main/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformer.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/TestData.java, extensions/common/iam/identity-trust/identity-trust-transform/src/test/java/org/eclipse/edc/iam/identitytrust/transform/to/JwtToVerifiableCredentialTransformerTest.java
the JWT VC [specification](https://www.w3.org/TR/vc-data-model/#jwt-encoding) mandates that the credentials issuance date be taken from the `nbf` claim.
before, our code took it from the `iat` claim, and this PR fixes that.
mandated by the spec, although it seems wrong...
Closes #4754
=> fix: use `nbf` claim for issuance date

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClient.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/defaults/DefaultCredentialServiceClientTest.java
adds support for dcp v1.0 in default credential service client with backward compatibility option.
This is marked as breaking change just notify the change of switching by default to dcp v1.0.
The dcp client can still support for now the v0.8 version by applying the setting
```
edc.dcp.v08.enabled=true
```
dcp v1.0 adoption
Closes #4765  …
=> feat: adds support for dcp v1.0 in default credential service client

spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialStatus.java, spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialStatusSerDesTest.java
this PR improves the serialization/deserialization of the `CredentialStatus` object, specifically when not using the JSON-LD 
transformers.
It does that by adding `@JsonAnySetter` and `@JsonAnyGetter` to the additional properties
fix ser-des
=> chore: improve SerDes of CredentialStatus

spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/CredentialSubject.java, spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/VerifiableCredential.java
adds `toBuilder()` methods to several VC model classes
to enable easy copying, and setting values. this is needed when updating credentials, e.g. status list credentials in IH
=> feat: add `toBuilder()` methods

docs/developer/decision-records/2025-02-06-object_mutability_and_copying/README.md, docs/developer/decision-records/README.md
adds a decision record about `toBuilder()` and `copy()` implementations.
traceable and transparent decision
Closes #4797 
=> docs: decision record about toBuilder and copy

docs/developer/decision-records/2025-02-05-state-machine-retry-processor-refactor/README.md, docs/developer/decision-records/README.md
Provides DR for `RetryProcess` component refactor.
Part of #4792 
=> docs: provide DR for RetryProcess refactor

data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/type/v2024/from/JsonObjectFromTransferProcessV2024Transformer.java, data-protocols/dsp/dsp-transfer-process/lib/dsp-transfer-process-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/v2024/from/JsonObjectFromTransferProcessV2024TransformerTest.java
maps the new `TERMINATED_REQUESTED` to `TERMINATED` on DSP.
Integration of #4766 
follow DSP specs
Part of #4592 
=> feat: map TERMINATING_REQUESTED status to TERMINATED on DSP get transfer process call

core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/AsyncStatusResultRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/CompletableFutureRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessConfiguration.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessFactory.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/RetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/StatusResultRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/EntityStateException.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/Process.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/ProcessContext.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/ResultRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/RetryProcessor.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/UnrecoverableEntityStateException.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcessTest.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcessTest.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/ResultRetryProcessTest.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/RetryProcessorTest.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java
As a consequence of #4766 and related discussion, introduces the `RetryProcessor` concept, that will eventually replace the current `RetryProcess` (that has been deprecated for the time being).
Please refer to the DR:
https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2025-02-05-state-machine-retry-processor-refactor
- the `RetryProcessor` has been used on `TransferProcess` as demonstration, PR to replace all the usages of `RetryProcess` around the codebase will come after this.
PArt of #4592 
Closes #4792  …
=> refactor: introduce RetryProcessor

core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonArrayTranslator.java, core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/JsonArrayTranslatorTest.java
implements the `JsonArrayTranslator`, to enable querying top-level JSON arrays in SQL stores.
- this feature is an addition to the current `JsonFieldTranslator` and should only be used for top-level JSON arrays
Closes #4813 
=> feat: implement JsonArrayTranslator

core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessConfiguration.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/EntityRetryProcessFactory.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcess.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/retry/processor/Process.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureResultRetryProcessTest.java, core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/retry/processor/FutureRetryProcessTest.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/AbstractContractNegotiationManager.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ProviderContractNegotiationManagerImpl.java, core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ProviderContractNegotiationManagerImplTest.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java
Switch all the deprecated `RetryProcess` usages to `RetryProcessor`
refactor
- switched the `entityReload` return type to `StoreResult<E>` because the usage of it requires a leased entity, and the `StateEntityStore.findByIdAndLease` returns a result
Closes #4815 
=> refactor: replace all the RetryProcess usages with RetryProcessor

core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonArrayTranslator.java, core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/JsonArrayTranslatorTest.java
Passes the column name of the `JsonArray` field to the `JsonArrayTranslator` since in some case the single element in the path might be camel case. 
Allow usage of `JsonArrayTranslator` for camel case JSON Array properties
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributi …
=> chore: add column name to JsonArrayTranslator

extensions/common/auth/auth-delegated/src/main/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtension.java, extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java
This PR add the audience Validation for the API management context
Not validating audience is a security risk.
I have added some tests to validate the modification in the extension. But I could not find a way to change the value of an injected configuration field annotated by `@Settings`. So I can't unit test that when I set an audience, everything works as expected.
I have validated the code manually though. 
@paullatzelsperger 
Closes #4768 
=> fix: Add missing audience validation when accessing management api with oauth

core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/EntityStateFieldTranslator.java, core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/FieldTranslator.java, core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonArrayTranslator.java, core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/JsonFieldTranslator.java, core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslator.java, core/common/lib/sql-lib/src/test/java/org/eclipse/edc/sql/translation/EntityStateFieldTranslatorTest.java, core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/AndOperatorCriteriaToPredicate.java, core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/InMemoryStatefulEntityStore.java, core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/ReflectionBasedQueryResolver.java, core/common/lib/store-lib/src/main/java/org/eclipse/edc/store/StatefulEntityCriteriaToPredicate.java, core/common/lib/store-lib/src/test/java/org/eclipse/edc/store/ReflectionBasedQueryResolverTest.java, core/common/lib/store-lib/src/test/java/org/eclipse/edc/store/StatefulEntityCriteriaToPredicateTest.java, core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/controlplane/defaults/storage/contractnegotiation/InMemoryContractNegotiationStore.java, core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/controlplane/defaults/storage/transferprocess/InMemoryTransferProcessStore.java, core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/InMemoryDataPlaneInstanceStore.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryDataPlaneStore.java, core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/store/sql/InMemoryPolicyMonitorStore.java, extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/StatefulEntityMapping.java, extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/postgres/ContractNegotiationMapping.java, extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/transferprocess/store/schema/postgres/TransferProcessMapping.java, extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/schema/DataPlaneInstanceMapping.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/DataFlowMapping.java, extensions/policy-monitor/store/sql/policy-monitor-store-sql/src/main/java/org/eclipse/edc/connector/policy/monitor/store/sql/schema/PolicyMonitorMapping.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/entity/StateResolver.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/CriteriaToPredicate.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QueryResolver.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/DataPlaneSelectorApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Supports filtering stateful entities by the `state` string representation. 
The concept evolves around an interface that provides a way to convert a `String` state representation into `int`:
```java
public interface StateResolver {
int resolve(String stringState);
}
```
Different paths have been followed for in memory and sql stores.
The logic of the `ReflectionBasedQueryResolver` that takes care to apply a `QuerySpec` to a `Stream` was quite coupled, so a `CriteriaToPredicate` interface was introduced, it just converts a `List<Criterion>` into a `Predicate<ENTITY>`.
The default implementation has the same logic that was in the resolver:
```java
@Override
public Predicate<T> convert(List<Criterion> criteria) {
return criteria.stream()
.map(criterionOperatorRegistry::<T>toPredicate) …
```
=> feat: filter state by string

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java
Fixes the order of the parameters in three logs in the DataPlane to ensure consistent reading of DataSource, DataDestination and DataFlowId fields in a Transfer Process.
To keep logic order in log reading.
Closes #4804
=> refactor: incorrect paramaters order in dataplane logs regarding DataFlow Id

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtension.java, extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImpl.java, extensions/common/iam/verifiable-credentials/src/test/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImplTest.java
Support VPs without VCs in IdentityAndTrustService.
Closes #4807 
=> fix: support VP without VCs in IdentityAndTrustService

dist/bom/controlplane-base-bom/build.gradle.kts, dist/bom/controlplane-feature-sql-bom/build.gradle.kts, system-tests/e2e-transfer-test/control-plane/build.gradle.kts, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ManagementEndToEndExtension.java
Adds missing modules to the controlplane boms
Closes #4759 
=> build: add missing control-plane-api and policy-monitor modules to boms

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/validation/SelfIssueIdTokenValidationAction.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/validation/SelfIssueIdTokenValidationActionComponentTest.java
adds IssuerKeyIdValidationRule to SI token validation
Closes #4853 
=> fix: adds IssuerKeyIdValidationRule to SI token validation

docs/developer/decision-records/2025-02-27-move-provisioning-phase-data-plane/README.md, docs/developer/decision-records/README.md
DR about moving the provisioning/deprovisioning phases from control-plane to data-plane
Part of #4793 
=> docs: add DR for moving provisioning phase in the data-plane

extensions/common/crypto/jwt-verifiable-credentials/src/main/java/org/eclipse/edc/verifiablecredentials/jwt/rules/JtiValidationRule.java, extensions/common/crypto/jwt-verifiable-credentials/src/test/java/org/eclipse/edc/verifiablecredentials/jwt/rules/JtiValidationRuleTest.java
this PR changes the JTI validation from white-listing to black-listing
avoid coupling of the token issuer and the token verifier at the database layer
- another PR in IdentityHub will fix the token issuer side.
Closes #4836
=> feat: switch JTI validation to black-listing

data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/catalog/http/dispatcher/DspCatalogHttpDispatcherExtension.java, data-protocols/dsp/dsp-http-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtension.java, data-protocols/dsp/dsp-http-api-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtensionTest.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/DspHttpCoreExtension.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspRequestBasePathProviderImpl.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/GetDspHttpRequestFactory.java, data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/PostDspHttpRequestFactory.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/dispatcher/GetDspHttpRequestFactoryTest.java, data-protocols/dsp/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/dispatcher/PostDspHttpRequestFactoryTest.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/dispatcher/DspRequestBasePathProvider.java, data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/http/dispatcher/DspNegotiationHttpDispatcherExtension.java, data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/http/dispatcher/DspTransferProcessDispatcherExtension.java, data-protocols/dsp/dsp-version/dsp-version-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/version/http/dispatcher/DspVersionHttpDispatcherExtension.java, extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/connector/controlplane/test/system/utils/Participant.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
Introduces Multiprotocol DSP path without relying on well known (EDC) paths for DSP request
More info here #4711 
Closes #4711 
=> feat: introduce multi protocol dsp path

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/registry/TransferServiceRegistryImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/registry/TransferServiceSelectionStrategy.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/registry/TransferServiceRegistryImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/registry/TransferServiceRegistry.java
Adds a prioritization for `TransferServices` and deprecates the `TransferServiceSelectionStrategy`. Until the latter is removed, keeps it as a fallback solution in case no prioritized `TransferServices` have been registered.
To improve transfer service selection
me
Closes #4873
=> feat: prioritized transfer services

settings.gradle.kts
Fixes the path that makes the nightly to fail
https://github.com/eclipse-edc/Release/actions/runs/14119093762/job/39571341659
=> chore: fix dsp negotiation 2025 path

docs/developer/decision-records/2025-03-17-retry-processor-on-dataflow-completion/README.md
Add decision record for retry processor on dataflow completion
State changes to be made to avoid infinite retries on `DataFlow` completion
Closes https://github.com/eclipse-edc/Connector/issues/4860
=> docs: DR for retry processor on dataflow completion

core/common/runtime-core/src/main/java/org/eclipse/edc/runtime/core/validator/JsonObjectValidatorRegistryImpl.java, core/common/runtime-core/src/test/java/org/eclipse/edc/runtime/core/validator/JsonObjectValidatorRegistryImplTest.java, spi/common/validator-spi/src/main/java/org/eclipse/edc/validator/spi/JsonObjectValidatorRegistry.java
this PR changes the `JsonObjectValidatorRegistryImpl` such that it now contains multiple validators per type and it merges all the results of the individual validations.
to easily add custom validators to built-in ones
Closes #4892 
=> feat: allow multiple validators per type

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/EmbeddedTransferProcessHttpClient.java, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClient.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/port/TransferProcessApiClient.java
Applies a retry mechanism in the `DataFlowManagerImpl` when processing the `Dataflow`'s *COMPLETED* and *FAILED* states
After the data transfer, the `DataFlow` transitions to either *COMPLETED* or *FAILED* depending on whether the transfer succeeded or failed. In either case, the data plane notifies the control plane of the transfer outcome. If this notification fails, the `DataFlow` transitions to its current state, causing the state machine manager to pick it up again and retry the process. Since there is no limit to the number of retries, this process could potentially continue forever.
Check this DR for more information: https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2025-03-17-retry-processor-on-dataflow-completion
@ndr-brt
Relates to …
=> feat: add retry mechanism on dataflow completion

extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndExtension.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferStreamingEndToEndTest.java
E2E postgres tests are still flaky (ref #4761 ), destroy eventual existing dbs before creating new ones.
Tried in my fork, tests passed on 8 executions in a row
Closes #4761 
=> build(test): drop and create database on e2e

data-protocols/dsp/build.gradle.kts, data-protocols/dsp/dsp-2025/build.gradle.kts, data-protocols/dsp/dsp-2025/dsp-http-api-configuration-2025/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/v2025/DspApiConfigurationV2025Extension.java, data-protocols/dsp/dsp-http-api-base-configuration/build.gradle.kts, data-protocols/dsp/dsp-http-api-base-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiBaseConfigurationExtension.java, data-protocols/dsp/dsp-http-api-base-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, data-protocols/dsp/dsp-http-api-base-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiBaseConfigurationExtensionTest.java, data-protocols/dsp/dsp-http-api-configuration/build.gradle.kts, data-protocols/dsp/dsp-http-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtension.java, data-protocols/dsp/dsp-http-api-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtensionTest.java, data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/api/DspBaseWebhookAddress.java, settings.gradle.kts, system-tests/protocol-2025-test/src/test/java/org/eclipse/edc/test/e2e/protocol/v2025/Dsp2025Runtime.java, system-tests/protocol-test/src/test/java/org/eclipse/edc/test/e2e/protocol/DspRuntime.java
Refactors the DSP api configuration modules. Moves common code to a new  module `dsp-http-api-base-configuration`. This includes:
- creation & registration of port mapping/API context
- registration of `ObjectMapperProvider` for the API context
- creating the base webhook address
- registering subtypes on the JSON-LD object mapper
Introduces an interface for the DSP base webhook, which is provided by the new extension and injected into the existing DSP api config extensions. The existing API config extensions now only perform version-specific configurations/registrations. Includes the new module into the build files for `dsp` and `dsp-2025`.
To remove the duplicated code for creating the base webhook. Also, previously the port mapping was only registered in `DspApiConfigurationExtension`, …
=> refactor: move DSP base webhook and port mapping to separate module

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java
Adds retry mechanism to consumer provision
it was left off in the previous PR to keep it smaller
Part of #4793 
=> feat: add retry mechanism to consumer provision

settings.gradle.kts, system-tests/protocol-tck/tck-extension/build.gradle.kts, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/ContractNegotiationRequest.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckControllerExtension.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckWebhookController.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/data/DataAssembly.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationGuard.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationTriggerRegistry.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationTriggerSubscriber.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/DelayedActionGuard.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/TckGuardExtension.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/Trigger.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/identity/NoopIdentityService.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/identity/TckIdentityExtension.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/recorder/StepRecorder.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/setup/TckSetupExtension.java, system-tests/protocol-tck/tck-extension/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension, system-tests/protocol-tck/tck-extension/src/test/java/org/eclipse/edc/tck/dsp/recorder/StepRecorderTest.java
Adds an extension needed to prime and run an EDC for the DSP TCK tests.
=> feat: Implement extension for priming the EDC under test

extensions/common/http/jersey-core/README.md
Improve exception mappers for the JerseyRestService.
Closes #4958
=> docs: improve exception mappers for the JerseyRestService

core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/runtime/BaseRuntimeTest.java, extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPoolServiceExtension.java, spi/common/boot-spi/src/main/java/org/eclipse/edc/spi/system/ServiceExtension.java
Adds a `cleanup` method on `ServiceExtension` that will be called after all the `shutdown` will be completed.
Note that in the DR the idea was to call it `finalize`, forgetting that it is an already existing (and deprecated) method on the `Object` class.
bugfix
Closes #4947 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contri …
=> fix: avoid exceptions on shutdown by adding cleanup extension phase

extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/transform/JsonObjectFromContractNegotiationTransformer.java, extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/transform/JsonObjectFromContractNegotiationTransformerTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/controlplane/contract/spi/types/negotiation/ContractNegotiation.java
adds `assetId` and `correlationId` in `ContractNegotiation`.
Convenience.
Closes #4945 
=> feat: add assetId and correlationId in ContractNegotiation response

system-tests/dsp-compatibility-tests/connector-under-test/build.gradle.kts
Fixes nightly tests caused by missing `IdentityService`
Ref: https://github.com/eclipse-edc/Connector/actions/runs/14923475762/job/41923090929
=> chore: fixes nightly tests

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java
Fix the `restartFlow` mechanism in `DataPlaneManager`, unifying the behavior with the `start` method.
fix bug, avoid duplication
Closes #4975 
=> fix: data flow restart mechanism

core/common/token-core/src/test/java/org/eclipse/edc/jwt/rules/ExpirationIssuedAtValidationRuleTest.java, core/common/token-core/src/test/java/org/eclipse/edc/jwt/rules/NotBeforeValidationRuleTest.java, extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/DcpDefaultServicesExtension.java, extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java, extensions/common/iam/identity-trust/identity-trust-sts/lib/identity-trust-sts-remote-lib/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/RemoteSecureTokenService.java, extensions/common/iam/oauth2/oauth2-client/src/main/java/org/eclipse/edc/iam/oauth2/client/Oauth2ClientImpl.java, extensions/common/iam/oauth2/oauth2-client/src/test/java/org/eclipse/edc/iam/oauth2/client/Oauth2ClientImplTest.java, extensions/data-plane/data-plane-http-oauth2-core/src/test/java/org/eclipse/edc/connector/dataplane/http/oauth2/Oauth2CredentialsRequestFactoryTest.java, extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DataPlaneAuthorizationServiceImpl.java, gradle/libs.versions.toml, settings.gradle.kts, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/ClaimToken.java, spi/common/identity-trust-spi/src/main/java/org/eclipse/edc/iam/identitytrust/spi/SecureTokenService.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecorator.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/client/Oauth2CredentialsRequest.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/client/PrivateKeyOauth2CredentialsRequest.java, spi/common/oauth2-spi/src/main/java/org/eclipse/edc/iam/oauth2/spi/client/SharedSecretOauth2CredentialsRequest.java, spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecoratorTest.java
this PR changes the use of ISO-8601 strings as temporal JWT claims to be numeric date values.
RFC 7519 requires them to be `NumericDate` values, i.e. Epoch seconds
The culprit is the Nimbus library, which fails to parse JSON Web tokens where the `nbf`, `exp` and `iat` claims are not numeric.
Closes #4991 
=> fix: use numeric JWT claims instead of ISO-8601

data-protocols/dsp/dsp-lib/dsp-transfer-process-lib/dsp-transfer-process-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/type/v2024/from/JsonObjectFromTransferProcessV2024Transformer.java, data-protocols/dsp/dsp-lib/dsp-transfer-process-lib/dsp-transfer-process-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/v2024/from/JsonObjectFromTransferProcessV2024TransformerTest.java, system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/CompatibilityTests.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/data/DataAssembly.java
Currently apart from the allowed failure we have additional tests failing the fix was
- `TP_C:01-02` : serialize correctly `COMPLETED_REQUESTED`
- `TP_C:01-04`: added in allow failure because the second start message can arrive while the state is `SUSPEND_REQUESTED` instead of `SUSPENDED`
- `CN_C:01-02`: We are sending the subsequent contract request from a consumer using the wrong path. For subsequent request we should use the providePid bounded contract request path   …
=> chore: fixes tck tests CI

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationProtocolServiceImpl.java, core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/controlplane/contract/spi/types/negotiation/ContractNegotiation.java, system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/CompatibilityTests.java
Fixes the remaining two failing tests:
- `CN:03-01`
- `CN_C:01-02`
For `CN:03-01` additional checks on the protocol layer where added in order to return `conflict` when  the message cannot be processed. Previously messages were ignored when on final states which means that the response of the
connector was 200, which was not what `CN:03-01` test was expecting since the tests try to deliver a terminated message while the state is finalized.
For `CN_C:01-02` the fix was if when processing the requesting state in the consumer side there are more than 1 contract offer, then it's considered a counter offer from the consumer and it uses a process bound request endpoint.
dsp compliance
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be …
=> fix: fixes last two CN dsp-tck tests

data-protocols/dsp/dsp-spi/src/main/java/org/eclipse/edc/protocol/dsp/spi/version/DspVersions.java, system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/resources/docker.tck.properties, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckWebhookController.java
Adds support for metadata (`.well-known/dspace-version`) test in dsp tck.
In order to do that the 2025 version naming has been aligned with the upstream DSP example
`2025-1` instead of `2025/1` which impacts the path where the version is exposed
`<connector-dsp>/2025-1`  instead of `<connector-dsp>/2025/1` 
and the protocol field 
`dataspace-protocol-http:2025-1` instead of `dataspace-protocol-http:2025/1`
Closes #5034 
_Please be sure to take a look at the …
=> feat: add dsp tck metadata test integration

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java
use `"*/*"` wildcard instead of the wrong `"*"` one
fix wildcard
Closes #5037
=> fix: use proper wildcard for HTTP accept header

data-protocols/dsp/dsp-lib/dsp-transfer-process-lib/dsp-transfer-process-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/type/v2024/from/JsonObjectFromTransferProcessV2024Transformer.java, data-protocols/dsp/dsp-lib/dsp-transfer-process-lib/dsp-transfer-process-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transform/v2024/from/JsonObjectFromTransferProcessV2024TransformerTest.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java, spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessTest.java, system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/CompatibilityTests.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/data/DataAssembly.java
Fixes dsp-tck tests:
- `TP:01-01`
- `TP:01-03`
- `TP:01-05`
We will base the decision if a TP is `TERMINATED` or `COMPLETED` only by checking the `errorDetail` field as a temporary workaround. This will not require any changes for users.
We can  revisit this behavior once https://github.com/eclipse-edc/Connector/issues/4793 is in.
dsp-compliance
Closes #5032 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and …
=> feat: support DSP correct state in deprovisioning

core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPoint.java, core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/ValueInjectionPoint.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/injection/ConfigurationInjectionPointTest.java, core/common/boot/src/test/java/org/eclipse/edc/boot/system/testextensions/ExtensionWithConfigObject.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/AbstractStateEntityManager.java, core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/StateMachineConfiguration.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/ContractCoreExtension.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/TransferCoreExtension.java, core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorExtension.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/DataPlaneFrameworkExtension.java, core/policy-monitor/policy-monitor-core/src/main/java/org/eclipse/edc/connector/policy/monitor/PolicyMonitorExtension.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
Extract the `StateMachineConfiguration` record, that represent the configuration for a generic state machine.
To have this working I had to implement the `SettingContext` functionality in the configuration injection.
It's now possibile to define common configuration structure appliable to different contexts.
cleanup
Closes #5046  …
=> refactor: uniform state machine configurations

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/command/handlers/CompleteProvisionCommandHandler.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/command/handlers/CompleteProvisionCommandHandlerTest.java, core/control-plane/control-plane-transfer/src/test/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImplTest.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/provision/ResourceDefinitionGeneratorManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/provision/ResourceDefinitionGeneratorManagerImplTest.java, extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DataPlaneAuthorizationServiceImpl.java, extensions/data-plane/data-plane-iam/src/test/java/org/eclipse/edc/connector/dataplane/iam/DataPlaneAuthorizationServiceImplTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/v1/DataPlaneSignalingApiControllerTest.java, extensions/data-plane/data-plane-signaling/data-plane-signaling-client/src/test/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClientTest.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/transfer/DataFlowStartMessage.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java, spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessStates.java, spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/DataPlaneAuthorizationService.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/iam/NoOpDataPlaneAuthorizationService.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/manager/DataPlaneManager.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/port/TransferProcessApiClient.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/Deprovisioner.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/ProvisionedResource.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/Provisioner.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/provision/ProvisioningTransferConsumerEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/provision/ProvisioningTransferProviderEndToEndTest.java
Implement data-plane provisioning/deprovisioning.
Migrating provisioning from control-plane to data-plane
- create new status `STARTUP_REQUESTED`, that is symmetrical with the `PROVISION_REQUESTED`, but on the provider side: if there's any resource to be provisioned, the TP will be put in such state, waiting for the provisioning completion, at that point, the `STARTING` action will be triggered again, the eventual EDR will be created by the Data-Plane and the message will be sent to the consumer.
- `DataPlaneManager.start(DataFlowStartMessage startMessage)` is now idempotent: if the flow has already been created and provisioned, it will trigger the data flow, creating the eventual EDR to be returned to the control-plane and sent to the consumer.
_Please @-mention the committer that will …
=> feat: provider data-plane provisioning/deprovisioning

extensions/common/iam/identity-trust/identity-trust-core/src/main/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtension.java, extensions/common/iam/identity-trust/identity-trust-core/src/test/java/org/eclipse/edc/iam/identitytrust/core/IdentityAndTrustExtensionTest.java
register the JtiValidationRule in the `DCP_SELF_ISSUED_TOKEN_CONTEXT` instead of the `JWT_VC_TOKEN_CONTEXT`
by definition, VCs encoded as JWT will have a JTI that contains the credential ID, so the JTI will be "constant".
In addition, DCP only requires the JTI of a Self-issued ID token be validated.
Closes
=> fix: use correct context for JtiValidationRule

core/common/runtime-core/src/main/java/org/eclipse/edc/runtime/core/RuntimeCoreServicesExtension.java, core/common/runtime-core/src/main/java/org/eclipse/edc/runtime/core/event/EventRouterImpl.java, core/common/runtime-core/src/test/java/org/eclipse/edc/runtime/core/event/EventRouterImplTest.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/asset/AssetEventListener.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/contractdefinition/ContractDefinitionEventListener.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/policydefinition/PolicyDefinitionEventListener.java, core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/secret/SecretEventListener.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/ContractCoreExtension.java, core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/listener/ContractNegotiationEventListener.java, core/control-plane/control-plane-contract/src/test/java/org/eclipse/edc/connector/controlplane/contract/listener/ContractNegotiationEventListenerTest.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/TransferCoreExtension.java, core/control-plane/control-plane-transfer/src/main/java/org/eclipse/edc/connector/controlplane/transfer/listener/TransferProcessEventListener.java, spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventRouter.java
Adds a `<E extends Event> void publish(E event)` to the `EventRouter`, that will permit to publish events without having to care about `EventEnvelope` and its attributes (`id`, `at`).
the `<E extends Event> void publish(EventEnvelope<E> eventEnvelope)` will be kept to permit eventual customization of the envelope, but the common case is to have a central envelope definition.
refactoring, usability
Closes #5069
_Please be sure to take a look at the [contributing …
=> refactor: add publish Event method on EventRouter

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImplTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlowStates.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/provision/ProvisioningTransferProviderEndToEndTest.java
Adds a retry mechanism on the notification about completed provision phase from data-plane to control-plane, that will keep the states consistent.
It has been done by adding a new state `PROVISION_NOTIFYING` in between `PROVISIONING` and `PROVISIONED`
manage edge cases
Added also "in-memory with separated data-plane" test flavor for the provider provisioning. That was already implicitly implemented in #4896 , now explicitly covered.
Part of #4793
=> feat: add retry mechanism on provisioned notification from dp to cp

extensions/common/sql/sql-test-fixtures/src/testFixtures/java/org/eclipse/edc/sql/testfixtures/PostgresqlEndToEndExtension.java, system-tests/dsp-compatibility-tests/compatibility-test-runner/build.gradle.kts, system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/PostgresEdcCompatibilityDockerTest.java, system-tests/protocol-tck/tck-extension/build.gradle.kts, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationTriggerSubscriber.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/TckGuardExtension.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/TransferProcessTriggerSubscriber.java
Adds dsp-tck testing using postgres persistence instead of memory
Closes #5119 
=> feat: add dsp tck with pg under test

core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/manager/DataPlaneManagerImpl.java, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/EmbeddedTransferProcessHttpClient.java, extensions/control-plane/api/control-plane-api-client/src/main/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClient.java, extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/EmbeddedTransferProcessHttpClientTest.java, extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/controlplane/api/client/transferprocess/TransferProcessHttpClientTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/port/TransferProcessApiClient.java
Make `TransferProcessClient` accept `DataFlow` instead of `DataFlowStartMessage`
For some reasons we are using the signaling message representation all around, when it should be bound to the communication between control-plane and data-plane.
- the usages of the `DataFlow.toRequest()` methods are still there, because the way we are validating/starting transfers both from signaling api and from data plane manager is a little tangled. some further refactoring could come.
Part of #4793
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contribu …
=> refactor: use DataFlow instead of StartMessage where possible

core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/store/AbstractSqlStore.java, extensions/data-plane/data-plane-iam/src/main/java/org/eclipse/edc/connector/dataplane/iam/service/DataPlaneAuthorizationServiceImpl.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStore.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataFlowStatements.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/DataFlowStatements.java, extensions/data-plane/store/sql/data-plane-store-sql/src/main/resources/dataplane-schema.sql, extensions/data-plane/store/sql/data-plane-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/store/sql/PostgresDataPlaneStoreTest.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataFlow.java, spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/provision/ProvisionResource.java, spi/data-plane/data-plane-spi/src/test/java/org/eclipse/edc/connector/dataplane/spi/provision/ProvisionResourceTest.java, spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/provision/ProvisioningTransferConsumerEndToEndTest.java, system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/provision/ProvisioningTransferProviderEndToEndTest.java
Persists `ProvisionResource` in `DataFlow` into sql database
**BREAKING CHANGE**: a migration on the `dataplane-schema.sql` is required: a new `resource_definitions JSON DEFAULT '[]'` column has been added
move provisioning into data-plane
Part of #4793 
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.m …
=> feat: data-plane provision resource sql persistence

extensions/common/iam/identity-trust/identity-trust-core/src/main/resources/document/dcp.v1.0.jsonld
updates the `dcp.v1.0.jsonld` file with the latest changes from DCP
this could lead to un-expandable JSON-LD messages, e.g. when IdentityHub is embedded in the connector
- basically just copied IdentityHub's json-ld file over
- 
Closes #5134
=> fix: update DCP JSON-LD file to reflect latest DCP spec

system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/PostgresEdcCompatibilityDockerTest.java, system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/identity/TckIdentityExtension.java
After merging [this PR](https://github.com/eclipse-edc/Connector/pull/5154), the DSP TCK test is failing due to a missing service. This PR provides this service as part of the `tck-extension` and changes the TCK test from nightly to e2e test, so that issues like this one can be discovered more quickly in the future. 
Fix pipeline
me
=> fix: DSP TCK runtime

extensions/common/api/lib/management-api-lib/src/main/java/org/eclipse/edc/api/management/schema/ManagementApiJsonSchema.java, extensions/common/api/management-api-configuration/src/main/resources/management-api-version.json, extensions/common/api/management-api-schema-validator/src/main/resources/schema/management/v4/data-address-schema.json, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractdefinition/ContractDefinitionApiExtension.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractdefinition/v4/ContractDefinitionApiV4.java, extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractdefinition/v4/ContractDefinitionApiV4Controller.java, extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/contractdefinition/v4/ContractDefinitionApiV4ControllerTest.java, extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/edr/EdrCacheApiExtension.java, extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/edr/v4/EdrCacheApiV4.java, extensions/control-plane/api/management-api/edr-cache-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/edr/v4/EdrCacheApiV4Controller.java, extensions/control-plane/api/management-api/edr-cache-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/edr/v4/EdrCacheApiV4ControllerTest.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/BasePolicyDefinitionApiController.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/PolicyDefinitionApiExtension.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/model/PolicyEvaluationPlanRequest.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/v4/PolicyDefinitionApiV4.java, extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/v4/PolicyDefinitionApiV4Controller.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/BasePolicyDefinitionApiControllerTest.java, extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/v4/PolicyDefinitionApiV4ControllerTest.java, extensions/control-plane/api/management-api/secrets-api/src/main/java/org/eclipse/edc/connector/api/management/secret/SecretsApiExtension.java, extensions/control-plane/api/management-api/secrets-api/src/main/java/org/eclipse/edc/connector/api/management/secret/v4/SecretsApiV4.java, extensions/control-plane/api/management-api/secrets-api/src/main/java/org/eclipse/edc/connector/api/management/secret/v4/SecretsApiV4Controller.java, extensions/control-plane/api/management-api/secrets-api/src/test/java/org/eclipse/edc/connector/api/management/secret/v4/SecretsApiV4ControllerTest.java, extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtension.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/v4/ContractDefinitionApiV4EndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/v4/DataPlaneSelectorApiV4EndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/v4/EdrApiV4EndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/v4/PolicyDefinitionApiV4EndToEndTest.java, system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/v4/SecretsApiV4EndToEndTest.java
Add v4alpha controllers for
- PolicyDefinition
- ContractDefinition
- Secret
- DataPlaneSelector
- Edr
Relates #5137 
=> feat: more v4alpha controllers

docs/developer/decision-records/2025-08-26-participant-context/README.md, docs/developer/decision-records/README.md
DR about the introduction of participant context,  enabling the core connector components to be used
for multiple participants workload.
=> docs: DR about introducing a participant context

core/control-plane/control-plane-contract-manager/src/main/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImpl.java, core/control-plane/control-plane-contract-manager/src/test/java/org/eclipse/edc/connector/controlplane/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java, data-protocols/dsp/dsp-core/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/dispatcher/DspHttpRemoteMessageDispatcherImpl.java
transition consumer negotiation to `TERMINATED` if request fails. 
No point in sending a termination message since the provider won't be aware of the negotiation.
Closes #5243 
=> fix: terminate consumer negotiation right away if request fails
