- LICENSE
broken formatting prevents GH from detecting license properly
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
> fix license formatting

- core/protocol/web/src/main/java/org/eclipse/dataspaceconnector/web/transport/JettyService.java
- extensions/aws/s3/provision/src/main/java/org/eclipse/dataspaceconnector/provision/aws/s3/S3ProvisionPipeline.java
- launchers/demo-e2e/src/main/java/org/eclipse/dataspaceconnector/runtime/EdcRuntime.java
- launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
- scripts/atlas-deployment/main.tf
- scripts/connector-deployment/connector-ingress.tf
- scripts/connector-deployment/main.tf
> Change names

- README.md
- launchers/basic/build.gradle.kts
- launchers/basic/edc-config-docker.properties
- launchers/basic/edc-config.properties
- launchers/basic/src/main/java/org/eclipse/dataspaceconnector/runtime/ConnectorRuntime.java
- launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
- settings.gradle.kts
This pull request updates the `README.md` document
> Updates the README

- CONTRIBUTING.md
This PR adds a brief CONTRIBUTING.md file stating how potential contributors can help evolving this project.
The CONTRIBUTING.md file currently lacks information regarding code formatting/style. The IDSA Dataspace Connector project uses a slightly amended [sun_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml) and [PMD](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/main/scripts/ci/pmd-rules.xml) configuration which IMO could also be applied to this project as well. This is going to be added by a subsequent issue / pull request. 
> Add CONTRIBUTING.md, closes #17

- README.md
> update gaia-x homepage

- launchers/demo-e2e/Dockerfile
It's a simple fix so I didn't open an issue, hope that's ok
> launchers: Fix demo-e2e jar path

- build.gradle.kts
- gradle.properties
Signed-off-by: Dominik Pinsel <email@dominik-pinsel.com>
> gradle: set java version to 11, closes #22

- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/metadata/GenericDataCatalogEntry.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/metadata/GenericDataCatalogEntryTest.java
This annotation is needed for proper deserialization.
> spi: add missing jackson annotation (#93)

- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/StatusCheckerRegistryImpl.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
- core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplConsumerTest.java
- extensions/aws/s3/provision/src/main/java/org/eclipse/dataspaceconnector/provision/aws/AwsProvisionExtension.java
- extensions/aws/s3/provision/src/main/java/org/eclipse/dataspaceconnector/provision/aws/s3/S3StatusChecker.java
- extensions/aws/s3/provision/src/test/java/org/eclipse/dataspaceconnector/provision/aws/s3/S3StatusCheckerTest.java
- extensions/azure/blob/provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/AzureProvisionExtension.java
- extensions/azure/blob/provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerStatusChecker.java
- extensions/azure/blob/provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerStatusCheckerTest.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/StatusChecker.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/StatusCheckerRegistry.java
> Decouple status checking from provisioned resources

- samples/other/file-transfer-s3-to-s3/README.md
- samples/other/file-transfer-s3-to-s3/build.gradle.kts
- samples/other/file-transfer-s3-to-s3/postman/IDS Eclipse S3 to S3.postman_collection.json
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/DemoLauncher.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/api/ClientApiController.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/api/ClientApiControllerExtension.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/controller/DemoExtension.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/controller/S3toS3TransferFlowController.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/vault/SingletonVault.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/vault/SingletonVaultExtension.java
- samples/other/file-transfer-s3-to-s3/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
- samples/other/file-transfer-s3-to-s3/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.VaultExtension
- settings.gradle.kts
This PR should be merged after https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/94 since it depends on the serialization fix.
> samples: add s3-to-s3 transfer demo sample (#96)

- core/bootstrap/src/main/java/org/eclipse/dataspaceconnector/system/CoreServicesExtension.java
- core/bootstrap/src/main/java/org/eclipse/dataspaceconnector/system/DefaultServiceExtensionContext.java
- core/bootstrap/src/test/java/org/eclipse/dataspaceconnector/system/CoreServicesExtensionTest.java
- extensions/aws/s3/provision/src/main/java/org/eclipse/dataspaceconnector/provision/aws/AwsProvisionExtension.java
- extensions/azure/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreExtension.java
- extensions/filesystem/configuration-fs/src/main/java/org/eclipse/dataspaceconnector/configuration/fs/FsConfigurationExtension.java
- extensions/filesystem/vault-fs/src/main/java/org/eclipse/dataspaceconnector/security/fs/FsConfiguration.java
- extensions/iam/distributed-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreHubExtension.java
- extensions/iam/iam-mock/src/main/java/org/eclipse/dataspaceconnector/iam/mock/IamMockExtension.java
- extensions/iam/oauth2/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/Oauth2Extension.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/api/ClientApiControllerExtension.java
- samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/vault/SingletonVaultExtension.java
- samples/other/streaming/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/protocols/DemoProtocolsTransferExtension.java
Apply standard naming for all EDC settings: edc.*
> Standardize EDC setting keys (#84)

- extensions/in-memory/assetindex-memory/src/main/java/org/eclipse/dataspaceconnector/metadata/memory/CriterionToPredicateConverter.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/Criterion.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/asset/Asset.java
Allow the customization of Asset for display in the federated catalogue.
> spi: Allow Asset to contain custom properties

- extensions/iam/distributed-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/resolution/DidResolverRegistryImpl.java
- extensions/iam/distributed-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/resolution/DefaultDidPublicKeyResolverTest.java
- extensions/iam/distributed-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/resolution/DidResolverRegistryImplTest.java
- extensions/iam/distributed-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DistributedIdentityServiceExtension.java
- extensions/iam/distributed-identity/identity-did-service/src/test/java/org/eclipse/dataspaceconnector/identity/DistributedIdentityServiceTest.java
- extensions/iam/distributed-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/resolution/DidResolutionResult.java
- extensions/iam/distributed-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/resolution/DidResolver.java
- extensions/iam/distributed-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/resolution/DidResolverRegistry.java
- extensions/iam/distributed-identity/identity-did-web/README.md
- extensions/iam/distributed-identity/identity-did-web/build.gradle.kts
- extensions/iam/distributed-identity/identity-did-web/src/main/java/org/eclipse/dataspaceconnector/iam/did/web/ConfigurationKeys.java
- extensions/iam/distributed-identity/identity-did-web/src/main/java/org/eclipse/dataspaceconnector/iam/did/web/WebDidExtension.java
- extensions/iam/distributed-identity/identity-did-web/src/main/java/org/eclipse/dataspaceconnector/iam/did/web/resolution/DidFunctions.java
- extensions/iam/distributed-identity/identity-did-web/src/main/java/org/eclipse/dataspaceconnector/iam/did/web/resolution/WebDidResolver.java
- extensions/iam/distributed-identity/identity-did-web/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
- extensions/iam/distributed-identity/identity-did-web/src/test/java/org/eclipse/dataspaceconnector/iam/did/web/resolution/DidFunctionsTest.java
- extensions/iam/distributed-identity/identity-did-web/src/test/java/org/eclipse/dataspaceconnector/iam/did/web/resolution/WebDidResolverTest.java
- extensions/iam/distributed-identity/identity-did-web/src/test/resources/did.json
- extensions/iam/distributed-identity/registration-service/src/main/java/org/eclipse/dataspaceconnector/iam/registrationservice/crawler/CrawlerJob.java
- extensions/ion/ion-client/src/main/java/org/eclipse/dataspaceconnector/ion/DefaultIonClient.java
- extensions/ion/ion-client/src/test/java/org/eclipse/dataspaceconnector/ion/IonClientImplTest.java
This PR implements Part 3 of #152
> Feature/152-Web-DIDs, Part 3: Implement Web DID Resolver

- .github/workflows/verify.yaml
- launchers/basic/build.gradle.kts
fixed the build file of `launchers/basic` and added a sanity check for it.
> fixed broken launcher config and added a sanity check

- core/schema/src/main/java/org/eclipse/dataspaceconnector/schema/DataSchema.java
- core/schema/src/main/java/org/eclipse/dataspaceconnector/schema/RelationshipSchema.java
- core/schema/src/main/java/org/eclipse/dataspaceconnector/schema/SchemaExtension.java
- core/schema/src/main/java/org/eclipse/dataspaceconnector/schema/SchemaRegistryImpl.java
- core/schema/src/main/java/org/eclipse/dataspaceconnector/schema/policy/PolicySchema.java
- core/schema/src/test/java/org/eclipse/dataspaceconnector/schema/SchemaRegistryTest.java
- core/schema/src/test/java/org/eclipse/dataspaceconnector/schema/SchemaTest.java
- extensions/aws/s3/s3-schema/src/main/java/org/eclipse/dataspaceconnector/schema/s3/BucketSchemaExtension.java
- extensions/aws/s3/s3-schema/src/main/java/org/eclipse/dataspaceconnector/schema/s3/S3BucketSchema.java
- extensions/azure/blob/blob-schema/src/main/java/org/eclipse/dataspaceconnector/schema/azure/AzureBlobStoreSchema.java
- extensions/azure/blob/blob-schema/src/main/java/org/eclipse/dataspaceconnector/schema/azure/BlobStorageSchemaExtension.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/schema/SchemaRegistry.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/schema/Schema.java
- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/schema/SchemaAttribute.java
Hello everyone,
I just saw that the Schema is not part of the SPI and moved it.
> Move Schema to SPI

- spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/ContractAgreement.java
> Add Contract domain object, closes #229

- data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsContractOfferToContractOfferTransformer.java
fixed the failing `IdsContractOfferToContractOfferTransformerTest`
> fixed failing test

- extensions/dataloading/dataloading-asset/build.gradle.kts
- extensions/dataloading/dataloading-spi/build.gradle.kts
fixed two little copy paste errors
> fixed artifact names for dataloading modules

- .github/workflows/integrationtests.yaml
> ci: execute ITs also on every push on main branch

- core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
- core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
- data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
Signed-off-by: Denis Neuling <denis.neuling@daimler.com>
Co-authored-by: Denis Neuing <denis.neuling@daimler.com>
> contract-validation: add validation of agreement start/end time (closes #295)

- samples/05-file-transfer-cloud/README.md
- samples/05-file-transfer-cloud/consumer/config.properties
- samples/05-file-transfer-cloud/data-seeder/src/main/java/org/eclipse/dataspaceconnector/sample5/data/seeder/FakeSetup.java
> Update Sample5 (closes #306)

- samples/01-basic-connector/README.md
- samples/02-health-endpoint/README.md
- samples/03-configuration/README.md
- samples/03-configuration/build.gradle.kts
- samples/04-file-transfer/README.md
- samples/04-file-transfer/consumer/build.gradle.kts
- samples/04-file-transfer/consumer/config.properties
- samples/04-file-transfer/provider/build.gradle.kts
- samples/04-file-transfer/provider/config.properties
- samples/04-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
* Update `README`s 
* Fix #203 by moving hardcoded file path of sample 04 to configuration
* Verified the first 4 samples (don't have enough tools to run sample 05)
would be good to have this merged before the Introduction session at the Gaia-X hackaton of tomorrow
> samples: update execution procedures

- extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ClientController.java
- extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ControlApiServiceExtension.java
- extensions/api/control/src/test/java/org/eclipse/dataspaceconnector/api/control/ClientControlCatalogApiControllerTestServiceExtension.java
- extensions/azure/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
> control-api: add endpoint to initiate a contract negotiation

- core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
- core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
- core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
- data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractAgreementSender.java
- data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
- data-protocols/ids/ids-api-multipart-endpoint-v1/build.gradle.kts
- data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
- data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
> Remove workaround from `ArtifactRequestHandler`

- data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRejectionHandler.java
- data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsResourceCatalogToDataCatalogTransformer.java
- extensions/api/control/src/test/java/org/eclipse/dataspaceconnector/api/control/ClientControlCatalogApiControllerTest.java
> ids-transform: fix id formatting

- extensions/catalog/catalog-service/build.gradle.kts
- extensions/catalog/federated-catalog-cache/build.gradle.kts
- extensions/catalog/federated-catalog-node/build.gradle.kts
- extensions/catalog/federated-catalog-spi/build.gradle.kts
- extensions/in-memory/fcc-node-directory-memory/build.gradle.kts
- extensions/in-memory/fcc-store-memory/build.gradle.kts
- launchers/registration-service-app/build.gradle.kts
- spi/build.gradle.kts
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataAddressTest.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataRequestTest.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedResourceTest.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ResourceDefinitionTest.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ResourceManifestTest.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TestProvisionedResource.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TestResourceDefinition.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessTest.java
- spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferTypeTest.java
Maybe not my job, but I thought this may be important before a first release. Refers to this discussion #343
> license: update incorrect licensing information

- data-protocols/ids/ids-api-catalog/src/main/java/org/eclipse/dataspaceconnector/ids/api/catalog/IdsCatalogApiServiceExtension.java
Variable renamed from dapService to dapsService
> chore: Typo in variable fixed

- .github/workflows/publish.yaml
- build.gradle.kts
> Artifacts publishing

- core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
- core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
> Use CountDownLatch instead of Thread.sleep in test

- data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/policy/IdsPolicyService.java
- docs/diagrams/distributed-identity/data.request.puml
- docs/diagrams/distributed-identity/service.discovery.puml
- extensions/in-memory/contractdefinition-store-memory/build.gradle.kts
- extensions/in-memory/negotiation-store-memory/build.gradle.kts
- samples/other/commandline/consumer/src/main/java/org/eclipse/dataspaceconnector/consumer/command/ids/IdsConstants.java
I think Ronja and I already fixed some wrong naming in our latest pull requests, so this is a really small one :D even better
> refactor: replace client with consumer

- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
- core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplConsumerTest.java
Consistent update of TransferProcesses in `TransferProcessManagerImpl`:
* Only update processes whenever changes are done
* Call `TransferProcessListeners` always after process has been updated
Closes #324
> Transfer Process Manager: consistent update of transfer processes

- core/bootstrap/src/main/java/org/eclipse/dataspaceconnector/system/DefaultServiceExtensionContext.java
Hi everyone,
this PR introduces the writing of a corresponding warning message to the console (monitor) for the edge case of multiple extensions contributing the same type of service.
> Add warning in case of multiple services of same type (closes issue #395)

- extensions/aws/aws-test/README.md
- extensions/aws/aws-test/build.gradle.kts
- extensions/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/AbstractS3Test.java
- extensions/aws/s3/provision/src/test/java/org/eclipse/dataspaceconnector/provision/aws/s3/S3StatusCheckerIntegrationTest.java
As discussed in #292 .
Also added the possibility to load the aws profile for running tests using the environment variable `AWS_PROFILE`
> extensions: replace old aws sdk with the new one

- extensions/iam/oauth2/oauth2-core/README.md
> docs(readme): oauth2-core readme

- .github/workflows/integrationtests.yaml
- extensions/aws/aws-test/README.md
- extensions/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/AbstractS3Test.java
> extensions: run s3 integration tests against a local docker container

- launchers/data-loader-cli/README.md
- launchers/data-loader-cli/src/main/resources/assets.json
- launchers/data-loader-cli/src/main/resources/config.properties
- launchers/data-loader-cli/src/main/resources/contractdefs.json
> Update data loader documentation

- core/base/src/main/java/org/eclipse/dataspaceconnector/core/system/CoreServicesExtension.java
To fix exception thrown at this line
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/e82b5a0fd76f78f2b416b7e5ed6a96a138f55dea/extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java#L88
> core: generalize parser

- extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java
- extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/impl/Oauth2Configuration.java
> extensions: improve error message simplifying configuration object

- docs/Policies.md
Added Policy documentation as part of December's refactoring week.
> Add policy documentation

- core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
- core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
> core: evaluate futures correctly

- extensions/api/observability/src/main/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApiExtension.java
- extensions/azure/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetQueryBuilder.java
- extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/TestHelper.java
- samples/04.0-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
- samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
- samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/asset/Asset.java
> spi: remove policyId from Asset

- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/ProxyEntryHandlerRegistryImpl.java
- docs/architecture-principles.md
- extensions/azure/blobstorage/blob-api/src/main/java/org/eclipse/dataspaceconnector/common/azure/BlobStoreApiImpl.java
- extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
- extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/LoaderImpl.java
- extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/query/CacheQueryAdapterImpl.java
- extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
- extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/resolution/DidPublicKeyResolverImpl.java
- extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtensionTest.java
- extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/resolution/DidPublicKeyResolverImplTest.java
- extensions/ion/ion-client/src/main/java/org/eclipse/dataspaceconnector/ion/IonClientExtension.java
- extensions/ion/ion-client/src/main/java/org/eclipse/dataspaceconnector/ion/IonClientImpl.java
- extensions/ion/ion-client/src/test/java/org/eclipse/dataspaceconnector/ion/IonClientImplTest.java
> rename single implementers to "*Impl" convention

- onboarding.md
- samples/04.2-modify-transferprocess/README.md
Fix a sample path and added 4.1 and 4.2 to the list.
> samples: update onboarding guide

- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CommandExtension.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/BoundedCommandQueue.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/CommandHandlerRegistryImpl.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/commands/CancelTransferCommand.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/commands/DeprovisionRequest.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/commands/TransferProcessCommand.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandler.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/DeprovisionRequestHandler.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/TransferProcessCommandHandler.java
- core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/BoundedCommandQueueTest.java
- core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandlerTest.java
- core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/DeprovisionCommandHandlerTest.java
- samples/05-file-transfer-cloud/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
renamed all packages to `...command` instead of `commandqueue`.
Fixes #551
> renamed all packages to 'command'

- docs/command-queue.md
> Added documentation for the CommandQueue

- extensions/azure/blobstorage/blob-core/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
- extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyExtension.java
This will fix bug reported here: #581
> extensions: fix typo

- core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/FieldInjectionPoint.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/InjectionPointScanner.java
`@Inject(required=false)` injection points were reported as errors, which is wrong. This PR fixes that.
> Optional injection points are not reported as errors anymore

- data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/AssetToIdsResourceTransformer.java
- data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsResourceToAssetTransformer.java
- data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/AssetToIdsResourceTransformerTest.java
- data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsResourceToAssetTransformerTest.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/asset/Asset.java
> Asset descriptions in IDS, closes #578

- extensions/transaction/transaction-local/src/main/java/org/eclipse/dataspaceconnector/transaction/local/LocalTransactionExtension.java
> Add @provides to LocalTransactionExtension, closes #610

- core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/observe/ContractNegotiationObservableImpl.java
- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/observe/TransferProcessObservableImpl.java
- extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyRestService.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/command/Command.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/observe/ObservableImpl.java
- spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/observe/ObservableImplTest.java
- spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/WebService.java
Closes #658 
Closes #659 
Closes #662
> Code Cleanup

- core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandler.java
- core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandlerTest.java
- spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcess.java
- spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessStates.java
- spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessTest.java
Adds a new state CANCELLED to the transferprocess.
Closes #515
> Adds a CANCELLED state to the TransferProcess

- extensions/transaction/transaction-atomikos/src/main/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionContext.java
- extensions/transaction/transaction-atomikos/src/test/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionContextTest.java
- extensions/transaction/transaction-atomikos/src/test/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionExtensionTest.java
> Propagate exception with Atomikos (#696)

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
adds an initial PR template 
Closes #698
> Pull Request Template

- extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/TransferProcessApiController.java
- resources/openapi/openapi.yaml
- resources/openapi/yaml/control.yaml
- resources/openapi/yaml/transferprocess.yaml
Found some smaller issues. Should be self explaining
> DataManagementApi: Fix method naming and return type

- CHANGELOG.md
- CONTRIBUTING.md
This PR adds the initial `CHANGELOG.md` to the root directory.
We need to document implementations to make changes (e.g., features and bug fixes) visible to other developers and users.
Closes #770 
Not relevant.
> docs: create initial changelog

- .github/workflows/integrationtests.yaml
Use `windows-latest` image
Potentially resolves the issue. I started a few runs and they all succeeded.
Closes #845
> Cosmos DB emulator: use latest Windows image

- .github/workflows/issue-auto-assign-project.yaml
- .github/workflows/pull-request-auto-assign-project.yaml
Replace action to assign projects.
> fix(ci): replace action for project assignment

- extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
- extensions/sql/contract-definition/store/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
Renames and fixes the signature of `SqlContractDefinitionStore#delete`. 
Caused compile errors on `main`, apparently due to a unfavorable merge/rebase constellation.
- Added tests for the `deleteById` method.
- Added `static` imports for all the constants.
Closes #924
> Bugfix: compile error on `main` due to a signature change

- docs/developer/decision-records/2022-03-15-policy-scopes/README.md
Adds a decision record for policy scopes.
> doc(decision): Decision Record for Policy Scopes

- core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
- core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImpl.java
- core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/RuleBindingRegistryImpl.java
- core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/ScopeFilter.java
- core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplScenariosTest.java
- core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImplTest.java
- core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/RuleBindingRegistryImplTest.java
- core/base/src/test/java/org/eclipse/dataspaceconnector/core/base/policy/ScopeFilterTest.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/AndConstraint.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/MultiplicityConstraint.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/OrConstraint.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Permission.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Prohibition.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/XoneConstraint.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyEngine.java
- spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/RuleBindingRegistry.java
Add rule type bindings as described in #856
Explained in the issue.
#856
> feature: Implement rule type bindings and scope filtering

- core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
- core/base/src/test/java/org/eclipse/dataspaceconnector/core/CoreServicesExtensionTest.java
- core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/PolicyRegistrationTypes.java
Renames a class and method
Closes #946
> chore: Rename RegistrationTypes and remove method

- extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
> Federated Catalog Cache: fixed logging statement

- data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionHandler.java
- data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsResourceCatalogToDataCatalogTransformer.java
- extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/HttpApiKeyAuthContainerRequestFilter.java
- resources/edc-checkstyle-config.xml
- Add a rule to fail build on InnerAssignment checkstyle check violation.
- Fix existing violations. 
Increases readability.
Relates to #991
> CI: Add InnerAssignment checkstyle module

- extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApi.java
- extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApi.java
- extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApi.java
- extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApi.java
- extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyApi.java
- extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
- extensions/api/observability/src/main/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApi.java
- extensions/api/observability/src/main/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApiController.java
- extensions/data-plane-selector/selector-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/api/DataplaneSelectorApi.java
- extensions/data-plane-selector/selector-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/api/DataplaneSelectorApiController.java
- extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/webhook/HttpProvisionerWebhookApiController.java
- extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubApi.java
- openapi.md
- resources/openapi/openapi.yaml
- resources/openapi/yaml/asset.yaml
- resources/openapi/yaml/contractagreement.yaml
- resources/openapi/yaml/contractdefinition.yaml
- resources/openapi/yaml/contractnegotiation.yaml
- resources/openapi/yaml/http-provisioner.yaml
- resources/openapi/yaml/identity-did-core.yaml
- resources/openapi/yaml/observability.yaml
- resources/openapi/yaml/policydefinition.yaml
- resources/openapi/yaml/selector-api.yaml
- resources/openapi/yaml/transferprocess.yaml
This PR adds the `@Tag` annotation to the REST API Controllers to enable better rendering in HTML
To improve readability.
> Chore: Adds Swagger `@Tag` annotations to API controllers

- .github/workflows/verify.yaml
- CODEOWNERS
Keep the file up-to-date (as it was not done in previous PRs)
Remove inconsistencies
--
> docs: update CODEOWNERS

- launchers/ids-connector/README.md
It adds a section to the `ids-connector` launcher's README on using a custom truststore when running the launcher in Docker.
The way to add a custom truststore currently described in the README does not work.
> docs: update ids-launcher README.md

- extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java
A little oversight that made the CI fail
-
-
-
> test: fix cosmosdb integration test

- CHANGELOG.md
> release: Carve milestone 4 CHANGELOG

- docs/developer/decision-records/2022-06-03-event-framework/README.md
- docs/developer/decision-records/README.md
Adds a decision records about Event Framework
To define some basic concepts for this feature
-
Closes #1412
> docs: add event framework decision record

- build.gradle.kts
removes a log line that was forgotten
> Fix: Removes a log line that was forgotten previously

- docs/developer/decision-records/2022-06-09-shared-clock/README.md
- docs/developer/decision-records/README.md
Decision Record for shared Clock.
Corresponding implementation already merged in #1416.
Closes #1364
> Core: shared Clock DR

- .github/workflows/codeql-analysis.yml
- .github/workflows/performancetests.yaml
- .github/workflows/scan-pull-request.yaml
- .github/workflows/verify.yaml
Merges PRs #1523, #1524, #1525, #1526, #1527 
ECA not signed
--
Closes #1523 
Closes #1524 
Closes #1525 
Closes #1526 
Closes #1527
> build(deps): update github_actions dependencies

- contribution_categories.md
this document should help contributors to decide how and where their code should be hosted
There is a need from the community to have guidance on that topic.
> doc: add feature categorizations

- .github/ISSUE_TEMPLATE/adoption_request.md
- contribution_categories.md
Adds an issue template for adoption requests.
organizational reasons, the label "adoption" will help filtering
--
Relates to #1577
> chore: add issue template for adoption requests

- docs/developer/README.md
- docs/developer/decision-records/2022-07-04-type-manager/README.md
Adds a decision record for issue #1581.
Document thoughts and concepts.
PR containing the implementation will follow.
Related #1581
> docs: add decision record for serialization contexts

- .github/workflows/first-interaction.yml
Fixes yaml syntax (thx IntelliJ -.-)
Action failed to run
--
> fix(first-interaction): correct yaml syntax

- docs/swaggerui/swagger-spec.js
- extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/query/QuerySpecDto.java
- extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java
- extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java
- extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddressDto.java
- extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DtoValidationTest.java
- extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/model/ContractAgreementDto.java
- extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionDto.java
- extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/ContractAgreementDto.java
- extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/ContractOfferDescription.java
- extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/NegotiationInitiateRequestDto.java
- extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDto.java
- extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/DataPlaneTokenValidationApi.java
- extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/webhook/HttpProvisionerWebhookApi.java
- extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/webhook/HttpProvisionerWebhookApiController.java
- extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/webhook/ProvisionerWebhookRequest.java
- resources/openapi/openapi.yaml
- resources/openapi/yaml/asset.yaml
Add custom message on every `jakarta-validation` annotations
To improve error details readability
-
Closes #1491
> feat: define custom message on jakarta validation

- extensions/http-provisioner/build.gradle.kts
- extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
Fix `HttpProvisionerExtensionEndToEndTest`
it was flaky
- introduced awaitility to tight it
Closes #1798
> fix: broken test

- extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java
Update DataPlaneTransferSyncExtension, so that `DataEncrypter` can be provided by an extension.
- NoopDataEncrypter is unsecure
-
Closes #1804
> feat: DataEncrypter provided by extension

- core/control-plane/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
- core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
Use `SendRetryManager` to handle failed transfer initialization.
To avoid endless loop
- the use of `SendRetryManager` is not easy to figure out, it could be better refactored, I'll create an issue
Closes #1954
> fix: avoid loop on initiate transfer failure

- NOTICE.md
This PR updates the list of third party licenses.
As new dependencies are introduces, this list needs to be updated.
> docs: update list of third party licenses

- docs/developer/events.md
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetCreated.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetDeleted.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetEventPayload.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCancelled.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCompleted.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioned.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEnded.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEventPayload.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessFailed.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessInitiated.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioned.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioningRequested.java
- spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessRequested.java
Adding missing javadoc and updating documentation about how to filter Events.
Improved Documentation is always needed
Closes #1970
> docs(Event Framework): updating and extending doc

- CODEOWNERS
Reduce mentions in `CODEOWNERS` to committers.
Clean up
--
> docs: clean up CODEOWNERS

- docs/developer/build-your-own-connector.md
Add a documentation markdown that explains how to build a connector using BOM dependencies and explaining how to customize it
Improve documentation
- I thought that the best way to have this BOM thing documented was to show how to use them
Closes #1438
> docs: document BOM usages

- core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
- core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
- core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
- core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
- core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
- data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
- data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
- data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
- spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/validation/ContractValidationService.java
Apply the suggestion described in #2077 
Make more clear the responsibility of each method
Closes #2077
> refactor(ContractValidationService): rename interface methods + docs

- core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
- core/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/pipeline/PipelineServiceImpl.java
- core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/e2e/EndToEndTest.java
- core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/pipeline/PipelineServiceImplTest.java
- extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/DataPlaneTransferClientExtension.java
This PR improves logging about conditionally loaded modules and negotiated configurations.
Since it helps debugging and testing.
Closes #2122
> fix: add more logging to data-plane extensions (fixes #2122)

- extensions/common/http/jersey-core/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/mapper/ExceptionMappersIntegrationTest.java
Fix flaky test ExceptionMappersIntegrationTest
Tests were failing on a locale which was not `en`
Closes #2141
> fix(jerseyExtension):  flaky test ExceptionMappersIntegrationTest

- docs/developer/decision-records/2022-10-20-trust-framework-adoption-repository/README.md
- docs/developer/decision-records/README.md
Add ADR for creation of Gaia-X Bundle repository.
Related to EDC adoption in Gaia-X.
> docs: Add ADR for creation of Trust Framework Adoption repository

- README.md
Add this badges to the README
- build status
- coverage
- discord chat
- Maven central release
- License
Quick access to some relevant info about the project
Closes #2166
> feat(Readme): add badges to the README

- README.md
Update maven badge to the new group id
documentation
-
Ref #2103 
Ref #2166
> docs: Update maven badge to the new group id

- extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
Fixes a checkstyle violation introduced by PR #2150 
checkstyle
> fix: checkstyle

- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
- core/control-plane/contract-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/ContractCoreExtensionTest.java
- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
- core/control-plane/transfer-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- docs/developer/README.md
- docs/developer/performance-tuning.md
- resources/openapi/openapi.yaml
Changes default values for the state machine settings, document how can they be used to improve performances.
Documentation, improve "out of the box" performances
- renamed the transfer and the contract extension classes to follow the naming standard
- improved logging on the `TransferProcessManagerImpl`
- the default values modification improved tests run time significantly
Closes #2219
- [ x documented public classes/methods?
> feat: improve "out of the box" performances

- resources/ci/discord_webhook.sh
adds a CONTENT parameter to the discord web hook
allow for a bit more customization
> build: update discord webhook

- README.md
Adds snapshot and nightly build badges to README 
transparency
Closes #2233
> feat(README): adds snapshot and nightly build badges

- docs/developer/decision-records/2022-11-28-release-management/README.md
- docs/developer/decision-records/README.md
- resources/ci/discord_webhook.sh
Adds a decision record about necessary changes to our CI/CD pipeline. 
documentation
> docs(build): decision record about CD refactoring (Jenkins)

- README.md
Fix jenkins badges
They showed an error
-
> fix: jenkins badges

- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java
- core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImplTest.java
make the transfer process in EndpointDataReferenceReceiverRegistry fail if no receivers are registered.
To ensure that if no receivers are registered the transfer process fails.
Closes #2228
> chore(EndpointDataReferenceReceiverRegistry): make the transfer process fail if no receivers are registered

- spi/common/transaction-spi/src/test/java/org/eclipse/edc/transaction/spi/NoopTransactionContextTest.java
Fix checkstyle error on header
CI failing
> chore(build): fix checkstyle

- README.md
Fix build badge
It was showing an error and it didn't point to the `main` branch as expected
> build(badges): fix build badge

- docs/developer/decision-records/2023-01-26-release-process/README.md
- docs/developer/decision-records/README.md
Adds a DR that describes the new EDC release process
documentation
> docs: add DR about new release process

- NOTICE.md
- extensions/common/iam/iam-mock/build.gradle.kts
Remove `java-jwt`, as it is not used by any module.
cleanup
> chore: remove unused dependency

- extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/policydefinition/store/SqlPolicyDefinitionStore.java
Add missing wrapping transaction blocks in `SqlPolicyDefinitionStore` that are very likely causing connection leaking.
Fix bug
- did some cleanup
Closes #2286
> fix: adding missing wrapping transaction blocks in `SqlPolicyDefinitionStore`

- .github/workflows/verify.yaml
> fix: disable flaky ADF test

- extensions/common/metrics/micrometer-core/README.md
Corrected the broken link that starts with `IdeaProjects`
(the maintainer seems to use the IntelliJ Idea, and it might work only in his PC.)
To link to the appropriate document
> docs(micrometer-core): correct link url

- docs/developer/decision-records/2023-02-27-dataspace-protocol-transferprocess-state-transitions/README.md
- docs/developer/decision-records/README.md
Add decision record
Part of #2512
> docs: add decision record about transfer process state transitions change

- docs/developer/decision-records/2023-03-09-event-framework-refactoring/README.md
- docs/developer/decision-records/README.md
Adds a DR for refactoring the event framework
> docs: add decision record about event framework refactoring

- build.gradle.kts
- gradle.properties
As documented in
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:group
> fix: use gradle 'group' property instead of 'groupId'

- core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/AsyncStreamingDataSink.java
- core/data-plane/data-plane-util/src/test/java/org/eclipse/edc/connector/dataplane/util/sink/AsyncStreamingDataSinkTest.java
As described in #2712 
Closes #2712
> feat: adds a Streaming Async Data Sink

- spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/JsonLd.java
Add the interface for the `JsonLd` service.
dataspace protocol
> feat: add JsonLd service interface

- core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplIntegrationTest.java
- core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplPerformanceTest.java
- core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplIntegrationTest.java
- core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetServiceImpl.java
- core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java
- core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
- core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
- core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndexTest.java
- core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryDataAddressResolverTest.java
- data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
- data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/MultipartControllerIntegrationTest.java
- extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
- extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndex.java
- extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java
- extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java
- spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java
- spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
- system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java
- system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/edc/test/extension/api/FileTransferExtension.java
> refactor(AssetIndex): harmonize CRUD operations

- core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
- core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndexTest.java
- extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/DataAddressDtoToDataAddressTransformer.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetCreationRequestDto.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetRequestDto.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetResponseDto.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/model/AssetUpdateRequestDto.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/AssetRequestDtoToAssetTransformer.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/AssetToAssetResponseDtoTransformer.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/AssetUpdateRequestWrapperDtoToAssetTransformer.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/model/AssetCreationRequestDtoTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/model/AssetCreationRequestDtoValidationTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/model/AssetEntryDtoTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/model/AssetResponseDtoTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/model/AssetUpdateRequestDtoTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/model/AssetUpdateRequestDtoValidationTest.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/transform/AssetRequestDtoToAssetTransformerTestCreation.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/transform/AssetToAssetResponseDtoTransformerTest.java
- resources/openapi/yaml/management-api/asset-api.yaml
- spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetPredicateConverter.java
- spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/asset/Asset.java
- spi/common/core-spi/src/test/java/org/eclipse/edc/spi/asset/AssetPredicateConverterTest.java
- spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
This PR extends the in-memory storage to accost private properties.
The changes private properties bring, have to be reflected in all storage variations.
> feat(Asset): Private properties for asset in-memory storage

- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractCoreExtension.java
- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractExpiryCheckFunction.java
- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
- core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
Removes an unused reference to `Clock.`
> chore: Remove unused Clock reference

- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
- core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
- core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
- data-protocols/dsp/build.gradle.kts
- data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java
- data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractAgreementMessageTransformer.java
- data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractRequestMessageTransformer.java
- data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementMessageTransformerTest.java
- data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractRequestMessageTransformerTest.java
- extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToActionTransformer.java
- extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToActionTransformerTest.java
- extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessNewApiController.java
- extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/DataPlaneInstanceDocumentSerializationTest.java
- resources/openapi/openapi.yaml
- spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/EdcHttpClient.java
- spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
- spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java
- spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/ContractId.java
- spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java
- system-tests/e2e-transfer-test/control-plane/build.gradle.kts
- system-tests/e2e-transfer-test/runner/build.gradle.kts
- system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
- system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/KafkaTransferTest.java
- system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java
> build: switch e2e tests to dsp

- spi/common/catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/Dataset.java
Adds a builder method to the `DataSet`
Consistency, serializability
> chore: add_builder_method

- extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherExtension.java
Adds missing `@Inject`
Closes #3007
> fix(CallbackEventDispatcher): add missing inject

- .github/PULL_REQUEST_TEMPLATE.md
remove line breaks in PR template
Avoid (erroneous?) rendering w/ line breaks.
.
_Please be sure to take a look at
the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request)
and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)_
> chore: fix PR template formatting

- docs/developer/decision-records/2023-05-17-release-process/README.md
- docs/developer/decision-records/README.md
> docs: decision record for the new release process

- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
Fix the NPE when looking up for a secret by passing a null value
Bug fix
Closes #3111
> fix(TransferProcessManager): fix NPE on not present keyname

- extensions/common/api/api-observability/src/main/java/org/eclipse/edc/api/observability/ObservabilityApi.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApi.java
- extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApi.java
- extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java
- extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApi.java
- extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApi.java
- extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApi.java
- resources/openapi/openapi.yaml
- resources/openapi/yaml/management-api/api-observability.yaml
- resources/openapi/yaml/management-api/asset-api.yaml
- resources/openapi/yaml/management-api/contract-agreement-api.yaml
- resources/openapi/yaml/management-api/contract-definition-api.yaml
- resources/openapi/yaml/management-api/contract-negotiation-api.yaml
- resources/openapi/yaml/management-api/policy-definition-api.yaml
- resources/openapi/yaml/management-api/transfer-process-api.yaml
- spi/common/core-spi/src/main/java/org/eclipse/edc/spi/iam/TokenParameters.java
Resolving the current OpenAPI errors.
It resolves the OpenAPI error by adding the missing description fields.
Closes #3120
> fix: open api errors

- extensions/common/api/api-observability/src/main/java/org/eclipse/edc/api/observability/ObservabilityApi.java
- resources/openapi/openapi.yaml
- resources/openapi/yaml/management-api/api-observability.yaml
should fix https://github.com/eclipse-edc/Connector/issues/3245
See #3245 for information
Simple adjustment to API description
Closes #3245
> fix: Adjusting return types of observability api

- .github/workflows/verify.yaml
Renames the test workflow to avoid special characters and keep it consistent with other repos.
.
> chore: rename workflow

- system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
> fix: end to end transfer process flaky test

- core/control-plane/contract-core/build.gradle.kts
- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
- core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
- core/control-plane/control-plane-aggregate-services/build.gradle.kts
- core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java
- core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
- core/control-plane/transfer-core/build.gradle.kts
- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImpl.java
- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ProvisionManagerImpl.java
- core/data-plane/data-plane-framework/build.gradle.kts
- core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
- core/data-plane/data-plane-framework/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceTransferServiceImpl.java
- core/data-plane/data-plane-util/build.gradle.kts
- core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/ParallelSink.java
- extensions/data-plane/data-plane-client/build.gradle.kts
- extensions/data-plane/data-plane-client/src/main/java/org/eclipse/edc/connector/dataplane/client/EmbeddedDataPlaneClient.java
- extensions/data-plane/data-plane-client/src/main/java/org/eclipse/edc/connector/dataplane/client/RemoteDataPlaneClient.java
- gradle/libs.versions.toml
- system-tests/telemetry/telemetry-test-runner/build.gradle.kts
- system-tests/telemetry/telemetry-test-runner/src/test/java/org/eclipse/edc/test/e2e/tracing/TracingEndToEndTest.java
- system-tests/tests/build.gradle.kts
This will avoid deprecation warnings
> build(deps): bump opentelemetry versions

- docs/developer/build-your-own-connector.md
> docs: update build your own connector

- DEPENDENCIES
updates the DEPENDENCIES file with the latest approvals from EF
keeping it up-to-date
> chore: update DEPENDENCIES file with latest approvals

- docs/developer/decision-records/2023-09-07-policy-monitor/README.md
- docs/developer/decision-records/README.md
`PolicyMonitor` DR
Part of #3422 
> docs: PolicyMonitor DR

- docs/developer/decision-records/2023-10-04-json-ld-scopes/README.md
Adds a Decision Record for Json-Ld processing scopes.
Closes #3508
> feat: Add scope Decision Record

- core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
- core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImplTest.java
- extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
- spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/TransferProcess.java
Automatically deprovision provider transfers.
Cleanup transfer resources
-
Closes #2563 
> feat: automatic deprovisioning for provider transfers

- docs/developer/decision-records/2024-01-12-dynamic-constraint-functions/README.md
- docs/developer/decision-records/README.md
Adds a decision record about Dynamic constraint functions
Policy Engine flexibility
Relates #3775
> docs: decision record about dynamic constraint functions

- .github/workflows/release-edc.yml
Publish openapi ui to github pages on release with the release version
> build(docs): publish openapi ui on release

- extensions/control-plane/api/management-api/management-api-test-fixtures/src/testFixtures/java/org/eclipse/edc/test/system/utils/Participant.java
Exposes the Participant#id field and refactor the offer resolve for common usage  in `requestAsset` and `initContractNegotiation`
clean up
> feat: public Participant#getId 

- docs/developer/data-plane-signaling/data-plane-signaling-token-handling.md
Qualify auth endpoint property values.
Closes #4010.
> docs: Qualify auth endpoint property values

- core/common/util/build.gradle.kts
- core/common/util/src/main/java/org/eclipse/edc/util/reflection/PathItem.java
- core/common/util/src/main/java/org/eclipse/edc/util/reflection/ReflectionUtil.java
- extensions/common/iam/decentralized-identity/identity-did-core/build.gradle.kts
- extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/FieldTranslator.java
- extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldTranslator.java
- extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslator.java
- extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/TranslationMapping.java
- extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/JsonFieldTranslatorTest.java
- extensions/common/sql/sql-core/src/test/java/org/eclipse/edc/sql/translation/PlainColumnFieldTranslatorTest.java
- extensions/control-plane/store/sql/asset-index-sql/build.gradle.kts
- spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/PathItemTest.java
Removes improper dependencies
Closes #4020
> chore: remove util dependency on SPI and remove Jax-RS dependency

- extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/ContractNegotiationApi.java
- extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/validation/ContractRequestValidator.java
- extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/ContractNegotiationApiTest.java
Document contract offer schema. 
because it has some required fields in it (@id, target, assigner)
> docs: improve ContractRequest api doc

- gradle/libs.versions.toml
- spi/common/core-spi/build.gradle.kts
- spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/BitString.java
- spi/common/verifiable-credentials-spi/src/test/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/statuslist/BitStringTest.java
adds the method BitString#set for changing the underlying bitstring + writer
testability
> feat: BitString set API

- core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/controlplane/ControlPlaneDefaultServicesExtension.java
- core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/controlplane/defaults/storage/policydefinition/InMemoryPolicyDefinitionStore.java
- core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/controlplane/defaults/storage/policydefinition/InMemoryPolicyDefinitionStoreTest.java
removes LockManager in favour of ConcurrentHashMap
CME exception
Closes #4141
> fix: removes LockManager in favour of ConcurrentHashMap

- DEPENDENCIES
- extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java
- extensions/common/iam/identity-trust/identity-trust-service/src/test/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustServiceTest.java
add checks on SI token issuer vs VP issuer
> chore: add checks on SI token issuer vs VP issuer

- DEPENDENCIES
- core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/ControlPlaneServicesExtension.java
- core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImpl.java
- core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessEventDispatchTest.java
- core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessServiceImplTest.java
- core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/validation/ContractValidationServiceImpl.java
- system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TransferProcessApiEndToEndTest.java
Integrate fix 0eff36e55bc5c529c1ec966677c7cd16658e21cb  in `v0.6.4`.
Fix.
> fix: integrate fix commit 0eff36e55bc5c529c1ec966677c7cd16658e21cb to v0.6.4

- DEPENDENCIES
- extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/v3/PolicyDefinitionApiV3Controller.java
> chore: remove wrong deprecation warning on policy controller

- DEPENDENCIES
- extensions/data-plane/data-plane-public-api-v2/src/main/resources/public-api-version.json
- resources/openapi/public-api.version
Publish `public-api` version with the v2 version
api documentation
Closes #4346 
> docs(api): add public api version

- core/data-plane/data-plane-core/src/main/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImpl.java
- core/data-plane/data-plane-core/src/test/java/org/eclipse/edc/connector/dataplane/framework/pipeline/PipelineServiceImplTest.java
Close `DataFlow` when the transfer is completed and remove it from the reference map. 
avoid leak
Closes #4438
> fix: close DataSource after transfer

- docs/developer/decision-records/2024-09-24-sts-accounts-api/README.md
- docs/developer/decision-records/README.md
Add a decision-record about the STS Accounts API to manage STS Accounts
make decisions transparent
> docs: add Decision Record about STS Accounts API

- data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-transform-lib/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformer.java
- data-protocols/dsp/dsp-negotiation/lib/dsp-negotiation-transform-lib/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java
removes double forNamespace call
bug fix
> fix: removes double forNamespace call

- docs/developer/decision-records/2025-01-28-async-protocol-message-processing/README.md
- docs/developer/decision-records/README.md
Add DR to outline a decision about the async protocol message processing
Part of #4592 
> docs: add DR for async protocol message processing

- docs/developer/decision-records/2025-02-07-http-proxy-data-plane-deprecation/README.md
- docs/developer/decision-records/README.md
DR for HTTP proxy data plane deprecation
Part of #4791 
> docs: DR for http-proxy deprecation

- data-protocols/dsp/dsp-http-api-configuration/src/main/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtension.java
- data-protocols/dsp/dsp-http-api-configuration/src/test/java/org/eclipse/edc/protocol/dsp/http/api/configuration/DspApiConfigurationExtensionTest.java
- data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/DspHttpCoreExtension.java
- system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferPullEndToEndTest.java
Amend https://github.com/eclipse-edc/Connector/pull/4868
> chore: amend config change on wellknown path

- docs/developer/decision-records/2025-03-14-prioritized-transfer-services/README.md
- docs/developer/decision-records/README.md
Adds a decision record about prioritized transfer services.
To improve selection of a transfer service for a given transfer, if multiple are applicable.
me
> docs: DR for prioritized transfer services

- core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImpl.java
- core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImplTest.java
Enable the deletion of asset if they are not referenced by a contract agreement.
Currently code prevents delete asset referenced in a contract negotiation, which incorrect.
Closes #4884 
> fix: fix delete asset prevention logic based on contract negotiation

- core/common/lib/state-machine-lib/src/main/java/org/eclipse/edc/statemachine/StateMachineManager.java
- core/common/lib/state-machine-lib/src/test/java/org/eclipse/edc/statemachine/StateMachineManagerTest.java
Catch single processor failure, that will permit the other processor to run.
Improve the shutdown mechanism to match the [one shown in the documentation](https://github.com/adoptium/jdk/blob/dfacda488bfbe2e11e8d607a6d08527710286982/src/java.base/share/classes/java/util/concurrent/ExecutorService.java#L105-L126).
better exception handling
Closes #4900 
> feat: improve StateMachineManager exception catching and shutdown mechanism

- core/common/boot/src/main/java/org/eclipse/edc/boot/system/runtime/BaseRuntime.java
- core/common/boot/src/test/java/org/eclipse/edc/boot/system/runtime/BaseRuntimeTest.java
Make `BaseRuntime.shutdown` to catch exceptions thrown by `ServiceExtension.shutdown` calls
Permit full shutdown also if an extension unexpectedly fails.
Closes #4901 
> feat: catch shutdown exceptions

- core/common/connector-core/build.gradle.kts
- core/common/lib/crypto-common-lib/build.gradle.kts
- core/common/lib/keys-lib/build.gradle.kts
- core/common/lib/validator-lib/build.gradle.kts
Cleans up dependencies
Closes #4916
> chore: cleanup core dependencies

- docs/developer/decision-records/2025-04-30-finalize-phase/README.md
- docs/developer/decision-records/README.md
Adds DR for `finalize` phase
Part of #4947 
> docs: add DR for finalize phase

- README.md
- extensions/common/http/jersey-micrometer/README.md
- extensions/common/http/jetty-micrometer/README.md
- extensions/common/metrics/micrometer-core/README.md
fix incorrect developer documentation links.
Closes #4969
> docs: fix incorrect developer documentation links

- system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/CompatibilityTests.java
- system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/EdcCompatibilityDockerTest.java
- system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/java/org/eclipse/edc/tck/dsp/EdcCompatibilityEmbeddedTest.java
- system-tests/dsp-compatibility-tests/compatibility-test-runner/src/test/resources/docker.tck.properties
- system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckWebhookController.java
- system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/data/DataAssembly.java
- system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/guard/ContractNegotiationGuard.java
Sdd support for new contract negotiation tests in dsp-tck
> chore: add support for new cn tests

- data-protocols/dsp/build.gradle.kts
includes dsp 2025 impl in the dsp bom
Closes #5087 
> feat: includes dsp 2025 impl in the dsp bom

- extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/validation/PolicyDefinitionValidator.java
- extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/validation/PolicyDefinitionValidatorTest.java
Adds operator evaluation in the `PolicyDefinitionValidator`
Improve error response messages
Closes #5099
> fix: add operator validation to provide meaningful error

- build.gradle.kts
- gradle/libs.versions.toml
Related to: https://github.com/eclipse-edc/GradlePlugins/pull/354
> build: use edc-build from Gradle Plugin Portal

- .github/workflows/publish-context.yaml
- extensions/common/api/lib/management-api-lib/src/main/java/org/eclipse/edc/api/management/ManagementApi.java
- extensions/common/api/management-api-configuration/src/main/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtension.java
- extensions/common/api/management-api-configuration/src/test/java/org/eclipse/edc/connector/api/management/configuration/ManagementApiConfigurationExtensionTest.java
- extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
- extensions/common/json-ld/src/main/resources/document/management-context-v2.jsonld
- spi/common/core-spi/src/main/java/org/eclipse/edc/spi/constants/CoreConstants.java
- system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/SerdeEndToEndTest.java
- system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/TestFunctions.java
Creates new JSON-LD context v2, that will be enable by default in MGMG api v4 (currently v4alpha)
Closes #5135 
> feat: draft JSON-LD context v2 + tests

- core/common/boot/src/main/java/org/eclipse/edc/boot/system/injection/InjectionContainer.java
- extensions/control-plane/transfer/transfer-data-plane-signaling/src/test/java/org/eclipse/edc/connector/controlplane/transfer/dataplane/flow/DataPlaneSignalingFlowControllerTest.java
- resources/suppressions.xml
- spi/common/verifiable-credentials-spi/src/main/java/org/eclipse/edc/iam/verifiablecredentials/spi/model/revocation/BitString.java
- system-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
- system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/provision/ProvisioningTransferConsumerEndToEndTest.java
Now that checkstyle released a new working version, we can remove the indentation suppression
> chore: disable checkstyle indentation suppression

- core/common/participant-context-single-core/src/main/java/org/eclipse/edc/participantcontext/single/SingleParticipantContextDefaultServicesExtension.java
- core/common/participant-context-single-core/src/test/java/org/eclipse/edc/participantcontext/SingleParticipantContextDefaultServicesExtensionTest.java
- data-protocols/dsp/dsp-core/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/http/message/DspRequestHandlerImpl.java
- data-protocols/dsp/dsp-core/dsp-http-core/src/test/java/org/eclipse/edc/protocol/dsp/http/message/DspRequestHandlerImplTest.java
- data-protocols/dsp/dsp-http-spi/src/main/java/org/eclipse/edc/protocol/dsp/http/spi/message/DspRequest.java
- data-protocols/dsp/dsp-lib/dsp-catalog-lib/dsp-catalog-http-api-lib/src/testFixtures/java/org/eclipse/edc/protocol/dsp/catalog/http/api/controller/DspCatalogApiControllerTestBase.java
- data-protocols/dsp/dsp-lib/dsp-negotiation-lib/dsp-negotiation-http-api-lib/src/testFixtures/java/org/eclipse/edc/protocol/dsp/negotiation/http/api/controller/DspNegotiationApiControllerTestBase.java
- data-protocols/dsp/dsp-lib/dsp-transfer-process-lib/dsp-transfer-process-http-api-lib/src/testFixtures/java/org/eclipse/edc/protocol/dsp/transferprocess/http/api/controller/DspTransferProcessApiControllerBaseTest.java
- extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/asset/BaseAssetApiController.java
- extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/asset/BaseAssetApiControllerTest.java
- extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractdefinition/BaseContractDefinitionApiController.java
- extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/contractdefinition/BaseContractDefinitionApiControllerTest.java
- extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/BaseContractNegotiationApiController.java
- extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/contractnegotiation/BaseContractNegotiationApiControllerTest.java
- extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/policy/BasePolicyDefinitionApiController.java
- extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/policy/BasePolicyDefinitionApiControllerTest.java
- extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/BaseTransferProcessApiController.java
- extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/controlplane/api/management/transferprocess/BaseTransferProcessApiControllerTest.java
- extensions/data-plane-selector/data-plane-selector-client/src/test/java/org/eclipse/edc/connector/dataplane/selector/RemoteDataPlaneSelectorServiceTest.java
- extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiController.java
- extensions/data-plane-selector/data-plane-selector-control-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiControllerTest.java
- spi/common/connector-participant-context-spi/src/main/java/org/eclipse/edc/participantcontext/spi/service/ParticipantContextSupplier.java
- system-tests/protocol-tck/tck-extension/src/main/java/org/eclipse/edc/tck/dsp/controller/TckWebhookController.java
refactor participant context supplier to be fallible
Closes #5244 
> feat: refactor participant context supplier to be fallible
