.gitignore
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplConsumerTest.java

In the current implementation of the `TransferProcessManager` there was a bug that caused transfer processes, that have no managed resources, to be stuck in `REQUESTED_ACK` state. This PR fixes that by adding several checks.

[Bugfix] Fix stuck TransferProcesses when resources are not managed

---

SECURITY.md

Just adding the basic information for SECURITY.md file as suggested by Eclipse Foundation. This file can be maintained for future versions to be supported or extended with additional information.

add simple SECURITY.md as requested by EF

---

data-protocols/ids/ids-spi/build.gradle.kts

Just a small typo that results in a weird package name when published to maven local.

ids-spi: fixed typo in artifactId of `data-protocols.ids-spi`

---

docs/architecture-principles.md
extensions/iam/distributed-identity/registration-service/src/main/java/org/eclipse/dataspaceconnector/iam/registrationservice/crawler/CrawlerContext.java
extensions/iam/distributed-identity/registration-service/src/main/java/org/eclipse/dataspaceconnector/iam/registrationservice/crawler/CrawlerExtension.java
extensions/iam/distributed-identity/registration-service/src/main/java/org/eclipse/dataspaceconnector/iam/registrationservice/crawler/CrawlerJob.java
extensions/iam/oauth2/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/Oauth2Extension.java
extensions/iam/oauth2/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/impl/IdentityProviderKeyResolver.java
extensions/iam/oauth2/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/impl/IdentityProviderKeyResolverTest.java
extensions/ion/ion-core/src/main/java/org/eclipse/dataspaceconnector/ion/util/JsonCanonicalizer.java
samples/other/copy-file-to-s3bucket/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/AwsDemoExtension.java
samples/other/copy-file-to-s3bucket/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/DemoS3FlowController.java
samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/controller/DemoExtension.java
samples/other/file-transfer-s3-to-s3/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/controller/S3toS3TransferFlowController.java

Ref #193 
Update the `architecture-principles.md` file and replaced the `ObjectMapper` instantiations in the production code.

extensions: prefer TypeManager over ObjectMapper

---

data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/PermissionToPermissionTransformer.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/PermissionToPermissionTransformerTest.java

Hello everyone,
the code contained  a ToDo (that was wrongly added by me) explaining, that it's not defined where how a EDC/ODRL duty should be mapped to IDS Permission (pre- or post-duty).
But that's not correct. In ODRL a duty in a permission is always a pre-duty. Therefore we are able to map it from EDC to IDS. It only doesn't work the other way around.

Small fix for PermissionToPermissionTransformer

---

.github/workflows/integrationtests.yaml

I-Tests need to be enabled explicitly by adding a job to the workflow file.

Added CosmosDB-based AssetIndex  integrationtest to i-test workflow

---

data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/AbstractMultipartControllerIntegrationTest.java

This PR introduces an own ObjectMapper instance to the IDS MultipartController to be able to make de/serialization configurable without interfering with what other subsystems require the global ObjectMapper to be capable of. (Closes #261)

ids-endpoint: Makes ObjectMapper to be configurable/injectable via constructor (closes #261)

---

data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/policy/IdsPolicyExpressions.java
extensions/policy/ids-policy/build.gradle.kts
extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/AbsSpatialPositionConstraintFunction.java
extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/IdsPolicyExtension.java
extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/PartnerLevelConstraintFunction.java
extensions/policy/ids-policy/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
extensions/policy/ids-policy/src/test/java/org/eclipse/dataspaceconnector/ids/policy/AbsSpatialPositionConstraintFunctionTest.java
extensions/policy/ids-policy/src/test/java/org/eclipse/dataspaceconnector/ids/policy/PartnerLevelConstraintFunctionTest.java
settings.gradle.kts

Add an extension that defines two functions for ids policy validation:
* `AbsSpatialPositionConstraintFunction` that checks the region
* `PartnerLevelConstraintFunction` that checks the partner level

extensions: add ids policy extension

---

core/bootstrap/src/main/java/org/eclipse/dataspaceconnector/monitor/MonitorProvider.java

When pulling in dependencies that rely on certain logging functionality [you can hit this error ](http://www.slf4j.org/codes.html#null_MDCA). It looks like this is caused by the returned nulls in the MonitorProvider, which [in this code ](http://www.slf4j.org/api/src-html/org/slf4j/MarkerFactory.html#line.44) result in the MarkerFactory/MDCAdapter to be null. 
Updated the provider to match the [NOPProvider that can be found here](http://www.slf4j.org/api/src-html/org/slf4j/helpers/NOPServiceProvider.html#line.8) for the MarkerFactory and MDCAdapter.

Initialize MonitorProvider correctly

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/build.gradle.kts
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/AbstractMultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/build.gradle.kts
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
extensions/aws/s3/provision/src/test/java/org/eclipse/dataspaceconnector/provision/aws/s3/S3StatusCheckerIntegrationTest.java

The old implementation made it possible for a `ContractDefinitionStore` supplied by an extension to get overwritten by the `InMemory...` one. That should now be corrected - the in-mem one is only used as fallback.

corrected the lazy-instantiation of the ContrDefStore

---

extensions/aws/s3/provision/src/test/java/org/eclipse/dataspaceconnector/provision/aws/s3/S3StatusCheckerIntegrationTest.java

unfortunately, again, we need to merge this into `main` before we see the effects due to the workflow configuration.

Fixes a faulty test setup for the S3 StatusChecker Integration test

---

extensions/api/control/README.md
extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ControlApiServiceExtension.java
extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/HttpApiKeyAuthContainerRequestFilter.java
extensions/api/control/src/test/java/org/eclipse/dataspaceconnector/api/control/ClientControlCatalogApiControllerTest.java

Adding a simple HTTP API-Key `ContainerRequestFilter` to the control-api. Closes #302.

control-api: Adds api-key HTTP containerRequestFilter (closes #302)

---

extensions/jdk-logger-monitor/README.md
extensions/jdk-logger-monitor/build.gradle.kts
extensions/jdk-logger-monitor/src/main/java/org/eclipse/dataspaceconnector/logger/LoggerMonitor.java
extensions/jdk-logger-monitor/src/main/java/org/eclipse/dataspaceconnector/logger/LoggerMonitorExtension.java
extensions/jdk-logger-monitor/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.MonitorExtension
extensions/jdk-logger-monitor/src/test/java/org/eclipse/dataspaceconnector/logger/LoggerMonitorTests.java
extensions/jdk-logger-monitor/src/test/java/org/eclipse/dataspaceconnector/logger/TestLogHandler.java
settings.gradle.kts

- Adds a monitor logger extension.
- java.util.logging is used for logger. This will not introduce any additional dependency.
- Adds unit tests.
- Adds documentation.
Closes #297 (https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/297)

Adds monitor logger extension

---

data-protocols/ids/ids-api-multipart-endpoint-v1/build.gradle.kts
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java

Replaces usage of TransferProcessStore with TransferProcessManager in ids-multipart.
Closes #301 
Brendan Cronin brendan.cronin@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

Ids-multipart: Replace usage of TransferProcessStore with -Manager

---

extensions/azure/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndex.java
extensions/azure/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetQueryBuilder.java
extensions/azure/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java
extensions/azure/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexTest.java
extensions/azure/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetQueryBuilderTest.java
extensions/in-memory/assetindex-memory/src/main/java/org/eclipse/dataspaceconnector/metadata/memory/CriterionToPredicateConverter.java
extensions/in-memory/assetindex-memory/src/test/java/org/eclipse/dataspaceconnector/metadata/memory/CriterionToPredicateConverterTest.java
extensions/in-memory/assetindex-memory/src/test/java/org/eclipse/dataspaceconnector/metadata/memory/InMemoryAssetIndexTest.java
spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/Criterion.java

Both the in-memory and the CosmosDB implementation of the `AssetIndex` can now handle the "IN" operator. Tests were added to verify that.
_Please be aware that the concrete syntax depends on the implementation! E.g. CosmosDB requires the list to be in brackets and - depending on the datatype - surrounded by single quotation marks, whereas the in-memory variant doesn't!_
Querying for a String property named `"someProperty"` would result in the following valid Criterion arguments:
|Impl | operandLeft | operator | operandRight |
| --------| :------------- |-------------:| :-----|
|In-mem | someProperty | "IN" | "(val1, val2, val3)" |
|cosmos | someProperty | "IN" | "('val1', 'val2', 'val3')"|
closes #307 
_Smaller changes to the `CosmosAssetIndex` and `CosmosAssetQueryBuilder` were …

Added "IN" operator to all AssetIndex imlementations

---

extensions/azure/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
extensions/azure/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreConfig.java
extensions/azure/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreExtension.java
extensions/azure/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/ContractNegotiationDocument.java
extensions/azure/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/Lease.java
extensions/azure/contract-negotiation-store-cosmos/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
extensions/azure/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/azure/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreTest.java
extensions/azure/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
extensions/azure/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/ContractNegotiationDocumentSerializationTest.java

ContractNegotiation module still had wrong package names, and also had the wrong feature in `provides()`

fixed package names in contract negotiation module

---

extensions/jdk-logger-monitor/build.gradle.kts

This should fix the `409 Confict` error on publish phase

extensions: remove version and groupId from jdk-logger-monitor

---

extensions/iam/distributed-identity/registration-service/README.md
extensions/iam/distributed-identity/registration-service/doc/onboarding_flow.md
extensions/iam/distributed-identity/registration-service/doc/onboarding_flow.puml
extensions/iam/distributed-identity/registration-service/doc/verification.md
extensions/iam/distributed-identity/registration-service/doc/verification.puml

This PR adds sequence diagrams and accompanying documentation about the following flows:
- onboarding new connectors, issuing verified credentials/claims
- verifying those claims 
Those flows are only valid in a distributed identity scenario, which uses DIDs and Identity Hubs[
Adapting the `registration-service` and `registration-service-api` will be done in a subsequent PR, this serves merely as basis for discussion.

Documentation about onboarding new connectors (DistributedIdentity)

---

docs/architecture/README.md
samples/04.1-file-transfer-listener/README.md
samples/04.1-file-transfer-listener/consumer/build.gradle.kts
samples/04.1-file-transfer-listener/consumer/config.properties
samples/04.1-file-transfer-listener/listener/build.gradle.kts
samples/04.1-file-transfer-listener/listener/src/main/java/org/eclipse/dataspaceconnector/extensions/listener/MarkerFileCreator.java
samples/04.1-file-transfer-listener/listener/src/main/java/org/eclipse/dataspaceconnector/extensions/listener/TransferListenerExtension.java
samples/04.1-file-transfer-listener/listener/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
settings.gradle.kts
spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/TransferProcessListener.java

Added Javadoc, Markdown documentation, and a sample on creating a `TransferProcessListener` to react to transfer state changes (in particular, transfer completion on the consumer side).
Closes #240

TransferProcessListener doc and sample

---

NOTICE.md
docs/developer/releases.md

Hi everyone,
this PR introduces an instruction for developers describing the versioning scheme, legal requirement towards distribution artifacts, and the process of publishing maven artifacts.
Additionally, the NOTICE file now states the fact that the list of 3rd party libraries covers all submodules of the project (which is relevant when the file is embedded in an individual module jar).

Create developer instruction for versioning and publishing

---

build.gradle.kts
data-protocols/ids/ids-api-transfer/build.gradle.kts
data-protocols/ids/ids-api-transfer/src/main/java/org/eclipse/dataspaceconnector/ids/api/transfer/ArtifactRequestController.java
data-protocols/ids/ids-api-transfer/src/test/java/org/eclipse/dataspaceconnector/ids/api/transfer/ArtifactRequestControllerTest.java
data-protocols/ids/ids-core/build.gradle.kts
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/message/DataRequestMessageSender.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/message/DataRequestMessageSenderTest.java
extensions/jdk-logger-monitor/build.gradle.kts
spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataRequest.java

This PR contains a proposal to solve issue #299  by extending the DataRequest object with a Map of custom properties.
- add properties Map field to DataRequest
- add the properties to the artifactMessage in DataRequestMessageSender so that they are passed to the provider
- read the properties in ArtifactRequestController
- add unit tests for verifying that the properties were passed from DataRequest to ArtifactRequestMessage in consumer and from ArtifactRequestMessage to DataRequest in provider
Closes #299

spi: extend DataRequest with custom properties field

---

samples/05-file-transfer-cloud/README.md
samples/05-file-transfer-cloud/terraform/main.tf
samples/05-file-transfer-cloud/terraform/output.tf
samples/05-file-transfer-cloud/terraform/variables.tf

Generate X.509 certificate in Terraform, rather than on local machine.
Benefits:
- not requiring OpenSSL tools to be installed locally to deploy.
- not requiring the user to manually enter certificate information.
- useful Terraform code that can be adapted by end users for development environments.
Deployment fails against upstream main because of #381, but I tested it against an older head with minor modifications.
Other improvements:
- Locked terraform provider versions for maximum stability.
- Applied `terraform fmt` to format terraform files.

sample 5: generate service principal certificate with Terraform

---

samples/02-health-endpoint/README.md
samples/02-health-endpoint/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthApiController.java
samples/03-configuration/README.md
samples/03-configuration/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthApiController.java
samples/04-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
samples/05-file-transfer-cloud/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java

Issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/405:

samples: return json as specified in produces and update readme examples

---

.github/workflows/integrationtests.yaml

Seems like the docker service didn't like the use of environment variables in the volume path.
Set these as absolute path.
Ref #440

integration-tests: set absolute path on docker volumes

---

.github/workflows/integrationtests.yaml

As stated in #221 this should fix the daps integration test running.
The problem is that the docker volumes change the permissions in the workspace folder so there's the need to reset them before.

integration-tests: reset permissions

---

core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManager.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManagerImplTest.java
extensions/catalog/federated-catalog-cache/build.gradle.kts
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/DefaultLoader.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/controller/CatalogController.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/query/CacheQueryAdapterRegistryImpl.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/query/DefaultCacheQueryAdapter.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/query/IdsMultipartNodeQueryAdapter.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheEndToEndTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/TestUtil.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/query/InMemoryFccQueryAdapterRegistryTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/query/QueryEngineImplTest.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/CacheQueryAdapter.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/CacheQueryAdapterRegistry.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/FederatedCacheStore.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/QueryResponse.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/model/UpdateResponse.java
extensions/in-memory/fcc-store-memory/src/main/java/org/eclipse/dataspaceconnector/catalog/store/InMemoryFederatedCacheStore.java
extensions/in-memory/fcc-store-memory/src/main/java/org/eclipse/dataspaceconnector/catalog/store/InMemoryFederatedCacheStoreExtension.java
samples/other/streaming/src/test/java/org/eclipse/dataspaceconnector/transfer/demo/protocols/stream/DemoPushStreamTransferTest.java

The Federated Catalog Cache now uses IDS Multipart Catalog queries, and instead of Assets it also only deals with `ContractOffer` objects.
Furthermore, the FCC now ships with an IDS-Multipart-based `NodeQueryAdapter` implementation and registers it for the `"ids-multipart"` protocol.
Closes #402 
_Unrelated: a potential NPE in the Async-TPM was fixed too_

Migrates the Federated Catalog subsystem over to use IDS Multipart

---

core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/provision/ProvisionContextImpl.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/provision/ProvisionManagerImpl.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManager.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/DelegatingTransferProcessManager.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/SyncTransferProcessManager.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/TestResourceDefinition.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/provision/ProvisionManagerImplTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManagerImplConsumerTest.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/message/DataRequestMessageSender.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/message/DataRequestMessageSenderTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/crawler/CrawlerImplTest.java
samples/05-file-transfer-cloud/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
samples/other/public-rest-api/src/main/java/org/eclipse/dataspaceconnector/demo/api/rest/DemoApiController.java
spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/TransferProcessManager.java
spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ProvisionContext.java
spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ProvisionManager.java

Part of #330
This PR bring all the code that calls methods that change a transfer process (`create`, `update`, `delete`) inside `TransferProcessManager`, that will help introducing the command queue.
I have two questions, both for @jimmarino and @paullatzelsperger 
1. The process of handling post-provision/deprovision actions using `ProvisionContext` is pretty hard to understand (it took me a while), I would suggest to change that implementation, I have two proposal:
* Make `Provisoner`'s `provision` and `deprovision` and `ProvisionManager`'s `provision` and `deprovision` return a `CompletableFuture` containing the result, doing so, the definition of what should be done after the provisioning/deprovisioning will be set right after the method call, more easy to read. (preferred solution …

Isolate TransferProcessStore usage into TransferProcessManager

---

data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/types/SecurityProfile.java
data-protocols/ids/ids-spi/src/test/java/org/eclipse/dataspaceconnector/ids/spi/types/SecurityProfileTest.java

Issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/397:

securityprofile: refactor exception-message and add test

---

build.gradle.kts

The comment reported that this dependency was "used for the multihash lib", but we don't use that dependency (there are some copy-and-pasted files from it).
This is currently breaking CI (e.g. https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/4607127286?check_suite_focus=true) because the mulsesoft repository is responding 502 but, since it's not needed, we can get rid of it.

Remove unused mulesoft repository

---

extensions/in-memory/fcc-store-memory/src/main/java/org/eclipse/dataspaceconnector/catalog/store/InMemoryFederatedCacheStore.java
extensions/in-memory/fcc-store-memory/src/test/java/org/eclipse/dataspaceconnector/catalog/store/InMemoryFederatedCacheStoreTest.java

Current implementation uses the id of the inserted `ContractOffer` as key in the underlying map of the in-memory store. 
However this id is not contains a random string (see `ContractOfferServiceImpl`), thus leading the store to contain duplicate versions of the same asset and to grow indefinitely.

fix: Repair InMemoryFederatedCacheStore as non-unique ContractOffer is used as key in the store

---

core/base/src/main/java/org/eclipse/dataspaceconnector/core/system/DefaultServiceExtensionContext.java
core/base/src/test/java/org/eclipse/dataspaceconnector/core/system/DefaultServiceExtensionContextTest.java
spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/Requires.java

As an after-task to the recent module loading PR (#475) I brought back the `@Requires` annotation to conform to the original issue (#469) and to enable programmatic/manual dependency resolution.

Re-added the @Requires annotation

---

extensions/filesystem/vault-fs/src/main/java/org/eclipse/dataspaceconnector/core/security/fs/FsPrivateKeyResolver.java
extensions/filesystem/vault-fs/src/test/java/org/eclipse/dataspaceconnector/core/security/fs/FsRsaPrivateKeyResolverTest.java
extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java
extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/impl/Oauth2ServiceImpl.java
extensions/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/impl/Oauth2ServiceImplTest.java

Issue #382 
Adjustments to support EC private keys. The oauth2-core (Oauth2Extension, Oauth2ServiceImpl) and the filesystem-vault (FsPrivateKeyResolver and -Test) were changed. I hope I didn't miss anything (VaultPrivateKeyResolver parser ?).

ecdsa: support ecdsa private keys

---

extensions/azure/cosmos/fcc-node-directory-cosmos/build.gradle.kts

Removed a maven publication that probably slipped in after some merge/rebase

Removed erroneous maven publication from FCC Node Directory Cosmos

---

extensions/catalog/federated-catalog-spi/build.gradle.kts

`catalog-spi` was already used

extensions: fix duplicated artifact name

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java

To avoid NPE when `obtainClientCredentials` fails

data-protocols: evaluate obtainClientCredentials result

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractAgreementSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
extensions/api/control/src/test/java/org/eclipse/dataspaceconnector/api/control/ClientControlCatalogApiControllerTest.java

The `ids.webhook.address` should be evaluated and verified on the initialization phase, this will avoid unexpected errors on execution.

data-protocols: evaluate ids.webhook.address at startup and not lazily

---

launchers/basic/build.gradle.kts
launchers/data-loader-cli/build.gradle.kts
launchers/ids-connector/build.gradle.kts
launchers/registration-service-app/build.gradle.kts
samples/01-basic-connector/build.gradle.kts
samples/02-health-endpoint/build.gradle.kts
samples/03-configuration/build.gradle.kts
samples/04-file-transfer/consumer/build.gradle.kts
samples/04-file-transfer/provider/build.gradle.kts
samples/04.1-file-transfer-listener/consumer/build.gradle.kts
samples/05-file-transfer-cloud/consumer/build.gradle.kts
samples/05-file-transfer-cloud/provider/build.gradle.kts
samples/other/commandline/consumer/build.gradle.kts
samples/other/custom-runtime/build.gradle.kts
samples/other/file-transfer-s3-to-s3/build.gradle.kts

This is my first and not very significant contribution :)
Here is a warning-free way of specifying the main class: [JavaApplication].(https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaApplication.html)

build system: avoid deprecated gradle.kts features to specify main class

---

.github/workflows/generate_openapi_spec.yaml
README.md
build.gradle.kts
extensions/api/control/build.gradle.kts
extensions/api/observability/build.gradle.kts
extensions/catalog/federated-catalog-cache/build.gradle.kts
extensions/iam/decentralized-identity/identity-did-core/build.gradle.kts
gradle.properties
openapi.md
resources/openapi/openapi.yaml
resources/openapi/yaml/control.yaml
resources/openapi/yaml/federated-catalog-cache.yaml
resources/openapi/yaml/identity-did-core.yaml
resources/openapi/yaml/observability.yaml
settings.gradle.kts

This PR adds two Gradle tasks to automatically scan the code base and generate a `*.yaml` specification: 
```shell
./gradlew clean resolve
./gradlew mergeOpenApiFiles
```
Unfortunately I'm not savvy enough in Gradle and Kotlin to have those two tasks somehow depend on each other, so we need to execute them separately. 
Also updated docs.

Automatic swagger generation

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AsyncTransferProcessManager.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/ContractNegotiationListener.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/ContractNegotiationObservable.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/Observable.java

This PR makes the `Provider- and ConsumerContractNegotiationManagers` observable by providing the possibility to register listeners. The listeners will be notified about every state change on a `ContractNegotiation` instance. The PR also refactors the `ContractNegotiationIntegrationTest` to use listeners instead of signaling stores to determine when the desired end state has been reached.
Closes #352

contract negotiation: add contract negotiation listener

---

.github/workflows/integrationtests.yaml
samples/other/file-transfer-s3-to-s3/build.gradle.kts

Since blobstorage's `provision` module was renamed to `blob-provision`, integration tests started to fail, this will fix them.

integration-test: fix path

---

common/util/src/main/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctions.java
common/util/src/main/java/org/eclipse/dataspaceconnector/common/string/StringUtils.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctionsTest.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/string/StringUtilsTest.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContextTest.java
extensions/filesystem/configuration-fs/build.gradle.kts
extensions/filesystem/configuration-fs/src/main/java/org/eclipse/dataspaceconnector/configuration/fs/FsConfigurationExtension.java
extensions/filesystem/configuration-fs/src/test/java/org/eclipse/dataspaceconnector/configuration/fs/FsConfigurationExtensionTest.java
extensions/filesystem/configuration-fs/src/test/resources/edc-configuration.properties
extensions/iam/daps/src/test/java/org/eclipse/dataspaceconnector/iam/daps/DapsIntegrationTest.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ConfigurationExtension.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtensionContext.java

This PR extends the configuration feature and adds an option to filter by prefix. There also is a new helper method that will then interpret the resulting properties hierarchically.
Having this feature makes configuring multiple instances of a single thing (e.g. datasources) much easier.
Closes #546

Add filtering for properties and making them hierarchical

---

samples/04.1-file-transfer-listener/README.md
samples/04.1-file-transfer-listener/consumer/build.gradle.kts
samples/04.1-file-transfer-listener/consumer/config.properties
samples/04.2-modify-transferprocess/README.md

While running the samples 04.1 and 04.2, I noticed some inconsistencies in both READMEs as well as the configuration of the consumer for 04.1. Therefore, the samples could not be run by just copying the commands from the README. This should be fixed with this PR.

sample: update samples 04.1 and 04.2

---

samples/05-file-transfer-cloud/consumer/build.gradle.kts

Provisioning of an S3 Bucket, like described in the README.md, did not working because the provisioner was not registered in the consumer.

Fix Sample 5: AWS S3 Provision, closes #563

---

extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ClientController.java
extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/response/NegotiationStatusResponse.java
samples/04.0-file-transfer/README.md
samples/04.1-file-transfer-listener/README.md

This PR adds a new endpoint to the control API, that returns the current status for a negotiation as well as the contract agreement ID, if the negotiation has been confirmed. The READMEs of sample 04.0 and 04.1 have been updated to use the new endpoint for obtaining the agreement ID.
Closes #390

control-api: endpoint for negotiation state

---

core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
core/base/src/main/java/org/eclipse/dataspaceconnector/core/health/HealthCheckServiceImpl.java
core/base/src/test/java/org/eclipse/dataspaceconnector/core/health/HealthCheckServiceImplTest.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/health/HealthCheckService.java

core: health check service cache can be refreshed at boot completion

---

core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ReflectiveObjectFactory.java
core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/ReflectiveObjectFactoryTest.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/loader/LoaderManagerImpl.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/loader/LoaderManagerImplTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/ContractNegotiationObservable.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/NegotiationWaitStrategy.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/observe/Observable.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/retry/WaitStrategy.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ObjectFactory.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/ObservableTest.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/observe/ObservableTest.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/TransferProcessObservable.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/TransferWaitStrategy.java

This PR makes the following package adjustments in core-spi:
1. WaitStrategy moves from the top-level SPI package to the retry subpackage.
2. ObjectFactory and ReflectiveObjectFactory move from the top-level SPI package to the system subpackage. This removes package cycles.
3. Observable moves from the top-level SPI package to the observe subpackage.

Minor SPI package cleanup

---

extensions/filesystem/vault-fs/src/main/java/org/eclipse/dataspaceconnector/core/security/fs/FsConfiguration.java
extensions/filesystem/vault-fs/src/main/java/org/eclipse/dataspaceconnector/core/security/fs/FsVaultExtension.java
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcRuntimeExtension.java

This PR removes the default value (`"test123"`) from the `FsConfiguration`. 
Providing a default password is not very useful in the first place, but more importantly CodeQL will qualify hard-coded credentials as High Risk (PR #692 by @Izzzu), so this serves as preliminary work for that.
Unrelated: the `ConsoleMonitor` in ithe `EdcRuntimeExtension` was replaced with a `Monitor` to avoid spamming STDOUT during testing.

Removed default `KEYSTORE_PASSWORD` from `FsConfiguration`

---

.github/workflows/publish.yaml

closes #707 
Prevent running the `publish` workflow on forks. Artifacts should only be published on the upstream repository.

Prevent publish workflow execution on forks

---

core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContextTest.java
extensions/sql/pool/apache-commons-pool/src/test/java/org/eclipse/dataspaceconnector/sql/pool/commons/CommonsConnectionPoolServiceExtensionTest.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/configuration/ConfigImpl.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/system/configuration/ConfigImplTest.java

This PR converts all config values from `UPPER_SNAKE_CASE` to `java.dot.notation` to have a normalized format internally.
Closes #708

Environment variables are converted to dot-notation Java Properties

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplIntegrationTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java

Follow up of #690 .
Since we decided to change the lock implementation as decided in #690, and given that there was a test that persisted to fail on github action (but it passed on my machine) I decided to extract the only feature it remained in that PR
Currently, on the managers (TransferProcess and ContractNegotiation) the store object is injected on the "start" method invocation. Since there are no reasons to do that, I added a `store` method on the builders and make it as a mandatory field on the managers.

core: initialize store at manager build

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSenderTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/transfer/DataPlanePublicApiRequestFilter.java
extensions/data-plane/data-plane-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/api/transfer/DataPlanePublicApiRequestFilterTest.java

In current implementation the id of the `DataRequest` is generated on provider side. Thus there is no correlation that can be made between the `DataRequest` sent to the consumer and the one the is actually processed by the provider. 
In this PR we propose a modification that consists in generating the `DataRequest` id on the consumer side (if none already exists) and then to forward it through the IDS `ArtifactRequestMessage`.
We also take the opportunity of this PR to perform minor fix related to the data plane framework and add some documentation.
In the case of synchronous data transfer (see #585) , the provider data plane is used to collect the data from the source. During the Artifact Request, the provider control plane will thus return to the consumer the url and token (see …

ids: generate `DataRequest` id on consumer side and forward it into `ArtifactRequestMessage`

---

core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java

It removes a transition in the `TransferProcessManagerImpl`, where a process in the  `IN_PROGRESS` state is transitioned to `IN_PROGRESS` again, if it hasn't been completed yet.
As the transition is not allowed by the `TransferProcess`, it causes an error in sample 04.2 as described in the linked issue. This problem could either be resolved by removing that particular transition or by allowing the transition from `IN_PROGRESS` to `IN_PROGRESS`. As the `IN_PROGRESS` state is an ongoing state, a `TransferProcess` in that state should not be transitioned to it again. That way, the state timestamp indicates the complete time the `TransferProcess` has been in that state and might therefore be used to identify processes that fail to complete in a certain amount of time.
Closes #725

Fix sample 04.2

---

NOTICE.md

Hi all,
this PR updates the list of third party licenses inside the root NOTICE.md file.
For this, all current direct and indirect dependencies within each project module were analysed and reviewed using the Eclipse Dash License tool.

Update list of third party licenses

---

common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtilTest.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObjectSubSubclass.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObjectSubclass.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
extensions/http/jetty/src/test/java/org/eclipse/dataspaceconnector/extension/jetty/JettyServiceTest.java
extensions/in-memory/contractdefinition-store-memory/build.gradle.kts
extensions/in-memory/contractdefinition-store-memory/src/main/java/org/eclipse/dataspaceconnector/contractdefinition/store/memory/InMemoryContractDefinitionStore.java
extensions/in-memory/contractdefinition-store-memory/src/test/java/org/eclipse/dataspaceconnector/contractdefinition/store/memory/InMemoryContractDefinitionStoreTest.java
extensions/in-memory/negotiation-store-memory/src/main/java/org/eclipse/dataspaceconnector/negotiation/store/memory/InMemoryContractNegotiationStore.java
extensions/transaction/transaction-atomikos/src/test/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionExtensionTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java

It adds support for a `QuerySpec` to the `ContractDefinitionStore` and all its implementors.
Certain endpoints in the DataManagementApi specify that paging, filtering and sorting be supported, so that clients can fine-tune their queries. This PR adds that functionality.
- reflection: the `ReflectionUtil` class was improved to provide central methods e.g. to get  fields from a class, including supertypes
- reflection: the `getFieldValue` method now accepts property names in the dot-notation and recursively descends down the object graph to retrieve the value.
- for the in-memory stores the creation of propery comparators is now handled centrally.
- in some tests the `ConsoleMonitor` has been replaced with a generic `Monitor` to avoid log spam
Closes #634

`ContractDefinitionStore` supports paging

---

.github/workflows/verify.yaml
README.md
common/util/src/testFixtures/java/org/eclipse/dataspaceconnector/common/testfixtures/TestUtils.java
docs/developer/decision-records/2022-02-14-helm-chart/README.md
launchers/generic/Dockerfile
launchers/generic/README.md
resources/charts/dataspace-connector/Chart.yaml
resources/charts/dataspace-connector/templates/NOTES.txt
resources/charts/dataspace-connector/templates/_helpers.tpl
resources/charts/dataspace-connector/templates/configmap.yaml
resources/charts/dataspace-connector/templates/deployment.yaml
resources/charts/dataspace-connector/templates/hpa.yaml
resources/charts/dataspace-connector/templates/ingress.yaml
resources/charts/dataspace-connector/templates/secret.yaml
resources/charts/dataspace-connector/templates/service.yaml
resources/charts/dataspace-connector/values.yaml
samples/04.0-file-transfer/README.md
samples/04.0-file-transfer/consumer/build.gradle.kts
samples/04.0-file-transfer/integration-tests/minikube/README.md
samples/04.0-file-transfer/integration-tests/minikube/minikube-test.sh
samples/04.0-file-transfer/integration-tests/minikube/values-consumer.yaml
samples/04.0-file-transfer/integration-tests/minikube/values-provider.yaml
samples/04.0-file-transfer/integration-tests/src/test/java/org/eclipse/dataspaceconnector/samples/FileTransferAsClientIntegrationTest.java
samples/04.0-file-transfer/integration-tests/src/test/java/org/eclipse/dataspaceconnector/samples/FileTransferIntegrationTest.java
samples/04.0-file-transfer/integration-tests/src/test/java/org/eclipse/dataspaceconnector/samples/FileTransferTestUtils.java
samples/04.0-file-transfer/provider/build.gradle.kts
samples/04.1-file-transfer-listener/README.md

A [Helm Chart](https://helm.sh) is provided to be used to deploy the EDC runtime in Kubernetes environments.
The chart is highly configurable:
- Configurable runtime based on Docker image of base EDC, Data Plane Framework Server, or custom runtime.
- Configurable environment variables (as [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/)) for runtime settings, following [12-factor principles](https://12factor.net/config).
- Configurable secrets (injected as environment variables into pods).
- Configurable labels and annotations.
- Configurable ingress.
The chart was generated using `helm create` in order to follow best practice for components, configurability and ingress definitions, and adapted to fit the EDC runtime.
A generic Dockerfile was created that builds a …

Helm chart with minikube tests (#432)

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartCatalogDescriptionRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractAgreementSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractRejectionSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartDescriptionRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSenderTest.java

It changes the scope used to request a token in the `IdsMultipartSender`. Previously, the ID of the recipient connector was used here instead of `idsc:IDS_CONNECTOR_ATTRIBUTES_ALL`.
As defined [here](https://github.com/International-Data-Spaces-Association/IDS-G/tree/main/Components/IdentityProvider/DAPS/#request-call-to-get-a-token), the DAPS expects the scope to be `idsc:IDS_CONNECTOR_ATTRIBUTES_ALL` for a token request. 
In order to limit the token to certain connectors, the `aud` field should be used as stated [here](https://github.com/International-Data-Spaces-Association/IDS-G/tree/main/Components/IdentityProvider/DAPS/#request-token-that-is-handed-in-at-daps-side). Though at the moment, this feature is not supported by the DAPS.
Changing the scope for the token request eliminates …

Use correct scope for obtaining token in IdsMultipartSender

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/LoaderImpl.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/CachedAsset.java

- Adds the `originator` to `CachedAsset`s, which are used during catalog queries
- Provides dummy values for `ContractOffer#provider` and `ContractOffer#consumer`, which is a quick workaround for issue #753 
During testing with the [EDC Showcase](https://github.com/microsoft/edc-showcase) I noticed some minor bugs.
Relates to #753

Fixes some minor (and some less minor) bugs

---

common/util/build.gradle.kts
common/util/src/testFixtures/java/org/eclipse/dataspaceconnector/common/testfixtures/TestUtils.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerIntegrationTest.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionsApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyApiControllerIntegrationTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/TransferProcessApiControllerIntegrationTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/loader/LoaderManagerImplTest.java
extensions/data-plane/data-plane-http/build.gradle.kts
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/DataSourceToDataSinkTests.java
extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyRestServiceTest.java
extensions/http/jetty/build.gradle.kts
extensions/http/jetty/src/test/java/org/eclipse/dataspaceconnector/extension/jetty/JettyServiceTest.java
extensions/iam/decentralized-identity/identity-did-web/build.gradle.kts
extensions/iam/decentralized-identity/identity-did-web/src/test/java/org/eclipse/dataspaceconnector/iam/did/web/resolution/WebDidResolverTest.java
extensions/iam/oauth2/oauth2-core/build.gradle.kts
extensions/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/Oauth2ServiceImplTest.java
extensions/ion/ion-client/build.gradle.kts
extensions/transfer-functions/transfer-functions-core/build.gradle.kts
extensions/transfer-functions/transfer-functions-core/src/test/java/org/eclipse/dataspaceconnector/transfer/functions/core/flow/http/HttpDataFlowControllerTest.java
extensions/transfer-functions/transfer-functions-core/src/test/java/org/eclipse/dataspaceconnector/transfer/functions/core/flow/http/HttpStatusCheckerTest.java

This PR introduces diverse fixes for unstable tests.
It seems the introduction of Jacoco (https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/702) has increased test time by ~50%, which might cause some timeouts or race conditions to be hit.
- Multiple tests using OkHttp client have been fixed. Default timeouts are quite short and they were increased.
- `LoaderManagerImplTest#batchSizeNotReachedWithinTimeframe` was using a queue with 3 elements, which was not testing what was intended ("Verify that the loader manager waits one pass when the queue does not yet contain sufficient elements"), as 3 is exactly the limit for the LoaderManager to start processing. This processing took sometimes longer than the configured 100ms timeout, making the test fail.
This should solve 16 …

Fix unstable tests in CI

---

extensions/catalog/federated-catalog-cache/build.gradle.kts
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheEndToEndTest.java

This PR complements #735 by fixing a further test that was using OkHttp with default timeouts.

Use OkHttpClient with enhanced timeouts in FederatedCatalogCacheEndToEndTest

---

data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/ControlApiServiceExtension.java
extensions/api/observability/src/main/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApiExtension.java
extensions/api/observability/src/test/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApiExtensionTest.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyRestService.java
extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtensionTest.java
extensions/iam/decentralized-identity/registration-service-api/src/main/java/org/eclipse/dataspaceconnector/samples/identity/registrationservice/api/RegistrationServiceApiExtension.java
samples/02-health-endpoint/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthEndpointExtension.java
samples/03-configuration/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthEndpointExtension.java
samples/04.0-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
samples/04.0-file-transfer/provider/build.gradle.kts
samples/05-file-transfer-cloud/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
samples/other/streaming/src/main/java/org/eclipse/dataspaceconnector/transfer/demo/protocols/DemoProtocolsTransferExtension.java
spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/WebService.java

this Pull request
* removes a deprecated method (registerController) and replaces usages with the supported method
* removes components that are not used from the 04-file-transfer example

rename registerController->registerResource, remove deprecated method

---

CONTRIBUTING.md

Added a section to `CONTRIBUTING.md` about reporting flaky tests.
All contributors should be on the lookout for potential SW quality issues. This addition makes sure no-one can claim ignorance.
Closes #768

Added section about flaky tests

---

samples/04.0-file-transfer/README.md

It changes the path to the `contractoffer.json` in sample 04.0's README.
Currently, the path `client/src/main/resources/contractoffer.json` is stated in the README, but does not exist in the sample.

sample: update path to contractoffer.json in README

---

.github/workflows/integrationtests.yaml
docs/integration-testing.md
extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/CosmosTestClient.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/TestFunctions.java

Use Cosmos DB Emulator in CI. The integration test pipeline currently runs only in upstream main, as it requires access to an Azure Cosmos DB instance. This now runs the pipeline in every PR.
This allows fully validating changes that affect the Cosmos DB related extensions *before* merging to upstream main, rather than *after*.
One test had a logical issue due to incomplete data cleanup, and was fixed.
Pipeline was run 100 times without failures.
Use gradle-build-action as it does a better job of caching than setup-java, to accelerate the pipeline in most runs (from 12 min without cache to 6 min)
Closes #360

CI: Use Cosmos DB Emulator

---

docs/developer/dependency_resolution.md

Adds developer documentation about dependency resolution and registration.
On several occasions we've noticed that the dependency resolution mechanism was used incorrectly, so adding the relevant documentation aims to alleviate that.
Does not include detailed documentation about the `ObjectFactory`, the `Injector` or the `InjectionPointScanner` to keep the scope of the document focused on the high-level concepts.
Closes #775 
_not relevant_

Adds documentation about dependency resolution

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

Add an issue template for a bug report. Additionally add important links to submit feature requests, ask for help, or find the documentation.
This improves the way of contributing to the project. We used this in the DSC project before (see screenshot below). It helps to guide people to the right links. I enabled blank issues so it should be possible to add an issue without using a template (in DSC, we turned it off).
Please note that our issue page will look differently as I modified the content.

feat: add issue template

---

.github/PULL_REQUEST_TEMPLATE.md

Adds checkboxes for changelog updates and project linking to the pull request template.
To remind people of addressing those topics when opening a pr.
Needs to be merged after #772 as this introduces the changelog.

chore: add changelog and project changes to PULL_REQUEST_TEMPLATE.md

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsContractAgreementToContractAgreementTransformer.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/ContractAgreementToIdsContractAgreementTransformerTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
extensions/in-memory/negotiation-store-memory/src/test/java/org/eclipse/dataspaceconnector/negotiation/store/memory/TestFunctions.java

Contract dates should be in epoch seconds. Where this is not the case the PR fixes it.
This is necessary for the IDS-Serializer update, which validate the dates.
-
Relates #236

Fix dates to epoch seconds, related #236

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/check-changelog.yaml

Adds an action that checks for changelog modifications.
As an addition to the reminder in the pull request template, the pipeline checks the changelog for changes. If there are none, a warning is displayed. Continue on error is set to true.

ci: add action to check changelog modifications

---

extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSource.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSourceFactory.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSourceTest.java

This improve some unit-tests for `HttpDataSource` and `HttpDataSourceFactory` classes. Especially it adds a step that verifies the actual content of the `HttpDataSource` generated by the factory.

refactor: Improve unit test for HttpDataSource and HttpDataSourceFactory

---

CHANGELOG.md
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreExtension.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/model/ContractDefinitionDocument.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/TestFunctions.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/model/ContractDefinitionDocumentSerializationTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreExtension.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/ContractNegotiationDocument.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/ContractNegotiationDocumentSerializationTest.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/AbstractCosmosConfig.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/CosmosDocument.java
extensions/azure/cosmos/fcc-node-directory-cosmos/src/test/java/org/eclipse/dataspaceconnector/catalog/node/directory/azure/CosmosFederatedCacheNodeDirectoryIntegrationTest.java
extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java

Harmonizes the usage of partition keys across all subclasses of `CosmosDocument`: partition keys must be static and should be passed in from "the outside", e.g. the connector ID or a configured value. 
This effectively causes all documents to be put into a single logical partition. 
There was a variety of approaches to partition keys, e.g. the `ContractDefinitionDocument` used an `accessPolicyId`. 
This could produce unexpected results, even bugs, e.g. updating the access policy would move the document into another logical partition, even causing it to get ignored by the SPROC.
- Our initial plan to use the document ID turned out to be impossible, because there is no way to execute stored procedures across logical partitions, specifically the `nextForState` SPROC would then become …

CosmosDB: Use static partition key for all `CosmosDocuments`

---

.github/workflows/integrationtests.yaml
CHANGELOG.md
extensions/aws/aws-test/build.gradle.kts
extensions/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/AbstractS3Test.java

Adds a HTTP call to evaluate MinIO's [health endpoint](https://docs.min.io/minio/baremetal/monitoring/healthcheck-probe.html), retries every 2 seconds for at most 10 seconds.
When the Github runner starts the MinIO container and simultaneously launches the test, sometimes this causes the AWS S3 StatusChecker test to fail with strange errors due to MinIO not completely booted.
- The wait loop uses Awaitility, as we already have that in our test environment
- The names of the MinIO credentials were also updated, as the old ones are deprecated
Closes #795

Added health probe to wait for MinIO

---

CHANGELOG.md
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
data-protocols/ids/ids-transform-v1/build.gradle.kts
data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsTransformServiceExtension.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/IdsTransformServiceExtensionTest.java
docs/developer/dependency_resolution.md
extensions/api/observability/src/main/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApiExtension.java
extensions/api/observability/src/test/java/org/eclipse/dataspaceconnector/api/observability/ObservabilityApiExtensionTest.java
extensions/iam/decentralized-identity/identity-did-core/build.gradle.kts
extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtensionTest.java
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/DependencyInjectionExtension.java
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java

Created a JUnit extension to provide lightweight dependency injection (DI) services for unit tests.
Need for mocking private fields that are injected by the DI container.
Refactored relevant tests that were relying on dedicated constructors to circumvent the DI mechanism.
Closes #817

DI test harness

---

CHANGELOG.md
extensions/api/data-management/asset/build.gradle.kts
resources/openapi/openapi.yaml
resources/openapi/yaml/asset.yaml

Adds the `swagger-gradle-plugin` to the `asset-api` module.
Adds the generated `assets.yaml`
Updates the aggregate `openapi.yaml`
Because the api of the Asset Data Management controller needs to be documented.
-
-

Add missing Assets controller openapi

---

system-tests/tests/build.gradle.kts
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferLocalSimulation.java

Exclude unnecessary Gatling dependencies that are pulled in.
Also relaxes an assertion that I observed to be violated in one run.
Accelerate the build.
Closes #829

Performance tests: Exclude some Gatling transitive dependencies

---

.github/workflows/integrationtests.yaml
CHANGELOG.md
extensions/aws/aws-test/README.md
extensions/aws/aws-test/src/testFixtures/java/org/eclipse/dataspaceconnector/aws/testfixtures/AbstractS3Test.java
extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3ClientProvider.java
extensions/aws/s3/s3-core/src/main/java/org/eclipse/dataspaceconnector/aws/s3/core/S3ClientProviderImpl.java
extensions/aws/s3/s3-data-operator/build.gradle.kts
extensions/aws/s3/s3-data-operator/src/main/java/org/eclipse/dataspaceconnector/aws/s3/operator/S3BucketReader.java
extensions/aws/s3/s3-data-operator/src/main/java/org/eclipse/dataspaceconnector/aws/s3/operator/S3BucketWriter.java
extensions/aws/s3/s3-data-operator/src/test/java/org/eclipse/dataspaceconnector/aws/s3/operator/S3DataOperatorIntegrationTest.java
samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java

In the process of deploying an EDC to transfer data from an S3 bucket to another we noticed that the data cannot be read because the `S3BucketReader` is a dummy implementation.
An implementation of `S3BucketReader`. a `S3ClientProvider` was introduced upfront to permit testability.

extensions: implement S3BucketReader

---

.github/workflows/verify.yaml

Adds a step on the `Test Code` workflow that will publish and show test results on github action user interface in this way:
It will be more easy to understand which test failed and why instead of having to go through all the gradle output
-
Closes #849

publish test results

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Adds an issue template for feature requests and provides a link to blank issues.
To make people's lives easier.
Closes #841

chore: add issue template for feature requests

---

CHANGELOG.md
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
extensions/azure/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStore.java
extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java
extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/TestHelper.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
extensions/in-memory/transfer-store-memory/src/main/java/org/eclipse/dataspaceconnector/transfer/store/memory/InMemoryTransferProcessStore.java
extensions/in-memory/transfer-store-memory/src/main/java/org/eclipse/dataspaceconnector/transfer/store/memory/TransferProcessPredicateConverter.java
extensions/in-memory/transfer-store-memory/src/test/java/org/eclipse/dataspaceconnector/transfer/store/memory/InMemoryTransferProcessStoreTest.java
extensions/in-memory/transfer-store-memory/src/test/java/org/eclipse/dataspaceconnector/transfer/store/memory/TestFunctions.java
extensions/in-memory/transfer-store-memory/src/test/java/org/eclipse/dataspaceconnector/transfer/store/memory/TransferProcessPredicateConverterTest.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/store/TransferProcessStore.java

1. Adds a `findAll(QuerySpec spec)` method, which returns all TPs covered by a specific query
2. Removes a couple of methods, that were not implemented anywhere. 
ad 1. This is necessary because the Data Management API allows for querying TPs. This impl apparently slipped through the cracks in Milestone 2.
ad 2. The methods that were removed always threw an `UnsupportedOperationException`. Better not to have dead code.
n/a
Closes #859

cleanup(TransferProcessStore): add `findAll` and remove unneeded methods

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/issue-auto-assign-project.yaml
.github/workflows/pull-request-auto-assign-project.yaml

Adds an action to auto assign issues and pull requests to the basic project. Fixes formatting of checklist in pr template (see below).
Avoids having to do this manually as long as there is only one GitHub project.
and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) 
for details_)

ci: add action to auto assign issues and pull requests to project

---

docs/developer/dpf_selector.md

Adds a document outlining the technical aspects of the DPF selector.
Once this PR is accepted, this technical concept will serve as documentation for the DPF selector feature, after some linguistic adaptations, ofc.
Class names, method signatures etc. should be regarded as "preliminary", they may change until the finished implementation.
Changelog entry will be added during the implementation PR.
Contributes to #832

DPF Selector: add technical concept

---

CHANGELOG.md
extensions/azure/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndex.java
extensions/azure/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexExtension.java
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexTest.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/CosmosDbApi.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/CosmosDbApiImpl.java
extensions/azure/cosmos/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/cosmos/azure/CosmosDbApiImplIntegrationTest.java
extensions/dataloading/src/main/java/org/eclipse/dataspaceconnector/dataloading/AssetLoader.java
extensions/in-memory/assetindex-memory/src/main/java/org/eclipse/dataspaceconnector/metadata/memory/InMemoryAssetIndex.java
extensions/in-memory/assetindex-memory/src/test/java/org/eclipse/dataspaceconnector/metadata/memory/InMemoryAssetIndexTest.java
extensions/in-memory/assetindex-memory/src/test/java/org/eclipse/dataspaceconnector/metadata/memory/InMemoryDataAddressResolverTest.java

- Added deleteById method in AssetLoader interface
- Implemented method for AssetLoader implementations (inMemory & CosmosDB implementations)
Part of the issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/801. This is needed for the Data Management API.
- Updated contract of CosmosDbApi.deleteItem to return the item, to avoid querying the item twice.
- Added Monitor dependency to CosmoAssetIndex to be able to log when an item is not found.
Closes #801

Dataloading extension: Add deleteById to AssetLoader.

---

.github/workflows/pull-request-auto-assign-project.yaml

Adds permission to action.
Currently, the action that should assign a new PR to a project fails:
```
{
"message": "Resource not accessible by integration",
"documentation_url": "https://docs.github.com/rest/reference/projects#create-a-project-card"
}
```
This issue seems to be known and a possible solution ist mentioned (https://github.com/actions/first-interaction/issues/10). Worth a try.

fix(action): add permissions to pull-request-auto-assign-project.yaml

---

.github/workflows/verify.yaml
CHANGELOG.md
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
extensions/in-memory/negotiation-store-memory/src/main/java/org/eclipse/dataspaceconnector/negotiation/store/memory/InMemoryContractNegotiationStore.java
extensions/in-memory/negotiation-store-memory/src/test/java/org/eclipse/dataspaceconnector/negotiation/store/memory/InMemoryContractNegotiationStoreTest.java
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcRuntimeExtension.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/negotiation/ContractNegotiation.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/negotiation/ContractNegotiationStates.java
system-tests/e2e-transfer-test/control-plane/src/main/java/org/eclipse/dataspaceconnector/test/e2e/ControlPlaneTestController.java
system-tests/e2e-transfer-test/runner/build.gradle.kts
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/EndToEndTransferTest.java
system-tests/tests/build.gradle.kts

Migrate all the state transition to the 2-state pattern as described in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/825 for `ContractNegotiationManager`s
Use the 3-state pattern could lead to problems, described in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/825
the `CONFIRMING_SENT` status has been removed since it's not needed anymore
I had to implement a lease mechanism into the `InMemoryContractNegotiationStore` (for the cosmos implementation was already done in #724)
I add the `-quiet` parameter to the gradle test task, to avoid printing the system tests logs on the pipeline
Fix #825 (supposing that #831 would be merged before this)

core: apply 2-state transition pattern to ContractNegotiationManagers

---

CHANGELOG.md
core/contract/README.md
core/contract/build.gradle.kts
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationManager.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/transfer/README.md
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStore.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/persistence/StateEntityStore.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/store/TransferProcessStore.java

Add configuration settings to set the batch size of the state machines:
- `edc.negotiation.consumer.state-machine.batch-size`: `ConsumerContractNegotiationManagerImpl`
- `edc.negotiation.provider.state-machine.batch-size`: `ProviderContractNegotiationManagerImpl`
- `edc.transfer.state-machine.batch-size`: `TransferProcessManagerImpl`
As stated in #393 currently the batch size is hard-coded, adding settings will permit more fine-grained configuration of the EDC
Extracted `StateMachineStore` interface that is extended by `TransferProcessStore` and `ContractNegotiationStore`, this will permit to have a unique documentation point for `nextForState`, and in the future could lead to a stronger abstraction that could avoid further duplications.
Extracted `AbstractContractNegotiationManager` that …

core: give possibility to configure state machine batch sizes

---

docs/testing.md
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcRuntimeExtension.java
system-tests/e2e-transfer-test/runner/build.gradle.kts
system-tests/tests/build.gradle.kts

Makes the `EdcRuntimeExtension` load the resources of an "extension runtime" from the `main` folder.
Currently, there are two way of handling extension runtime dependencies: 
- not define them into the "runner/tests" module as dependency (as it's done by the `system-tests:end-to-end-transfer:runner` module)
- define them as `testRuntimeOnly` (as it's done by the `system-tests:tests` module)
both of them are wrong, for these reasons:
- the first because it does not define a "build" order for the modules, so you must have every extension runtime module built by the test run, otherwise the extension runtimes will not be loaded.
- the second because it loads all the dependencies of the extension runtimes into the common class loader, and so every extension runtime will have the union of the …

system-tests: avoid system-tests failure when runtimes are not fully built

---

CHANGELOG.md
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
extensions/in-memory/contractdefinition-store-memory/src/main/java/org/eclipse/dataspaceconnector/contractdefinition/store/memory/InMemoryContractDefinitionStore.java
extensions/in-memory/contractdefinition-store-memory/src/test/java/org/eclipse/dataspaceconnector/contractdefinition/store/memory/InMemoryContractDefinitionStoreTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java

- Updated the contract of ContractDefinitionStore.delete to return the deleted ContractDefinition.
- Updated the name of the method `delete` to `deleteById` for consistency with other service and correspond to the story definition.
Part of task #802.
Closes #802

spi: Return the deleted ContractDefinition when deleting ContractDefinition.

---

extensions/sql/policy/docs/er.puml
extensions/sql/policy/docs/schema.sql
extensions/sql/policy/sql_policy_store_proposal.md

Signed-off-by: Brendan Cronin <brendan.cronin@mercedes-benz.com>
Design proposal for SQL implementation of PolicyStore. Simplified implementation for PolicyStore::findAll, limiting QuerySpec to Limit and Offset functionality for now.
Prepares #866
Brendan Cronin brendan.cronin@mercedes-benz.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)

SQL: Design Proposal for SQL Policy Store

---

docs/developer/decision-records/2022-03-11-story-issues/README.md
docs/developer/decision-records/2022-03-11-umbrella-issues/README.md

Adds a decision-record about the use of "story" issues, a.k.a. umbrella issues.
A decision was made to use task lists in issues, which greatly improves the structure of work, keeps PRs clean and succinct and makes code reviews easier and more easily digestible.
n/a
n/a

doc(decision): document use of "story" issues

---

data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractAgreementHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractOfferHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRejectionHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/Handler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/NotificationMessageHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/AbstractDescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ArtifactDescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ConnectorDescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/DataCatalogDescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/DescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/RepresentationDescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ResourceDescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/message/MultipartRequest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/NotificationMessageHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/DescriptionHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/RepresentationDescriptionRequestHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/description/ResourceDescriptionRequestHandlerTest.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImpl.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImpl.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImplTest.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/CatalogService.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/ConnectorService.java

Simplify interfaces of `CatalogService` and `ConnectorService` passing a `ClaimToken` object instead of a wrapping `Result`.
It's a simple refactor that simplifies things, and avoids to carry around a `Result` object after it has already been evaluated.
*
Closes #373

refactor: Simplify CatalogService and ConnectorService interfaces

---

CHANGELOG.md
samples/04.3-open-telemetry/README.md
samples/04.3-open-telemetry/docker-compose.yaml
samples/04.3-open-telemetry/logging.properties
samples/04.3-open-telemetry/provider/build.gradle.kts
settings.gradle.kts

- Fixed sample 04.3 that was broken (env variables should now be in UPPER_CASE; issue with ports/API Key configuration)
- Fixed instructions for using Application Insights with the sample
- Used `jdk-logger-monitor` in the sample so that monitor logs are exported to java.util.logging, and from there captured by the Application Insights agent if used
- Sample was broken
- Azure users need a sample for Application Insights
Closes #861

Samples: fixed Observability Sample, added instructions for Azure Application Insights

---

CHANGELOG.md
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationIntegrationTest.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
extensions/azure/events/src/main/java/org/eclipse/dataspaceconnector/events/azure/AzureEventGridPublisher.java
samples/04.1-file-transfer-listener/listener/src/main/java/org/eclipse/dataspaceconnector/extensions/listener/MarkerFileCreator.java
samples/other/run-from-junit/src/test/java/org/eclipse/dataspaceconnector/junit/ConsumerRunner.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/observe/ContractNegotiationListener.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/observe/TransferProcessListener.java

- Call the listeners before the state transition is persisted.
- Add  _confirmingSent_ method to ContractNegotiationListener
A custom extension may need to perform custom processing after a data transfer has reached a certain stage.
Triggering custom logic on TransferProcess state changes requires registering a TransferProcessListener. However listeners are not guaranteed to be called, e.g. if the instance crashes after persisting the state change but before invoking the listener. Custom logic in the listener can be crucial for the functioning of client applications, thus EDC needs to guarantee that these are called before advancing a transfer process to the next state is made durable.
- calling observable (_observable.invokeForEach(observe)_) and saving negotiation/transferProcess were …

core: Call the listeners before the state transition is persisted

---

CHANGELOG.md
data-protocols/ids/ids-api-configuration/build.gradle.kts
data-protocols/ids/ids-api-configuration/src/main/java/org/eclipse/dataspaceconnector/ids/api/configuration/IdsApiConfigurationExtension.java
data-protocols/ids/ids-api-configuration/src/test/java/org/eclipse/dataspaceconnector/ids/api/configuration/IdsApiConfigurationExtensionTest.java
extensions/http/jetty/build.gradle.kts
extensions/http/jetty/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyExtension.java
extensions/http/jetty/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyService.java
spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/WebServer.java

It adds an interface `WebServer` to the `web-spi` module. The interface is implemented by the `JettyService`.
The `ids-api-configuration` module adds an API context, even if it is not defined in the `config.properties`. It therefore needs to access the `JettyService` and currently has a dependency on the `http` extension. Adding the interface allows for removing this dependency, as the API context can now be added via the interface.
Besides the method for adding a new port mapping, the `JettyService` also contains a public method `void registerServlet(String contextName, Servlet servlet)`. It might make sense to move this to the `WebServer` interface, too, but as the second parameter is a `jakarta.servlet.Servlet`, this would require adding a dependency to the `web-spi`'s build file. …

web-spi: add WebServer interface

---

gradle.properties

Removes the gradle workers settings
These settings are raising problems on different developers machines
* Seems like the build time without the parameters is pretty much the same as with (on my repo the `Test Code` task took 15m, that's pretty much the average time it took with the parameters set. parallelism is not always a solution :) )
Closes #958
Superseds #897

gradle: remove workers configuration settings

---

.github/workflows/integrationtests.yaml
CHANGELOG.md
docs/testing.md
extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/CosmosTestClient.java
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java

Run Cosmos DB tests on a cloud instance in CI, instead of emulator.
As a result PRs from forks are not automatically tested in CI. Contributors should run CI on their fork, and post a link to the successful build in the PR.
Successful run: https://github.com/agera-edc/DataSpaceConnector/actions/runs/2038470930
Emulator is not reliable running in GitHub agent.
Adapted one unit test for portability, since deleteAllItemsByPartitionKey is disabled by default on new Cosmos DB accounts.
Closes #845

Integration tests: Run CosmosDB integration tests on cloud in CI

---

samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java

It updates the permission in the `transfer-file` module of sample 04.0. It changes the permission's action from `idsc:USE` to `USE` and adds a permission target.
Currently, upon description request the transformer throws an error when transforming the permission from sample 4 due to a missing target and an unknown action type. While the description request is not required for sample 4 to run successfully, people might look at this sample and define their policies in the same way, which would then lead to these errors.

sample 4: update permission

---

CHANGELOG.md
extensions/sql/contract-definition/store/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
extensions/transaction/transaction-atomikos/src/main/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionContext.java
extensions/transaction/transaction-local/src/main/java/org/eclipse/dataspaceconnector/transaction/local/LocalTransactionContext.java
extensions/transaction/transaction-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transaction/NoopTransactionContext.java
extensions/transaction/transaction-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transaction/TransactionContext.java

overloads the `TransactionContext#execute()` method to be able to return a result. 
This is useful when wrapping read-calls in transactions, because it gets rid of having to declare an `AtomicReference`.
An explicit functional interface `ResultTransactionBlock` was also declared to maintain consistency.
none

Feature: adds `execute` method with result to the `TransactionContext`

---

core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/commands/AddProvisionedResourceCommand.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/AddProvisionedResourceCommandHandler.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/AddProvisionedResourceCommandHandler.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/ProvisionCompletionDelegate.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java

This PR lays the foundation for supporting out-of-process provisioning requests, for example, via HTTP.

feature: Implement callback command

---

common/state-machine-lib/src/test/java/org/eclipse/dataspaceconnector/common/statemachine/StateMachineTest.java

Fix a flaky test
After #912 one test of `StateMachineTest` stated breaking randomly, caused by the change of the order of calling `waitStrategy.success` and `waitStrategy.waitForMillis`
-
-

test: fix flaky test

---

extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/DtoTransformerRegistryImpl.java
extensions/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/transformer/DtoTransformerRegistryImplTest.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApi.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiController.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiExtension.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/model/ContractAgreementDto.java
extensions/api/data-management/contractagreement/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerIntegrationTest.java
extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerTest.java
extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/model/ContractAgreementDtoTest.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/DataRequestDto.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDto.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDto.java
extensions/api/data-management/transferprocess/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiApiControllerTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDtoTest.java

Fix package names as well as class names in comments. Presumably several packages were cookie-cut from "contractdefinition", after which the package name needs to be updated.

Data management: fix package names

---

core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/provision/ResourceManifestGeneratorImpl.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/provision/ResourceManifestGeneratorImplTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplIntegrationTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/build.gradle.kts
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/AwsProvisionExtension.java
extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3ConsumerResourceDefinitionGenerator.java
extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/AzureProvisionExtension.java
extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGenerator.java
extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGeneratorTest.java
samples/other/run-from-junit/src/test/java/org/eclipse/dataspaceconnector/junit/EndToEndTest.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ConsumerResourceDefinitionGenerator.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ProducerResourceDefinitionGenerator.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ProviderResourceDefinitionGenerator.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ResourceManifestGenerator.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResource.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcess.java
spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResourceTest.java
spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessTest.java

In order to support HTTP-based data provisioning (https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/963), it must be possible for the provisioner to supply the EDC control plane with a data address to resolve generated data. This backend-supplied data address is a Content Data Address as described in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/976.
See #977
Closes #977

feature:content addresses

---

.github/workflows/verify.yaml
build.gradle.kts

- Do not run unit tests in quiet mode, as this prevents the name of failing (flaky) tests to be shown in build log.
- Avoid having two `tasks.withType<Test>` blocks for clarity.

Unit testing: fix configuration

---

core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoader.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContextTest.java
core/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoaderTest.java
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
samples/other/custom-runtime/src/main/java/org/eclipse/dataspaceconnector/demo/runtime/CustomRuntime.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtensionContext.java

Moves the extension loading logic from the `DefaultServiceExtensionContext` to `ExtensionLoader`
Currently `DefaultServiceExtensionContext` do a lot of things, and it's not clear why it has to load extension too. On the other hand, the `ExtensionLoader` is just a static methods container, and it seems the best place to put this kind of logic.
* had to put a pair of class cast on `EdcRuntime` because it has no other way to know that it has a `MultiSourceServiceLocator` service locator instance. Adding a generic class parameter to `BaseRuntime` seems a bit too much, but feedback is welcome.
-

core: move extension loading logic from ServiceExtensionContext to ExtensionLoader

---

CHANGELOG.md
extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/SqlTransferProcessStoreExtension.java
extensions/sql/transfer-process-store/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresStatements.java
extensions/sql/transfer-process-store/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension

Adds the previously forgotten service extension to register the SQL TPS.
It wasn't there before.
n/a
Closes #1027

Bugfix: adds extension to register SQL TPS

---

.github/workflows/codeql-analysis.yml
.github/workflows/generate_openapi_spec.yaml
.github/workflows/integrationtests.yaml
.github/workflows/verify.yaml

Workflow files now ignore changes to the `/docs` and root `.md` files. CodeQL, OpenApi generation, (unit and integration) tests, and style checks will therefore not be (re-)run if changes are made to those files.
Prevents the unnecessary consumption of resources and waste of time. E.g. when merge conflicts in the `CHANGELOG.md` are resolved, the pipeline does not need to be triggered again.
Closes #1023

ci: add paths ignore to workflow files

---

samples/05-file-transfer-cloud/README.md

It changes the URL used for obtaining the agreement ID after initiating a contract negotiation in sample 5's README.
The URL currently used for getting the agreement points to the endpoint for getting agreements by their ID. Using the negotiation ID as stated in the README, it always returns 404, as no agreement with that ID exists.

sample 5: change request to get agreement id

---

CHANGELOG.md
extensions/sql/asset/index/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/PostgresSqlAssetQueries.java
extensions/sql/asset/index/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetIndex.java
extensions/sql/asset/index/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetQueries.java
extensions/sql/asset/index/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetTables.java
extensions/sql/asset/index/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlConditionExpression.java
extensions/sql/asset/index/src/test/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetIndexTest.java
extensions/sql/asset/index/src/test/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlConditionExpressionTest.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/AssetSelectorExpression.java

Adds support for `QuerySpec` filtering and `AssetSelectorExpression`, i.e. filtering on Asset properties.
This is necessary for generating and validating `ContractOffer`s.
- Currently not all operators support prepared statements, e.g., the `IN` operator.
- sorting is not yet implemented
Closes #1014

AssetIndex: add support for `QuerySpec` filtering

---

extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/transformer/DtoTransformerRegistryImpl.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestToDataRequestDtoTransformer.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformer.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtensionTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestToDataRequestDtoTransformerTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestTransformerTestData.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformerTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessTransformerTestData.java

Add a transformer from TransferProcess to its DTO, for controllers in the Data Management API to expose transfer process information.
#809 implementation was split into this PR and PR #1005.
Data Management API surface
Relates to #809

Data Management API: Created TransferProcess transformers

---

CHANGELOG.md
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Duty.java
core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Permission.java
core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Policy.java
core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Prohibition.java
core/policy/policy-evaluator/src/test/java/org/eclipse/dataspaceconnector/policy/model/DutyTest.java
core/policy/policy-evaluator/src/test/java/org/eclipse/dataspaceconnector/policy/model/PermissionTest.java
core/policy/policy-evaluator/src/test/java/org/eclipse/dataspaceconnector/policy/model/PolicyTest.java
core/policy/policy-evaluator/src/test/java/org/eclipse/dataspaceconnector/policy/model/ProhibitionTest.java
samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
samples/05-file-transfer-cloud/data-seeder/src/main/java/org/eclipse/dataspaceconnector/sample5/data/seeder/FakeSetup.java

It sets the target for policies and rules to the corresponding asset ID when `ContractOffers` are created.
At the moment, a `ContractDefinition's` contract policy is added to the `ContractOffer` as is. If the target of a rule is missing, this leads to errors during transformation. Therefore, it is currently required that a fixed target is set for each rule.
The static target has been removed from the rules created in samples 04.0 and 05, as the target will now be added when `ContractOffers` are requested.
Closes #609

contract offers: add asset id as policy and rule target

---

CHANGELOG.md
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
extensions/http-provisioner/build.gradle.kts
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/AbstractHttpResourceDefinition.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/ConfigParser.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderProvisioner.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderResourceDefinition.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderResourceDefinitionGenerator.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProvisionedContentResource.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProvisionerExtension.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProvisionerRequest.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/ProvisionerConfiguration.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/ConfigParserTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderProvisionerTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderResourceDefinitionGeneratorTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderResourceDefinitionTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProvisionerExtensionEndToEndTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProvisionerFixtures.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProvisionerRequestTest.java
settings.gradle.kts
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionResponse.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResource.java
spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResourceTest.java

This PR implements the HTTP Provisioner as described by #963.
The API callback endpoint and support for token-based authorization will be added by @paullatzelsperger in a subsequent PR. 
Closes #963

feature: Implement HTTP Provisioner

---

.github/workflows/verify.yaml
build.gradle.kts
resources/edc-checkstyle-config.xml

This reverts commit 5f523dcf1233451ca2932855098c70baf2854de1.
Revert the header checkstyle rule for now. We realized that the rule is too strict. PR with unrelated changes are failing.
We want to revert it for now to avoid disturbing opening of PRs.
We will come with a better solution later.

Revert "ci: add checkstyle rule for Java file headers (#997)"

---

CHANGELOG.md
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/IdsContractAgreementToContractAgreementTransformer.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/ContractAgreementToIdsContractAgreementTransformerTest.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/ContractAgreementToContractAgreementDtoTransformer.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationServiceImplTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/ContractAgreementToContractAgreementDtoTransformerTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/ContractNegotiationToContractNegotiationDtoTransformerTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
extensions/in-memory/negotiation-store-memory/src/test/java/org/eclipse/dataspaceconnector/negotiation/store/memory/TestFunctions.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/sql/contract-negotiation-store/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/SqlContractNegotiationStoreExtensionTest.java
extensions/sql/contract-negotiation-store/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/TestFunctions.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/agreement/ContractAgreement.java

Replaces `Asset` with `assetId` on `ContractAgreement`
Simplifies object structure, avoid data duplication.
-
Point 1. of #828

refactor: replace Asset with assetId on ContractAgreement

---

core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/TestProvisionedDataDestinationResource.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisionedResource.java
extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisioner.java
extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisionedResourceTest.java
extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3StatusCheckerIntegrationTest.java
extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerProvisionedResource.java
extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisioner.java
extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerProvisionedResourceTest.java
extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerStatusCheckerIntegrationTest.java
extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisionerTest.java
extensions/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderProvisioner.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/HttpProviderProvisionerTest.java
samples/04.2-modify-transferprocess/simulator/src/main/java/org/eclipse/dataspaceconnector/samples/sample042/TransferSimulationExtension.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResource.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedDataAddressResource.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedDataDestinationResource.java
spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ProvisionedContentResourceTest.java

This PR adds a `ProvisionedDataAddressResource` and creates a class hierarchy for data address resources. This consolidates common properties and simplifies the `TPM`.
It simplifies the codebase.

chore: Provisioning types cleanup

---

core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
core/micrometer/src/main/java/org/eclipse/dataspaceconnector/metrics/micrometer/MicrometerExecutorInstrumentation.java
core/micrometer/src/main/java/org/eclipse/dataspaceconnector/metrics/micrometer/MicrometerExtension.java
extensions/azure/data-plane/storage/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/DataPlaneAzureStorageExtension.java
extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImpl.java
extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtensionTest.java
extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/e2e/EndToEndTest.java
extensions/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImplTest.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpExtension.java
extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/DataTransferExecutorServiceContainer.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ExecutorInstrumentation.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ExecutorInstrumentationImplementation.java

Share a thread pool across all DPF transfers. Made number of threads configurable.
Instrument the thread pool with metrics.
This allows better control of resources.
Had to introduce `ExecutorInstrumentationImplementation` class for better control of optional dependencies.
Closes #618

DPF: share thread pool

---

core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/util/CyclicDependencyException.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/util/TopologicalSort.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/azure/azure-test/README.md
extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/DataTransferExecutorServiceContainer.java
launchers/data-loader-cli/README.md
launchers/data-loader-cli/src/test/java/org/eclipse/dataspaceconnector/examples/JsonFileGenerator.java
samples/04.2-modify-transferprocess/simulator/src/main/java/org/eclipse/dataspaceconnector/samples/sample042/TransferSimulationExtension.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ExecutorInstrumentationImplementation.java

This PR modifies some Java source files to enable the checkstyle header check rule in #997.
Reduce the developer overhead of fixing checkstyle header issues after merging #997.
- CyclicDependencyException.java: removed Jetty notice since the class is a generic implementation of `EdcException`
- TopologicalSort.java: moved Jetty notice down so that standard header goes first
- DataRequestMessageSender.java: deleted empty file
- JsonFileGenerator.java: moved out of default package. This will also allow to create a package name rule later
Also fixed an unrelated merge remnant marker in a README file.
Relates to #991

CI: checkstyle rule for Java file headers: additional fixes

---

common/util/src/main/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctions.java

This PR modifies the _propOrEnv_ method in _ConfigurationFunctions_ class to use default value if property is null or blank instead of checking only if it's null.
Environment variable or property shouldn't be blank, but rather unset if that's the case. 
This change should fix the failing Cosmos DB integration tests on main branch.
It implements the 3rd possible solution from bug: #1057 
Closes #1057

Bug fix: Default value if the env var is null or blank

---

CHANGELOG.md
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreExtension.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/in-memory/negotiation-store-memory/src/main/java/org/eclipse/dataspaceconnector/negotiation/store/memory/InMemoryContractNegotiationStore.java
extensions/in-memory/negotiation-store-memory/src/main/java/org/eclipse/dataspaceconnector/negotiation/store/memory/InMemoryContractNegotiationStoreExtension.java
extensions/in-memory/negotiation-store-memory/src/test/java/org/eclipse/dataspaceconnector/negotiation/store/memory/InMemoryContractNegotiationStoreTest.java
extensions/in-memory/negotiation-store-memory/src/test/java/org/eclipse/dataspaceconnector/negotiation/store/memory/TestFunctions.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/SqlContractNegotiationStoreExtension.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/ContractNegotiationStatements.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresStatements.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/sql/contract-negotiation-store/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/TestFunctions.java
extensions/sql/contract-negotiation-store/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
extensions/sql/contract-negotiation-store/src/test/resources/schema.sql
spi/contract-spi/build.gradle.kts
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStore.java
spi/policy-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/store/PolicyArchive.java

Implements a `PolicyArchive` that gives access to all policies, that have been received by "foreign" connectors, i.e. that were contained in a `ContractAgreement`.
Other objects, such as the `TransferProcessManager` might need access to those policies, so they need a way to get them out of storage, but compile-time coupling to the `ContractNegotiationStore` is to be avoided for obvious reasons.
- In actuality, the `ContractNegotiationStore` extends the `PolicyArchive` interface. All implementors simply persist the entire `Policy`, and then provide a means to query them.
- `PolicyArchive#findbyPolicyId` returns a `Stream` now, because theoretically contracts could have policies that are (slightly) different, but share the same policy ID. This could be the case if the we ever allowed a …

Feature: add `PolicyArchive` plus implementations

---

build.gradle.kts
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
docs/testing.md
extensions/catalog/federated-catalog-cache/build.gradle.kts
extensions/data-plane/integration-tests/build.gradle.kts
launchers/junit/src/testFixtures/java/org/eclipse/dataspaceconnector/junit/launcher/EdcExtension.java
samples/other/custom-runtime/src/main/java/org/eclipse/dataspaceconnector/demo/runtime/CustomRuntime.java
system-tests/e2e-transfer-test/runner/build.gradle.kts
system-tests/tests/build.gradle.kts

- `./gradlew clean test` does not log anything from (successful) test runs.
- A runtime flag is available (and documented) to make test runs verbose.
- With `./gradlew clean test`, if a test fails, the test name and failure cause are printed
Improve developer experience
Fixed BaseRuntime so as not to apply a shutdown hook to tests, that was causing extra logging at test completion.
Sample run showing clear message when a test fails:
https://github.com/agera-edc/DataSpaceConnector/runs/5749889045?check_suite_focus=true
```
2022-03-30T07:23:21.2000714Z CoreServicesExtensionIntegrationTest > shouldProvideHostnameExtension(Hostname) FAILED
2022-03-30T07:23:21.2001408Z     java.lang.AssertionError: Something strange happened
2022-03-30T07:23:21.2002146Z         at …
```

CI: control test verbosity

---

common/util/build.gradle.kts
common/util/src/main/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctions.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/configuration/ConfigurationFunctionsTest.java

ℹ️   This PR is a follow up for https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1064 which contained incomplete fix - changed the `if (value != null)` into `if (!StringUtils.isNullOrBlank(value))` only for system properties and not for environment variables. 
This PR modifies the _propOrEnv_ method in _ConfigurationFunctions_ class to use default value if **environment variable** is null or blank instead of checking only if it's null.
Environment variable shouldn't be blank, but rather unset if that's the case. 
This change should fix the failing Cosmos DB integration tests on main branch.
It implements the 3rd possible solution from bug: #1057 
Added unit tests for the _ConfigurationFunctions_ class after PR feedback.
Closes #1057

Bug fix: Default value if the environment variable is null or blank

---

extensions/sql/asset/index/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension

Change [META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension#L14](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/sql/asset/index/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension#L14) to become `org.eclipse.dataspaceconnector.sql.asset.index.SqlAssetIndexServiceExtension`
sql-asset-index extension has been registered incorrectly
Closes #1080

sql: Fix sql-asset-index service descriptor (fixes #1080)

---

resources/edc-checkstyle-config.xml

Extracted rules from the [Azure Java SDK checkstyle configuration](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml) that were not used in EDC, and do not generate any violations in the current codebase.
Detect potential code quality issues in future PRs
Relates to #991

CI: checkstyle miscellaneous rules

---

extensions/sql/contract-negotiation-store/docs/ddl_postgres.sql

It removes the `NOT_NULL` constraint on the column `correlation_id` of the `edc_contract_negotiation` table in `ddl_postgres.sql` of the `sql/contract-negotiation-store` module. It instead adds a `CHECK` constraint on the table, that checks whether the `correlation_id` column is not null for negotiations of type `PROVIDER`.
Currently, the `correlation_id` column may not be null for any contract negotiation. As only the provider sets a correlation ID for negotiations, this causes an error as soon as a `ContractNegotiation` is created and persisted on consumer side.

Contract negotiation Postgres DDL: allow null correlation id for type consumer

---

CODEOWNERS
CONTRIBUTING.md

This adds a `CODEOWNERS` file to the repo. The `CONTRIBUTING.md` was extended to hint on how to maintain the file's content.
As discussed in one of the latest committer rounds, this is a nice possibility to define contact persons (and automatically assign pull request reviewers) for specific modules and files. As noted in both modified files, the `CODEOWNERS` file should not represent all contributions to the code. What persons and organizations actually contributed to each file can be seen on GitHub and is documented in the license headers. It's all about major contact persons.
While creating this pull request, GitHub already provided some feedback:
We can add this file nevertheless, to have and provide an overview about responsibilities. However, GitHub automatisms will work only …

feat: add CODEOWNERS file to repository

---

extensions/sql/policy/store/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension

Change [META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension#L14](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/sql/policy/store/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension#L14) to become `org.eclipse.dataspaceconnector.sql.policy.SqlPolicyStoreExtension`
sql-policy-store extension has been registered incorrectly
Closes #1081

sql: Fix sql-policy-store service descriptor (fixes #1081)

---

CHANGELOG.md
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiExtension.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/ContractOfferDescription.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/NegotiationInitiateRequestDto.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/TestFunctions.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformerTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/contractnegotiation.yaml
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java
spi/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOfferTest.java

Replaced the `String offerId` property in `NegotiationInitiateDto` with a new object called `ContractOfferDescription`, which is essentially a wrapper around the offer id, asset id and policy id.
The IDS communication requires an `Asset` and a `Policy` to be present on a `ContractOffer`, even when sending from consumer to provider.
To avoid having a dependency onto the catalog's query endpoint, I put a shim in that creates a sparsely populated (=empty except the ID) Asset and Policy.
- This changes the REST API
Closes #985

ContractNegotiationService: refactor signature of DTO and method

---

extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/ContractOfferDescription.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/TestFunctions.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformerTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java

Adds a `policy` field to `NegotiationInitiateRequestDto`
To permit definition of custom policy on negotiation.
-
Closes #1078

extensions: add custom policy field to NegotiationInitiateRequestDto

---

CHANGELOG.md
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/SendRetryManager.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessSendRetryManager.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessSendRetryManagerTest.java
extensions/in-memory/transfer-store-memory/src/main/java/org/eclipse/dataspaceconnector/transfer/store/memory/InMemoryTransferProcessStore.java
extensions/in-memory/transfer-store-memory/src/test/java/org/eclipse/dataspaceconnector/transfer/store/memory/InMemoryTransferProcessStoreTest.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/retry/ExponentialWaitStrategy.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/retry/WaitStrategy.java

If the Consumer tries to initiate a transfer but the Provider is not available, the consumer does not manage the error. If the Provider later becomes available, the request did not get processed. This PR solves this issue.
If the request is unsuccessful, we keep the entity in the same state (with a state update, to increment its internal state count) and save it to break the lease and send the TP again potentially on the next iteration.
This "long retry" mechanism implements an exponential wait mechanism so as not to overflow the provider when it becomes available again. There might be many consumers queuing up requests to one provider.
After a given number of retries is exhausted, the transfer state moves to ERROR.
An additional "short retry" mechanism could also be implemented later in …

Transfers: reliably send transfers from consumer to provider

---

.github/workflows/performancetests.yaml
CHANGELOG.md
common/util/src/testFixtures/java/org/eclipse/dataspaceconnector/common/annotations/PerformanceTest.java
docs/testing.md
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferIntegrationTest.java
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferLocalSimulation.java

- Adds simple performance test example by reusing existing test.
- Adds performancetests.yml workflow to run nightly and can be triggered manually as well.
- Update documentation to adds a section about performance tests.
- Base work for future performance tests.
Closes #1020

Testing: Performance test example with workflow

---

CHANGELOG.md
extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/exception/mappers/EdcApiExceptionMapper.java
extensions/api/api-core/src/test/java/org/eclipse/dataspaceconnector/api/exception/mappers/EdcApiExceptionMapperTest.java
extensions/data-plane-selector/selector-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java

Makes `EdcApiExceptionMapper` handle `jakarta.ws.rs` exceptions correctly
To avoid unclear `503` status response (see #1101 )
- The mapper now does not return the exception message as the body, because it's not a secure behavior, it's always better to hide exception details to the outside, or at least report them in a way that is not related to the exception itself (e.g. the `EdcApiException` could have an optional field that brings an object that should be used as body for the response.
- A status description is added as `reasonPhrase` to detail the error type.
- The `ObjectNotModifiableException` (that's currently not used anywhere in the application) has been switched to `409` because `423` is not a state described by the jakarta's `Status` enum and it's also not mentioned in the …

extensions: handle jakarta exceptions correctly

---

extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/ContractNegotiationStatements.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresStatements.java
extensions/sql/contract-negotiation-store/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/sql/contract-negotiation-store/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
extensions/sql/contract-negotiation-store/src/test/resources/schema.sql

The `UPDATE` statement for the `ContractNegotiation` now also contains an entry for the `ContractAgreement`, so that it gets persisted as well.
Was missing before.
the `queryNegotiations` method now also features a `JOIN` statement, so that `ContractAgreements` are fetched as well.
Closes #1073

Bugfix: update `ContractAgreement`, when `ContractNegotiation` is updated

---

data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/policy/CustomIdsConstraintDeserializer.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/policy/IdsConstraintTest.java
extensions/policy/ids-policy/src/main/java/org/eclipse/dataspaceconnector/ids/policy/IdsPolicyExtension.java

This PR brings two fixes for IDS policies:
- add binding for _USE_ action to _ALL_SCOPE_ (otherwise, policy constraints are never evaluated)
- improve resiliency of CustomIdsConstraintDeserializer as it was not properly checking potentially null values before using them.

ids: IDS policy fixes

---

extensions/azure/data-plane/common/build.gradle.kts

This PR adds missing artifact publication for `data-plane-azure-common` which is required by the DPF server launcher.
Closes #1168

fix: publish data-plane-azure-common artifact

---

CHANGELOG.md
common/state-machine-lib/src/main/java/org/eclipse/dataspaceconnector/common/statemachine/StateMachine.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiController.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiController.java
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiController.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyApiController.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/asset.yaml
resources/openapi/yaml/contractdefinition.yaml
resources/openapi/yaml/contractnegotiation.yaml
resources/openapi/yaml/policydefinition.yaml
resources/openapi/yaml/transferprocess.yaml

Adapts the `@Produces` and `@Consumes` annotations on all DataManagementAPI controller such that they reflect what the methods actually consume/produce.
Wrong content types may cause problems when generating client SDKs from the OpenApi spec.
- fixed a wrong validity check in the `ContractNegotiationApiController`
- added default `provider` and `consumer` fields in the transformer.
- removed a logline from `StateMachine` that spammed the log every couple of seconds.
Closes #1126

Fix: corrects content types in DataManagementApi controllers

---

build.gradle.kts
extensions/sql/asset-index-sql/build.gradle.kts
extensions/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetIndexTest.java
extensions/sql/contract-definition-store-sql/build.gradle.kts
extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
extensions/sql/contract-negotiation-store-sql/build.gradle.kts
extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
extensions/sql/policy-store-sql/build.gradle.kts
extensions/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/slq/policy/store/SqlPolicyStoreTest.java
extensions/sql/transfer-process-store-sql/build.gradle.kts
extensions/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStoreTest.java

Adds the `@ComponentTest` annotation to all SQL-related tests.
Those tests are not unit tests (the use non-mocked collaborators such as H2) and therefore should only run when triggered explicitly to reduce test runtime on local machines.
- I also added a short test summary to the root buildfile, which produces output such as 
```
-----------------------------------------------------------------
|  Results: SUCCESS (32 tests, 32 passed, 0 failed, 0 skipped)  |  
-----------------------------------------------------------------
```
Closes #1132

Feature: use @component test in sql tests

---

extensions/api/control/src/main/java/org/eclipse/dataspaceconnector/api/control/response/NegotiationStatusResponse.java
extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/IdentityHub.java
resources/edc-checkstyle-config.xml

Add a rule for checkstyle check [MissingDeprecated](https://checkstyle.sourceforge.io/config_annotation.html#MissingDeprecated).
Verifies that the annotation @Deprecated and the Javadoc tag @deprecated are both present when either of them is present.
Improve code consistency and reduce spurious PR diffs.
Relates to #991

CI: add checkstyle rule for MissingDeprecated

---

extensions/api/auth-spi/src/main/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilter.java
extensions/api/auth-spi/src/test/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilterTest.java

the `AuthenticationRequestFilter` should skip checking auth headers for OPTIONS requests.
When using the REST APIs from a browser, they usually send "preflight" requests using the `OPTIONS` method. Since it's actually the browsers sending those requests and not the frontend application, there is no way to attach any auth header, therefore the preflight requests always get rejected with a 401.

Bugfix: Skip authentication of OPTIONS requests

---

extensions/data-plane-selector/selector-api/build.gradle.kts
extensions/data-plane-selector/selector-core/build.gradle.kts

Maven artefacts for `selector-api` and `selector-core` were misnamed as `data-plane-selector-spi`. Therefore 3 artefacts used that same name.
Closes #1184

DPF: fix Maven artifact names

---

CHANGELOG.md
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/SummaryPrinterAdapter.java
buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/TestSummaryPlugin.java

This PR adds a gradle plugin that prints a small test summar
Un-clutter the root `build.gradle.kts`
Should be merged after #1143, and the test listener code from there (in `build.gradle.kts`) should be removed before merging this.
Closes #1148

Build: adds plugin that prints a small summary

---

CHANGELOG.md
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/DependencyRulesPlugin.java
buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/ModuleNamesPlugin.java

Adds a gradle plugin that fails if duplicate module name exists
In the case of conflict will print something like:
```
Duplicated module names found: 
assetindex:
project ':extensions:in-memory:assetindex'
project ':extensions:sql:assetindex'
```
To avoid situations like the one described in #1135 to reoccur.
- modules existent in the `samples` and the `system-tests` folder will be excluded
- only modules with the build file will be checked
Closes #1174

build: introduce plugin to check duplicate module names

---

extensions/data-plane-transfer/data-plane-transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneTransferConsumerProxyTransformer.java
extensions/data-plane-transfer/data-plane-transfer-core/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/core/proxy/DataPlaneTransferConsumerProxyTransformerTest.java

This PR adds the boolean flags for request properties (query params, request body...) to the http `DataAddress` generated to represent the provider DPF proxy. Without these flags, all the request arguments get filtered by the consumer DPF proxy before they reach the provider DPF.  
Recover proper DPF proxy behavior. 
Contributes to #1180. One end-to-end test should be added in `system-tests:e2e-transfer-test` in order to close the issue. This will be done in a separated PR, once #1199 is merged.

fix: Prevent consumer DPF proxy to filter request arguments 

---

CHANGELOG.md
extensions/data-plane-transfer/data-plane-transfer-client/build.gradle.kts
extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/EmbeddedDataPlaneTransferClient.java
extensions/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/client/RemoteDataPlaneTransferClient.java
extensions/data-plane/data-plane-framework/build.gradle.kts
extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/DataPlaneFrameworkExtension.java
extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImpl.java
extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/pipeline/PipelineServiceImpl.java
extensions/data-plane/data-plane-framework/src/main/java/org/eclipse/dataspaceconnector/dataplane/framework/pipeline/PipelineServiceTransferServiceImpl.java
extensions/data-plane/data-plane-spi/build.gradle.kts
extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java
extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java
samples/04.0-file-transfer/transfer-file/build.gradle.kts
samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSink.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/telemetry/InMemoryTraceCarrier.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/telemetry/Telemetry.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/telemetry/TraceCarrier.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataFlowRequest.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataFlowRequestTest.java
system-tests/runtimes/file-transfer-provider/build.gradle.kts
system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSink.java
system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferDataSinkFactory.java
system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/TracingIntegrationTest.java

Add trace context propagation at different points within DPF:
- `DataPlaneManagerImpl`: trace context is propagated to the corresponding async worker threads through the "DataFlowRequest" entities stored in the processing queue.
- `ParallelSink`: trace context is propagated to the async workers that process parts. No entity is persisted in this case, the trace context is propagated in memory.
Additionally `TracingIntegrationTest` was extended to verify traces propagation within DPF is working properly.
In order to have traces spanning across asynchronous calls it is required to propagate the tracing context to worker threads. See resulting trace visualization in Jaeger:
Closes #936

Observability: Trace context propagation within DPF

---

CHANGELOG.md
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiController.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiController.java
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiController.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApi.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/NegotiationId.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/model/NegotiationState.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyApiController.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApi.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferId.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferState.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/asset.yaml
resources/openapi/yaml/catalog-api.yaml
resources/openapi/yaml/contractdefinition.yaml
resources/openapi/yaml/contractnegotiation.yaml
resources/openapi/yaml/transferprocess.yaml
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/FileTransferSimulationUtils.java

All API endpoints of the DataManagementApi now `@Produce` and `@Consume` `APPLICATION_JSON`. Those controller methods that previously returned a simple `String` now return a complex object that can be serialized to JSON in order to make things consistent.
To allow easier consumption in (generated) API clients.
n/a
Closes #1175

DataManagementApi: all API endpoints produce and consume APPLICATION_JSON

---

CHANGELOG.md
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java

For consumer-side transfers that are `IN_PROGRESS`, a `StatusChecker` (when provided) should execute on every `TransferProcessManagerImpl` (every 5 seconds) to check if e.g. the destination blob has been produced.
Following refactoring of the lease mechanism (probably with changes in #724), when the `StatusChecker` reports that the transfer is not completed, the lease was not broken after a Status check resulting in the output being incomplete. Therefore the status checker was only run again at lease timeout (every 60 seconds).
Closes #1206

TransferProcessManager: Break lease after status check

---

CHANGELOG.md
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/controller/FederatedCatalogApiController.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheEndToEndTest.java

This PR modifies the previous path `/catalog` for the Federated Catalog API controller to `/federatedcatalog`.
In case Data Management API are registered on the default context, there is a conflict between the endpoints respectively defined in `CatalogApiController` and in `CatalogController`, as both are registered on the same path `/catalog`.

catalog: Fix interference between Catalog API based on same path

---

extensions/azure/data-plane/storage/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureStorageDataSink.java
extensions/azure/data-plane/storage/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureDataSourceToDataSinkTest.java
extensions/azure/data-plane/storage/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/pipeline/AzureStorageDataSinkTest.java
extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java
extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java

AzureStorageDataSink writes a blob named `.complete` after all parts are transferred
End-to-end flow for blob storage transfers across EDC and DPF is not working (#1183). This is one of multiple PRs to solve several issues causing the problem.
When a data transfer target is an Azure Storage container, the consumer did not detect transfer completion. 
`ObjectContainerStatusChecker` polls for a blob called `*.complete` in the destination storage container to determine if a transfer has completed on the provider side. As `AzureStorageDataSink` did not currently write this file, transfer completion was never detected.
Closes #1210

DPF Azure storage: Write ".complete" blob

---

CHANGELOG.md
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/DataAddressInformationDto.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDto.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformer.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformerTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessTransformerTestData.java
resources/openapi/openapi.yaml
resources/openapi/yaml/contractnegotiation.yaml
resources/openapi/yaml/control.yaml
resources/openapi/yaml/federated-catalog-cache.yaml
resources/openapi/yaml/policydefinition.yaml
resources/openapi/yaml/selector-api.yaml
resources/openapi/yaml/transferprocess.yaml

Provide DataManagement API client information about data destination properties, such as the automatically provisioned Azure storage container name when `managedResources=true`.
End-to-end flow for blob storage transfers across EDC and DPF is not working (#1183). This is one of multiple PRs to solve several issues causing the problem; this PR is required to build a system test to validate the flow end to end.
When performing a transfer to Azure blob with `managedResources=true`, the consumer EDC provisions a storage container with a randomly generated name. The container is used as destination of the data copy on the provider DPF.
The client polls the TransferProcess API for completion. When the transfer is completed, the client can access the data in the storage container. However, the …

TransferProcess API: provide provisioned resource information

---

samples/02-health-endpoint/README.md
samples/02-health-endpoint/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthEndpointExtension.java
samples/03-configuration/README.md
samples/03-configuration/build.gradle.kts
samples/03-configuration/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthEndpointExtension.java

Update sample-03 documentation
It was out of date.
-
Closes #1218

samples: update documentation

---

CHANGELOG.md
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/AbstractMultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ContractAgreementHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/AbstractMultipartControllerIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/ObjectMapperFactory.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/XmlGregorianCalendarDeserializer.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/XmlGregorianCalendarModule.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/serialization/XmlGregorianCalendarSerializer.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/util/CalendarUtil.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/serialization/XmlGregorianCalendarModuleTest.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/serialization/XmlGregorianCalendarTest.java
data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/ContractAgreementRequestToIdsContractAgreementTransformer.java

It add a custom serializer and deserializer to the `ObjectMappers` in the `ids` modules.
Enables serialization and deserialization of `XMLGregorianCalendar` instances. Thus, the dates in `ContractAgreements` can be mapped correctly.
Once the IDS Information Model serializer is integrated, this solution should be deprecated.
Closes #1226

fix: IDS date serialization

---

CHANGELOG.md
extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/rules/ContractValidationRule.java
extensions/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/rules/ContractValidationRuleTest.java

As #1227 fixed date serdes, this PR enable `ContractValidationRule`.
To verify that the contract is still valid before transferring data.
-
Closes #1127

data-plane: enable contract validation rule

---

buildSrc/src/main/java/org/eclipse/dataspaceconnector/gradle/ModuleNamesPlugin.java

Changes how the `ModuleNamePlugin` excludes `samples` ans `system-tests`
To permit EDC to be loaded as submodule
- Tried to add unit tests, but doing it into the `buildSrc` folder [seems not so straightforward](https://github.com/gradle/gradle/issues/8224)
Closes #1232

bugfix: exclude sample and system-tests modules from module name check also if edc is loaded as submodule

---

extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImpl.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImplTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java

On every crawler run that the `PartitionManagerImpl` schedules, the `FederatedCacheNodeDirectory` is queried to get up-to-date information about "who is in the dataspace".
Note the periodic scheduling is implemented in the `ExecutionPlan`, or more specifically the `RecurringExecutionPlan`. This is because crawlers themselves are not scheduled in any form, they merely activate when a new `WorkItem` arrives in their queue. 
To be able to react to changes in the node directory
- completely unrelated: the port in the http provisioner test was randomized, because I noticed that that test fails when the port is already bound.
Closes #1230

Feature: FCC node directory is queried on every plan execution

---

CHANGELOG.md
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/PartitionConfiguration.java

This PR does two things:
1. changes the scheduler period from minutes to seconds 
2. changes the configuration keys to be more shell-friendly by replacing `"-"` with `"."`
**please update your configs accordingly!**
improve debugability and shell-friendliness
also added the `@EdcSetting` annotation, which has no functional impact as of now.

Catalog: fixes property names and period time unit 

---

samples/04.0-file-transfer/README.md
samples/04.0-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java

It updates the `README` of sample `04.0-file-transfer`.
The `README` was not up to date. It e.g. still mentioned the control API, which is not used in the sample anymore.
Closes #1256

docs: update sample 04.0 README

---

CHANGELOG.md
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractAgreementSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSenderTest.java

It dynamically sets the webhook address path from the configured IDS API path in the `MultipartContractOfferSender`.
The path was previously hardcoded, leading to an error if the path was configured to anything else than the default.
Closes #1249

fix: always use configured IDS API path in webhook address

---

.github/actions/run-tests/action.yml
.github/workflows/verify.yaml
CHANGELOG.md

Include component tests coverage in codecov coverage report.
It makes more sense that component tests coverage is included in coverage report as they are unit tests.
Closes #1217

CD: Include component tests coverage in codecov code coverage report.

---

extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisioner.java
extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisionerTest.java

When generating an Azure Storage Access Signature for the provider to write data into the consumer's destination blob storage, name the resource with a unique ID (e.g. `eead021e-3a76-44d4-81ec-1d79f2031dcd-container`) rather than with the fixed string `resource`.
Enable concurrent transfers not to overwrite one another's key in the vault.
Closes #1204

Azure storage: Ensure resource name is unique to avoid key collisions

---

CHANGELOG.md
extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java
extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/IdentityProviderKeyResolver.java
extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/IdentityProviderKeyResolverConfiguration.java
extensions/iam/oauth2/oauth2-core/src/test/java/org/eclipse/dataspaceconnector/iam/oauth2/core/identity/IdentityProviderKeyResolverTest.java

Make `IdentityProviderKeyResolver` throw exception if it's not able to get the keys at startup
This will avoid EDC starting without having keys loaded
- Enclose the `ExecutorService` inside the key resolver and exposing only a `start` and a `stop` method to give to the resolver full control of the cache refresh mechanism
- Introduce a `IdentityProviderKeyResolverConfiguration` pojo
- In the related issue we were talking about a retry mechanism, but since it's a topic that was already discussed in (#336) as "short retry" probably we need to reason about it at the http client level. will open an issue about
Closes #1262

bugfix: throws exception if `IdentityProviderKeyResolver` cannot get keys at startup

---

CHANGELOG.md
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/LoaderImpl.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/loader/LoaderManagerImpl.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/store/InMemoryFederatedCacheStore.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/defaults/store/InMemoryFederatedCacheStoreTest.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/FederatedCacheStore.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/Loader.java

This PR cleans out the FCC cache store before re-populating it again with the results of a crawl run.
To avoid having stale entries: when a connector removes a contract definition, all other connectors would still have corresponding (but invalid) offers.
n/a

Bugfix: clear FCC store before updating

---

extensions/azure/cosmos/policy-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyStoreExtension.java

Currently `Vault` is not injectable. 
#1285 should fix the problem but we need a fast (and simpler) resolution for this specific bug.
See #1272 
-
Closes #1272

bugfix: get vault through context

---

CHANGELOG.md
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexTest.java
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetQueryBuilderTest.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosConditionExpression.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClause.java
extensions/azure/cosmos/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosConditionExpressionTest.java
extensions/azure/cosmos/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClauseTest.java
resources/openapi/openapi.yaml

Properly interprets the SQL-statements based on the right-hand operand of the `Criterion` and adds statement placeholders as needed.
To make the statement interpreter more robust and avoid SQL injection attacks.
Closes #1282 
Closes #1002

Bugfix: improve Cosmos DB statement parser

---

CHANGELOG.md
extensions/aws/s3/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketProvisionerTest.java
extensions/http/jetty/src/test/java/org/eclipse/dataspaceconnector/extension/jetty/JettyServiceTest.java
extensions/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityServiceTest.java
extensions/jdk-logger-monitor/src/main/java/org/eclipse/dataspaceconnector/logger/LoggerMonitor.java
extensions/jdk-logger-monitor/src/test/java/org/eclipse/dataspaceconnector/logger/LoggerMonitorTest.java
extensions/jdk-logger-monitor/src/test/java/org/eclipse/dataspaceconnector/logger/TestLogHandler.java
extensions/sql/lease-sql/src/test/java/org/eclipse/dataspaceconnector/sql/lease/SqlLeaseContextTest.java
extensions/transaction/transaction-atomikos/src/test/java/org/eclipse/dataspaceconnector/transaction/atomikos/AtomikosTransactionExtensionTest.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/monitor/ConsoleMonitor.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/monitor/Monitor.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/monitor/MultiplexingMonitor.java

Sanitize log messages replacing `\n` and `\r` with a whitespace.
Line breaks in logs can be used by attackers as reported here: https://www.veracode.com/security/java/cwe-117
- replaced anonymous class instances of `Monitor` to simplify its hierarchy
Closes #1145

logs: sanitize log messages

---

CHANGELOG.md
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java
extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetQueryBuilderTest.java
extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosConditionExpression.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QuerySpec.java

This PR fixes failing integration tests for the AssetIndex based on CosmosDB. The test code previously still used the "old" formatted string format, which is obsolete since the introduction of the `CosmosConditionExpression`.
Some test code still used the old format.
Added a feature to `CosmosConditionExpression` that tries to reinterpret/parse a `Criterion` based on the operator and right-hand operand.
Closes #1313

Fix: broken CosmosDB tests

---

core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java

Fixes a broken link inside JavaDoc preventing `gradle build` to finish successfully.
Local integration in CI fails, because of broken builds.

core: Fix javadoc error preventing 'gradle build' to finish successfully

---

extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/azure/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreIntegrationTest.java

fixes more CosmosDB tests, which were not caught by the previous PR #1315 
There seems to be a functional difference between the Cosmos Emulator (which I used for testing locally) and the actual CosmosDB instance: when sorting based on a non-existing field, the cosmos emulator returns an empty list, whereas on the "real" cosmos does not affect the result.
Closes #1313

Bugfix: fixed more Cosmos DB tests

---

CHANGELOG.md
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java

When deleting a `ContractDefintion` from a `CosmosContractDefinitionStore` it was deleted from Cosmos, but was **not** deleted from the cache.
This PR fixes that.
ContractDefs were not properly deleted, which caused subsequent queries to return wrong results. The cache must be kept in sync with the actual database.
The current "caching" strategy is just a first version as it 1:1 mirrors the actual database, and a more elaborate strategy with proper eviction rules etc. should be devised. This will hopefully come out of #1173.
n/a

Bugfix: also remove ContractDef from cache when deleting

---

CONTRIBUTING.md
pr_etiquette.md

Adds a document to outline proper PR decorum.
To better shape the collaboration.
I created a new document and referenced it from `CONTRIBUTING.md` because there already were many bullet points and it seemed to be more readable that way.

Docs: adds pr etiquette document

---

.github/workflows/verify.yaml

Add write permissions to `checks` an `pull-requests` on CI
To make `Upload-Test-Report` job work
-
Closes #1329

ci: add missing permissions

---

CHANGELOG.md
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDto.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformer.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessToTransferProcessDtoTransformerTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/TransferProcessTransformerTestData.java
extensions/sql/transfer-process-store-sql/docs/schema.sql
extensions/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresStatements.java
extensions/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStore.java
extensions/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/TransferProcessStoreStatements.java
extensions/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/TestFunctions.java
resources/openapi/openapi.yaml
resources/openapi/yaml/selector-api.yaml
resources/openapi/yaml/transferprocess.yaml
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcess.java
spi/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TransferProcessTest.java

Add timestamps when querying TransferProcesses in Data management API.
Useful for web front-ends, to allow to sort transfers by dates.
Closes #1297

DM API: Add timestamps in TransferProcess DTO

---

CONTRIBUTING.md
docs/templates/README.md
docs/templates/decision-record.md
docs/templates/extension.md
docs/templates/launcher.md

Adds templates for documenting decision records, extensions, and launchers.
Would be nice if the documentation files followed the same structure. Furthermore, it makes it easier for developers to add necessary information.
--
Closes #1291

docs: provide documentation templates

---

CHANGELOG.md
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImpl.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImplTest.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/PartitionConfiguration.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/model/RecurringExecutionPlan.java
extensions/catalog/federated-catalog-spi/src/test/java/org/eclipse/dataspaceconnector/catalog/spi/PartitionConfigurationTest.java

wraps the `workItemQueue.addAll(...)` statement in  a `try-catch` block so that an exception does not cause the `ExecutionPlan` to die a silent death anymore.
When the `Runnable`, that gets passed to the `ExecutionPlan`, throws an exception, for example because the queue is full, this caused the `ExecutionPlan` to die silently.
Catching and logging any exception mitigates that.
- An `IllegalStateException` that is thrown by `workQueue.addAll()` is somewhat of an expected situation, therefore I opted for logging only a `WARNING`, as opposed to any other exception, that is logged as `SEVERE`.
- That situation will arise more quickly if the period of the recurring execution plan is set to a very low value.
- reading from the queue (`CrawlerImpl#L77`) already guards against any Throwable.
- …

Bugfix: `PartitionManagerImpl` should not swallow exceptions

---

.github/workflows/pull-request-auto-assign-project.yaml

Updates the PR workflow that should assign any new PR to the project's "in progress" column. Remove permission lines and add `column_name`.
Currently, the action never fails. However, no PR gets automatically assigned to a project, although this should now be the case for most, since we have more technical committers. I'm pretty sure this has worked before when I replaced the action in [5808a51](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commits/main/.github/workflows/pull-request-auto-assign-project.yaml). 
Will search for another action if this still not works.

workflow: update pull-request-auto-assign-project.yaml

---

CHANGELOG.md
docs/developer/modules.md
resources/charts/dataspace-connector/templates/configmap.yaml
resources/charts/dataspace-connector/templates/deployment.yaml
resources/charts/dataspace-connector/templates/ingress.yaml
resources/charts/dataspace-connector/templates/service.yaml
resources/charts/dataspace-connector/values.yaml
system-tests/minikube/minikube-test.sh
system-tests/minikube/values-consumer.yaml
system-tests/minikube/values-controlplane.yaml
system-tests/minikube/values-provider.yaml

This PR brings some improvement to the existing Helm charts, which was tainted for only being used to deploy the Control Plane of the EDC. 
In order to avoid code duplication for deploying other components of the EDC (data plane, data plane selector, federated catalog...), we make the existing Helm charts more generic. Especially,:
- We remove the hardcoded environment variables within the Deployment objects, as this is specific to the EDC component which is being deployed (for example, Data Plane does not have an IDS port, so existing charts could not be used to deploy the DPF). 
- Ports numbering is now up to the client which is using the helm charts, and is no longer hardcoded in the helm chart (as this is something that is defined at image build-time).
- Unlimited number of ports can …

helm: Make Helm charts more generic

---

.github/workflows/close-inactive-issues.yml

chore: allow manual triggering of close-inactive-issue workflow

---

.github/workflows/close-inactive-issues.yml

Extend `operations-per-run` from 30 to 200. Add `-1` to either issue- or pr-specific param, as the top level parameter sets a default value we need to overwrite. Remove write permissions for issues or PRs as a step should only run on either issues or PRs. 
see above
--
Relates #1392

chore: refine close-inactive-issue workflow

---

data-protocols/ids/ids-api-configuration/README.md

It updates the README of the `ids-api-configuration` module.
The README structure does currently not match the template for documenting extensions.

docs: update ids-api-configuration README

---

CHANGELOG.md
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QuerySpec.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/query/QuerySpecTest.java

This PR adds the `limit` parameter to the `String#split` method, causing the right-hand operand to be used "as-is", and not chop off parts after the "=" sign.
When building `QuerySpec`s out of a filter string, there was a bug when the right-hand operand contained a `"="` sign: the portion right of it would get chopped off because `String#split` would tokenize into too many elements.
The Regex to detect EQUALS expressions and the generic parse step (the `else` path) was adapted, so that the right-hand operand may also contain spaces.
**Please comment in case this is not the desired behaviour**
Closes #1380

Bugfix: right-hand operand may contain equals signs

---

CHANGELOG.md
extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/api/DataPlaneTransferTokenValidationApiController.java
extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/controller/DataPlanePublicApiController.java
extensions/iam/decentralized-identity/dummy-credentials-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/verifier/DummyCredentialsVerifier.java
extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/credentials/CredentialsVerifier.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/agent/ParticipantAgent.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/iam/ClaimToken.java

This PR replaces the current `Map<String, String>` used to carry the `ParticipantAgent` claims with a `Map<String, Object>`.
In order to enable carrying more complex objects into the `ParticipantAgent` claims, such as a complex json-structured file as described in the Gaia-X Trust Framework.
Closes #1404.

core: Make ParticipantAgent claims more generic

---

.github/workflows/close-inactive-issues.yml

Increase operations as the dry run showed that 200 is still not enough. Enable workflow.
To actually run the action.
--
Closes #1392

chore: activate close-inactive-issue workflow

---

CHANGELOG.md
data-protocols/ids/build.gradle.kts

Removes the `ids:token-validation` dependency from the IDS BOM.
To avoid transitive dependency onto `Oauth2ValidationRulesRegistry`
n/a
Closes #1387

Fix: remove `token-validation` dependency from BOM

---

common/util/build.gradle.kts
common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/AnotherObject.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtilTest.java
common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObjectSubSubclass.java
core/defaults/src/main/java/org/eclipse/dataspaceconnector/core/defaults/negotiationstore/InMemoryContractNegotiationStore.java
core/defaults/src/test/java/org/eclipse/dataspaceconnector/core/defaults/negotiationstore/InMemoryContractNegotiationStoreTest.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreTest.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/TestFunctions.java
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/model/ContractNegotiationDocumentSerializationTest.java
extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/ContractNegotiationStatements.java
extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresStatements.java
extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/TestFunctions.java
extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStore.java

This PR adds a method to the `ContractNegotiationStore` that returns all `ContractNegotiation`s that have a `ContractAgreement` which references a particular asset in order to check, whether the asset can be deleted or not.
Deleting Assets should be forbidden once it is referenced by a `ContractAgreement`. Previously the check used a filter expression, which is not (yet) implemented for SQL.
- The implementations for CosmosDB and InMem did not change functionally - the same query as was there before can be used. Only SQL - due to its relational nature - needed some love. 
- the `ReflectionUtil` threw a NPE when recursively resolving a field, who's parent is null, e.g. `ContractNegotiation -> contractAgreement -> assetId` when `contractAgreement` is null.
Closes #1403

Bugfix: check to determine if asset can be deleted

---

CONTRIBUTING.md

Adds a section to `CONTRIBUTING.md` about labeling issues and PRs `stale` and then auto-closing them.
Full transparency and disclosure

Doc: adds info about stale issues/PRs

---

.github/workflows/performancetests.yaml
extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/AbstractAzureBlobTest.java
extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/TestFunctions.java
extensions/azure/blobstorage/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectContainerStatusCheckerIntegrationTest.java
extensions/azure/data-plane/storage/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azurestorage/AzureDataPlaneCopyIntegrationTest.java
system-tests/azure-data-factory-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/AzureDataFactoryTransferIntegrationTest.java
system-tests/azure-tests/build.gradle.kts
system-tests/azure-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferIntegrationTest.java
system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferLocalSimulation.java
system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferSimulationConfiguration.java
system-tests/azure-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/BlobTransferUtils.java
system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/FileTransferSimulationConfiguration.java
system-tests/tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/local/TransferLocalSimulation.java
system-tests/tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/utils/TransferSimulationConfiguration.java
system-tests/tests/src/testFixtures/java/org/eclipse/dataspaceconnector/system/tests/utils/TransferSimulationUtils.java

Gatling System/Performance test scope is extended to include catalog query (contract offers) as well as deprovisioning after data transfer is performed.
This allows catching more potential errors, and provides additional performance data.
Catalog query takes slightly over 5 seconds locally, so extended the global timeout from 5 to 10 seconds.
Closes #1296

System tests: extend Gatling scope

---

extensions/azure/data-plane/data-factory/src/test/java/org/eclipse/dataspaceconnector/azure/dataplane/azuredatafactory/AzureDataFactoryCopyIntegrationTest.java

Updated ADF Integration test to create unique secrete key for sas token to avoid deletion conflict for parallel runs.
Fix for reported flaky test issue (https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1359).
Closes #1359

Flaky test: Update test to avoid key removal conflict during parallel test runs

---

CHANGELOG.md
extensions/api/api-core/build.gradle.kts
extensions/api/data-management/asset/build.gradle.kts
extensions/api/data-management/contractagreement/build.gradle.kts
extensions/api/data-management/contractdefinition/build.gradle.kts
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionDto.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/model/ContractDefinitionDtoValidationTest.java
extensions/api/data-management/contractnegotiation/build.gradle.kts
extensions/api/data-management/transferprocess/build.gradle.kts
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDto.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferRequestDtoValidationTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/transferprocess.yaml

Add validation for contract definition id
Validation of contract definition id by creation solves the problem in negotiation process when the id is not valid.
Marking jersey-bean-validation helps for the correct validation of parameters.
Closes #1347

Feature: add validation for contract definition id #1372

---

docs/developer/decision-records/2022-06-02-ids-serializer/README.md
docs/developer/decision-records/README.md

Formulate a decision record for the further proceeding regarding the usage of an IDS serializer. Let's discuss!
As discussed with @jimmarino @mspiekermann, and @ronjaquensel, for maintenance reasons, we decide not to use the IDS serializer library that is currently being used by the DSC and other IDS connector reference implementations. Instead, we will continue using our own implementation to deserialize IDS objects.
see the markdown file

decision record: ids serializer implementation

---

build.gradle.kts
gradle.properties

This PR reinstates the previously discarded `edcVersion` variable to hold the default value for the version.
Due to some gradle weirdness it was possible that the version string was `"unspecified"` in subprojects.
**We won't be able to produce SNAPSHOT versions until this is merged**

Bugfix: brings back the edcVersion variable in the build file

---

extensions/azure/azure-test/src/testFixtures/java/org/eclipse/dataspaceconnector/azure/testfixtures/CosmosTestClient.java
resources/azure/testing/terraform-apply.sh
resources/azure/testing/terraform/main.tf
resources/azure/testing/terraform/outputs.tf

Adds scripting scaffold to provision a CosmosDB instance with terraform when setting up forks.
To maintain consistency with the other Azure resources.
Closes #1377

Feature: create CosmosDB with terraform for integration testing

---

CHANGELOG.md
pr_etiquette.md

fixes dead link in "Etiquette for pull requests" documentation.
as a follow-up of 05af5e45745fe897d2d0c20095fe2e30d8d00c2c.
Closes #1477.
- [-] added appropriate tests?
- [-] performed checkstyle check locally?
- [-] added/updated copyright headers?
- [-] documented public classes/methods?
- [-] added/updated relevant documentation?
- [-] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

Docs: fix dead link to architecture principles page. (fixes #1477)

---

CHANGELOG.md
core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventRouterImpl.java
core/base/src/test/java/org/eclipse/dataspaceconnector/core/event/EventRouterImplTest.java
core/defaults/src/main/java/org/eclipse/dataspaceconnector/core/defaults/assetindex/InMemoryAssetIndex.java
docs/developer/README.md
docs/developer/events.md
extensions/api/data-management/asset/build.gradle.kts
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiExtension.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetListener.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetObservable.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetObservableImpl.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/EventAssetListener.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetEventDispatchTest.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java
extensions/azure/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndex.java
extensions/dataloading/src/main/java/org/eclipse/dataspaceconnector/dataloading/AssetLoader.java
extensions/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/asset/index/SqlAssetIndex.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/AssetCreated.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/AssetDeleted.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/Event.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/EventRouter.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/EventSubscriber.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/TypeManager.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/event/AssetCreatedTest.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/event/AssetDeletedTest.java
system-tests/e2e-transfer-test/runner/build.gradle.kts

Introduce events for domain class `Asset` and publish them through the `EventRouter`
To permit asynchronous notifications
- Add a first documentation markdown about how to subscribe to and how to publish events
- Implement a default behavior for `AssetLoader.accept(Asset asset, DataAddress dataAddress)` to remove some duplication
- Add the event publishing in the `AssetService` class. Currently not every component that act on Assets pass through the service (e.g. `DataLoader`). So here I have a question: should `AssetService` moved to an upstream module (like the core module or a dedicated core-asset module?)
- Add serialization capabilities to all the events. The deserialization could be achived registering the event types on the `TypeManager`. This process is described in the doc …

core: dispatch Asset events

---

CHANGELOG.md
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/loader/LoaderManagerImpl.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/management/PartitionManagerImpl.java
extensions/catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/LoaderManager.java

To avoid inconsistent loader storages, the time, when they are cleared was changed.
Now, all loaders are cleared just before the `ExecutionPlan` is scheduled.
Do avoid inconsistent loader storages.
- the `pre-executionHook` could be used for other tasks as well. 
- theoretically we could add a `post-executionHook` as well, but that was not needed as of now.
Closes #1495

Bugfix: change time when loaders are cleared

---

CHANGELOG.md
core/contract/build.gradle.kts
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java

Fixes a race condition in the `ContractNegotiationIntegrationTest` by replacing the `CountdownLatch` with `awaitility`.
Awaitility allows for better control over timed assertions than a latch - here it allows us to assert multiple things, in particular:
- the listener's `pre*` method has been called
- both negotiation managers are in the desired state
The latch only waited for the _first_ condition, whereas Awaitility waits for _all of them_.
To avoid race conditions, causing sporadically failing tests.
- countdown latches have been replaced only in the `ContractNegotiationIntegrationTest`
- replacing was also done in the `@Disabled` tests (why are they disabled?)
Closes #1505

Bugfix: replace countdown latches with awaitility

---

CHANGELOG.md
extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/azure/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreIntegrationTest.java

Fix failing Cosmos DB integration test `CosmosContractNegotiationStoreIntegrationTest`.
Cosmos DB behavior recently changed as [documented](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-order-by): *Queries with ORDER BY will return all items, including items where the property in the ORDER BY clause isn't defined.*
Also fixed logic for failing org.eclipse.dataspaceconnector.cosmos.policy.store.CosmosPolicyDefinitionStoreIntegrationTest#verify_readWriteFindAll
Closes #1512

Cosmos DB: update missing field behavior

---

.github/workflows/assign-issue-to-project.yaml
.github/workflows/assign-pr-to-project.yaml
.github/workflows/close-inactive-issues.yml

Stale action ignores "bug" issues. Rename project column from "Backlog" to "Open" (will be changed in the project tab accordingly). Change workflow event of PR project assignment.
Optimize GitHub automation 
--

chore: optimize GitHub project management

---

.github/dependabot.yml

Adds `dependabot.yml`.
Dependabot is activated but currently does not open up pull request to automatically update dependencies. 
There are a lot more properties to customize this file. These initial lines may be sufficient in the first place. Setting the limit to "5" prevents from being spammed with dependabot PRs. 
Not sure how this works with a multimodule project. If dependabot scans the `settings.gradle` and every module gets its version from there, it hopefully works.
Closes #906

chore(dependabot): add dependabot.yml to activate auto dependency updates

---

CHANGELOG.md
core/defaults/src/main/java/org/eclipse/dataspaceconnector/core/defaults/contractdefinition/InMemoryContractDefinitionStore.java
core/defaults/src/test/java/org/eclipse/dataspaceconnector/core/defaults/contractdefinition/InMemoryContractDefinitionStoreTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionServiceImpl.java
extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionServiceImplTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
extensions/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/assetindex/schema/postgres/PostgresAssetIndexTest.java
extensions/sql/common-sql/src/main/java/org/eclipse/dataspaceconnector/sql/translation/SqlQueryStatement.java
extensions/sql/common-sql/src/main/java/org/eclipse/dataspaceconnector/sql/translation/TranslationMapping.java
extensions/sql/contract-definition-store-sql/build.gradle.kts
extensions/sql/contract-definition-store-sql/docs/schema.sql
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreExtension.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/schema/BaseSqlDialectStatements.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/schema/ContractDefinitionStatements.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/schema/postgres/ContractDefinitionMapping.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/schema/postgres/CriterionMapping.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/schema/postgres/PostgresDialectStatements.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/schema/postgres/SelectorExpressionMapping.java
extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/TestFunctions.java
extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/postgres/PostgresContractDefinitionStoreTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java

Adds full query support to the `SqlContractDefinitionStore`.
Makes the flexible query feature reach "into" the database.
- removed the "special" method(s) from the `SqlContractDefinitionStore`.
Closes #1458

Feature: add full query support for SQL ContractDefinition store

---

extensions/api/auth-spi/src/main/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilter.java
extensions/api/auth-spi/src/test/java/org/eclipse/dataspaceconnector/api/auth/AuthenticationRequestFilterTest.java
spi/web-spi/src/main/java/org/eclipse/dataspaceconnector/spi/exception/AuthenticationFailedException.java

AuthenticationRequestFilter now throws an `AuthenticationFailedException` instead of a `NotAuthorizedException`, as this will trigger returning a HTTP 401 instead of a 403.
To return the correct HTTP status code
.

Fix: throw auth-failed exception

---

CHANGELOG.md
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImplTest.java
core/defaults/src/main/java/org/eclipse/dataspaceconnector/core/defaults/contractdefinition/InMemoryContractDefinitionStore.java
core/defaults/src/test/java/org/eclipse/dataspaceconnector/core/defaults/contractdefinition/InMemoryContractDefinitionStoreTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/IdsApiMultipartDispatcherV1IntegrationTestServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsApiMultipartEndpointV1IntegrationTestServiceExtension.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/azure/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
extensions/catalog/federated-catalog-cache/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FccTestExtension.java
extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
extensions/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/store/ContractDefinitionStore.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QuerySpec.java

Does not use a `QuerySpec` when executing `SqlContractDefinitionStore#findAll`, instead execute a plain `SELECT * FROM...`.
all = no limits!
Closes #1515

Fix: do not use `QuerySpec` when SqlContractDefinitionStore#findAll()

---

docs/developer/README.md
docs/developer/sql_queries.md

Adds a documentation file to explain how dynamically assembled SQL queries work.
Documentation is good!
Most of the code that is referenced in this PR will get merged in #1476.
Closes #1485

Doc: add documentation about dynamic SQL queries

---

extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityServiceExtension.java

Fix to use the correct class, as supported to be supplied by `IdentityDidCoreExtension`.
Runtime does not work when integrated in MVD, an exception is thrown that a resolver is missing for the given class. Use of the superclass is also the semantically correct code.

Decentralized identity: fix private key class

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java

Rephrases log message and sets log level from `info` to `debug`.
Detail failures and prevent logs from being spammed.
--
Closes #1513

chore(ContractDefinitionServiceImpl): refactor log level and message during policy evaluation

---

CHANGELOG.md
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiController.java

Fixed debug information in creating and deleting contract definitions via data-managment api
Previously it was logged that a contract negotiation was created/deleted instead of a contract definition. 
Closes #1584

fix: debug log output for ContractDefinition create and delete

---

.github/workflows/verify.yaml
CHANGELOG.md
core/transfer/build.gradle.kts
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/TransferProcessCommandExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandler.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/DeprovisionRequestHandler.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/SingleTransferProcessCommandHandler.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/listener/EventTransferProcessListener.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/command/handlers/CancelTransferCommandHandlerTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
extensions/api/data-management/transferprocess/build.gradle.kts
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiExtension.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessEventDispatchTest.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCancelled.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCompleted.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioned.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEnded.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessFailed.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessInitialized.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioned.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessRequested.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/observe/TransferProcessListener.java

Dispatch `TransferProcess` events
To permit asynchronous notifications
- <s>Removed the check on checkstyle job on CI, that should fix 1567 already</s>
- Introduced `awaitility` on `TransferProcessManagerImplTest`, as it was pretty mandatory to have the tests working. It's already a little part of #1583 
- Had to add a `postAction` method on the `SingleTransferProcessCommandHandler` to make the `CancelTransferProcess` command being able to notify the observable about the cancellation.
Closes #1439

core: dispatch `TransferProcess` events

---

docs/developer/decision-records/2022-07-06-release-automation/README.md

Adds decision-record about why and how we want to trigger releases from within GitHub Actions.
to have a traceable history

docs: add decision-record about triggering releases from GitHub

---

.github/workflows/verify.yaml

checkstyle check was not getting executed in downstram forks as it was configured to run on PR against main branch only. This PR removes this restriction so that checkstyle step gets execute on every CI run and also marks checkstyle step as failure in case of any checkstyle errors.
checkstyle step executed successfully on downstream fork.
- https://github.com/agera-edc/DataSpaceConnector/runs/7196648638?check_suite_focus=true
- https://github.com/agera-edc/DataSpaceConnector/runs/7196658195?check_suite_focus=true
Detect checkstyle related errors earlier e.g. downstream forks.
Closes #1567

CI: Execute checkstyle CI step on each run

---

.github/workflows/first-interaction.yml

Adds an action to comment issues and PRs of new contributors.
In the context of our discussion yesterday, I remembered this action. Maybe it will help. 
--

action: add bot for first interactions

---

extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/validation/TokenValidationClientImpl.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSource.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/pipeline/HttpDataSourceTest.java

Add http response body into the error logs of HttpDataSource.
Response body generally contains reason why the call was unsuccessful, e.g. access token expired, malformed request...

logs: Add relevant information in HttpDataSource logs

---

docs/_sidebar.md

Replaces link to Swagger UI
Link in GitHub pages is not working. It points to <https://eclipse-dataspaceconnector.github.io/swaggerui/index.html> but should point to <https://eclipse-dataspaceconnector.github.io/DataSpaceConnector/swaggerui/index.html>.
--

fix(docs): replace link to swagger ui

---

spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/AbstractResult.java
spi/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/result/ResultTest.java

Removes the `@NotNull` annotation on `AbstractResult#getContent` and the null-check on the `getFailureMessages()` method.
Just some housekeeping
Closes #1655

chore: cleanup `Result` and `AbstractResult`

---

CHANGELOG.md
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationManager.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/ArtifactRequestHandler.java
extensions/aws/s3/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/AwsProvisionExtension.java
extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisioner.java
extensions/azure/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStoreExtension.java
extensions/azure/data-plane/data-factory/src/main/java/org/eclipse/dataspaceconnector/azure/dataplane/azuredatafactory/AzureDataFactoryTransferManager.java
extensions/azure/events/src/main/java/org/eclipse/dataspaceconnector/events/azure/AzureEventExtension.java
extensions/azure/events/src/main/java/org/eclipse/dataspaceconnector/events/azure/AzureEventGridPublisher.java
extensions/azure/vault/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVault.java
extensions/azure/vault/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
extensions/catalog/federated-catalog-cache/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/controller/FederatedCatalogApiController.java
extensions/filesystem/configuration-fs/src/main/java/org/eclipse/dataspaceconnector/configuration/fs/FsConfigurationExtension.java
extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java

Adapt logs to the [logging guide](https://eclipse-dataspaceconnector.github.io/DataSpaceConnector/#/developer/logging)
-
-
Closes #1425

cleanup: adapt logs to logging guide

---

extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ServiceResultHandler.java
extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/result/ServiceFailure.java
extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/result/ServiceResult.java
extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiController.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiController.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/service/ContractAgreementService.java
extensions/api/data-management/contractagreement/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/service/ContractAgreementServiceImpl.java
extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerTest.java
extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/service/ContractAgreementServiceImplTest.java
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiController.java
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/service/ContractDefinitionService.java
extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/service/ContractDefinitionServiceImpl.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerTest.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/service/ContractDefinitionServiceImplTest.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiController.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationService.java
extensions/api/data-management/contractnegotiation/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationServiceImpl.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationServiceImplTest.java
extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiController.java
extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionService.java
extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionServiceImpl.java
extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiControllerTest.java
extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionServiceImplTest.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiController.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessService.java
extensions/api/data-management/transferprocess/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImpl.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessServiceImplTest.java

this PR changes the signature of all API services (the ones used by the controllers) to use `ServiceResult`s when querying.
`ServiceResults` (or `Result`s in general) are a pattern in EDC and should be used wherever possible.
- moved the `handleFailureResult` methods into a helper class `ServiceResultHandler`.
- removed the `EdcQueryException` from the `EdcExceptionMapper` again.
Closes #1654

Feature: refactor API services (query methods)

---

samples/04.0-file-transfer/integration-tests/build.gradle.kts
samples/04.0-file-transfer/integration-tests/src/testFixtures/java/org/eclipse/dataspaceconnector/extension/sample/test/FileTransferSampleTestCommon.java
samples/04.2-modify-transferprocess/modify-transferprocess-sample-integration-tests/build.gradle.kts
samples/04.2-modify-transferprocess/modify-transferprocess-sample-integration-tests/src/test/java/org/eclipse/dataspaceconnector/samples/sample042/test/ModifyTransferProcessSampleTest.java
settings.gradle.kts

This PR adds an automated integration tests that run in CI to prevent the samples breaking due to changes in the EDC.
The scope of this story is to add automated integration tests for sample 04.2.
Added test class `ModifyTransferProcessSampleTest.java`
Every step from sample 4.2 readme is reproduced in the automated tests to reduce the risk from sample guidance diverging from actual code base.
* No update to changelog as these changes apply to samples.
Closes #1588

Samples: add integration test to sample 04.2-modify-transferprocess

---

CHANGELOG.md
core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java
core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventRouterImpl.java
core/base/src/test/java/org/eclipse/dataspaceconnector/core/CoreServicesExtensionTest.java
core/base/src/test/java/org/eclipse/dataspaceconnector/core/event/EventRouterImplTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessEventDispatchTest.java

* Setting retly.limit to higer values enables transision to expected state.
* Disabling exponentional make transition to expected failure state within 10 seconds (which is default timeout of Awaitility).
* Waiting completion of EventRouter tasks.
Closes #1616

test: fix failure of TransferProcessEventDispatchTest (fixes #1616)

---

CHANGELOG.md
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartArtifactRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartCatalogDescriptionRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractAgreementSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractRejectionSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartDescriptionRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java

Adds a type check for IDS mulitpart message responses. 
Before, any IDS message was allowed as a response, although the further proccesing requires certain message types and contents. E.g. a state change would have been triggered in any case of a valid IDS response message, also for rejection messages.
Idea was not to check explicitly for rejection messages but to prevent processing unexpected responses.
Relates #1600

feat: add check for ids message response type

---

extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ServiceResultHandler.java

fixed Javadoc of ServiceResultHandler added by #1657.
Invalid characters in the Javadoc cause a warning and build failure.
```
> Task :extensions:api:api-core:javadoc
/Users/iwasakims/srcs/DataSpaceConnector/extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ServiceResultHandler.java:30: error: tag not allowed here: <th>
*   <th>reason</th>
^
/Users/iwasakims/srcs/DataSpaceConnector/extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ServiceResultHandler.java:31: error: tag not allowed here: <th>
*   <th>exception</th>
^
/Users/iwasakims/srcs/DataSpaceConnector/extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ServiceResultHandler.java:44: error: no summary or caption for table
* </table>
^ …
```

docs: fix javadoc issue on ServiceResultHandler

---

CHANGELOG.md
core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyContextImpl.java
core/base/src/main/java/org/eclipse/dataspaceconnector/core/base/policy/PolicyEngineImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImplTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/provision/ResourceManifestGeneratorImpl.java
core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/provision/ResourceManifestGeneratorImplTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplIntegrationTest.java
core/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplTest.java
docs/developer/policy-engine.md
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessEventDispatchTest.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractDefinitionService.java
spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/validation/ContractValidationService.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyContext.java
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/policy/PolicyEngine.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ResourceManifestContext.java
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/provision/ResourceManifestGenerator.java

It introduces two new policy scopes. The first one is `contract.cataloging`, which is used during the cataloging phase. The previously existing scope `contract.negotiation` is now used during the negotiation itself and to re-evaluate the policies before a new transfer process is created. The other new scope is `provision.manifest.verify`, which is used to evaluate a generated `ResourceManifest` to ensure that it fulfils the given policy.
Currently, policy evaluation only takes place during the negotiation phase.
Introduces the possibility to pass additional context information to the `PolicyEngine`, which is available to evaluation functions via the `PolicyContext`. This is required to pass information about the `ResourceManifest` to the functions.
Closes #1446
Closes #1331

feat: additional policy scopes

---

CHANGELOG.md
extensions/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStore.java
extensions/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/schema/BaseSqlDialectStatements.java
extensions/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/schema/TransferProcessStoreStatements.java
extensions/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStoreTest.java

This PR fixes a bug in the SQL impl where a `DataRequest` was not persisted when updating TransferProcesses.
.
Closes #1707

fix: added update stmt for DataRequest

---

CHANGELOG.md

Adds a pinned M5 section to the Changelog
Preparation for M5

chore: update CHANGELOG for M5

---

.github/release.yaml

Fixes the header in the GH release note configuration.
We're not introducing bugs, but bug fixes.
Closes #1718

chore(build): change bugfix header to 'Bugfixes'

---

extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java
extensions/iam/decentralized-identity/identity-did-core/src/test/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtensionTest.java

Inject DID services with `isDefault = true`
Allow Identity Hub integration tests to mock DidPublicKeyResolver. `EdcExtension.registerServiceMock()` only works with services that are created with `isDefault = true`, otherwise the mock is overwritten.

DID: Fix extension provider

---

docs/developer/decision-records/2022-07-22-simplify-fcc/README.md

Adds a decision-record about simplifying the FederatedCatalog.
Simplicity is a virtue!

doc(catalog): add decision record about simplification

---

CHANGELOG.md
extensions/http/jersey/README.md
extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyConfiguration.java
extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/JerseyRestService.java
extensions/http/jersey/src/main/java/org/eclipse/dataspaceconnector/extension/jersey/mapper/EdcApiExceptionMapper.java
extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/mapper/EdcApiExceptionMapperTest.java
extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/mapper/ExceptionMappersIntegrationTest.java

Return the "api error detail" response payload by default
The clients should be aware of the failure reason.
- having the possibility to include the stacktrace as it was hinted in the issue didn't seem a good idea, clients should only be aware of errors resolvable on their side, and the stacktrace won't help them at all, neither in a development environment
- Removed the "verbose" config settings as it has lost its value.
Closes #1492

feat: make rest api return error details on edc exceptions and validation error by default

---

CHANGELOG.md
extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java
extensions/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityServiceTest.java
system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/dataspaceconnector/test/e2e/BackendServiceTestExtension.java
system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/dataspaceconnector/test/e2e/ConsumerBackendServiceController.java
system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/dataspaceconnector/test/e2e/ProviderBackendApiController.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/AbstractEndToEndTransfer.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java

This PR adds a system test covering the use-case of a client data pull (see https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/585 for more details) with query parameters passed in input of the Data Plane public API.
Ensure query parameters are properly conveyed all the way to the provider data source (if its allows it).
Closes #1180

fix(DataPlane): Add system test for Client Data Pull with query parameters in the request

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/scan-pull-request.yaml
CONTRIBUTING.md

Add new regex that is more restrictive. PR titles have to match the conventional commit prefixes. Add label checker.
Improve PR quality. Label check was suggested in #1728.
...
Relates #1719

chore: improve pull request workflows

---

.github/workflows/scan-pull-request.yaml

Increase PR title length from 49 to 80 characters. 
Based on feedback.
Remove empty leftover `CHANGELOG.md`.

chore: increase allowed pr title length

---

docs/developer/decision-records/2022-07-27-custom-dto-validation/README.md

Adds a decision record for the custom-validation requirement.
To have a traceable and transparent trail of decisions
Documents #1736

docs: add decision record for custom validation

---

extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetEventDispatchTest.java
extensions/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
extensions/api/data-management/contractagreement/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractagreement/ContractAgreementApiControllerIntegrationTest.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
extensions/api/data-management/contractdefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/service/ContractDefinitionEventDispatchTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/api/data-management/contractnegotiation/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationEventDispatchTest.java
extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/PolicyDefinitionApiControllerIntegrationTest.java
extensions/api/data-management/policydefinition/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionEventDispatchTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/api/data-management/transferprocess/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/service/TransferProcessEventDispatchTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
extensions/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
extensions/http/jersey/src/test/java/org/eclipse/dataspaceconnector/extension/jersey/mapper/ExceptionMappersIntegrationTest.java
extensions/junit/src/main/java/org/eclipse/dataspaceconnector/junit/testfixtures/TestUtils.java

this PR explicitly adds configuration values for default port and context path to tests that spin up an EDC runtime.
When running `./gradlew test` with parallelism, parallel tests potentially attempt to spin up an EDC runtime, each of which binding against port 8181 (which is the default) which of course fails.
This supposedly only surfaced on local builds on machines with parallelism on, because it can never happen when running tests sequentially.
What made this a bit tricky to debug is the fact, that by default the gradle runner does not print STDOUT. Supplying the `-PverboseTest` argument does cause it to be printed, but then slows down test execution significantly, which made the bug not occur again.
Closes #1743

fix: explicitly set default ports in tests

---

extensions/http/jetty-micrometer/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyMicrometerConfiguration.java
extensions/http/jetty/src/main/java/org/eclipse/dataspaceconnector/extension/jetty/JettyService.java
extensions/http/jetty/src/test/java/org/eclipse/dataspaceconnector/extension/jetty/JettyServiceTest.java

The PR adds the Tags `jetty_context` and `jetty_port` to the jetty connection metrics (e.g. `jetty_connections_max`)
PR will result in this:
To support specific alerts for each context
Closes #1738

chore(observability): Add context information to jetty metrics

---

extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java
extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java

Fixes a bug where updating `ContractNegotiation` in Postgres fails with in an invalid type error.
The respective SQL `UPDATE` statement did not format a column as JSON properly. While this situation is indeed covered in the normal test (using H2), it did not surface before, because H2 does not really have a `JSON` type, and accepts `varchar`.
Currently, we only use an actual Postgres instance in tests that deal with the dynamic query stuff.
I added the test to both test classes, just to be extra sure.
Closes #1735

fix(sql): update the SQL statement to use correct data type

---

extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStoreTest.java

Correctly maps the `ContractNegotiation#type` field when reading from SQL storage
it did not get mapped before.
- the `Type.values()[VALUE]` is used. An `ArrayIndexOutOfBoundException` is thrown when the DB value is out-of-range.
Closes #1766

fix(sql): map contractnegotiation type

---

samples/01-basic-connector/README.md

This PR corrects the link to BaseRuntime.java of the getting started tutorial that I have found thanks to https://eclipse-dataspaceconnector.github.io/DataSpaceConnector/#/overview/hands-on
The [link](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/bootstrap/src/main/java/org/eclipse/dataspaceconnector/system/runtime/BaseRuntime.java) was returning 404
I have done this without creating an issue to not create overhead for a simple fix :) 
N/A
N/A

Correct BaseRuntime.java link for getting started tutorial

---

docs/developer/decision-records/2022-08-01-entity-timestamp/README.md
spi/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataRequest.java

Adds a decision record about how all or EDC entities will get a `createTimestamp` and an `lastUpdateTimestamp`.
Traceability, auditability.
removed an unused method in `DataRequest.java`
Documents #1370

docs: add decision record about create/update timestamps

---

.github/ISSUE_TEMPLATE/adoption_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/first-interaction.yml
CODEOWNERS
docs/developer/decision-records/README.md

Removes `no-changelog` label from dependabot PRs.
Exclusion from the changelog should not be decided by the action itself. (it may be interesting to have this information included in the release notes)
Little housekeeping of `CODEOWNERS`, docs and templates

chore: remove `no-changelog` label from dependabot PRs

---

core/base/build.gradle.kts
core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java
core/base/src/main/java/org/eclipse/dataspaceconnector/core/defaults/DefaultServicesExtension.java
extensions/azure/blobstorage/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/AzureProvisionExtension.java

This PR moves the factory methods for `RetryPolicy` and `OkHttpClient` from the `CoreServicesExtension` --> `DefaultServicesExtension`.
This is to avoid cyclic dependencies when attempting to `@Inject` either of these two into an extension, onto which the `CoreServicesExtension` in turn has a dependency, e.g. a `Vault` extension (it surfaced during #1534).
~~The two new `@Provider` methods were attributed as default providers (`isDefault=true`) to allow any other extension to override them.~~
[edit] removed the `isDefault` again, this caused problems with system tests
Closes #1775

fix: avoid cyclic dependency

---

docs/developer/decision-records/2022-08-04-documentation-automation/README.md
docs/developer/decision-records/README.md

Adds a decision record about docs automation from the input in #1494.
Information, as design decisions and architectural concepts, should not get lost in closed issues.
--
Relates #1302

docs: add decision record about documentation automation

---

extensions/api/auth-tokenbased/src/main/java/org/eclipse/dataspaceconnector/api/auth/TokenBasedAuthenticationExtension.java
extensions/api/data-management/api-configuration/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/configuration/DataManagementApiConfigurationExtension.java

Removes plain key from log line.
Password shouldn't be part of the log file
--
Closes #1780

fix: remove logging of api key from TokenBasedAuthenticationExtension

---

core/policy/policy-evaluator/src/main/java/org/eclipse/dataspaceconnector/policy/model/Policy.java

Fix broken link in `Policy` javadoc.

fix: Fix broken link in Policy javadoc

---

core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventRouterImpl.java
core/base/src/test/java/org/eclipse/dataspaceconnector/core/event/EventRouterImplTest.java
docs/developer/events.md
spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/EventRouter.java

Introduce sync subscribers on `EventRouter`
To permit reliable event dispatch
-
Closes #1774

feat: introduce sync subscribers on EventRouter

---

.github/workflows/codeql-analysis.yml

Avoid execution of CodeQL scanning on `push` event on `dependabot/**` branches
Because it causes failures, e.g.: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/7742411601?check_suite_focus=true
The error suggested to do it:
> Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, **please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches**. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
-
-

fix: avoid CodeQL run for dependabot pushes

---

samples/02-health-endpoint/README.md

The tutorial 2 at https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/samples/02-health-endpoint/README.md mentions that port and api root can be changed in JettyService.java and JerseyService.java but they both happen at JettyConfiguration.java . Thus, this PR updates the readme to take this into account.
The links and the associated text were wrong.

docs: fix link to JettyConfiguration in Tutorial 2

---

docs/developer/default_provider_methods.md
docs/developer/dependency_resolution.md

Adds more details about the dependency injection mechanism, in particular about default provider methods.
Default provider methods have been a repeated source for problems due to them being misused. This document should avoid that.
- at some point we'll have to go through the code base and correct usages of default provider methods. A subsequent PR will do that.
Closes #1806

docs: add details about DI mechanism, esp. default providers

---

docs/developer/decision-records/2022-08-11-versioning_and_artifacts/README.md

Adds a D-R about using only Maven artifacts (instead of local checkouts) and how the versioning is supposed to work.
While local checkouts have their upsides, I find them cumbersome and quirky to work with.
_List other areas of code that have changed but are not necessarily linked to the main feature. .
.

docs: add decision record about using maven artifacts

---

extensions/junit/src/main/java/org/eclipse/dataspaceconnector/junit/extensions/EdcExtension.java
extensions/junit/src/main/java/org/eclipse/dataspaceconnector/junit/extensions/TestServiceExtensionContext.java
extensions/junit/src/test/java/org/eclipse/dataspaceconnector/junit/extensions/EdcExtensionTest.java
extensions/junit/src/test/java/org/eclipse/dataspaceconnector/junit/extensions/MockMonitorExtension.java
extensions/junit/src/test/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.MonitorExtension

This PR introduces a subclass of `DefaultServiceExtensionContext` that maintains a list of service mocks (in addition to the normal services).
Then, when services are to be registered or resolved, that list of mocks is queried first to make sure, that mocks are always used first.
When service mocks are registered, we need to make sure they do not get overwritten by the normal extension loading.
.
Closes #1819

feat: do not overwrite registered mocks in tests

---

system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java

Using test resources copied by processTestResources task of Gradle instead of files in the source tree.
Tests should not update files under version control in order to avoid mysterious test failures and  unintentional change  checked in.
Closes #1829
- [] assigned appropriate label? (exclude from changelog with label `no-changelog`)

test: e2e-transfer-test should use copied test resources

---

core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/policy/PolicyEquality.java
core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/policy/PolicyEqualityTest.java
core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/AbstractEndToEndTransfer.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/Participant.java

Add an equality check between contract offer policy and contract negotiation policy in `ContractValidationService`
To avoid injection of malicious policies.
- this check is needed since currently the negotiation is automatically, and no counter offers are supported
- the equality check is done using the `ObjectMapper`'s `ObjectNode` as it is way less disruptive than overriding the `equals` method on every policy model class 
- the `target` has been excluded from the check for reasons explained in the issue: #1791 
- in `ContractValidationServiceImpl` the way the target asset is retrieved has been simplified, since the `id` must always be present, it can be used as the only criteria to get the `Asset`
- I'm not a supporter of "unhappy path e2e tests" but I needed this to light the way to …

fix: validate offer policy equality with definition policy on negotiation

---

docs/developer/decision-records/2022-08-17-remove_h2_database_tests/README.md

Adds a decision-record about removing H2 as test database.
While H2 has its advantages (easy spin-up, low footprint) there also are downsides when targeting a specific database, because some of the specific features are not available in H2. In the past, this has lead to undetected bugs.
.
Documents #1754

docs: add decision record about removing H2

---

system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/AbstractEndToEndTransfer.java

Made test cases of  e2e-transfer-test use independent asset and contract definition.
Invoking EndToEndTransferPostgresqlTest multiple times causes fails due to unintentional reusing of persisted asset information.
Closes #1824

test: fix failure of e2e-transfer-test due to unintentional reuse of asset

---

spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/AbstractResult.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/result/Result.java
spi/common/core-spi/src/test/java/org/eclipse/dataspaceconnector/spi/result/ResultTest.java
spi/common/transport-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transformer/TransformerContextImpl.java

adds some syntactic sugar to the `Result` and `AbstractResult` class to make them usable in fluent statements.
Enable code fluency and more descriptive and succinct code pieces.
- I tried to add the methods to the base class wherever possible to make them available to all subclasses.
Closes #1823

feat: fluent use of `Result`

---

core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoader.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/injection/lifecycle/ExtensionLifecycleManager.java
core/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/injection/lifecycle/PreparePhase.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtension.java

Adds an additional lifecycle method to `ServiceExtension` which is invoked after _all_ extensions have completed their initialization. The contract of this hook is:
- all service registrations are completed
- all extensions have finished executing the `initialize()` method
- the `prepare()` method of _all extensions_ will be invoked first
- the `start()` method of _all extensions_ will be invoked second
Sometimes users may want to perform (potentially long-running) preparatory tasks, that rely on service registration and initialization being complete, such as querying a `*Registry`. 
Since the contract of the `start()` method is that it signals the ability of EDC to accept incoming requests, the `start()` method is unsuitable for these kinds of tasks.
.
Closes #1765

feat: add prepare() lifecycle phase to extensions

---

extensions/data-plane/integration-tests/build.gradle.kts
extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpPullIntegrationTests.java
extensions/data-plane/integration-tests/src/test/java/org/eclipse/dataspaceconnector/dataplane/http/DataPlaneHttpToHttpIntegrationTests.java

Remove `Faker` from data plane integration tests, as it seems to make them flaky (see #1847)
To strengthen tests
- the `DataPlaneHttpToHttpIntegrationTests` seems to be more of a `system-test` than an integration test, since it run a `launcher`: `data-plane-server`
- `DataPlaneHttpPullIntegrationTests` could stay in the `data-plane-http` module, since that's what it's testing
Closes #1847

fix: remove Faker from DataPlane integration tests

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartEndpointDataReferenceRequestSenderTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/EndpointDataReferenceHandler.java

Resets the used `ObjectMapper` for serializing the `MultipartEndpointDataReferenceRequestSender` payload to the default one, since `EndpointDataReference` is not an IDS object and `EndpointDataReferenceHandler` uses the same for reading this value.
Details the edc exception message in `IdsMultipartSender::checkResponseType`.
The IDS object mapper should only be used for de/serializing ids objects, not edc objects.
--
Relates #1781

chore(IdsMultipartSender): use default object mapper for data reference serialization

---

spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetCreated.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetDeleted.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/asset/AssetEventPayload.java

Add a 'intermediate' superclass for the Event Classes `AssetCreated` and `AssetDeleted`. 
Improve the work with the Event Framework and give the possibility to filter Events on a bigger group of events
Closes #1813

feat(Event Framework): add intermediate superclass for Asset Events

---

CODEOWNERS
settings.gradle.kts

When pulling the new project structure, I noticed that some deleted modules have not been removed from the `settings.gradle`. 
clean up
--

refactor: remove deleted modules from settings.gradle

---

spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCancelled.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessCompleted.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioned.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessDeprovisioningRequested.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEnded.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessEventPayload.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessFailed.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessInitiated.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioned.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessProvisioningRequested.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/transferprocess/TransferProcessRequested.java

Add a 'intermediate' superclass for the Event Payload Classes of the TransferProcess classes.
Improve the work with the Event Framework and give the possibility to filter Events on a bigger group of events.
Closes #1873

feat(Event Frame Work): add intermediate superclass for TransferProcess Events hierarchy

---

extensions/data-plane/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSink.java
extensions/data-plane/data-plane-s3/src/main/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkFactory.java
extensions/data-plane/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataSinkTest.java
extensions/data-plane/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/TestFunctions.java

Enables multipart upload via S3 Extension
Current implementation relies on loading all content of the file into InputStream thus making it impossible to use files larger than InputStream's MAX_BUFFER_SIZE
Closes #1875

feat: enable s3 multipart upload

---

data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform/type/asset/OfferedAssetToIdsResourceTransformer.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/OfferedAssetToIdsResourceTransformerTest.java

Permits a `Catalog`'s `Resource` to have multiple `ContractOffer`s
To fix an unexpected behavior
- Removed unnecessary null check on transform context and related tests

fix: avoid _contractOffer_ overwrite in `OfferedAssetToIdsResourceTransformer`

---

core/common/jwt-core/build.gradle.kts
docs/developer/modules.md

Deploys [JWT Core module](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/common/jwt-core) deployed to maven repo as `jwt-core`
was wrong resp colliding with jwt-spi
Closes #1906
<sub>Denis Neuling <denis.neuling@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

fix: jwt-core module produces jwt-core named jar artifact

---

docs/developer/decision-records/2022-09-01-google-cloud-storage-integration/README.md

Add decision record about adding an extension for Google Cloud Storage  (GCS)
GCS is the object storage on Google Cloud Platform (GCP). With the extension GCP customers will be enabled to participate in data spaces.
.
Documents  [#1908](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1908)

docs: add decision record for GCS integration

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/MultipartContractOfferSenderTest.java

Maps properties, when an IDS `ContractOffer` is mapped to an IDS `ContractRequest`.
To allow sending additional policy properties to the provider during the contract negotiation.
Closes #1901

fix: map policy properties to contract request

---

samples/01-basic-connector/README.md
samples/02-health-endpoint/README.md
samples/03-configuration/README.md
samples/04.0-file-transfer/README.md
samples/04.1-file-transfer-listener/README.md
samples/04.2-modify-transferprocess/README.md
samples/04.3-open-telemetry/README.md
samples/05-file-transfer-cloud/README.md

Adds a Previous Chapter | Next Chapter links to each tutorial under samples
Because it is not easy to navigate the tutorials without going back to the initial ToC or clicking a couple times through GitHub
Closes #1822

docs: add previous and next links to samples tutorial

---

core/common/state-machine/build.gradle.kts
core/common/state-machine/src/test/java/org/eclipse/dataspaceconnector/common/statemachine/StateMachineManagerTest.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImplIntegrationTest.java
core/data-plane/data-plane-framework/build.gradle.kts
core/data-plane/data-plane-framework/src/test/java/org/eclipse/dataspaceconnector/dataplane/framework/manager/DataPlaneManagerImplTest.java
extensions/control-plane/api/data-management/asset-api/build.gradle.kts
extensions/control-plane/api/data-management/asset-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetEventDispatchTest.java
extensions/control-plane/api/data-management/policydefinition-api/build.gradle.kts
extensions/control-plane/api/data-management/policydefinition-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyDefinitionEventDispatchTest.java

Replace CountDownLatch  with Awaitility where needed, according to the decision record #1789 
Improve test cohesion, help contributions
I'm not sure if this PR covers/refactor all tests that needed to be migrated to Awaitility.
Closes #1583

refactor: Replace CountDownLatch with Awaitility

---

styleguide.md

Fixes broken link
--
--
Closes #1932

fix(docs): change broken link in styleguide.md

---

.github/workflows/close-inactive-issues.yml

Adds `close-issue-reason` to close stale issues as "not planned" by default.
--
--
Closes #1947

chore(workflows): add close-issue-reason for stale bot

---

samples/04.2-modify-transferprocess/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ApiEndpointExtension.java
samples/04.2-modify-transferprocess/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
settings.gradle.kts

- Cleans up `settings.gradle`
- Removes
- `:samples:04.1-file-transfer-listener:transfer-file`
- `:samples:04.1-file-transfer-listener:api`
- `:samples:04.3-open-telemetry:micrometer`
- Adds
- `:samples:04.2-modify-transferprocess:api`
- Reordering (alphabetically) and grouping
- Resolves dependencies and method calls in sample-specific code (`ApiEndpointExtension` and `ConsumerApiController`)
Clean up after module refactoring
--

refactor: clean up gradle dependencies in samples

---

extensions/data-plane/data-plane-s3/src/test/java/org/eclipse/dataspaceconnector/aws/dataplane/s3/S3DataPlaneIntegrationTest.java

Updated the annotation of org.eclipse.dataspaceconnector.aws.dataplane.s3.S3DataPlaneIntegrationTest.
In order to make the test executed by specifying `-DincludeTags='AwsS3IntegrationTest'`.
Closes #1896 

test: S3DataPlaneIntegrationTest should be annotated with AwsS3IntegrationTest

---

spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractdefinition/ContractDefinitionCreated.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractdefinition/ContractDefinitionDeleted.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractdefinition/ContractDefinitionEventPayload.java

Add a 'intermediate' superclass for the Event Payload Classes of the ContractDefinition classes.
Improve the work with the Event Framework and give the possibility to filter Events on a bigger group of events.
Closes #1910

feat(Event Frame Work): add intermediate superclass for ContractDefinition Events hierarchy

---

spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationApproved.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationConfirmed.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationDeclined.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationEventPayload.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationFailed.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationInitiated.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationOffered.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationRequested.java

Add a 'intermediate' superclass for the Event Payload Classes of the ContractNegotiation classes.
Improve the work with the Event Framework and give the possibility to filter Events on a bigger group of events.
Closes #1912

feat(Event Frame Work): add intermediate superclass for ContractNegotiation Events hierarchy

---

core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/InMemoryStatefulEntityStore.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStore.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/transferprocessstore/InMemoryTransferProcessStore.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStoreTest.java
docs/swaggerui/swagger-spec.js
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/build.gradle.kts
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreExtension.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreTest.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/build.gradle.kts
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
resources/openapi/openapi.yaml
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/persistence/Lease.java
spi/control-plane/contract-spi/build.gradle.kts
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStoreTestBase.java
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/TestFunctions.java

variants
Adds a base class for all (integration) tests of the `ContractNegotiationStore`.
to have a common test specification for all stores, and to provide consistent behaviour.
- the `InMemory` implementation now supports leases as well
Closes #1940

feat(test): introduced a base class for all ContractNegotiationStore

---

extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowController.java
extensions/control-plane/data-plane-transfer/data-plane-transfer-client/src/test/java/org/eclipse/dataspaceconnector/transfer/dataplane/flow/DataPlaneTransferFlowControllerTest.java

Maps properties from a `DataRequest` when creating a `DataFlowRequest`.
Otherwise, properties of a `DataRequest` are lost.
Closes #1972

fix: map DataRequest properties to DataFlowRequest

---

extensions/common/vault/azure-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVault.java
extensions/common/vault/azure-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultExtensionTest.java
extensions/common/vault/azure-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/azure/AzureVaultTest.java

Avoid "severe" log on `AzureVault` when secret is not found.
To avoid misleading logs
- test-covered the `resolveSecret` method
- remove useless `CountDownLatch` on `AzureVaultExtensionTest`
Closes #1962

feat: avoid log azure vault

---

core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/ExecutionManager.java
core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtension.java
core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/ExecutionManagerTest.java
core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/cache/FederatedCatalogCacheExtensionTest.java
spi/federated-catalog/federated-catalog-spi/src/main/java/org/eclipse/dataspaceconnector/catalog/spi/FederatedCacheNodeFilter.java

This PR makes the filtering method (essentially a `Predicate`) extensible, so that users of the Federated Catalog can choose which nodes to crawl and which not to.
In some situations users may decide to skip crawling nodes, for example when the last X attempts to crawl them had failed, or any other elaborate metric. 
- The `ExecutionManager` initialises the filter method with a noop filter to enable fluent code and to avoid NPE's 
- By default, the `FederatedCatalogCacheExtension` uses a filtering method based on the connector name, that excludes the executing connector, so as to not crawl "ourself".
- users can provide a `FederatedCacheNodeFilter` object using the `@Provider` mechanism.
Closes #1979

feat(catalog): make FederatedCatalogNode filtering extensible

---

core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/policystore/InMemoryPolicyDefinitionStoreTest.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosConditionExpression.java
extensions/control-plane/store/cosmos/policy-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStore.java
extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreIntegrationTest.java
extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreTest.java
extensions/control-plane/store/sql/policy-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PostgresPolicyDefinitionStoreTest.java
spi/control-plane/policy-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/policy/store/PolicyDefinitionStoreTestBase.java

Removes in-memory local cache for CRUD and querying in `CosmosPolicyDefinitionStore`.
Cleanup and remove the limitation of local cache growth and querying mechanism.
* Querying over arrays will be supported with #1981 
Closes #1965

feat(store): remove cache on CosmosPolicyDefinitionStore

---

core/common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/contractdefinition/InMemoryContractDefinitionStoreTest.java
extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java
extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreTest.java
extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresContractDefinitionStoreTest.java
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/contract/offer/store/ContractDefinitionStoreTestBase.java

Removes in-memory local cache for CRUD and querying in `CosmosContractDefinitionStore`.
Cleanup and remove the limitation of local cache growth and querying mechanism.  
Closes #1964

feat(store): remove cache on CosmosContractDefinitionStore

---

gradle.properties

Bumps aws-sdk version to 2.17.278
Keep dependencies updated

chore: bump aws-sdk version to 2.17.278

---

build.gradle.kts
gradle.properties

Bumps swagger version to 2.2.2
Keep dependencies updated

chore: bump swagger version to 2.2.2

---

core/control-plane/transfer/src/test/java/org/eclipse/dataspaceconnector/transfer/core/TestResourceDefinition.java
extensions/control-plane/provision/blob-provision/src/main/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageResourceDefinition.java
extensions/control-plane/provision/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageProvisionerTest.java
extensions/control-plane/provision/blob-provision/src/test/java/org/eclipse/dataspaceconnector/provision/azure/blob/ObjectStorageResourceDefinitionTest.java
extensions/control-plane/provision/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/AbstractHttpResourceDefinition.java
extensions/control-plane/provision/http-provisioner/src/main/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderResourceDefinition.java
extensions/control-plane/provision/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderProvisionerTest.java
extensions/control-plane/provision/http-provisioner/src/test/java/org/eclipse/dataspaceconnector/transfer/provision/http/impl/HttpProviderResourceDefinitionTest.java
extensions/control-plane/provision/s3-provision/src/main/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketResourceDefinition.java
extensions/control-plane/provision/s3-provision/src/test/java/org/eclipse/dataspaceconnector/aws/s3/provision/S3BucketResourceDefinitionTest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/ResourceDefinition.java
spi/control-plane/transfer-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/TestResourceDefinition.java
spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/transfer/store/TestFunctions.java

It adds a `toBuilder()` method for all `ResourceDefinitions`.
During policy evaluation, functions may modify a `ResourceDefinition`. When each definition is re-created from scratch, information may get lost. Therefore, definitions should be convertable to a builder that can be easily modified.
Closes #1717

feat: add toBuilder for resource definitions

---

core/common/util/src/main/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtil.java
core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/ReflectionUtilTest.java
core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestGenericArrayList.java
core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestGenericObject.java
core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestGenericSubclass.java
core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObject.java
core/common/util/src/test/java/org/eclipse/dataspaceconnector/common/reflection/TestObjectWithList.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/ConditionExpression.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/ConditionExpressionParser.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosExistsExpression.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosPathConditionExpression.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/QuotedPathCollector.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/SqlStatement.java
extensions/common/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClause.java
extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/TestCollectionDocument.java
extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/ConditionExpressionParserTest.java
extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosExistsExpressionTest.java
extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/CosmosPathConditionExpressionTest.java
extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/QuotedPathCollectorTest.java
extensions/common/azure/cosmos-common/src/test/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/SqlStatementTest.java
extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStoreIntegrationTest.java
extensions/control-plane/store/cosmos/policy-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/cosmos/policy/store/CosmosPolicyDefinitionStoreIntegrationTest.java
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/contract/offer/store/ContractDefinitionStoreTestBase.java

Adds the support for the querying arrays when using the Cosmos store. The changes has been done at dialect level of the implementation of Cosmos store. 
An additional Expression has been added when translating the where condition into the Cosmos one. 
If in the Criterion left operand a collection is detected via reflection of `objectType` class in `SqlStatement` the single expression is rewritten using Cosmos `EXISTS` expression.
Have the same support of Posgres store when querying arrays.
The test `CosmosContractDefinitionStoreIntegrationTest#find_queryBySelectorExpression_entireCriterion` has been disabled since we do not support matching against JSON in our current implementation
Closes #1981

feat(store): implements array querying in Cosmos store

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/IdsMultipartSenderTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/DynamicAttributeTokenServiceImpl.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/util/ConnectorIdUtil.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/DynamicAttributeTokenServiceImplTest.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/DynamicAttributeTokenService.java

Moves code that was duplicated between `ids-api-multipart-dispatcher-v1` and `ids-api-multipart-endpoint-v1` to `ids-core`. Adds a utility class for resolving the connector's IDS ID setting and introduces a service for handling `DynamicAttributeTokens`.
To avoid duplications.
Closes #1727

refactor: move duplicated code to `ids-core`

---

extensions/common/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java
extensions/common/iam/decentralized-identity/identity-did-service/src/test/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityServiceTest.java

Add assertion of `Result` returned by `CredentialsVerifier` invokation.
Prevent `NullPointerException` when `CredentialsVerifier` invokation fails.

fix: Add missing result check in DecentralizedIdentityService

---

core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContext.java
core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/ExtensionLoader.java
core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/DefaultServiceExtensionContextTest.java
extensions/common/junit/src/test/java/org/eclipse/dataspaceconnector/junit/extensions/EdcExtensionTest.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtensionContext.java

Marks the `ServiceExtensionContext` in read-only mode before the prepare phase in the EDC boostrap.
Prevent undefined behavior when registering services in the prepare or start phase
Closes #1852

feat(ServiceExtensionContext): freeze the ServiceExtensionContext before the prepare phase

---

data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java

The `MultipartController` now uses the recipient of a response message as the audience for the token request.
Previously, the issuer of the message was used. Thus, the connector used itself as the token audience for responses.
Closes #2017

fix(MultipartController): use message recipient as token audience

---

core/common/boot/src/main/java/org/eclipse/dataspaceconnector/boot/system/runtime/BaseRuntime.java
core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/BaseRuntimeTest.java
core/common/boot/src/test/java/org/eclipse/dataspaceconnector/boot/system/testextensions/BaseRuntimeFixture.java

Adds the exception message to the severe log before exit
To have a clear information and diagnostic on why the system didn't boot
Closes #1960

fix(BaseRuntime): adds the exception messagge in the log before exit

---

docs/developer/decision-records/2022-09-29-sql-query-streaming/README.md
docs/developer/decision-records/README.md

Add decision records for SQL Query Streaming
See #2027 
-
-

docs: add DR for SQL Query Streaming

---

build.gradle.kts
docs/developer/autodoc.md
gradle.properties

Applies the `autodoc` plugin to the EDC code base.
metadata manifests should be auto-generated
- At this time we only have a `0.0.1-SNAPSHOT` version available
- The plugin, the annotation processor and the metamodel all use the same version, but I created three different variables, because their versioning might deviate in the future.
- the plugin's name and group id looks wrong, but actually needs to be this way, otherwise publishing to OSSRH Snapshots and the Gradle Portal would not be possible
- documentation will follow shortly, once the documentation-PR (https://github.com/eclipse-dataspaceconnector/GradlePlugins/pull/12) of the plugin itself is merged, because it will link there.

feat(build): add/apply autodoc plugin

---

core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplTest.java
core/federated-catalog/federated-catalog-core/src/main/java/org/eclipse/dataspaceconnector/catalog/cache/query/BatchedRequestFetcher.java
core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/query/BatchedRequestFetcherTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartCatalogDescriptionRequestSender.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/RequestUtil.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/util/RequestUtilTest.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImpl.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImpl.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/ConnectorServiceImplTest.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/CatalogService.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/ConnectorService.java
extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/service/CatalogServiceImpl.java
extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerTest.java
spi/common/catalog-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/catalog/CatalogRequest.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/message/Range.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QuerySpec.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferQuery.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferService.java

Extend existing CatalogRequest object with list of criteria used to filter Assets within Catalog response.
In a large scale environment, with multiple EDCs holding the information about hundreds of thousands of Assets, instead of looping thought all of the ContractOffers, there is a need to narrow the results down to even single offer. For example, an Asset might hold the 'special' type of data (like registry or database) and should be searchable by its type.
Closes #1966

feat: IDS catalog request filtering

---

docs/swaggerui/swagger-spec.js
extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApi.java
extensions/control-plane/api/data-management/catalog-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiController.java
extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/catalog-api.yaml

Adds validation to `providerUrl` query params
To prevent NPE and HTTP 500 response code
In order to add a custom message a `ValidationMessages.properties` has been created since
by default the `@NotNull` constraint validation in method params omit the param name.
Closes #2029

fix(CatalogApi): adds @NotNull to providerUrl param

---

extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java

Removes default value for `edc.transfer.proxy.token.verifier.publickey.alias`
Consistent setting public/private key, clear exception in case of settings missing
Closes #1889

fix(DataPlaneTransferSyncExtension): remove default value for publickey alias

---

core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/dataspaceconnector/catalog/query/BatchedRequestFetcherTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/sender/type/MultipartContractOfferSenderTest.java
docs/swaggerui/swagger-spec.js
extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerTest.java
extensions/control-plane/api/data-management/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/service/CatalogServiceImplTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/catalog-api.yaml
resources/openapi/yaml/federated-catalog-core.yaml
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java
spi/control-plane/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOfferTest.java

Removes `assetId` from `ContractOffer`
Cleanup, since `assetId` is not used  by anyone
Closes #2030

chore(ContractOffer): remove field assetId

---

core/common/base/build.gradle.kts
core/common/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreDefaultServicesExtension.java
spi/common/transaction-datasource-spi/src/main/java/org/eclipse/dataspaceconnector/spi/transaction/datasource/DefaultDataSourceRegistry.java
spi/common/transaction-datasource-spi/src/test/java/org/eclipse/dataspaceconnector/spi/transaction/datasource/DefaultDataSourceRegistryTest.java

Provide a default `DataSourceRegistry` 
improve developer experience
Closes #2032

feat(DataSourceRegistry): provides a default impl for DataSourceRegistry

---

core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImpl.java
core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractDefinitionServiceImplTest.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplIntegrationTest.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImplTest.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/assetindex/InMemoryAssetIndex.java
extensions/control-plane/store/cosmos/assetindex-cosmos/src/main/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndex.java
extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/SqlAssetIndex.java
spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/asset/AssetIndex.java
spi/common/core-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/asset/AssetIndexTestBase.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractDefinitionService.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferQuery.java

In the current implementation of the `ContractOfferSerivceImpl`, the `Range` parameter is used to limit `ContractDefinitions` rather than the resulting `ContractOffers`. This is a bug and could lead to more contractOffers than specified by `Range`.
This PR dynamically composes the `Stream<Asset>` based on the `from` and `to` parameters of the `Range`, skipping as many `Assets` as necessary, and applying the `skip` and `limit` parameters to the respective database query.
In doing that, it was necessary to add a method `AssetIndex.count(QuerySpec)` to obtain the number of Assets referenced by a particular `AssetSelectorExpression`.
To guarantee the correct/expected behaviour of the paging.
- This solution works regardless of the underlying implementation of the Stream returned by the …

fix: use the `range` to limit offers, not definitions

---

docs/swaggerui/swagger-spec.js
extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/DataRequestDto.java
extensions/control-plane/api/data-management/transferprocess-api/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/transform/DataRequestToDataRequestDtoTransformer.java
extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/control-plane/api/data-management/transferprocess-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/transferprocess/model/TransferProcessDtoTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/transferprocess-api.yaml

Adds the field `id` in `DataRequestDTO`
For correlating data requests across EDC instances via Data Management APIs
Closes #1866

fix(transferprocessApi): add id field in DataRequestDTO 

---

build.gradle.kts

Sets the output dir to be the build directory of every project
so that manifests get cleaned with the rest of the build artefacts

chore: set output dir of the autodoc plugin

---

core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/TestFunctions.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/ContractOfferToIdsContractOfferTransformerTest.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/dataspaceconnector/ids/transform/OfferedAssetToIdsResourceTransformerTest.java
extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/control-plane/api/data-management/contractnegotiation-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/contractnegotiation/service/ContractNegotiationServiceImplTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java
spi/control-plane/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOfferTest.java

Adds the check on asset field when building a ContractOffer
For consistency with the `getAsset` API, since the Asset is mandatory in the `ContractOffer`
While fixing this the style of the `ContractOffer.Builder` has been changed following our usual builder pattern
Closes #2052

fix(ContractOffer): add asset not null check when building a ContractOffer

---

.github/actions/run-tests/action.yml
.github/actions/setup-build/action.yml
.github/workflows/verify.yaml

updates some of the actions we use to their respective latest versions
some actions seem to use Node 12, which is [out of support](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12) as of April 2022, specifically:
- `actions/setup-java@v2`
- `actions/upload-artifact@v2`
- `actions/checkout@v2`
- `deepakputhraya/action-pr-title` is also affected, but there is no new version yet (latest is from June 1). I did, however, submit an [issue](https://github.com/deepakputhraya/action-pr-title/issues/24) there asking for the upgrade.

chore: update multiple GH action versions

---

core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImpl.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/control-plane/contract/src/test/java/org/eclipse/dataspaceconnector/contract/validation/ContractValidationServiceImplTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/ContractId.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/validation/ContractValidationService.java
spi/control-plane/contract-spi/src/test/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/ContractIdTest.java

Changes contract validation on consumer side when it receives the "confirmed" message from the provider, at this point the agreement is already reached and there should be only a formal validation of the id and the policy, no need to evaluate the latter.
It was an unnecessary evaluation.
- renamed the `validate` method to `validateConfirmed` to have a clear distinction on what's the purpose of the method avoiding confusion with the others.
- refactored `ContractId` to a more object oriented one.
- made `validateConfirmed` returns a `Result`, so the caller can obtain a detail on what was the problem.
Closes #1975

fix(validation): avoid policy evaluation on consumer side after agreement

---

extensions/common/vault/hashicorp-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultIntegrationTest.java
extensions/common/vault/hashicorp-vault/src/test/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/annotations/HashicorpVaultTest.java
system-tests/minikube/minikube-test.sh
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/remote/FileTransferAsClientIntegrationTest.java
system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/remote/annotations/MinikubeIntegrationTest.java

…ANNOTATION_TYPE
Closes #1949
This pr change the target of IntegrationTest annotation to block its direct use on test classes.
Also add a MinikubeIntegrationTest annotaton for End to End integration testing based on Minikube.
Then change the minikube-test.sh file to support the MinikubeIntegrationTest annotation.
Closes #1949

fix(tests): change IntegrationTest annotation target from TYPE to ANNOTATION_TYPE

---

.github/ISSUE_TEMPLATE/feature_request.md

Removes checklist from issue template
Has become misleading for new contributors
-
-

chore(github): remove checklist from issue template

---

docs/developer/decision-records/2022-10-10-naming-conventions/README.md
docs/developer/decision-records/README.md

Describes naming patterns for moduleIds, groupId, artifactIds, packages, and config properties.
To align the project's code structure.
Do you have a more concrete idea for the config naming, and an example?
Closes #1956

docs: add decision record for naming conventions

---

core/control-plane/control-plane-core/src/main/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStore.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/dataspaceconnector/core/controlplane/defaults/negotiationstore/InMemoryContractNegotiationStoreTest.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStore.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/schema/ContractNegotiationStatements.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStore.java
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/spi/contract/negotiation/store/ContractNegotiationStoreTestBase.java

Removes `ContractNegotiationStore.getAgreementsForDefinitionId`
cleanup since it was not used 
Closes #2069

refactor(ContractNegotiationStore): remove ContractNegotiationStore.getAgreementsForDefinitionId

---

core/data-plane-selector/data-plane-selector-core/build.gradle.kts
core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/core/DataPlaneSelectorDefaultServicesExtension.java
core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/InMemoryDataPlaneInstanceStore.java
core/data-plane-selector/data-plane-selector-core/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/store/InMemoryDataPlaneInstanceStoreTest.java
docs/developer/modules.md
extensions/data-plane-selector/selector-api/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/build.gradle.kts
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/docs/schema.sql
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtension.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/schema/BaseSqlDataPlaneInstanceStatements.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/schema/DataPlaneInstanceStatements.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/schema/postgres/PostgresDataPlaneInstanceStatements.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java
settings.gradle.kts
spi/data-plane-selector/data-plane-selector-spi/build.gradle.kts
spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/dataplane/selector/TestDataPlaneInstance.java
spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/dataplane/selector/TestFunctions.java
spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/dataspaceconnector/dataplane/selector/store/DataPlaneInstanceStoreTestBase.java

Add SQL store implementation for DataPlaneInstanceStore
Durability of Data Plane Instances
Closes #2074

feat(DataPlaneInstanceStore): add SQL store implementation

---

core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferResolverImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferResolverImplIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferResolverImplTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/MultipartControllerIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/IdsCoreServiceExtension.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImpl.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/dataspaceconnector/ids/core/service/CatalogServiceImplTest.java
extensions/control-plane/api/data-management-api/catalog-api/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/offer/ContractOfferResolver.java

Rename one of the `ContractOfferService`s to `ContractOfferResolver`
To avoid duplicated class names and let the class be more self-explainatory
-
Closes #1248

chore: rename ContractOfferService to ContractOfferResolver

---

docs/developer/decision-records/2022-10-21-gradle-versioncatalogs/README.md
docs/developer/decision-records/README.md

Adds a decision record about the usage of version catalogs in EDC.
Documentation and decision tracking.
- the implementation will be spread out over the GradlePlugins repo, EDC, and all the other projects (IH, RS, MVD,...)

docs: add decision record about EDC version catalogs

---

extensions/common/sql/sql-core/build.gradle.kts
extensions/common/sql/sql-core/src/main/java/org/eclipse/dataspaceconnector/sql/store/AbstractSqlStore.java
extensions/common/sql/sql-core/src/testFixtures/java/org/eclipse/dataspaceconnector/sql/PostgresqlStoreSetupExtension.java
extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/dataspaceconnector/sql/assetindex/SqlAssetIndex.java
extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/dataspaceconnector/sql/assetindex/PostgresAssetIndexTest.java
extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java
extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStoreExtension.java
extensions/control-plane/store/sql/contract-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/PostgresContractDefinitionStoreTest.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/build.gradle.kts
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/SqlContractNegotiationStoreExtension.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/SqlPolicyStoreExtension.java
extensions/control-plane/store/sql/policy-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/store/SqlPolicyDefinitionStore.java
extensions/control-plane/store/sql/policy-definition-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/policy/store/PostgresPolicyDefinitionStoreTest.java
extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/SqlTransferProcessStore.java
extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/dataspaceconnector/sql/transferprocess/store/PostgresTransferProcessStoreTest.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/test/java/org/eclipse/dataspaceconnector/dataplane/selector/store/sql/PostgresDataPlaneInstanceStoreTest.java

Adds a Base class for all SQL store which handle data source registry and JSON mapping.
It also introduces a custom extension for testing PG stores. 
Reduce duplicated code when implementing an SQL based store. 
All SQL store tests can be extended with `PostgresqlStoreSetupExtension` JUnit Extension which eliminates the boilerplate code of the test setup.
Closes #2114

refactor(SqlStore): create a base class for all SQL stores

---

.github/PULL_REQUEST_TEMPLATE.md
pr_etiquette.md

This PR adds description about the rule of PR title to contributor documentation.
Contributor can conform to the rule without seeing the result of GitHub job checking the title.
Closes # 2124

docs: add description about rule of PR title (fixes #2124)

---

core/control-plane/contract-core/README.md
core/control-plane/contract-core/src/main/java/org/eclipse/dataspaceconnector/contract/ContractServiceExtension.java
core/control-plane/transfer-core/README.md
core/control-plane/transfer-core/src/main/java/org/eclipse/dataspaceconnector/transfer/core/CoreTransferExtension.java

Makes the State machines iteration wait times to be configurable.
Currently the iteration wait times on the state machines is hardcoded to 5 seconds, would be good to have them configurable
Closes #2093

feat: make default_iteration_wait on state_machines configurable

---

.github/workflows/verify.yaml
core/common/util/src/testFixtures/java/org/eclipse/edc/util/testfixtures/annotations/ApiTest.java
core/federated-catalog/federated-catalog-core/build.gradle.kts
core/federated-catalog/federated-catalog-core/src/test/java/org/eclipse/edc/catalog/cache/FederatedCatalogCacheEndToEndTest.java
extensions/common/http/jersey-core/build.gradle.kts
extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/ExceptionMappersIntegrationTest.java
extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/validation/integrationtest/ValidationIntegrationTest.java
extensions/control-plane/api/data-management-api/asset-api/build.gradle.kts
extensions/control-plane/api/data-management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/asset/AssetApiControllerIntegrationTest.java
extensions/control-plane/api/data-management-api/catalog-api/build.gradle.kts
extensions/control-plane/api/data-management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
extensions/control-plane/api/data-management-api/contract-agreement-api/build.gradle.kts
extensions/control-plane/api/data-management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/contractagreement/ContractAgreementApiControllerIntegrationTest.java
extensions/control-plane/api/data-management-api/contract-definition-api/build.gradle.kts
extensions/control-plane/api/data-management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
extensions/control-plane/api/data-management-api/contract-negotiation-api/build.gradle.kts
extensions/control-plane/api/data-management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/control-plane/api/data-management-api/policy-definition-api/build.gradle.kts
extensions/control-plane/api/data-management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/policy/PolicyDefinitionApiControllerIntegrationTest.java
extensions/control-plane/api/data-management-api/transfer-process-api/build.gradle.kts
extensions/control-plane/api/data-management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/control-plane/provision/provision-http/build.gradle.kts
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
extensions/data-plane/data-plane-api/build.gradle.kts
extensions/data-plane/data-plane-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlaneApiIntegrationTest.java

Adds `@ApiTest` on all controller integration test for executing them on demand via `-DincludeTags="ApiTest"` 
and creates a separated CI job for executing them
Reduce `./gradlew test` execution time
Closes #2136

feat(api): adds @ApiTest tag for controller integration tests

---

extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Configuration.java
extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Extension.java

Add configurable TOKEN_EXPIRATION in oauth2 extension
The token expiration was hard-coded to 5 mins
Closes #2144

feat(oauth2): adds configuration of TOKEN_EXPIRATION

---

samples/05-file-transfer-cloud/README.md

Correct port of the file transfer process for the data consumer (9192)
The change was necessary because the documentation contained the wrong port (9191)

docs: correct port of the file transfer process for the data consumer (9192)

---

data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/message/FutureCallback.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/edc/protocol/ids/message/FutureCallbackTest.java
extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/mapper/EdcApiExceptionMapper.java
extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/EdcApiExceptionMapperTest.java
extensions/control-plane/api/data-management-api/catalog-api/src/main/java/org/eclipse/edc/connector/api/datamanagement/catalog/CatalogApiController.java
extensions/control-plane/api/data-management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/datamanagement/catalog/CatalogApiControllerIntegrationTest.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/BadGatewayException.java

Improve the error detail when a catalog is requested and the provider connector respond with an error.
Helps debugging
- test covered and refactored the `FutureCallback` class.
Closes #2152

feat: improve catalog request error detail

---

extensions/control-plane/provision/provision-oauth2/build.gradle.kts

Fix module `provision-oauth2` build after junit refactor merge
broken build

fix(build): fix provision-oauth2 module build after junit refactor merge

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplTest.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndexTest.java
extensions/control-plane/provision/provision-oauth2/build.gradle.kts
extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndex.java
extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java
extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/AssetStatements.java
extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/schema/BaseSqlDialectStatements.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QuerySpec.java
spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java

Avoids the default limit of 50 when requesting catalog in certain circumstances.
To achieve that:
- always set `limit` by default at the asset count retrieved by the `countAssets` call in the `ContractOfferResolverImpl.queryContractOffers` method.
- ignore `offset` and `limit` in the `countAssets` implementation, as it should count items filtering by the query, but not restricting the output with a range.
Fix bug
- could we remove set the `QuerySpec.limit`'s default value to `Integer.MAX_VALUE`? As the "security issue" is already handled by `QuerySpecDto`.
Closes #2064

fix: avoid default limit 50 on catalog creation

---

system-tests/tests/src/test/java/org/eclipse/edc/test/system/remote/FileTransferAsClientSimulation.java

removing usage of org.apache.commons:commons-lang3:3.12.0 pulled as transitive dependency of org.mock-server:mockserver-netty:5.14.0.
Relying on transitive dependency should be avoided.
Closes #1747

fix: remove usages of Apache Commons Lang

---

core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
data-protocols/ids/ids-api-configuration/src/main/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtension.java
data-protocols/ids/ids-api-configuration/src/test/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtensionTest.java
extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyExtension.java
extensions/control-plane/api/data-management-api/data-management-api-configuration/src/main/java/org/eclipse/edc/connector/api/datamanagement/configuration/DataManagementApiConfigurationExtension.java
extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/HttpWebhookExtension.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpWebhookExtensionTest.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/WebServer.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfiguration.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurer.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurerImpl.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/configuration/WebServiceSettings.java
spi/common/web-spi/src/test/java/org/eclipse/edc/web/spi/configuration/WebServiceConfigurerImplTest.java

Extract duplicated code when configuring an API extension
removes duplicated code
The common logic/ the default impl for the configurator has been placed in `web::spi` since we don't have yet a common module for web. 
Closes #2128

refactor(apiExtensions): removes duplicated code when configuring an API extension

---

extensions/common/iam/oauth2/oauth2-core/build.gradle.kts
extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Extension.java
extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java
extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImplTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/Result.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java

Adds the retry mechanism through `Failsafe` to `Oauth2ServiceImpl`
To improve resiliency.
- took the opportunity to improve error reporting and refactoring the service a bit 
- add a `compose` method on `Result` that maps the content to another result as it was missing, but it is useful in cases like this.
Closes #2171

feat: add retry mechanism to oauth2 service

---

samples/04.0-file-transfer/README.md
samples/04.0-file-transfer/consumer/build.gradle.kts
samples/04.0-file-transfer/integration-tests/src/test/java/org/eclipse/edc/sample/extension/FileTransferSampleTest.java
samples/04.0-file-transfer/integration-tests/src/testFixtures/java/org/eclipse/edc/sample/extension/FileTransferSampleTestCommon.java
samples/04.0-file-transfer/status-checker/build.gradle.kts
samples/04.0-file-transfer/status-checker/src/main/java/org/eclipse/edc/sample/extension/checker/SampleFileStatusChecker.java
samples/04.0-file-transfer/status-checker/src/main/java/org/eclipse/edc/sample/extension/checker/SampleStatusCheckerExtension.java
samples/04.0-file-transfer/status-checker/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
settings.gradle.kts

Adds a status checker for the file transfer consumer side
Consistent lifecycle of the file transfer on the consumer side.
Closes #1337

feat(samples): adds consumer status checker on file for sample 4

---

core/data-plane/data-plane-framework/build.gradle.kts
core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/store/InMemoryDataPlaneStoreTest.java
extensions/data-plane/store/sql/data-plane-store-sql/README.md
extensions/data-plane/store/sql/data-plane-store-sql/build.gradle.kts
extensions/data-plane/store/sql/data-plane-store-sql/docs/schema.sql
extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStore.java
extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/SqlDataPlaneStoreExtension.java
extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/BaseSqlDataPlaneStatements.java
extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/DataPlaneStatements.java
extensions/data-plane/store/sql/data-plane-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/store/sql/schema/postgres/PostgresDataPlaneStatements.java
extensions/data-plane/store/sql/data-plane-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/data-plane/store/sql/data-plane-store-sql/src/test/java/org/eclipse/edc/connector/dataplane/store/sql/PostgresDataPlaneStoreTest.java
settings.gradle.kts
spi/data-plane/data-plane-spi/build.gradle.kts
spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/store/DataPlaneStore.java
spi/data-plane/data-plane-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/spi/testfixtures/store/DataPlaneStoreTestBase.java

Adds a SQL implementation of `DataPlaneStore`
Currently one an in memory version is provided for the DataPlaneStore.
Closes #2090

feat(DataPlaneStore): implements SQL based storage for DataPlane flow requests

---

.github/ISSUE_TEMPLATE/feature_request.md

Remove "Type of issue" paragraph from `feature_request.md`
cleanup
-
Closes #2196

build: Remove issue type paragraph

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiController.java
core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiController.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiController.java
extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java
spi/common/web-spi/build.gradle.kts
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java

Adds usage of `TranferProcessService` in `TransferProcessControlApiController` instead of interacting directly
with the `TransferProcessManager`
Make the interaction with transfer processes more consistent.
In order to reuse some exception mapping the `ServiceResultHandler` has been moved from `api-core` to `web-spi`
Closes #2175

refactor(controlPlaneApi): Adds usage of TranferProcessService 

---

data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/controller/MultipartController.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/message/MultipartResponse.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/MultipartControllerIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/controller/MultipartControllerTest.java

Returns a security token in an IDS response only if the request is valid and authenticated.
Avoid to create and give a valid token to a potential attacker that could use it to do authenticated malicious calls.
-
Closes #2201

fix: avoid a security token in the response if the request is not valid

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/util/ResponseUtil.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/util/ResponseUtilTest.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java

Calls the `TransferProcessService` instead of the `TransferProcessManager` to initiate a new provider process in the `ArtifactRequestHandler`.
To handle the interaction with the `TransferProcessManager` in a consistent manner.
Adds an additional method to the `TransferProcessService` for initiating a provider process. Since the agreement referenced for the transfer always needs to be re-evaluated on provider side before the actual transfer is started, this validation was moved from the `ArtifactRequestHandler` to that method.
Closes #2180

refactor: use TransferProcessService in ArtifactRequestHandler

---

extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStoreExtension.java

Replaces the last occurence of the deprecated annotation `@EdcSetting` with `@Setting`.
So that the deprecated annotations can safely be removed.

chore: replace deprecated EdcSetting annotation

---

core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/transferprocess/TransferProcessControlApiController.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementApiController.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiController.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiController.java
extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/Failure.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/result/ResultTest.java
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/ServiceResultHandler.java

Refactor handling the result on all service all from controllers. 
Reduce duplicated code on result checking and exception mapping
The API `AbstractResult#orElseThrow` has been changed in order to unwrap the underlying content or throw an exception if the result is not ok.
Closes #2182

refactor(ServiceResultHandler): changed ServiceResultHandler#mapToException

---

extensions/data-plane/store/cosmos/data-plane-store-cosmos/README.md
extensions/data-plane/store/cosmos/data-plane-store-cosmos/build.gradle.kts
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreConfig.java
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreExtension.java
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/model/DataFlowRequestDocument.java
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStoreIntegrationTest.java
settings.gradle.kts

Adds a Cosmos implementation of `DataPlaneStore`
Closes #2091

feat(DataPlaneStore): adds Cosmos implementation for DataPlaneStore

---

docs/swaggerui/swagger-spec.js
resources/openapi/openapi.yaml
resources/openapi/yaml/api-observability.yaml

update OpenAPI definitions
fix failing CI on `main`
.
.

fix(build): update openapi definitions

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
extensions/control-plane/provision/provision-http/build.gradle.kts
extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/HttpWebhookExtension.java
extensions/control-plane/provision/provision-http/src/main/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiController.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpWebhookExtensionTest.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/transferprocess/TransferProcessService.java

Use the `TransferProcessService` instead of interacting directly with the `TransferProcessManager`
Encapsulate checks and business logic inside the `TransferProcessService`
Closes #2193

feat(HttpProvisioner): use TransferProcessService in the controller

---

resources/ci/discord_webhook.sh

Adds a script, that is executed by a dedicated Jenkins Job called [Send Discord Webhook](https://ci.eclipse.org/dataspaceconnector/job/Send%20Discord%20Webhook/). 
Notifications in Discord about succeeding/failing Jenkins Jobs
- The Job in question is in turn triggered by upstream SNAPSHOT builds, e.g. the EDC-Snapshot
- I put this file in the EDC repo, because the "Send Discord Webhok" jenkins job can then checkout the repo and use the script.
- I opted against dedicated jenkins plugins because having a script using the Discord API is likely quicker, more controllable and could be re-used, e.g. from Github Actions
_Currently this is only enabled for snapshot builds_

feat(build): add shell script to invoke Discord webhook

---

.github/workflows/trigger_snapshot.yml

Explicitly triggers Jenkins on every build on the `main` branch.
more reactive build
.
Closes #2234

build: add workflow to explicitly trigger EDC jenkins

---

.github/workflows/discord-webhook.yml

Setup notifications to discord on new issues, PRs and discussions. 
Improve working on GitHub
The messages include the name of the author, the title of the created item, a link to it, and information about the type and repo.
Example:
Relates to #1687

feat: add discord webhooks for issues, discussions and pull requests

---

README.md
docs/developer/openapi.md

Fix docs link after org renaming
The link is broken

chore: fix docs link

---

.github/workflows/assign-pr-to-project.yaml
extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java
extensions/common/http/jersey-core/src/test/java/org/eclipse/edc/web/jersey/mapper/ExceptionMappersIntegrationTest.java
extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java
extensions/common/http/jetty-core/src/test/java/org/eclipse/edc/web/jetty/JettyServiceTest.java
extensions/data-plane/data-plane-api/src/test/java/org/eclipse/edc/connector/dataplane/api/controller/DataPlaneApiIntegrationTest.java

Avoid setting `contextPath` on the `ServletContextHandler`, setting it as a servlet mapping
Currently the `/public` endpoint of the dataplane returns 302
-
Closes #2242

feat: support `/public` endpoint without trailing slash

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/dataaddress/DataAddressValidatorImpl.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/dataaddress/DataAddressValidatorImplTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiExtension.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/DataAddressDtoToDataAddressTransformer.java
extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/transform/DataAddressDtoToDataAddressTransformerTest.java
extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/edc/connector/dataplane/transfer/sync/proxy/DataPlaneTransferConsumerProxyTransformerTest.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/dataaddress/DataAddressValidator.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/HttpDataAddress.java

Introduce a new `DataAddressValidator` component, that takes case of validate any `DataAddress` that is going to be ingested by the system, currently in two different points: on `Asset` creation and on `TransferProcess` initialization.
Currently it validates the `baseUrl` field of `HttpData` data address, that must be a valid 
To fail fast in case of not well formatted data addresses.
- this is a simple version, but it could be made extensible if needed to give the opportunity to add validation for other types of `DataAddress` (e.g. s3, gcs, ...)
Closes #2235

feat: Add basic HttpDataAddress validation

---

spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java

removes an `{@param ....}` tag from the javadoc.
Gradle's `javadoc` task complained, causing the CI build to fail.
https://ci.eclipse.org/edc/job/Playground/job/Build-Component-Template/19/console

fix(javadoc): removed erronous tag

---

core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStore.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/command/handlers/SingleTransferProcessCommandHandler.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/CancelTransferCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/CompleteTransferCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/FailTransferCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplIntegrationTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStoreIntegrationTest.java
extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
samples/04.2-modify-transferprocess/simulator/src/main/java/org/eclipse/edc/sample/extension/transfer/TransferSimulationExtension.java
samples/04.2-modify-transferprocess/watchdog/src/main/java/org/eclipse/edc/sample/extension/watchdog/CheckTimeoutCommandHandler.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/store/TransferProcessStore.java
spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java

Replace `create` and `update` methods with `save` method that has upsert semantics
Consistency with other stores.
Closes #2224

refactor(TransferProcessStore): replaces create and update api with save with support of upsert

---

.github/workflows/trigger_snapshot.yml

Adds a condition to the Jenkins Snapshot trigger Job, so that only the upstream project may execute the job.
Forks may not trigger our EDC Jenkins.
- contrary to my solution proposal in the issue, I opted for flat-out disallowing forks to trigger the job _in general_ because forks may not use our EDC Jenkins instance, even if there are credentials present.
Closes #2256

fix(build): only the upstream project may trigger jenkins

---

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
core/control-plane/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
core/control-plane/control-plane-api/build.gradle.kts
core/control-plane/control-plane-api/src/main/java/org/eclipse/edc/connector/api/ControlPlaneApiExtension.java
core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/ControlPlaneApiExtensionTest.java
core/control-plane/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
extensions/common/api/control-api-configuration/README.md
extensions/common/api/control-api-configuration/build.gradle.kts
extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfiguration.java
extensions/common/api/control-api-configuration/src/main/java/org/eclipse/edc/connector/api/control/configuration/ControlApiConfigurationExtension.java
extensions/common/api/control-api-configuration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/common/http/jetty-core/src/main/java/org/eclipse/edc/web/jetty/JettyService.java
extensions/common/http/jetty-core/src/test/java/org/eclipse/edc/web/jetty/JettyServiceTest.java
extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/build.gradle.kts
extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/edc/connector/dataplane/transfer/sync/DataPlaneTransferSyncExtension.java
extensions/data-plane/data-plane-api/build.gradle.kts
extensions/data-plane/data-plane-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneApiExtension.java
resources/openapi/openapi.yaml
settings.gradle.kts
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java

Moves all the `control` APIs under the `control` context
Api restructure
-
Closes #2186

refactor: move `control` api endpoints under `control` context

---

extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/README.md
extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/edc/connector/dataplane/transfer/sync/DataPlaneTransferSyncExtension.java
extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/edc/connector/dataplane/transfer/sync/proxy/EmbeddedDataPlaneTransferProxyResolve.java
extensions/control-plane/data-plane-transfer/data-plane-transfer-sync/src/test/java/org/eclipse/edc/connector/dataplane/transfer/sync/proxy/EmbeddedPlaneTransferProxyResolverTest.java
extensions/data-plane/data-plane-api/src/main/java/org/eclipse/edc/connector/dataplane/api/DataPlaneApiExtension.java
spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/DataPlanePublicApiUrl.java

Registers a different DataPlane proxy when working with embedded data-plane which points
to the data plane `/public` api of the same runtime .
simplify test environments and samples
Closes #2226

feat(dataPlane): register a different resolve strategy when working with embedded data-plane

---

data-protocols/ids/ids-api-configuration/build.gradle.kts
data-protocols/ids/ids-api-configuration/src/main/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtension.java
data-protocols/ids/ids-api-configuration/src/test/java/org/eclipse/edc/protocol/ids/api/configuration/IdsApiConfigurationExtensionTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/IdsMultipartApiServiceExtension.java

Rename `ids` api context to `protocol`
Api restructure
- the  `ids` context name is deprecated, to be removed in the next releases
Closes #2187

refactor: Rename `ids` api context to `protocol`

---

docs/developer/decision-records/2022-12-05-edc-http-client/README.md
docs/developer/decision-records/README.md

Add decision record for `EdcHttpClient` that's a wrapper around `OkHttpClient` and `Failsafe` that will provide retry mechanism out-of-the-box. Ref. #1566 
document
-
Ref #1566

docs: provide decision record for EdcHttpClient

---

extensions/common/iam/oauth2/oauth2-core/README.md
extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2Extension.java
extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/Oauth2ExtensionTest.java
extensions/common/iam/oauth2/oauth2-daps/src/test/java/org/eclipse/edc/iam/oauth2/daps/DapsIntegrationTest.java
launchers/ids-connector/README.md
launchers/ids-connector/config.properties

Renames ` edc.oauth.public.key.alias` to `edc.oauth.certificate.alias`
clarity
Closes #2257

feat(oauth): renames  edc.oauth.public.key.alias to edc.oauth.certificate.alias

---

docs/developer/decision-records/2022-12-07-transaction-synchronization/README.md
docs/developer/decision-records/README.md

Adds a decision record for transaction synchronization.
docs

docs: add decision record for transaction synchronization

---

extensions/common/transaction/transaction-atomikos/src/main/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionContext.java
extensions/common/transaction/transaction-atomikos/src/test/java/org/eclipse/edc/transaction/atomikos/AtomikosTransactionContextTest.java
extensions/common/transaction/transaction-local/src/main/java/org/eclipse/edc/transaction/local/LocalTransactionContext.java
extensions/common/transaction/transaction-local/src/test/java/org/eclipse/edc/transaction/local/LocalTransactionContextTest.java
spi/common/transaction-spi/src/main/java/org/eclipse/edc/transaction/spi/NoopTransactionContext.java
spi/common/transaction-spi/src/main/java/org/eclipse/edc/transaction/spi/TransactionContext.java
spi/common/transaction-spi/src/test/java/org/eclipse/edc/transaction/spi/NoopTransactionContextTest.java

Adds support transaction synchronization.
Refer to the Decision Record for transaction synchronization #2311.
Closes #2317.

feat: add support for transaction synchronization

---

core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/EntitySendRetryManager.java
core/common/state-machine/src/main/java/org/eclipse/edc/statemachine/retry/SendRetryManager.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/ContractNegotiationCommandExtension.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandler.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/ContractNegotiationCommandQueueIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
extensions/control-plane/api/management-api/catalog-api/src/test/java/org/eclipse/edc/connector/api/management/catalog/CatalogApiControllerIntegrationTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/command/DeclineNegotiationCommand.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java

Introduce a `decline` command and make the `ContractNegotiationApiController` launch it.
The current `/decline` endpoint is not declining the negotiation on both sides.
- improved the `SendRetryManager` interface, as it caused a lot of warnings due to bad design.
Closes #2259

fix: make negotiation api launch a `decline` command

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ContractAgreementHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/MultipartControllerIntegrationTest.java
data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/edc/protocol/ids/transform/type/contract/ContractAgreementFromIdsContractAgreementTransformer.java
data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/edc/protocol/ids/transform/type/policy/PermissionToIdsPermissionTransformer.java
data-protocols/ids/ids-transform-v1/src/test/java/org/eclipse/edc/protocol/ids/transform/ContractAgreementFromIdsContractAgreementTransformerTest.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java

Set the `ContractAgreement.assetId` field with the value coming out from the "IDS to EDC" model transformation, so it won't report the `urn:artifact` prefix
Bugfix
- moved some transformation logic that was in the `ContractAgreementHandler` to the `ContractAgreementFromIdsContractAgreementTransformer`
- these `ContractNegotiationIntegrationTest` are pure evil! I think they deserve some love.
- What's the point of having the logic for "counter offers" that's actually dead code? (`ConsumerContractNegotiationManager.offerReceived` is only called by tests). I would propose to remove all that logic since it will need to be re-engineered when actual use-cases will come. Follow-up issue will come (#2326)
Closes #2318

fix: correctly transform assetId back from IDS infomodel

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java

…onding unit tests
change the ValidateAgremment() return Type from boolean to Result<ContractAgreement>.
The change was to get the corresponding information as a user during the validation of the agreement.
Closes #2211

chore(ContractValidationService): change return type of validateAgreement from boolean to Result

---

README.md
docs/developer/architecture/README.md
docs/developer/architecture/terminology.md
docs/developer/decision-records/2022-02-10-code-coverage/README.md
docs/developer/decision-records/2022-04-21-dpf-blob-data-transfer/README.md
docs/developer/metrics.md
extensions/common/events/events-cloud-http/README.md
launchers/ids-connector/README.md
samples/04.1-file-transfer-listener/README.md
samples/04.3-open-telemetry/README.md
samples/README.md

Fixes markdown errors. 
Allow any frameworks to interpret markdown files correctly.
Changed "Eclipse Dataspace Connector" in `README.md` to "EDC Connector" to follow the renaming
Closes #2337

fix(docs): resolve markdown syntax errors

---

data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/serialization/IdsTypeManagerUtil.java
data-protocols/ids/ids-jsonld-serdes/src/test/java/org/eclipse/edc/protocol/ids/jsonld/SerializationTest.java
spi/common/transaction-spi/src/test/java/org/eclipse/edc/transaction/spi/NoopTransactionContextTest.java

Remove the `AbstractConstraint.class` serializer, that in fact was making the `LogicalOperator` not working.
To make logical constraints (or, and) work through ids.
-
Closes #2334

fix: make logical constraint serdes work

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/DescriptionRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/handler/DescriptionRequestHandlerTest.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/IdsCoreServiceExtension.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/service/CatalogServiceImpl.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/service/ConnectorServiceImpl.java
data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/util/ConnectorIdUtil.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/edc/protocol/ids/service/CatalogServiceImplTest.java
data-protocols/ids/ids-core/src/test/java/org/eclipse/edc/protocol/ids/service/ConnectorServiceImplTest.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/edc/protocol/ids/spi/service/CatalogService.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/edc/protocol/ids/spi/service/ConnectorService.java
data-protocols/ids/ids-spi/src/main/java/org/eclipse/edc/protocol/ids/spi/types/container/DescriptionRequest.java
spi/common/transaction-spi/src/test/java/org/eclipse/edc/transaction/spi/NoopTransactionContextTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/offer/ContractOfferQuery.java
system-tests/e2e-transfer-test/backend-service/src/main/java/org/eclipse/edc/test/e2e/BackendServiceTestExtension.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java

Set the correct `provider` (connector id) and `consumer` (issuer connector) fields on the `ContractOffer`
likely these fields will be removed from the contract offer in the future, but in the meantime better value them correctly since they are provided
Fix bug #753 
- introduced a `DescriptionRequest` data class that contains some fields necessary for the description request
- refactored `DescriptionRequestHandler` because it was hard to read with those 2 switch-case blocks.
Closes #753

fix: set correct `consumer` and `provider` ids on `ContractOffer`

---

.github/workflows/assign-issue-to-project.yaml
.github/workflows/assign-pr-to-project.yaml
CONTRIBUTING.md

updates references to the new project URL: https://github.com/orgs/eclipse-edc/projects/3
Fix CI

fix: project url

---

core/common/connector-core/README.md
core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java
core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/RetryPolicyFactory.java
core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/RetryPolicyFactoryTest.java

Gives the possibility to log `Failsafe` events by enabling specific settings
Improve debug experience
-
Closes #2351

feat: log `Failsafe` events

---

core/common/connector-core/build.gradle.kts
core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreDefaultServicesExtension.java
core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/base/EdcHttpClientImpl.java
core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/security/DefaultPrivateKeyParseFunction.java
core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/base/EdcHttpClientImplTest.java
core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/security/DefaultPrivateKeyParseFunctionTest.java
core/common/junit/src/main/java/org/eclipse/edc/junit/testfixtures/TestUtils.java
extensions/common/iam/oauth2/oauth2-client/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ClientExtension.java
extensions/common/iam/oauth2/oauth2-client/src/main/java/org/eclipse/edc/iam/oauth2/client/Oauth2ClientImpl.java
extensions/common/iam/oauth2/oauth2-client/src/test/java/org/eclipse/edc/iam/oauth2/client/Oauth2ClientImplTest.java
extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImpl.java
extensions/common/iam/oauth2/oauth2-core/src/test/java/org/eclipse/edc/iam/oauth2/identity/Oauth2ServiceImplTest.java
spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/EdcHttpClient.java
spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/EdcHttpClientException.java
spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/FallbackFactories.java
spi/common/http-spi/src/main/java/org/eclipse/edc/spi/http/FallbackFactory.java

Adds two methods to `EdcHttpClient`:
```
<T> Result<T> execute(Request request, Function<Response, Result<T>> mappingFunction)
<T> Result<T> execute(Request request, List<FallbackFactory> fallbacks, Function<Response, Result<T>> mappingFunction)
```
First one is just a shortcut to call the second one without `fallbacks`.
In `Failsafe`, a `Fallback` is an object that permits to apply retry also after a `Response` is received from the `OkHttpClient`, in particular it can be used to retry when the status result is not "successful" (not contained between 200 and 299) or is not a specific state. This is useful to retry calls when flaky statuses as `503 - service unavailable` are returned.
Improve resiliency
- the methods accept a `mappingFunction` that will apply on the `Response`, so it will …

feat: Introduce `Fallback` mechanism to `EdcHttpClient`

---

extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApi.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiController.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/AssetApiExtension.java
extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/transform/DataAddressToDataAddressDtoTransformer.java
extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerIntegrationTest.java
extensions/control-plane/api/management-api/asset-api/src/test/java/org/eclipse/edc/connector/api/management/asset/AssetApiControllerTest.java
resources/openapi/yaml/management-api/asset-api.yaml

Adds `/assets/{id}/address` endpoint to asset mgmt for getting the data address of an asset by the asset id
api enhancement
Closes #2363

feat(assetApi): adds endpoint for getting a DataAddress of an Asset

---

core/common/connector-core/build.gradle.kts
extensions/common/vault/vault-filesystem/build.gradle.kts
extensions/control-plane/transfer/transfer-data-plane/build.gradle.kts
extensions/data-plane/data-plane-azure-data-factory/build.gradle.kts

Bumps BouncyCastle to 1.72 Jdk18on
dependency update

build(deps): bump BouncyCastle to 1.72 Jdk18on

---

docs/developer/architecture/README.md
docs/developer/command-queue.md
docs/developer/metrics.md

Updates the links to samples in the documentation.
The links to samples have changed after the restructuring of the samples repository.

chore: update sample links

---

.github/workflows/apidoc.yaml

Run the publish job only when the event is a `push` on the upstream `main` branch
To avoid failures
Closes #2397

fix: publish to swaggerhub only on upstream main branch pushes

---

extensions/common/iam/oauth2/oauth2-client/src/main/java/org/eclipse/edc/iam/oauth2/client/Oauth2ClientImpl.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/README.md
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactory.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2DataAddressSchema.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionExtension.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2Provisioner.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/main/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ResourceDefinition.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2CredentialsRequestFactoryTest.java
extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/src/test/java/org/eclipse/edc/connector/provision/oauth2/Oauth2ProvisionerTest.java

Permits to add a `scope` parameter to the token request in the `provision-oauth2` extension
Some cases require it
- extracted a `Factory` that takes care of building the request object, this permitted to simplify the provisioner logic
Closes #2406

feat: add scope parameter to oauth2 provisioner

---

.github/dependabot.yml

Stops dependabot from opening PR to update `edc-versions`
the main branch sticks on `0.0.1-SNAPSHOT` version
Closes #2343

build: stops dependabot opening update PR on `edc-versions`

---

.github/dependabot.yml

Add the full dependency reference.
The current definition does not work
Closes #2343

build: fix dependabot edc-versions ignore entry

---

extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3Extension.java
extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java

Adds the support for key and secret from the vault
security improvement
Closes #2364

feat(dataPlaneS3): adds support for vault on data source address

---

docs/developer/decision-records/2023-02-10-nightly-builds/README.md

Adds a decision record about nightly builds becoming release versions instead of snapshots.
Will enable downstream projects to have repeatable builds other than milestones.
_Another PR to do the actual work will be created in the plugins repo and the pipelines repo_
Closes #2481

feat: decision record about nightly builds

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImplTest.java

- Adds test cases to evaluate catalog pagination across multiple contract definitions.
- Changes the logic which dynamically builds the offset and limit for each contract definition.
Previously the number of assets that should be skipped in the current iteration was dynamic but the limit was not, which caused the pagination to fail when across multiple contract definitions.
I decided to use a different approach that for me was easier to understand.
Based on the given range, the absolute offset and limit are static but could assume a different state on each iteration responding to the number of seen and fetched assets until that point. Therefore, I implemented the logic that sets the values of the dynamic offset and limit variables in the following expressions:
- The dynamic offset must be …

fix: catalog pagination

---

core/common/boot/src/main/java/org/eclipse/edc/boot/system/DefaultServiceExtensionContext.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/configuration/ConfigFactory.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/configuration/ConfigImpl.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/system/configuration/ConfigFactoryTest.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/system/configuration/ConfigImplTest.java

Move the `ENV_KEY_FORMAT` to `env.key.format` conversion to a dedicated method in `ConfigFactory`.
Permit to use settings with `snakeCase` format.
- add some missing documentation on `ConfigFactory`
Closes #2295

fix: permit `Config` keys with snakeCase format

---

docs/developer/decision-records/2023-02-22-update-entities/README.md
docs/developer/decision-records/README.md

Adds a decision record about `PUT` endpoints (entity updates)
To outline the technical concept and delineation of the "update" feature.
.
Closes #2507

docs: add decision record about PUT endpoints

---

docs/developer/decision-records/2023-02-22-contract-definition-validation/README.md
docs/developer/decision-records/README.md

Adds a Decision Record  for `ContractDefinition` validation

docs: decision record for ContractDefinition validation

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractdefinition/ContractDefinitionEventListener.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractdefinition/ContractDefinitionServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractdefinition/ContractDefinitionServiceImplTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApi.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiController.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiExtension.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionCreateDto.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionRequestDto.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionUpdateDto.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionUpdateDtoWrapper.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/transform/ContractDefinitionUpdateDtoWrapperToContractDefinitionTransformer.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiControllerIntegrationTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiControllerTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionCreateDtoTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionCreateDtoValidationTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionUpdateDtoTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/model/ContractDefinitionUpdateDtoValidationTest.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/transform/ContractDefinitionRequestDtoToContractDefinitionTransformerTest.java
resources/openapi/yaml/management-api/contract-definition-api.yaml
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractdefinition/ContractDefinitionUpdated.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/definition/observe/ContractDefinitionListener.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractdefinition/ContractDefinitionService.java

Add the `UPDATE` endpoint to the `ContractDefinitionApi`
to enable update semantics on contract definitions
- I created `ContractDefinitionUpdateDto` for updating the contract definition (same as ContractDefinitionRequestDto without the id)
- I created `ContractDefinitionUpdateDtoWrapper` which is a composition of `ContractDefinitionUpdateDto` + id to update
- The `ContractDefinitionUpdateDtoWrapper` is then transformed through the transformer registry into the final `ContractDefinition` to update
Closes #2510

feat: add update endpoint for ContractDefinition

---

build.gradle.kts
docs/developer/build-your-own-connector.md
gradle/wrapper/gradle-wrapper.properties
launchers/data-plane-server/build.gradle.kts
launchers/dpf-selector/build.gradle.kts
launchers/ids-connector/build.gradle.kts
system-tests/runtimes/azure-data-factory-transfer-consumer/build.gradle.kts
system-tests/runtimes/azure-data-factory-transfer-provider/build.gradle.kts
system-tests/runtimes/azure-storage-transfer-consumer/build.gradle.kts
system-tests/runtimes/azure-storage-transfer-provider/build.gradle.kts
system-tests/runtimes/file-transfer-consumer/build.gradle.kts
system-tests/runtimes/file-transfer-provider/build.gradle.kts

Upgrades to Gradle v8.0 and the shadow plugin to v8.0.
Keep up-to-date with developments, avoid technical debt.
**the CI on this PR will fail unless https://github.com/eclipse-edc/GradlePlugins/pull/89 is merged, as it lays the necessary ground work!**
Closes #

chore: upgrade to gradle 8, upgrade the shadow plugin

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java

Removes the check on `ContractDefinition` when validating the contract agreement
The `ContractDefinition` is not required at this point, since all the info for validating the contract
are in the contract itself.
Closes #2517

feat(ContractValidation): removes the check on ContractDefinition when validating an agreement

---

docs/developer/decision-records/2023-03-02_entity_store_refactoring/README.md

Adds a decision record about the projected `*store` refactoring.
Establish more consistency across our stores and request semantics.
.
Closes #2535

docs: add decision record about store refactoring

---

build.gradle.kts
spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
spi/common/aggregate-service-spi/src/test/java/org/eclipse/edc/service/spi/result/ServiceResultTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreFailure.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java

- Renames `ServiceResult` -> `RequestResult` and `ServiceFailure` -> `RequestFailure`
- Moves the `RequestResult` and `RequestFailure` to the `core-spi` module
- deleted the now-empty `aggregate-service-spi` module and references to it
_this is just renaming and moving, no functional change was performed_
Make these two classes accessible to more core features like entity stores
- I also uncommented a line in the root `build.gradle.kts`, which I assume slipped in by mistake
Closes #2545

refactor: rename and move ServiceResult

---

extensions/common/azure/azure-cosmos-core/src/main/java/org/eclipse/edc/azure/cosmos/CosmosDbApi.java
extensions/common/azure/azure-cosmos-core/src/main/java/org/eclipse/edc/azure/cosmos/CosmosDbApiImpl.java
extensions/common/azure/azure-cosmos-core/src/test/java/org/eclipse/edc/azure/cosmos/CosmosDbApiImplIntegrationTest.java
extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndex.java
extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractdefinition/CosmosContractDefinitionStore.java
extensions/control-plane/store/cosmos/contract-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractdefinition/CosmosContractDefinitionStoreTest.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStore.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStore.java
extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreTest.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStore.java
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
spi/common/aggregate-service-spi/src/test/java/org/eclipse/edc/service/spi/result/ServiceResultTest.java

Replaces the `saveItem` method of the `CosmosDbApi` with a dedicated `create()` and `update()` method, both of which in turn call the `createItem` and `replaceItem` methods of the Cosmos SDK.
Preparatory work for #2531 
- Any exceptions coming from the CosmosSDK are not wrapped in an `EdcException` anymore, the calling store implementations must handle a `NotFoundException` and a `ConflictException`
- Subsequent work (#2536 #2537 #2538 #2539) will add code to handle the exceptions and convert them into `StoreResult`s
Closes #2531

refactor: add create update to cosmos api

---

spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/offer/store/ContractDefinitionStore.java

Fixes the Javadoc in the `ContractDefinitionStore`
Currently it fails to generate the Javadoc

chore(ContractDefinitionStore): fix javadoc typo on ContratDefinitionStore

---

core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorServiceImpl.java
core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/core/DataPlaneSelectorExtension.java
core/data-plane-selector/data-plane-selector-core/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/InMemoryDataPlaneInstanceStore.java
extensions/data-plane-selector/data-plane-selector-api/build.gradle.kts
extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiController.java
extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/DataPlaneSelectorApiExtensionTest.java
extensions/data-plane-selector/data-plane-selector-api/src/test/java/org/eclipse/edc/connector/dataplane/selector/api/DataplaneSelectorApiControllerIntegrationTest.java
extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStore.java
extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreExtension.java
extensions/data-plane-selector/store/cosmos/data-plane-instance-store-cosmos/src/test/java/org/eclipse/edc/connector/dataplane/selector/store/cosmos/CosmosDataPlaneInstanceStoreIntegrationTest.java
extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java
spi/data-plane-selector/data-plane-selector-spi/build.gradle.kts
spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/DataPlaneSelectorService.java
spi/data-plane-selector/data-plane-selector-spi/src/main/java/org/eclipse/edc/connector/dataplane/selector/spi/store/DataPlaneInstanceStore.java
spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java

Refactor the `DataPlaneInstanceStore` as follows:
- Removed upsert semantic
- Added specific update method
- Introduced StoreResult for `create`, `update`  operations
- Removed  `saveAll(Collections)` APIs
to unify the store implementation, keep code paths clean and separate
The Upsert semantic has been moved to the service layer until we support updating instances
also in the HTTP layer
Closes #2556

refactor(DataPlaneInstanceStore): removed upsert semantic and introduced results on CU operations

---

.github/workflows/verify.yaml
core/common/junit/src/main/java/org/eclipse/edc/junit/extensions/EdcRuntimeExtension.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStore.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreIntegrationTest.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreTest.java
extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStore.java
extensions/control-plane/store/cosmos/policy-definition-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/policydefinition/CosmosPolicyDefinitionStoreIntegrationTest.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
extensions/data-plane/store/cosmos/data-plane-store-cosmos/src/main/java/org/eclipse/edc/connector/dataplane/store/cosmos/CosmosDataPlaneStore.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java
spi/data-plane-selector/data-plane-selector-spi/src/testFixtures/java/org/eclipse/edc/connector/dataplane/selector/spi/testfixtures/store/DataPlaneInstanceStoreTestBase.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/EndToEndTransferCosmosDbTest.java
system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/Participant.java

This PR does two things:
- fixes some broken CosmosDB tests
- simplifies the check in `verify.yaml` whether or not to actually run the Cosmos tests.
Some test were simply broken due to misconfiguration, e.g. the `EndToEndTransferCosmosDbTest` used the same Cosmos database and containers for both the `Provider` and the `Consumer`, causing them to overwrite each other's entries. 
Other tests were broken due to the recent distinction between `createItem()` and `updateItem()`, replacing the previous `upsert()`, which caused exceptions and assertion errors.
As for the check in the `verify.yaml`: it apparently didn't work (or stopped working at some point in time), causing the Cosmos tests to not have been executed.
Now, the check is simplified to `if: env.COSMOS_KEY`, checking if the …

fix: repair cosmos tests and simplify GH action check

---

core/data-plane/data-plane-framework/src/test/java/org/eclipse/edc/connector/dataplane/framework/e2e/EndToEndTest.java
core/data-plane/data-plane-util/src/main/java/org/eclipse/edc/connector/dataplane/util/sink/OutputStreamDataSinkFactory.java
core/data-plane/data-plane-util/src/test/java/org/eclipse/edc/connector/dataplane/util/sink/OutputStreamDataSinkFactoryTest.java
extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactory.java
extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactory.java
extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkFactoryTest.java
extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceFactoryTest.java
extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactory.java
extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSourceFactory.java
extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactoryTest.java
extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSourceFactoryTest.java
extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSinkFactory.java
extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSourceFactory.java
extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSinkFactoryTest.java
extensions/data-plane/data-plane-google-storage/src/test/java/org/eclipse/edc/connector/dataplane/gcp/storage/GcsDataSourceFactoryTest.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactory.java
extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactory.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSinkFactoryTest.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceFactoryTest.java
spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSinkFactory.java
spi/data-plane/data-plane-spi/src/main/java/org/eclipse/edc/connector/dataplane/spi/pipeline/DataSourceFactory.java
system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/edc/test/extension/api/FileTransferDataSinkFactory.java
system-tests/runtimes/file-transfer-provider/src/main/java/org/eclipse/edc/test/extension/api/FileTransferDataSourceFactory.java

Currently, both 'DataSourceFactory' and 'DataSinkFactory' have validation method from the type Result<Boolean> but we want them to be represented by as simpler which is Result<Void> 
To make the Validation check result more clear when it is used
Closes #2498

chore: simplify DataSourceFactory and DataSinkFactory APIs

---

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/type/MultipartTransferRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/type/MultipartTransferRequestSenderTest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/DataRequest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferCompletionMessage.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRequestMessage.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferStartMessage.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java

Remove `RemoteMessage` interface declaration from `DataRequest` and introduce a dedicate `TransferRequestMessage`. Replaces `MultipartArtifactRequestSender` with `MultipartTransferRequestSender`.
decoupling
- add some missing documentation on remote messages
Closes #2564

refactor: separate `DataRequest` from `RemoteMessage`

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractAgreementVerificationMessage.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractNegotiationEventMessage.java

Adds `correlationId` to `ContractAgreementVerificationMessage` and `ContractNegotiationEventMessage`.
The dataspace protocol delegates need the `negotiationId` to build the URL for the request.
Sry, missed that in #2595
Closes #2617

feat(negotiation): add correlationId to new RemoteMessages

---

build.gradle.kts
docs/developer/releases.md
gradle.properties
settings.gradle.kts

- avoid `defaultVersion`, that's not needed, 
- remove `projectVersion.set(actualVersion)` that's not used anymore
- add `mavenLocal` as repository for plugin management (used in the Release repo for the release process)

fix: cleanup version to fix release

---

build.gradle.kts
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/listener/ContractNegotiationEventListener.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/AbstractContractNegotiationManager.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/DispatchFailure.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/DispatchFailure.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
settings.gradle.kts
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventEnvelope.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationConsumerAgreed.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationConsumerRequested.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationConsumerVerified.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationDeclined.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationFailed.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationProviderAgreed.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationProviderFinalized.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/contractnegotiation/ContractNegotiationProviderOffered.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/event/EventTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/observe/ContractNegotiationListener.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java

Add missing event dispatch on state changes
dataspace protocol implementation
- renamed `transition` methods on `ContractNegotiation` and `TransferProcess` to match with the actual DSP states
- introduced parameterized tests for dispatch failure both for CN and TP managers. This cleaned up the test classes a lot.
Closes #2603

feat(dsp): new event dispatch on state changes

---

extensions/common/json-ld/build.gradle.kts
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdKeywords.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/util/JsonLdUtil.java
extensions/common/json-ld/src/main/resources/META-INF/resources/org.eclipse.edc.spi.system.ServiceExtension
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/util/JsonLdUtilTest.java
settings.gradle.kts

Adds an extension that provides an ObjectMapper for working with JSON-LD and utility functions for expanding and compacting JSON-LD structures.
JSON-LD support is required for the dataspace protocol implementation.
Transformers that handle the mapping between EDC model and JSON-LD will be added in a separate PR.
Relates #2474

feat: add json-ld module

---

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdKeywords.java

the `@see` tag was misused and caused jenkins to break: https://ci.eclipse.org/edc/job/Publish-Component/

fix: javadoc compilation

---

core/common/boot/src/main/java/org/eclipse/edc/boot/monitor/MonitorProvider.java

Update expected version of slf4j API of SLF4JServiceProvider implementation.
to fix warnings like:
```
S3StatusCheckerIntegrationTest STANDARD_ERROR
SLF4J: The requested version 1.8 by your slf4j binding is not compatible with [2.0]
SLF4J: See https://www.slf4j.org/codes.html#version_mismatch for further details.
```
EDC now [expects slf4j-api 2.0.7](https://github.com/eclipse-edc/GradlePlugins/blob/be9b4417bbe483590e3d348827d88b8699d6480b/gradle/libs.versions.toml#L38).
Closes #2654

fix: update expected slf4j-api version of MonitorProvider

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/ControlPlaneServicesExtension.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/IdsMultipartApiServiceExtension.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ContractAgreementHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ContractRejectionHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ContractRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/util/ResponseUtil.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/MultipartControllerIntegrationTest.java
spi/common/aggregate-service-spi/src/main/java/org/eclipse/edc/service/spi/result/ServiceResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/message/RemoteMessageDispatcherRegistry.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/response/StatusResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/AbstractResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/Result.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/result/StoreResult.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/system/health/HealthCheckResult.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ConsumerContractNegotiationManager.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ProviderContractNegotiationManager.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractnegotiation/ContractNegotiationService.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java
system-tests/tests/src/test/java/org/eclipse/edc/test/system/local/TracingIntegrationTest.java

Adds missing methods on `ContractNegotiationService` that will permit the DSP controller to ingest an incoming `RemoteMessage` to the service
refactoring
- at this point is pretty clear the `*ed` public methods on the managers could be inlined, or their logic being put into  command/command handlers (to follow a pattern that we're currently following). I left this refactoring for the future to avoid conflicts with #2630 
- set `correlationId` also on consumer side, this will simplify the "fetch" logic a bit, because the correlationId will become the key used both by consumer and provider to retrieve the negotiation from the store.
- pulled up `Result.flatMap` to `AbstractResult`, so every other `*Result` could use it (really handy to convert from an `AbstractResult` extension to another …

feat(dsp): add missing notify methods on `ContractNegotiationService`

---

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/AbstractJsonLdTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/JsonLdTransformer.java

Removes remaining @see tags from `json-ld` module.
The usage of @see causes the javadoc task to fail.

fix: javadoc tags

---

.github/workflows/verify.yaml

Adds a `Javadocs` validation job
We are currently catching javadoc related errors only in jenkins build job
Closes #2675

feat(CI): add javadoc checks

---

core/common/junit/src/main/java/org/eclipse/edc/junit/assertions/AbstractResultAssert.java

Fixes compilation issue
A breaking change in the `AbstractResult` class caused the merge of the `AbstractResultAssert` PR to break compilation.
Their checks were working because the breaking change happened between the checks and the merge.

fix: fix compilation

---

data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/build.gradle.kts
data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/catalog/dispatcher/DspCatalogHttpDispatcherExtension.java
data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/catalog/dispatcher/delegate/CatalogRequestHttpDelegate.java
data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/catalog/dispatcher/delegate/CatalogRequestHttpDelegateTest.java
settings.gradle.kts

Creates the `dsp-catalog-http-dispatcher` module, which provides the delegate for sending catalog requests.
To support the dataspace protocol catalog specification.
Relates #2474

feat: dataspace protocol catalog HTTP dispatcher

---

extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/SqlContractNegotiationStore.java
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java

This PR fixes the call to `SqlContractNegotiationStore#nextForState` for ContractNegotiation where the ContractAgreement is available.
Currently the state machine throws an exception for state `AGREED`
The mapper for `SqlContractNegotiationStore#nextForState` has been changed. If the agreement id in contract negotiation is not null it gets lazy loaded.
Closes #2692

fix(SqlContractNegotiationStore): fix next for state when the agreement is not null

---

extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java
extensions/data-plane/data-plane-http/src/test/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSourceTest.java
extensions/data-plane/data-plane-integration-tests/src/test/java/org/eclipse/edc/connector/dataplane/http/DataPlaneHttpToHttpIntegrationTests.java

Streams the HTTP response content instead of materializing it in memory. Note that this PR has the added benefit of removing logging response content which should not be done as it could potentially leak sensitive data.
**NB** Introducing end-to-end HTTP streaming changes the supported retry semantics. First, we cannot easily support sink retries without implementing a multipart wire transfer protocol that the sink endpoint supports. Second, the retry mechanism for source connections only works for initial connection establishment. If an error occurs with the source socket connection, it is not possible to establish a new connection and fast-forward to the failure point in the stream without underlying wire protocol and endpoint support.  
Therefore, this PR removes the …

feat: support End-to-End Async HTTP Streaming Part I

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/DatasetResolverImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/DatasetResolverImplTest.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndexTest.java
extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/QuerySpecDtoToQuerySpecTransformerTest.java
extensions/control-plane/store/cosmos/asset-index-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndex.java
extensions/control-plane/store/cosmos/asset-index-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndexIntegrationTest.java
extensions/control-plane/store/cosmos/asset-index-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/assetindex/CosmosAssetIndexTest.java
extensions/control-plane/store/sql/asset-index-sql/src/main/java/org/eclipse/edc/connector/store/sql/assetindex/SqlAssetIndex.java
extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetIndex.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QuerySpec.java
spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java

Supports catalog filtering
dataspace-protocol implementation
- I noticed that there's a method in the `AssetIndex` used only by tests: `queryAssets(AssetSelectorExpression expression)`, I took some time to replace its test occurrencies with the actually used `queryAssets(QuerySpec querySpec)` and remove it. There still are some duplicate tests in the `Postgres`/`Cosmos`/`InMemory` integration test classes to be moved to the `AssetIndexTestBase`, but I will open an issue to do that later on.
Closes #2697

feat: support catalog filtering

---

spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractOfferRequest.java

Change impl of  `ContractOfferRequest` from `RemoteMessage` to `ContractRemoteMessage`.
Algin with other contract-related remote messages.
--
Closes #2722

chore(spi): make ContractOfferRequest implement ContractRemoteMessage

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/catalog/DatasetResolverImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/DatasetResolverImplIntegrationTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/catalog/DatasetResolverImplTest.java

Implement catalog pagination 
dsp
- the implementation is way easier than the `ids` one, that's way the catalog is not listing `ContractOffer`s anymore, but `Dataset`. This could be way less efficient because, in fact, to have a page of the catalog, there'll be the need to create the whole list of the dataset, because a dataset cannot be considered completed if it doesn't have the whole list of offer attached. 
- An alternative could be to fetch assets first and then for every asset fetch the definitions and, if the definition selector matches the asset, create the offer. this will likely be faster for certain scenarios (e.g. a lot of assets, not a lot of definitions), while it would be slower for other ones (e.g. not a lot of assets, a lot of definitions). I will open an issue to …

feat: dsp catalog pagination

---

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/event/EventRouterImpl.java
core/common/junit/src/main/java/org/eclipse/edc/junit/matchers/EventEnvelopeMatcher.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetEventDispatchTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/policydefinition/PolicyDefinitionEventDispatchTest.java
extensions/common/events/events-cloud-http/src/main/java/org/eclipse/edc/event/cloud/http/CloudEventsPublisher.java
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcher.java
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherExtension.java
extensions/control-plane/callback/callback-event-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherExtensionTest.java
extensions/control-plane/callback/callback-event-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventRouter.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventSubscriber.java

Change the `EventSubscriber` interface API 
Avoid compiler warnings
- also `EventEnvelope` suffers from warnings, caused by the fact that the type of the payload is not known until it has been set with the `payload` builder method. I'd propose to add the payload as a member of the `newInstance` method to avoid this, eventually in another PR.
Closes #2740

refactor: resolve EventSubscriber warnings

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java

Adds the `ContractAgreement` in context when evaluating the policy 
To access information about `ContractAgreement` in custom `AtomicConstraintFunction`
Closes #2754

feat(ContractValidation): adds ContractAgreement in policy context formation when validating the contract

---

docs/developer/decision-records/2023-04-18-api-controllers-testing/README.md
docs/developer/decision-records/README.md

Add decision record for API controllers testing
decision
-
Part of #2742

docs: add decision record for api controllers testing

---

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java
core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplPerformanceTest.java
core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/ReflectionBasedQueryResolver.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/assetindex/InMemoryAssetIndex.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/asset/AssetPredicateConverter.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/BaseCriterionToPredicateConverter.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/asset/AssetPredicateConverterTest.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/query/BaseCriterionToPredicateConverterTest.java

Refactor `DatasetResolverImpl` to achieve better performances.
This is one of the most crucial components, because building a `Catalog` could become an heavy operation, as it is done on demand and it involves different stores.
I added two simple performance tests, one of them was failing with the old implementation.
With the new implementation the `Dataset` is built starting from the `Asset`s, and the advantage is that the pagination is applied before the `Stream` collection, this way there won't be any overkill operation.
Note that the `ContractDefinition`s are loaded in memory, this is because the `definitionsFor` method is expensive, because for every `ContractDefinition` the `accessPolicy` must be verified. Having all the definitions in memory shouldn't be an issue tho, as they are …

feat: improve `DatasetResolverImpl` performances

---

data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/build.gradle.kts
data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/catalog/dispatcher/delegate/CatalogRequestHttpDelegate.java
data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/catalog/dispatcher/delegate/CatalogRequestMessageHttpDelegateTest.java

In the `CatalogRequestHttpDelegate`, compacts the catalog request JSON-LD structure when building a request. This includes setting the JSON-LD context.
When the catalog request is received, it is expected in the compacted form and compaction was previously missing.

fix(dsp catalog dispatcher): compact catalog request

---

extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java

Avoids logging the proxied HTTP request, which can expose sensitive information.
Closes #2773

fix: avoid logging sensitive information

---

core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/IdsMultipartRemoteMessageDispatcherTest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferTerminationMessage.java

Adds the attribute fields `code` and `reason` to `TransferTerminationMessage` like the [spec](https://docs.internationaldataspaces.org/dataspace-protocol/transfer-process/transfer.process.protocol#5.-transferterminationmessage) describes. Also adds the new fields to exisiting Tests.
To align the TransferTerminationMessage with the dataspace-protocol
The issue #2764 also defines to add the `code` attribute to the ContractNegotiationTerminationMessage. This is done in
the PR #2771.
Relates #2764

feat: dataspace-protocol add missing fields to TransferTerminationMessage

---

extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionApiExtension.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionNewApi.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionNewApiController.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionNewDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionNewResponseDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionNewUpdateDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionNewUpdateWrapperDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionRequestDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionResponseDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/model/PolicyDefinitionUpdateWrapperDto.java
extensions/control-plane/api/management-api/policy-definition-api/src/test/java/org/eclipse/edc/connector/api/management/policy/PolicyDefinitionNewApiControllerIntegrationTest.java
resources/openapi/openapi.yaml
resources/openapi/yaml/management-api/policy-definition-api.yaml
spi/common/web-spi/src/main/java/org/eclipse/edc/web/spi/exception/InvalidRequestException.java

Add missing functionalities to the `PolicyDefinitionNewApiController`, that will replace the current one over the long term
dataspace protocol
trasformers are still missing and they will be implemented in a subsequent PR
Closes #2768

feat: implementing missing methods in `PolicyDefinitionNewApiController`

---

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImpl.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/flow/DataFlowManagerImplTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java
extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataAddressConstants.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataAddressConstantsTest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowController.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/flow/DataFlowManager.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/DataFlowResponse.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferStartMessage.java

Adds the DataAddress field in TransferStartMessage
This is a preliminary work for supporting the EDR via the new protocol
The `DataFlowManager` and `DataFlowController` interface has been changed, now they returns a `DataFlowResponse` which optionally may contain a `DataAddress`.
The `ConsumerPullTransferDataFlowController` now returns the `EDR` encoded in the `DataAddress`, which will be then 
set in the `TransferStartMessage` on the provider side.
Still not sure yet how is the best way to encode an EDR into a `DataAddress`. 
Should we namespace the known properties?
Closes #2727

feat(TransferStartMessage): adds DataAddress field

---

data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/DspTransferProcessTransformExtension.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromDataAddressTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromDataAddressTransformerTest.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromAssetTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToDataAddressTransformer.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/PayloadTransformer.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromAssetTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToAssetTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToDataAddressTransformerTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/CoreConstants.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java
spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java

Adds a `JsonObjectToDataAddressTransformer` plus tests.
DataAddresses must be (JSON-LD)-type-aware, so we need a transformer for it.
this PR is needed for #2767 
- I had to (re-)create the `CoreConstants.java` into the `core-spi`, because we need access to the `EDC_NAMESPACE`. This is already done in PR #2807, but that is not yet merged.
Needed for #2767 
Needed for #2806

feat(dsp): add transformer for JsonObjectToDataAddress

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationServiceImplTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiController.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerIntegrationTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiControllerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/NegotiationInitiateRequestDtoToDataRequestTransformerTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/negotiation/ConsumerContractNegotiationManager.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractRequestData.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/contractnegotiation/ContractNegotiationService.java

This PR refactor `ContractNegotiationService` and `ConsumerContractNegotiationManager` in order to take `ContractRequest` as input for initiating a contract negotiation instead of `ContractRequestMessage` which implements  `RemoteMessage` and it's supposed to be used only when dealing with protocol communication. 
Clean up, decoupling
We could entirely separate the classes that represent remote messages in their own modules
Closes #2815

feat(ContractNegotiationService): restored callbacks 

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/asset/AssetQueryValidator.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetQueryValidatorTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/asset/AssetServiceImplTest.java
spi/common/core-spi/src/testFixtures/java/org/eclipse/edc/spi/testfixtures/asset/AssetIndexTestBase.java
system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/AssetApiEndToEndTest.java

Change the `AssetQueryValidator` so that it allows for any query path, not just known `Asset` properties.
However, query paths (= left-operands) must start with a letter or an underscore.
This will be needed for more complex `AssetSelectorExpression`s.
- I added a test to the `AssetIndexTestBase` that performs a complex query on a nested JSON structure.
Closes .

feat(asset): enable querying assets by custom properties

---

extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/util/JsonLdUtil.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java

Implements the `JsonLd` service
replace the static `JsonLdUtil`, allow for registering additional namespaces.
Closes #2830
Closes #2832

feat(dsp): add a titanium-based impl of the JsonLd service

---

core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/CoreServicesExtension.java
core/common/connector-core/src/test/java/org/eclipse/edc/connector/core/CoreServicesExtensionTest.java

Moves the `PolicyRegistrationTypes.TYPES` registration in the `CoreServicesExtension#prepare` phase
To make sure types are registered correctly in all available mappers.
Closes #2843

feat(CoreServicesExtension): move types registration to the prepare phase

---

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/CatalogCoreExtension.java
core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/CatalogDefaultServicesExtension.java
core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DefaultDistributionResolver.java
core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DefaultDistributionResolverTest.java
data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/DspCatalogApiExtension.java

Removes the cyclic dependency between `CatalogCoreExtension`, `ControlPlaneServicesExtensions` and `DspCatalogApiExtension`:
* Removes direct injections of `DataService`
* Provides the `DataServiceRegistry` in `CatalogDefaultServicesExtension` instead of `CatalogCoreExtension`
* In the `DspCatalogApiExtension` registers the `DataService` with the `DataServiceRegistry` instead of providing it
* Refactors the `DefaultDistributionResolver` to use the `DataServiceRegistry` instead of a `DataService` directly
So that dsp modules can be used in a runtime

fix: resolve dsp cyclic dependency

---

extensions/control-plane/callback/callback-event-dispatcher/build.gradle.kts
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/CallbackProtocolResolverRegistryImpl.java
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcher.java
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherExtension.java
extensions/control-plane/callback/callback-event-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherTest.java
extensions/control-plane/callback/callback-http-dispatcher/build.gradle.kts
extensions/control-plane/callback/callback-http-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/http/CallbackEventDispatcherHttpExtension.java
extensions/control-plane/callback/callback-http-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/http/CallbackEventRemoteMessageDispatcher.java
extensions/control-plane/callback/callback-http-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/http/GenericHttpRemoteDispatcherWrapperTest.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/callback/CallbackEventRemoteMessage.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/callback/CallbackProtocolResolver.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/callback/CallbackProtocolResolverRegistry.java

Move callback package from core-spi to control-plane-spi
cleanup
Closes #2851

chore(Callbacks): move callback package from core-spi to control-plane-spi

---

core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/PolicyContextImpl.java
core/common/policy-engine/src/main/java/org/eclipse/edc/policy/engine/PolicyEngineImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/provision/ResourceManifestGeneratorImpl.java
spi/common/policy-engine-spi/src/main/java/org/eclipse/edc/policy/engine/spi/PolicyEngine.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/validation/ContractValidationService.java
spi/control-plane/control-plane-spi/build.gradle.kts

This PR adjusts `ContractValidationService.validateAgreement()` to use `TRANSFER_SCOPE` instead of `NEGOTIATION_SCOPE.` It also cleans up missing generics in some of the policy classes. 
Closes #2860

feat: adjust policy scope and adjust class generics

---

data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/DspCatalogApiExtension.java
data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/main/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/CatalogController.java
data-protocols/dsp/dsp-catalog/dsp-catalog-api/src/test/java/org/eclipse/edc/protocol/dsp/catalog/api/controller/CatalogControllerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationController.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiController.java

Uses the `Monitor's` supplier notation for debug logging in `dsp` controllers.
So that `format()` is only evaluated if debug logging is enabled.

refactor(dsp): use supplier notation for logging

---

extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionApiExtension.java
extensions/control-plane/api/management-api/contract-definition-api/src/main/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionNewApiController.java
extensions/control-plane/api/management-api/contract-definition-api/src/test/java/org/eclipse/edc/connector/api/management/contractdefinition/ContractDefinitionNewApiControllerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/build.gradle.kts
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApi.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/ContractAgreementDto.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/ContractNegotiationDto.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/NegotiationInitiateRequestDto.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromCallbackAddressTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromContractAgreementDtoTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromContractNegotiationDtoTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToCallbackAddressDtoTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToNegotiationInitiateRequestDtoTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiControllerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromCallbackAddressTransformerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromContractAgreementDtoTransformerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromContractNegotiationDtoTransformerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToCallbackAddressDtoTransformerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectToNegotiationInitiateRequestDtoTransformerTest.java
resources/openapi/yaml/management-api/contract-negotiation-api.yaml
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/callback/CallbackAddress.java
system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java
system-tests/runtimes/file-transfer-provider/build.gradle.kts

This PR adds the new (json-ld-aware) contract negotiation API as well as several new transformers:
- JsonObject <- CallbackAddress
- JsonObject <- ContractAgreement
- JsonObject <- ContractNegotiation
- JsonObject -> CallbackAddressDto
- JsonObject -> NegotiationInitiateRequest
Json-LD-ification of the API, needed for the new DSP
.
Closes #2838

feat: add contractnegotiation api for jsonld objects

---

system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java

Removes an assertion that did not bring any value really, but caused occasional flukes and failing tests.
test stability and focus
.

fix(test): remove assertion for CN status

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessServiceImplTest.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/storage/transferprocess/InMemoryTransferProcessStore.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/command/handlers/SingleTransferProcessCommandHandler.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/CancelTransferCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/CompleteTransferCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/DeprovisionCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/command/handlers/TerminateTransferCommandHandlerTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplIntegrationTest.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java
extensions/control-plane/api/control-plane-api-client/src/test/java/org/eclipse/edc/connector/api/client/transferprocess/TransferProcessHttpClientIntegrationTest.java
extensions/control-plane/api/control-plane-api/src/test/java/org/eclipse/edc/connector/api/TransferProcessControlApiControllerIntegrationTest.java
extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiControllerIntegrationTest.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/webhook/HttpProvisionerWebhookApiControllerIntegrationTest.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/main/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStore.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/CosmosTransferProcessStoreIntegrationTest.java
extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/SqlTransferProcessStore.java
extensions/control-plane/store/sql/transfer-process-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/transferprocess/PostgresTransferProcessStoreTest.java
extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/main/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiver.java
extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/src/test/java/org/eclipse/edc/connector/receiver/http/dynamic/HttpDynamicEndpointDataReferenceReceiverTest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/store/TransferProcessStore.java
spi/control-plane/transfer-spi/src/testFixtures/java/org/eclipse/edc/connector/transfer/spi/testfixtures/store/TransferProcessStoreTestBase.java

The persistence implementations in TransferProcessStore are refactrored in CRUD interactions.
consistency, recognizability
ref #2559

refactor(TransferProcessStore): harmonize CRUD operations

---

data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractAgreementMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractAgreementMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/DspNegotiationPropertyAndTypeNames.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java

Add consumer and provider ids to the DSP contract agreement.
Closes #2895

feat: add consumer/provider id support for DSP messages

---

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java
core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractRequestMessageTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromPolicyTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToDutyTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPermissionTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPolicyTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToProhibitionTransformer.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromPolicyTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToDutyTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPermissionTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPolicyTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToProhibitionTransformerTest.java
spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java
system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/PolicyDefinitionApiEndToEndTest.java

Sets `target` on catalog creation, and maps it on every from/to transformer that deals with policy and rules. 
dataspace-protocol
Closes #2911

fix: set target on Policy

---

data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/dispatcher/delegate/ContractRequestMessageHttpDelegateTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractAgreementMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractAgreementVerificationMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractNegotiationEventMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractNegotiationTerminationMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractNegotiationTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractRequestTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractAgreementMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractAgreementVerificationMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractNegotiationEventMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractNegotiationTerminationMessageTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/DspNegotiationPropertyAndTypeNames.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractAgreementVerificationMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractNegotiationEventMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractNegotiationTerminationMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractNegotiationTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractAgreementVerificationMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractNegotiationEventMessageTransformerTest.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractNegotiationTerminationMessageTransformerTest.java
spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/agreement/ContractNegotiationEventMessage.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiationTerminationMessage.java

This PR focuses on the contract negotiation transformers:
1. Improves test coverage and verifies handling of invalid messages
2. Removes  CRED_CREDENTIAL_SUBJECT and  SEC_PROOF as they should be removed from the DSP specifications
3. Remoes checksum handling as that should also be removed from the DSP specifications
4. Renames "object" variable names for clarity

chore(dsp): improve contract negotiation transformer error handling and align with the spec

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java

This PR adds a validation to the `ContractValidationServiceImpl#validateInitialOffer`, which ensures that the `assetId` that is contained in the incoming `ContractOffer`, is indeed referenced by the `AssetSelectorExpression` of the `ContractDefinition`', based on which the offer was supposedly created.
Not verifying this could be a potential avenue for malicious actors/attackers to negotiate a contract for an asset, that was not offered to them.
- The algorithm is as follows: a new `Criterion` ("assetId = xxx") is added to the selector expression, which is then used in a `count` query against the `AssetIndex`. If the count comes back non-zero, the check succeeds, otherwise fails. This works because by convention multiple criteria are conjoined with a logical `and` at the DB level.
- I …

feat(core): validate that requested asset is contained in ContractDefinition

---

core/control-plane/catalog-core/src/main/java/org/eclipse/edc/connector/catalog/DatasetResolverImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/offer/ContractOfferResolverImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ConsumerContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ContractNegotiationIntegrationTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImplTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationEventDispatchTest.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/storage/contractnegotiation/InMemoryContractNegotiationStoreTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/client/MultipartDispatcherIntegrationTest.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/CosmosContractNegotiationStoreIntegrationTest.java
extensions/control-plane/store/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/contractnegotiation/TestFunctions.java
extensions/control-plane/store/sql/contract-negotiation-store-sql/src/test/java/org/eclipse/edc/connector/store/sql/contractnegotiation/store/PostgresContractNegotiationStoreTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/ContractId.java
spi/control-plane/contract-spi/src/test/java/org/eclipse/edc/connector/contract/spi/types/ContractIdTest.java
spi/control-plane/contract-spi/src/testFixtures/java/org/eclipse/edc/connector/contract/spi/testfixtures/negotiation/store/ContractNegotiationStoreTestBase.java

This PR encodes the Asset-ID into the ContractOffer ID
provider runtimes should be able to restore one particular offer, and for that, they need both the ContractDefinition-ID _and_ the Asset-ID
.
Closes #2929

feat: make ContractOffer IDs include the AssetID

---

core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/ControlPlaneDefaultServicesExtension.java
core/control-plane/control-plane-core/src/main/java/org/eclipse/edc/connector/defaults/callback/CallbackRegistryImpl.java
core/control-plane/control-plane-core/src/test/java/org/eclipse/edc/connector/defaults/callback/CallbackRegistryImplTest.java
extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/model/CallbackAddressDto.java
extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/CallbackAddressDtoToCallbackAddressTransformer.java
extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/JsonObjectFromCallbackAddressTransformer.java
extensions/common/api/api-core/src/main/java/org/eclipse/edc/api/transformer/JsonObjectToCallbackAddressDtoTransformer.java
extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/CallbackAddressDtoToCallbackAddressTransformerTest.java
extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectFromCallbackAddressTransformerTest.java
extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectToCallbackAddressDtoTransformerTest.java
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcher.java
extensions/control-plane/callback/callback-event-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherExtension.java
extensions/control-plane/callback/callback-event-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/CallbackEventDispatcherTest.java
extensions/control-plane/callback/callback-http-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/http/CallbackEventDispatcherHttpExtension.java
extensions/control-plane/callback/callback-http-dispatcher/src/main/java/org/eclipse/edc/connector/callback/dispatcher/http/CallbackEventRemoteMessageDispatcher.java
extensions/control-plane/callback/callback-http-dispatcher/src/test/java/org/eclipse/edc/connector/callback/dispatcher/http/GenericHttpRemoteDispatcherWrapperTest.java
extensions/control-plane/callback/callback-static-endpoint/REAME.md
extensions/control-plane/callback/callback-static-endpoint/build.gradle.kts
extensions/control-plane/callback/callback-static-endpoint/src/main/java/org/eclipse/edc/connector/callback/staticendpoint/CallbackStaticEndpointExtension.java
extensions/control-plane/callback/callback-static-endpoint/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
extensions/control-plane/callback/callback-static-endpoint/src/test/java/org/eclipse/edc/connector/callback/staticendpoint/CallbackStaticEndpointExtensionTest.java
resources/openapi/yaml/management-api/contract-negotiation-api.yaml
resources/openapi/yaml/management-api/transfer-process-api.yaml
settings.gradle.kts
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/callback/CallbackAddress.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/callback/CallbackEventRemoteMessage.java
spi/control-plane/control-plane-spi/src/main/java/org/eclipse/edc/connector/spi/callback/CallbackRegistry.java

Implements static callbacks as outlined in this [Decision Record](https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2023-02-28-processing-callbacks#static-endpoints)
Completes the callback feature with static configurable ones 
The auth support via `Vault` has been also added to the dynamic callbacks
Closes #2627

feat(Callbacks): implements static callbacks configuration extension

---

data-protocols/dsp/dsp-transform/src/main/java/org/eclipse/edc/protocol/dsp/transform/DspTransformExtension.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromPolicyTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToAtomicConstraintTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToConstraintTransformer.java
extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToMultiplicityConstraintTransformer.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromPolicyTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToAtomicConstraintTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToConstraintTransformerTest.java
extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToMultiplicityConstraintTransformerTest.java
spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/PropertyAndTypeNames.java
spi/common/policy-model/src/main/java/org/eclipse/edc/policy/model/MultiplicityConstraint.java

Adds transformation support for ODRL logical constraints/EDC mulitplicity constraints.
For direction `EDC model -> JsonObject` implements the respective visitor methods in `JsonObjectFromPolicyTransformer`.
For direction `JsonObject -> EDC model` creates two new transformers for transforming to `AtomicConstraint` and `MultiplicityConstraint` respectively. The existing `JsonObjectToConstraintTransformer` identifies the type of constraint based on its properties and delegates back to the context to transform it to the correct constraint type.
To support ODRL logical constraints.
Makes the abstract builder in `MultiplicityConstraint` public to allow handling different builder sub types together in the transformer.
Closes #2671

feat: transform ODRL logical constraints

---

data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/transform/DspNegotiationPropertyAndTypeNames.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/to/JsonObjectToContractNegotiationTerminationMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/DspTransferProcessPropertyAndTypeNames.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferRequestMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferStartMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferCompletionMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferRequestMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferStartMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferTerminationMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromTransferRequestMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferCompletionMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferRequestMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferStartMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferTerminationMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/TestInput.java
extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/DataAddressDtoToDataAddressTransformerTest.java
extensions/common/api/api-core/src/test/java/org/eclipse/edc/api/transformer/JsonObjectFromDataAddressDtoTransformerTest.java
extensions/control-plane/api/management-api/transfer-process-api/src/test/java/org/eclipse/edc/connector/api/management/transferprocess/transform/TransferProcessToTransferProcessDtoTransformerTest.java
extensions/control-plane/store/cosmos/transfer-process-store-cosmos/src/test/java/org/eclipse/edc/connector/store/azure/cosmos/transferprocess/model/TransferProcessDocumentSerializationTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/DataAddress.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataAddressConstants.java

Fixes errors transforming transfer process messages that are in expanded Json-Ld form.
This PR also fixes issues involving DataAddress key namespaces, which are related to the transformer issues.
Closes #2963

fix: issues with transfer transformers and ld-expansion

---

extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementNewApi.java
extensions/control-plane/api/management-api/contract-agreement-api/src/main/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementNewApiController.java
extensions/control-plane/api/management-api/contract-agreement-api/src/test/java/org/eclipse/edc/connector/api/management/contractagreement/ContractAgreementNewApiControllerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationApiExtension.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApi.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/model/NegotiationState.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromNegotiationStateTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromStateTransformer.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiControllerTest.java
extensions/control-plane/api/management-api/contract-negotiation-api/src/test/java/org/eclipse/edc/connector/api/management/contractnegotiation/transform/JsonObjectFromNegotiationStateTransformerTest.java
resources/openapi/yaml/management-api/contract-agreement-api.yaml
resources/openapi/yaml/management-api/contract-negotiation-api.yaml
system-tests/management-api/management-api-test-runner/src/test/java/org/eclipse/edc/test/e2e/managementapi/ContractNegotiationApiEndToEndTest.java

Use JSON-LD obejects in all endpoints of `ContractNegotiationNewControllerApi` and `ContractAgreementNewApi`
consistency
Closes #2939

feat(contractNegotiationApi): json-ld all endpoints on ContractNegotiationNewApi and ContractAgreementNewApi

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/api/controller/DspTransferProcessApiControllerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/dispatcher/delegate/TransferRequestDelegateTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/to/JsonObjectToTransferRequestMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromTransferRequestMessageTransformerTest.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/to/JsonObjectToTransferRequestMessageTransformerTest.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/type/MultipartTransferRequestSender.java
data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/type/MultipartTransferRequestSenderTest.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandler.java
data-protocols/ids/ids-api-multipart-endpoint-v1/src/test/java/org/eclipse/edc/protocol/ids/api/multipart/handler/ArtifactRequestHandlerTest.java
extensions/control-plane/provision/provision-http/src/test/java/org/eclipse/edc/connector/provision/http/impl/HttpProvisionerExtensionEndToEndTest.java
spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/transfer/spi/types/protocol/TransferRequestMessage.java

Rename `id` to `processId` in `TransferRequestMessage`
Map it correctly
bugfix
Closes #2968

fix: map processId in `JsonObjectToTransferRequestMessageTransformer`

---

core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImpl.java
core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/ProviderContractNegotiationManagerImplTest.java
core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/contractnegotiation/ContractNegotiationProtocolServiceImplTest.java

Avoid the Contract service protocol to do a multiple state transition (REQUESTED and AGREEING).
service -> transition to REQUESTED
manager -> transition to AGREEING 
Closes #2962

feat: separate multiple state transitions

---

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/transfer/TransferProcessManagerImplTest.java

set id same as correlationId in consumer transfer process, to fullfill DSP specs.
Closes #2960

fix: set id same as correlationId in consumer transfer process

---

data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/dispatcher/DspTransferProcessDispatcherExtension.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-dispatcher/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/dispatcher/delegate/TransferRequestDelegate.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-dispatcher/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/dispatcher/delegate/TransferRequestDelegateTest.java

that transformation would break anyway because we haven't a transformer from json to TransferProcess
Closes #2958

fix: avoid pointless response handling in TransferRequestDelegate

---

core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImpl.java
core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/service/transferprocess/TransferProcessProtocolServiceImplTest.java

extract assetId from contractId
Closes #2959

fix: extract assetId from contractId

---

data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/main/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/type/from/JsonObjectFromTransferStartMessageTransformer.java
data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/src/test/java/org/eclipse/edc/protocol/dsp/transferprocess/transformer/from/JsonObjectFromTransferStartMessageTransformerTest.java

In the `JsonObjectFromTransferStartMessageTransformer` calls the context to transform the message's `DataAddress` instead of the message itself.
To avoid stack overflow error
Closes #2974

fix(dsp): stack overflow in transfer start transformer

---

data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/from/JsonObjectFromContractNegotiationTransformer.java
data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractNegotiationTransformerTest.java

Maps `*ING` status for ContractNegotiation in DSP transformer
Closes #2978

fix: map ING status for ContractNegotiation in DSP

---

core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/TransferCoreExtension.java
core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImpl.java
core/control-plane/transfer-core/src/test/java/org/eclipse/edc/connector/transfer/edr/EndpointDataReferenceReceiverRegistryImplTest.java
extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowController.java
extensions/control-plane/transfer/transfer-data-plane/src/test/java/org/eclipse/edc/connector/transfer/dataplane/flow/ConsumerPullTransferDataFlowControllerTest.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataAddressConstants.java
spi/common/core-spi/src/main/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataReference.java
spi/common/core-spi/src/test/java/org/eclipse/edc/spi/types/domain/edr/EndpointDataAddressConstantsTest.java

Implements the backward compatibility with `EndpointDataReferenceReceiver` on the new `dsp` protocol.
backward compatibility
The `EndpointDataReferenceReceiverRegistryImpl` now implements an `EventSubscriber` that operates 
on the `TransferStarted` event. If the event contains the `dataAddress`(EDR) it will forward it to the registered
receiver.
Closes #2926

feat(EndpointDataReferenceReceiver): backward compatibility via TranserStarted event

---

data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/test/java/org/eclipse/edc/protocol/dsp/negotiation/transform/from/JsonObjectFromContractNegotiationTransformerTest.java
spi/control-plane/contract-spi/src/main/java/org/eclipse/edc/connector/contract/spi/types/negotiation/ContractNegotiation.java

Remove unnecessarily introduced attribute `checksum` from `ContractNegotiation`.
Closes #2982

chore: remove checksum from ContractNegotiation
